### ISSUE TITLE
How to build horovod base image with tensorflow-gpu on node without gpu?

### ISSUE THREAD

**Issue by yamajik** [horovod/horovod#1005]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch)
2. Framework version: 1.13.1, latest, 1.0.0
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.3.7-1+cuda9.0
7. Python version: 2.7 - 3.6
8. OS and version: nvidia/cuda:9.0-devel-ubuntu16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Due to `check_tf_version` try to import tensorflow

``` shell 
Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_nccl.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.so
    error: import tensorflow failed, is it installed?

    Traceback (most recent call last):
      File "/tmp/pip-install-55X8ZZ/horovod/setup.py", line 55, in check_tf_version
        import tensorflow as tf
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


    Failed to load the native TensorFlow runtime.

    See https://www.tensorflow.org/install/errors

    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.


    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-55X8ZZ/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2iZQ04/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-55X8ZZ/horovod/
```

Couldn't import tensorflow(-gpu) on node without gpu.
So? How to build horovod base image with tensorflow-gpu on node without gpu?

**Comment by yamajik** [comment]
Maybe check tensorflow version in another way.

**Comment by alsrgv** [comment]
@yamajik, you can use the same trick that we use in our docker image build (`ldconfig` cuda/stubs): https://github.com/horovod/horovod/blob/master/Dockerfile#L52

**Comment by yamajik** [comment]
thx
