### ISSUE TITLE
Spark with Horovod Docker

### ISSUE THREAD

**Issue by vtczk** [horovod/horovod#1019]
**Environment:**
1 Docker image : horovod/horovod:0.16.1-tf1.12.0-torch1.0.0-mxnet1.4.0-py3.5
2. OS and version: Ubuntu 18.04.2 both hosts
3. Spark 2.4.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Is it possible to integrate spark with Horovod Docker?
I mean to run horovod jobs on the outside of docker container spark cluster from within the docker container?Or to achieve that spark would have to be launched inside the container?

I've also tried the simple example from the docs 

```python
def fn(magic_number):
    import horovod.torch as hvd
    hvd.init()
    print('Hello, rank = %d, local_rank = %d, size = %d, local_size = %d,magic_number = %d' % (hvd.rank(), hvd.local_rank(), hvd.size(), hvd.local_size(), magic_number))
    return hvd.rank()

import horovod.spark
horovod.spark.run(fn, args=(42,))

```
But it ends with following output 

```
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "pyspark.py", line 7, in <module>
[1,0]<stderr>:    import horovod.spark
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/horovod/spark/__init__.py", line 17, in <module>
[1,0]<stderr>:    import pyspark
[1,0]<stderr>:  File "/scripts/pyspark.py", line 8, in <module>
[1,0]<stderr>:    horovod.spark.run(fn, args=(42,))
[1,0]<stderr>:AttributeError: module 'horovod' has no attribute 'spark'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54949,1],0]
  Exit code:    1

```

Thanks for any help or clarification.

**EDIT** 
I did overcome the issue using either findspark or spark submit but still most of my spark jobs end with following error

```
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 0 cancelled part of cancelled job group horovod.spark.run.0
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1824)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2079)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

Any ideas?

**Comment by alsrgv** [comment]
@vtczk, is there any output before or after the exception `: org.apache.spark.SparkException: Job 0 cancelled part of cancelled job group horovod.spark.run.0`?

**Comment by vtczk** [comment]
@alsrgv this error keeps occuring.Latest example with full log was 

``` bash
[1,0]<stderr>:Using TensorFlow backend.
[1,1]<stderr>:Using TensorFlow backend.
[1,0]<stderr>:2019-04-24 17:59:23.193564: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
[1,0]<stderr>:2019-04-24 17:59:23.193617: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on this host (test-komputer2): /proc/driver/nvidia/version does not exist
[1,1]<stderr>:2019-04-24 17:59:23.193798: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
[1,1]<stderr>:2019-04-24 17:59:23.193873: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on this host (test-komputer2): /proc/driver/nvidia/version does not exist
[1,0]<stdout>:Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
[1,1]<stderr>:    "__main__", mod_spec)
[1,1]<stderr>:  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
[1,1]<stderr>:    exec(code, run_globals)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 55, in <module>
[1,1]<stderr>:    main(codec.loads_base64(sys.argv[1]))
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 47, in main
[1,1]<stderr>:    result = fn(*args, **kwargs)
[1,1]<stderr>:  File "/spark/spark-2.4.1-bin-hadoop2.7/test/test.py", line 30, in fn
[1,1]<stderr>:    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/keras/datasets/cifar10.py", line 22, in load_data
[1,1]<stderr>:    path = get_file(dirname, origin=origin, untar=True)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 182, in get_file
[1,1]<stderr>:    os.makedirs(datadir)
[1,1]<stderr>:  File "/usr/lib/python3.5/os.py", line 241, in makedirs
[1,1]<stderr>:    mkdir(name, mode)
[1,1]<stderr>:FileExistsError: [Errno 17] File exists: '/root/.keras/datasets'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[1,0]<stdout>:
     8192/170498071 [..............................] - ETA: 52:10
    40960/170498071 [..............................] - ETA: 21:03
   106496/170498071 [..............................] - ETA: 12:15
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54707,1],1]
  Exit code:    1
--------------------------------------------------------------------------
   188416/170498071 [..............................] - ETA: 7:51 19/04/24 17:59:24 INFO DAGScheduler: Asked to cancel job group horovod.spark.run.0
19/04/24 17:59:24 INFO TaskSchedulerImpl: Cancelling stage 0
19/04/24 17:59:24 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled
19/04/24 17:59:24 INFO TaskSchedulerImpl: Stage 0 was cancelled
19/04/24 17:59:24 INFO DAGScheduler: ResultStage 0 (collect at /usr/local/lib/python3.5/dist-packages/horovod/spark/__init__.py:71) failed in 5.110 s due to Job 0 cancelled part of cancelled job group horovod.spark.run.0
19/04/24 17:59:24 INFO DAGScheduler: Job 0 failed: collect at /usr/local/lib/python3.5/dist-packages/horovod/spark/__init__.py:71, took 5.151337 s
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/horovod/spark/__init__.py", line 71, in run_spark
    _make_mapper(driver.addresses(), num_proc, tmout, key)).collect()
  File "/spark/home/python/lib/pyspark.zip/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/spark/home/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/spark/home/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/spark/home/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 0 cancelled part of cancelled job group horovod.spark.run.0
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1824)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2079)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


19/04/24 17:59:24 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 4537 ms on 192.168.1.117 (executor 0) (1/2)
Traceback (most recent call last):
  File "/spark/spark-2.4.1-bin-hadoop2.7/test/test.py", line 232, in <module>
    horovod.spark.run(fn)
  File "/usr/local/lib/python3.5/dist-packages/horovod/spark/__init__.py", line 182, in run
    raise Exception('mpirun exited with code %d, see the error above.' % exit_code)
Exception: mpirun exited with code 1, see the error above.
19/04/24 17:59:24 INFO SparkContext: Invoking stop() from shutdown hook
19/04/24 17:59:24 INFO SparkUI: Stopped Spark web UI at http://192.168.1.101:4040
19/04/24 17:59:24 INFO StandaloneSchedulerBackend: Shutting down all executors
19/04/24 17:59:24 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
19/04/24 17:59:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/04/24 17:59:24 INFO MemoryStore: MemoryStore cleared
19/04/24 17:59:24 INFO BlockManager: BlockManager stopped
19/04/24 17:59:24 INFO BlockManagerMaster: BlockManagerMaster stopped
19/04/24 17:59:24 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/04/24 17:59:24 INFO SparkContext: Successfully stopped SparkContext
19/04/24 17:59:24 INFO ShutdownHookManager: Shutdown hook called
19/04/24 17:59:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-0ef45220-e51a-4681-affa-37479a22424d/pyspark-29eca27a-56b1-41c3-a7a8-7ee6ca223f6f
19/04/24 17:59:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-0ef45220-e51a-4681-affa-37479a22424d
19/04/24 17:59:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-4756c519-8eb1-4d06-a652-aa613fcb6b93



```

About the first error with dataset download, i've checked that all workers didnt have .keras folder before launching spark submit.
And still having previously mentioned error with py4j

**Comment by alsrgv** [comment]
@vtczk, it looks like every worker tries to download CIFAR10 at the same time, and they all try to create the same directory `/root/.keras/datasets`.  One workaround I can think of is to download this dataset during your Docker build, e.g. like this: https://github.com/horovod/horovod/blob/master/Dockerfile.test.cpu#L66.  Replace `mnist` with `cifar10`.

This is another suspicious issue:
```
[1,0]<stderr>:2019-04-24 17:59:23.193564: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
[1,0]<stderr>:2019-04-24 17:59:23.193617: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on this host (test-komputer2): /proc/driver/nvidia/version does not exist
```

Do you have GPUs in your cluster?  If not, then it's ok, otherwise, you may want to use [nvidia-docker](https://github.com/NVIDIA/nvidia-docker/).
