### ISSUE TITLE
Error: Horovod has been shut down.

### ISSUE THREAD

**Issue by Laurisjj** [horovod/horovod#1020]
**Environment:**
1. Framework: TensorFlow
2. Framework version:1.13.1
3. Horovod version:0.16.1
4. MPI version:4.0.0
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version:3.6.7
8. OS and version: Ubuntu 18.04

**Your question:**
What might be the reason I receive these errors when I run training using mpirun on multiple hosts? Training executes fine when using only a single instance, but fails when additional hosts are added. 

`Traceback (most recent call last):
  File "train.py", line 145, in <module>
    tf.app.run()
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 141, in main
    mon_sess.run(train_op, feed_dict={image: image_, label: label_})
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)`

`tensorflow.python.framework.errors_impl.UnknownError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after o
ne of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer1_conv2d_Conv2D_grad_tuple_control_dependency_1_0 (defined at <string>:78) ]]`

`Caused by op 'DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer1_conv2d_Conv2D_grad_tuple_control_dependency_1_0', defined at:
  File "train.py", line 145, in <module>
    tf.app.run()
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 106, in main
    train_op = opt.minimize(loss, global_step=global_step)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 230, in compute_gradients
    avg_grads = self._allreduce_grads(grads)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in allreduce_grads
    for grad in grads]
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in <listcomp>
    for grad in grads]
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 88, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 91, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 78, in horovod_allreduce
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/laurisjakobsons97/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()`

`UnknownError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the rank
s finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer1_conv2d_Conv2D_grad_tuple_control_dependency_1_0 (defined at <string>:78) ]]`

I'm using https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py example, configured to execute training only on CPUs.

**Comment by alsrgv** [comment]
@LaurisJ, could you create a [gist](https://gist.github.com) with the full error log?  The real issue is displayed before the `Horovod has been shut down` message.
