### ISSUE TITLE
pip installation fails with Tensorflow 1.13.1

### ISSUE THREAD

**Issue by jtchilders** [horovod/horovod#1028]
**Environment:**
1. Framework: TensorFlow
2. Framework version: TF = 1.13.1
3. Horovod version: 0.16.1
4. MPI version: MPICH 3.3
5. CUDA version: X
6. NCCL version: X
7. Python version: 3.7
8. OS and version: centos7

My goal is to have Tensorflow 1.13.1 + Horovod 0.16.1 running for an Intel KNL supercomputer.

I am building inside a Singularity container so my complete installation instructions can be found here: [github repo](https://github.com/jtchilders/singularity_image_recipes/blob/master/Singularity.dvs8_cnda040512_py36)

I use the Conda's Intel channel to install Intel's optimized version of Tensorflow and MKL. Then I pip install Horovod. I have MPICH 3.3 installed and in the PATH/LD_LIBRARY_PATH for Horovod to use.

The build goes fine without errors. You can see the [build log here](https://www.singularity-hub.org/containers/8633/log)

After the build I run the following tests:
```bash
-> singularity exec -e dvs8_cnda040512_py36.simg python -c "import tensorflow as tf;hello = tf.constant('hello TensorFlow');print(tf.Session().run(hello))"
2019-04-25 13:52:45.699344: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-04-25 13:52:45.725850: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300125000 Hz
2019-04-25 13:52:45.730041: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56534c80cd40 executing computations on platform Host. Devices:
2019-04-25 13:52:45.730075: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-31
OMP: Info #156: KMP_AFFINITY: 32 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 2 packages x 16 cores/pkg x 1 threads/core (32 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 0 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 0 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 0 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 0 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 0 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 0 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 0 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 0 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 0 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 0 core 15
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 1 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 1 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 1 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 1 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 1 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 1 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 1 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 1 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 1 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 1 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 1 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 1 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 1 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 1 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 15
OMP: Info #250: KMP_AFFINITY: pid 1963 tid 1963 thread 0 bound to OS proc set 0
2019-04-25 13:52:45.731732: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
b'hello TensorFlow'
```

Tensorflow appears to be working normally

Then I try Horovod:
```bash
-> singularity exec -e /projects/datascience/parton/singularity/dvs8_cnda040512_py36.simg python -c "import horovod.tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda3/4.5.12/lib/python3.7/site-packages/horovod/tensorflow/__init__.py", line 38, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/miniconda3/4.5.12/lib/python3.7/site-packages/horovod/tensorflow/mpi_ops.py", line 59, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/miniconda3/4.5.12/lib/python3.7/site-packages/horovod/tensorflow/mpi_ops.py", line 46, in _load_library
    library = load_library.load_op_library(filename)
  File "/miniconda3/4.5.12/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /miniconda3/4.5.12/lib/python3.7/site-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

I have tried building horovod from the github and what I find is that when building the Tensorflow shared library `horovod/tensorflow/mpi_lib.cython......so` there are undefined symbols. If I include `LDSHARED='gcc -shared -Wl,--no-undefined -lpthread'` in the build command I can get this command to fail with this error:

```bash
g++ -shared -Wl,--no-undefined -lpthread build/temp.linux-x86_64-3.7/horovod/common/common.o build/temp.linux-x86_64-3.7/horovod/common/fusion_buffer_manager.o build/temp.linux-x86_64-3.7/horovod/common/half.o build/temp.linux-x86_64-3.7/horovod/common/message.o build/temp.linux-x86_64-3.7/horovod/common/mpi_context.o build/temp.linux-x86_64-3.7/horovod/common/operations.o build/temp.linux-x86_64-3.7/horovod/common/parameter_manager.o build/temp.linux-x86_64-3.7/horovod/common/response_cache.o build/temp.linux-x86_64-3.7/horovod/common/timeline.o build/temp.linux-x86_64-3.7/horovod/common/ops/collective_operations.o build/temp.linux-x86_64-3.7/horovod/common/ops/mpi_operations.o build/temp.linux-x86_64-3.7/horovod/common/ops/operation_manager.o build/temp.linux-x86_64-3.7/horovod/common/optim/bayesian_optimization.o build/temp.linux-x86_64-3.7/horovod/common/optim/gaussian_process.o build/temp.linux-x86_64-3.7/horovod/common/logging.o build/temp.linux-x86_64-3.7/horovod/tensorflow/mpi_ops.o -o build/lib.linux-x86_64-3.7/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so -Wl,--version-script=horovod.lds -I/mpich/install/include -L/mpich/install/lib -lmpicxx -lmpi -L/miniconda3/4.5.12/lib/python3.7/site-packages/tensorflow -ltensorflow_framework
build/temp.linux-x86_64-3.7/horovod/tensorflow/mpi_ops.o: In function `tensorflow::Status tensorflow::errors::Unknown<char const*>(char const*)':
/miniconda3/4.5.12/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/lib/core/errors.h:116: undefined reference to `tensorflow::strings::StrCat(tensorflow::strings::AlphaNum const&)'
build/temp.linux-x86_64-3.7/horovod/tensorflow/mpi_ops.o: In function `tensorflow::register_op::OpDefBuilderWrapper<true>::OpDefBuilderWrapper(char const*)':
/miniconda3/4.5.12/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/framework/op.h:211: undefined reference to `tensorflow::OpDefBuilder::OpDefBuilder(std::string)'
```

There are additional `undefined reference` errors but I truncated the message.

Any idea what is happening here? I appears you are using portions of Tensorflow that are not being linked into the primary `libtensorflow_framework.so` library.

**Comment by abditag2** [comment]
Check this https://github.com/horovod/horovod/issues/431

**Comment by jtchilders** [comment]
From what I can tell on that thread, they are discussing compiler mismatch issues between the tensorflow wheel and the local build of horovod. This is related to symbol naming differences between versions of GCC earlier/later than 5.1. 

I am using gcc 8.2 in the container. I would presume if Intel was using GCC 5.1+ to build tensorflow 1.9, then they would also be using GCC 5.1+ for tensorflow 1.13.1 meaning GCC 8.2 should be compatible. However, I could try switching the GCC version.

Any suggestion on determining which version I should try or must I tray all of them to find the right one?

Thanks!

**Comment by ppwwyyxx** [comment]
`print(tf.COMPILER_VERSION)`

**Comment by jtchilders** [comment]
Thanks, 

so it appears the intel tensorflow 1.13.1 build was done using GCC 5.4.0

I switch my container build to install Devtoolset-4 (GCC 5.3.1) and I still get the same `undefined reference` error. I can't believe that 5.4 and 5.3.1 are so different that their libraries are not compatible, but perhaps I'm naive.

**Comment by alsrgv** [comment]
@jtchilders, we recently discovered in #656 that `conda install gcc_linux-64 gxx_linux-64` can bring in GCC-7 into the conda environment and resolve this issue. Could you give it a shot?

**Comment by jtchilders** [comment]
OK, after some additions, I arrived at [this recipe](https://github.com/jtchilders/singularity_image_recipes/blob/master/Singularity.mcnda040512_gcc7_py36)

This Conda install of the GCC 7, did solve the dependency problem. I don't understand why this is so particular and why GCC 8 did not work. It would be useful to understand that.

**Comment by alsrgv** [comment]
@jtchilders, my guess would be that there's another ABI incompatible change between GCC 7 and GCC 8.   :-/
