### ISSUE TITLE
How to run horovod script on SLURM

### ISSUE THREAD

**Issue by LeavesLei** [horovod/horovod#1038]
My horovod program can run successfully on single machine with multiple GPUs. But when I want to run it on cluster with SLURM, which reported a error. I have tow computing nodes and each of them has 4 GPUs. I want to use both of two nodes.
My script is as below:
```
#SBATCH --job-name="test_job"
#SBATCH --workdir=.
#SBATCH --output=horovod_%j.out
#SBATCH --error=horovod_%j.err

#SBATCH --ntasks=80
#SBATCH --tasks-per-node=40
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:4
#SBATCH --nodes=2
#SBATCH --time=04:00:00

export OMP_NUM_THREADS=4

module load cudnn/7.1.3;
module load atlas/3.10.3;
module load scalapack/2.0.2;
module load fftw/3.3.7;
module load szip/2.1.1;
module load opencv/3.4.1;
module load python/3.6.5_ML;

mpirun python TEM_train.py
```
The error is as below:
```
Caused by op 'DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0', defined at:
  File "TEM_train.py", line 123, in <module>
    opt, loss, TEM_trainable_variables, loss_real = TEM_Train(X_feature, Y_action, Y_start, Y_end, LR, config)
  File "TEM_train.py", line 84, in TEM_Train
    opt = opt.minimize(cost, var_list=TEM_trainable_variables)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 230, in compute_gradients
    avg_grads = self._allreduce_grads(grads)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in allreduce_grads
    for grad in grads]
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in <listcomp>
    for grad in grads]
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 88, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 91, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 78, in horovod_allreduce
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0 (defined at <string>:78) ]]

nit__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0 (defined at <string>:78) ]]

Traceback (most recent call last):
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[{{node DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TEM_train.py", line 166, in <module>
    Y_end: batch_label_end
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0 (defined at <string>:78) ]]

Caused by op 'DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0', defined at:
  File "TEM_train.py", line 123, in <module>
    opt, loss, TEM_trainable_variables, loss_real = TEM_Train(X_feature, Y_action, Y_start, Y_end, LR, config)
  File "TEM_train.py", line 84, in TEM_Train
    opt = opt.minimize(cost, var_list=TEM_trainable_variables)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 230, in compute_gradients
    avg_grads = self._allreduce_grads(grads)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in allreduce_grads
    for grad in grads]
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 209, in <listcomp>
    for grad in grads]
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 88, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 91, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 78, in horovod_allreduce
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/apps/PYTHON/3.6.5_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
         [[node DistributedAdagradOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0 (defined at <string>:78) ]]

--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30833,1],62]
  Exit code:    1
--------------------------------------------------------------------------

```

**Comment by zhanglistar** [comment]
We have done this it's easy using docker, but we want to migrate to k8s.

**Comment by zhanglistar** [comment]
Maybe k8s is a better solution than slurm.

**Comment by rakshithvasudev** [comment]
# maybe this blueprint may help in some level 

#!/bin/bash
#SBATCH -N 1 # No. of nodes needed
#SBATCH -n 3
#SBATCH -J hvd_3gpu # job name
#SBATCH -o something.o
#SBATCH -e something.o
#SBATCH -C c4140,m,32gb,v100 #change the features as per your requirement, use "gpulist" to see the features of all nodes
#SBATCH -p gpuq #partition name


#load modules here
module load cuda10.0/toolkit/10.0.130
module load gcc/7.2.0
source  activate yourenv


export LD_LIBRARY_PATH=$HOME/cuda:$HOME/cuda/include:$HOME/cuda/lib64:$HOME/modules/openmpi-4.0.0-flags/bin:$HOME/modules/openmpi-4.0.0-flags/include:$LD_LIBRARY_PATH
export PATH=$HOME/cuda:$HOME/cuda/include:$HOME/cuda/lib64:$HOME/modules/openmpi-4.0.0-flags/bin:$HOME/modules/openmpi-4.0.0-flags/include:$PATH
export OMPI_MCA_btl_openib_allow_ib=1



mpirun -np 1 --mca btl_openib_allow_ib 1 python $HOME/resnet.py  --batch_size=128  --epochs=90

**Comment by alsrgv** [comment]
@LeavesLei, look for the first error in your output. `Horovod has been shut down.` just means that something happened before and execution could not continue.
