### ISSUE TITLE
Can not convert a DistributedOptimizer into a Tensor or Operation.

### ISSUE THREAD

**Issue by DavidBrayford** [horovod/horovod#1101]
I am trying to convert an existing TensorFlow to use horovod for distributed training and now get an error when trying to execute the script: 

Traceback (most recent call last):
  File "/demo_isc19/Training/Segmentation/train_hvd.py", line 227, in <module>
    _, current=sess.run([opt,loss], feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 271, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 304, in __init__
    (fetch, type(fetch), str(e)))
TypeError: Fetch argument <horovod.tensorflow.DistributedOptimizer object at 0x2abe93ef3748> has invalid type <class 'horovod.tensorflow.DistributedOptimizer'>, must be a string or Tensor. (Can not convert a DistributedOptimizer into a Tensor or Operation.)

Code segment and it fails on the line:  `_, current=sess.run([opt,loss], feed_dict=feed_dict)`

`        

        # Collect a batch of images
        for j in range(args.batch_size):
            index = i*args.batch_size + j
            id = id_list[index]
            input_image = utils.load_image(train_input_names[id])
            output_image = utils.load_image(train_output_names[id])

            with tf.device('/cpu:0'):
                input_image, output_image = data_augmentation(input_image, output_image)

                # Prep the data. Make sure the labels are in one-hot format
                input_image = np.float32(input_image) / 255.0
                output_image = np.float32(helpers.one_hot_it(label=output_image, label_values=label_values))

                input_image_batch.append(np.expand_dims(input_image, axis=0))
                output_image_batch.append(np.expand_dims(output_image, axis=0))

        if args.batch_size == 1:
            input_image_batch = input_image_batch[0]
            output_image_batch = output_image_batch[0]
        else:
            input_image_batch = np.squeeze(np.stack(input_image_batch, axis=1))
            output_image_batch = np.squeeze(np.stack(output_image_batch, axis=1))

         feed_dict={net_input:input_image_batch,net_output:output_image_batch}
        init_op = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer())
        current=sess.run(init_op)
        _, current=sess.run([opt,loss], feed_dict=feed_dict)
`

**Comment by alsrgv** [comment]
@DavidBrayford, you can get an op that minimizes loss like this: https://github.com/horovod/horovod/blob/master/examples/tensorflow_word2vec.py#L183
