### ISSUE TITLE
Using FP16 doesn't make training faster

### ISSUE THREAD

**Issue by rakshithvasudev** [horovod/horovod#1115]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) : Tensorflow -gpu
2. Framework version: 1.12.0
3. Horovod version: 0.16.1
4. MPI version: 4.0.0 with cuda and ucx support
5. CUDA version: 10.0.130
6. NCCL version: 2.4.2
7. Python version: 3.6.8
8. OS and version: RHEL 7

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes

**Question:**
I'm trying to run my model (official_resnet_tf_1.12.0.py) with FP 16 horovod compression vs without FP 16 compression. I don't see improvement in training speeds much with FP16. I ran for 2 epochs and averaged with and without FP16 compression, here are the values:

with FP16 Compression, ran for 2 epochs and averaged: 
`388.25s per epoch
`

Here is how I'm running the job: 
`mpirun -np 1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO python $HOME/models/chexnet/official_resnet_tf_1.12.0.py  --batch_size=128  --epochs=2 --use_float16=True`

without FP16 Compression, ran for 2 epochs and averaged: 
`386.77s per epoch
`

Here is how I'm running the job: 
`mpirun -np 1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO python $HOME/models/chexnet/official_resnet_tf_1.12.0.py  --batch_size=128  --epochs=2 --use_float16=False`

One other interesting thing I'm noticing, as I add FP16 compression, training time increases by a small number. It holds true for fashion mnist model I tried training too. I've attached both the scripts.

   
1) I wonder why it is not getting any better with FP16? How to do FP16 training correctly?
2) This is just FYI: I also tried setting the default float to float16, using [set_backend](https://www.tensorflow.org/api_docs/python/tf/keras/backend/set_floatx)
Which throws me an error that looks like this:

```
Traceback (most recent call last):
  File "/home/rakvee/models/chexnet/official_resnet_tf_1.12.0.py", line 500, in <module>
    main()
  File "/home/rakvee/models/chexnet/official_resnet_tf_1.12.0.py", line 483, in main
    verbose=verbose)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 86, in fit_loop
    model._make_train_function()
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 700, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 480, in get_updates
    m_t = (self.beta_1 * m) + (1. - self.beta_1) * g
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 846, in _run_op
    return tensor_oper(value, *args)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 869, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/mnt/lustrefs/rakvee/miniconda3/envs/docker_pip2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 828, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5211,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

I've attached my training script as well : [models.zip](https://github.com/horovod/horovod/files/3242585/models.zip)

**Comment by alsrgv** [comment]
@rakshithvasudev, Horovod's FP16 compression applies only to the allreduce operation - it does not affect the gradient computation on each GPU.  In your example, allreduce operations are optimized out altogether since you're training using a single process.  In general, fp16 is useful if you're training on multiple servers with an underprovisioned network across them.

**Comment by rakshithvasudev** [comment]
Thanks for pointing out @alsrgv. Like you said that was not the right way to compare, my bad! I tried running on 8 processes with and without fp16 compression for 3 epochs. Here are the numbers I was able to see: 

without fp16 : 263.52s
with fp16 :  261.68s

Does that seem reasonable? Typically how much improvements can I expect with fp16?

**Comment by alsrgv** [comment]
@rakshithvasudev, you typically don't need fp16 if you use IB.  You'd see improvements if you had 10GbE or 25GbE.

**Comment by rakshithvasudev** [comment]
Got it! Thanks @alsrgv.
