### ISSUE TITLE
Using TFOptimizer thorws error

### ISSUE THREAD

**Issue by KushalDave** [horovod/horovod#1218]
Hi, 

I am trying to use the TF optimizers instead of the keras due to the Dense conversion in Keras optimizers. Here is the solution that I am following: https://github.com/keras-team/keras/issues/4365

But when I do this with Horovod (code taken from here https://github.com/horovod/horovod/issues/42 )-
learning_rate = K.variable(1.0 * hvd.size())
print('\n\n learning_rate: ', learning_rate)
tf_opt = tf.train.AdadeltaOptimizer(learning_rate)

# Add Horovod Distributed Optimizer.
tf_opt = hvd.DistributedOptimizer(tf_opt)

# Wrap with TF optimizer with Keras optimizer, pass learning rate.
opt = keras.optimizers.TFOptimizer(tf_opt)
opt.lr = learning_rate

print("HVD size: "  + str(hvd.size()))
# Horovod: add Horovod Distributed Optimizer.

mymod.compile(optimizer=opt, loss='categorical_crossentropy')

I get the following error: 
2019-07-13T01:09:12.881Z: [1,1]<stderr>:Traceback (most recent call last):
2019-07-13T01:09:12.881Z: [1,1]<stderr>:  File "TrainGen_Attention.py", line 363, in <module>
2019-07-13T01:09:12.881Z: [1,1]<stderr>:    tf_opt = hvd.DistributedOptimizer(tf_opt)
2019-07-13T01:09:12.881Z: [1,1]<stderr>:  File "python3.5/site-packages/horovod/keras/__init__.py", line 59, in DistributedOptimizer
2019-07-13T01:09:12.881Z: [1,1]<stderr>:    sparse_as_dense)
2019-07-13T01:09:12.881Z: [1,1]<stderr>:  File "python3.5/site-packages/horovod/_keras/__init__.py", line 70, in create_distributed_optimizer
2019-07-13T01:09:12.881Z: [1,1]<stderr>:    optimizer.get_config())
2019-07-13T01:09:12.881Z: [1,1]<stderr>:AttributeError: 'AdadeltaOptimizer' object has no attribute 'get_config'

**Comment by alsrgv** [comment]
@KushalDave, since you're using TensorFlow optimizer, can you use `import horovod.tensorflow as hvd_tf` and wrap optimizer like this: `tf_opt = hvd_tf.DistributedOptimizer(tf_opt)`?
