### ISSUE TITLE
Run Tensorflow benchmarks on Horovod

### ISSUE THREAD

**Issue by mmmeee1111** [horovod/horovod#1254]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: MKL1.13
3. Horovod version: latest
4. MPI version: 4.0.1
5. CUDA version:no
6. NCCL version:no
7. Python version:
8. OS and version:Ubuntu 16.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Hi, all, I ran tensorflow benchmarks on Horovod. While I run it on synthetic data, everything works well.
$python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC

But when I test it on real dataset, CIFAR-10, I met some errors.

$python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC --data_dir=train.tfrecords

I put the input data in the same directory with benchmark scripts to make sure that everything is correct.

2019-07-25 23:49:13.115340: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 72, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 62, in main
    bench = benchmark_cnn.BenchmarkCNN(params)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1273, in __init__
    self.params.data_name)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 245, in create_dataset
    raise ValueError('Could not identify name of dataset. '
ValueError: Could not identify name of dataset. Please specify with --data_name option.

**Comment by abditag2** [comment]
See if any of these steps help:

1. put the data in `/dataset/imagenet`
2. add `--data_name imagenet` to your command.
