### ISSUE TITLE
Running on multiple nodes: Horovod stuck on hvd.init()

### ISSUE THREAD

**Issue by AbdullahNauman** [horovod/horovod#1355]
I recently set up Horovod using a conda environment and am trying to run the _mnist_keras.py_ example. The example runs properly on one process. However, when trying to run on two GPUs, it either gets stuck at **hvd.init()** or displays the following error message: 

`Traceback (most recent call last):
    File "mnist_keras_hvd.py", line 21, in <module>
        K.set_session(tf.Session(config=config))
    File "/home/anauman/.conda/envs/dist_gans/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1570, in __init__
        super(Session, self).__init__(target, graph, config=config)
    File "/home/anauman/.conda/envs/dist_gans/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 693, in __init__
        self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1
    2019-08-27 07:32:15.191776: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10` 

A simple script that simple calls hvd.init() and exists, returns the following message: 

` [node02][[34578,1],1][../../../../../opal/mca/btl/tcp/btl_tcp_endpoint.c:796:mca_btl_tcp_endpoint_complete_connect] connect() to 172.17.0.1 failed: Connection refused (111) `

Could this be happening because in my system each node has only one GPU? When trying to run the training process across two nodes with mpirun: 

`mpirun -np 2 \ 
     -H node01:1, node02:1 \
     -bind-to none -map-by slot \
     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
     -mca pml ob1 -mca btl ^openib \
      python mnist_keras_hvd.py` 
 
I get an error saying the command '-H' could not be found. Since this system has an older version of OpenMPI, and I do not have administrative access, I cannot use _horovodrun_. 

For reference, I have also attached the slurm script that I am using. 
[hvd_slurm.batch.txt](https://github.com/horovod/horovod/files/3546601/hvd_slurm.batch.txt)

What could I do to properly run Horovod? Is the problem due to having the GPUs in separate nodes, or could it be something else? I have shared my environment details below. 

**Environment:**
1. Framework: Keras  
2. Framework version: 2.2.4
3. Horovod version: 0.17.1
4. MPI version: openmpi/3.0.0-gnu
5. CUDA version: 9.0
6. Python version: 3.7.3
7. OS and version: Scientific Linux 7.4 
8. GCC version: 7.2.0

Thanks for the help!

**Comment by AbdullahNauman** [comment]
Thank you for the response! 

I was able to find and install [OpenMPI 4.0 ](https://anaconda.org/conda-forge/openmpi) within my conda environment and get _horovodrun_ working. That seems to fix the problem for now. 

Thank you again.
