### ISSUE TITLE
:tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by khayamgondal** [horovod/horovod#1370]
I have cuda 10.0 installed, and exported` LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/`. This is how I built horovod `HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/usr/include HOROVOD_CUDA_INCLUDE=/usr/local/cuda-10.0/include HOROVOD_CUDA_LIB=/usr/local/cuda-10.0/lib64 pip install --no-cache-dir horovod==v0.16.4`
I run my application using ` horovodrun -np 2 -H localhost:2  python3 horovod_trianing.py` however, it throws following error message. 

```
[root@kube17 keras-helloworld]# horovodrun -np 2 -H localhost:2  python3 horovod_trianing.py
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "horovod_trianing.py", line 3, in <module>
[1,0]<stderr>:    import horovod.tensorflow.keras as hvd
[1,0]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/__init__.py", line 28, in <module>
[1,0]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
[1,0]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,0]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,0]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 43, in _load_library
[1,0]<stderr>:    library = load_library.load_op_library(filename)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
[1,0]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "horovod_trianing.py", line 3, in <module>
[1,1]<stderr>:    import horovod.tensorflow.keras as hvd
[1,1]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/__init__.py", line 28, in <module>
[1,1]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
[1,1]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,1]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,1]<stderr>:  File "/usr/local/lib64/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 43, in _load_library
[1,1]<stderr>:    library = load_library.load_op_library(filename)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
[1,1]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
Note: I have two Tesla V100 GPUs. 
TensorFlow = 1.14

**Comment by khayamgondal** [comment]
@tgaddair I know you are super busy, any help would be appreciated :)

**Comment by khayamgondal** [comment]
okay, for some reason I needed to explicity export by doing `export HOROVOD_CUDA_HOME =/path/to `after installing the horovod and before running it.
