### ISSUE TITLE
Horovod only uses Single GPU

### ISSUE THREAD

**Issue by khayamgondal** [horovod/horovod#1378]
I have two Tesla x100 GPUs, I am invoking the script as `horovodrun -np 2 -H localhost:2  python3 horovod_trianing.py ` 
In the logs I see that tensorflow initiates the connection to both GPUs, I also see the python processes running on both GPUs but the GPU utilizaiton for one GPU is always zero. Please see the nvidia-smi below,
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   39C    P0    44W / 250W |   **1966MiB / 16130MiB** |     **42%**      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   37C    P0    35W / 250W |    **853MiB / 16130MiB** |      **0%**      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    371272      C   python3                                      977MiB |
|    0    371273      C   python3                                      977MiB |
|    1    371272      C   python3                                      421MiB |
|    1    371273      C   python3                                      421MiB |
+-----------------------------------------------------------------------------+
In my script I have 
```
hvd.init()
# Horovod: pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = '0,1'
K.set_session(tf.Session(config=config))
```
What I am missing here? I am using TF 1.14, horovod==0.16.4

**Comment by tgaddair** [comment]
Hey @khayamgondal, please replace this line:

```
config.gpu_options.visible_device_list = '0,1'
```

with

```
config.gpu_options.visible_device_list = str(hvd.local_rank())
```

By setting the visible device list to `0,1`, you're telling *both* processes to use *both* GPUs. When there's limited model parallelism, each process will default to just using the first GPU it sees. 

So in this case, both processes are attempting to use GPU:0, which is resulting in GPU:1 being unused.  What you want to do instead is to have process 0 use GPU:0 and process 1 use GPU:1 so they don't step on each other. That's what achieve by setting visible device list to `local_rank()`.

**Comment by khayamgondal** [comment]
Thanks @tgaddair that throws the following error
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].
[1,0]<stderr>:  while setting up XLA_GPU_JIT device number 1
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "horovod_trianing.py", line 100, in <module>
[1,1]<stderr>:    history = model.fit(X, y, epochs=epochs, batch_size=BATCH_SIZE, callbacks=callbacks, verbose=1 if hvd.rank() == 0 else 0)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
[1,1]<stderr>:    steps_name='steps_per_epoch')
[1,1]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration
[1,1]<stderr>:    batch_outs = f(ins_batch)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
[1,1]<stderr>:    run_metadata=self.run_metadata)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
[1,1]<stderr>:    run_metadata_ptr)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:   [[{{node training/Adadelta_Allreduce/HorovodAllreduce_Adadelta_1_gradients_conv1d_BiasAdd_grad_BiasAddGrad_0}}]]
```

**Comment by tgaddair** [comment]
Looks like your process is only able to see one GPU.  Have you set `CUDA_VISIBLE_DEVICES`?  If so, try unsetting that first.

**Comment by khayamgondal** [comment]
Yes, I already have export CUDA_VISIBLE_DEVICES=0,1, keras mnist example works fine and I see it uses both GPUs. I have posted my source code below if that helps,
```
#!/usr/bin/python3

import horovod.tensorflow.keras as hvd
import tensorflow as tf
from tensorflow.keras import backend as K
import os,json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import datetime


#os.environ['HOROVOD_GLOO_IFACE'] = 'em2'

hvd.init()
# Horovod: pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
K.set_session(tf.Session(config=config))


EPOCHS = 500
BATCH_SIZE = 64

np.random.seed(0)

def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back)]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 1])
    return np.array(dataX), np.array(dataY)

data_folder = 'data'
data_file = 'IBM.csv'
data_path = os.path.join(data_folder, data_file) 

stock_data = pd.read_csv(data_path, usecols=['Volume','High', 'Low']) # IBM Stocks value for last 20 years.
stock_data = stock_data.apply(pd.to_numeric, errors='coerce')#.astype('float32') 
stock_data["average"] = (stock_data["High"] + stock_data["Low"] )/2 # We will be using avegrage stock value and the volume of the stock sold as our input features. 
stock_data = stock_data.drop(['High', 'Low'], axis=1) # we dont need high and low now so drop these columns

# we will be normalizing our input so it lies between 0-1
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))
input_data = sc.fit_transform(stock_data).astype('float32') # convert the object type to float32 for VNNI support

lookback= 15
X, y = create_dataset(input_data, lookback)

#Dividing in traning and testing datasets
test_size=int(.30 * len(X))
X_test = X[len(X) - test_size:]
y_test = y[len(y) - test_size:]
X = X[:len(X) - test_size]
y = y[:len(y) - test_size]

print('Training samples size {}'.format(X.shape) )
print('Testing samples size {}'.format(X_test.shape) )



model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X.shape[1], X.shape[2])))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(1))

# Horovod: adjust number of epochs based on number of GPUs.
epochs = int(math.ceil(EPOCHS / hvd.size()))

# Horovod: adjust learning rate based on number of GPUs.
opt = tf.keras.optimizers.Adadelta(1.0 * hvd.size())
# Horovod: add Horovod Distributed Optimizer.
opt = hvd.DistributedOptimizer(opt)
model.compile(optimizer=opt, loss='mse')  
if hvd.rank() == 0:
    model.summary()

callbacks = [
    # Horovod: broadcast initial variable states from rank 0 to all other processes.
    # This is necessary to ensure consistent initialization of all workers when
    # training is started with random weights or restored from a checkpoint.
    hvd.callbacks.BroadcastGlobalVariablesCallback(0),
    # Horovod: average metrics among workers at the end of every epoch.
    #
    # Note: This callback must be in the list before the ReduceLROnPlateau,
    # TensorBoard or other metrics-based callbacks.
    hvd.callbacks.MetricAverageCallback(),
]
# Horovod: save checkpoints only on worker 0 to prevent other workers from corrupting them.
if hvd.rank() == 0:
    callbacks.append(tf.keras.callbacks.ModelCheckpoint('./horovod-cps/checkpoint-{epoch}.h5'))
    callbacks.append(tf.keras.callbacks.TensorBoard(log_dir='boardlogs/{}'.format(datetime.datetime.now()))) #report logs to tensorboard

 
if hvd.rank() == 0:
    start_time = datetime.datetime.now()
history = model.fit(X, y, epochs=epochs, batch_size=BATCH_SIZE, callbacks=callbacks, verbose=1 if hvd.rank() == 0 else 0)
if hvd.rank() == 0:
    end_time = datetime.datetime.now()
    save_dir = 'output'
    if not os.path.exists(save_dir):
        os.mkdir(save_dir)
    model.save(os.path.join(save_dir, 'keras-helloworld-saved.h5'))
    print ('Training time {}'.format(end_time-start_time))
    with open(os.path.join(save_dir, 'keras-history-helloworld-saved.json'), 'w') as f:
        json.dump(history.history, f)
        
    print('inputs: ', [input.op.name for input in model.inputs])
    print('outputs: ', [output.op.name for output in model.outputs])


```

**Comment by tgaddair** [comment]
Hey @khayamgondal, this appears to be an upstream bug with `tf.keras.callbacks.TensorBoard` in TensorFlow 1.14 (see: https://github.com/tensorflow/tensorflow/issues/31451).

I was able to repro this issue in my environment with two GPUs and TF 1.14.  Removing the `TensorBoard` callback or rolling back to TensorFlow 1.12 fixed the issue.  If you're comfortable with either of those solutions, those would be the easiest workarounds for now.

I'll follow-up with the TensorFlow folks and see if they can look into this for you.

Regards.

**Comment by khayamgondal** [comment]
Thanks man, really appreciate for your help, I know you are super busy :)  I commented out the tensorboard calllback for now.

**Comment by jegesh** [comment]
I'm experiencing this with TF2.2, Horovod 0.19.5, on an AWS p3 instance that has 4 Tesla v100 GPUs.  Dropping the Tensorboard callback didn't solve it, however. I also tried setting `CUDA_VISIBLE_DEVICES` and using `mpirun` with '-oversubscribe' as suggesting [here](https://github.com/horovod/horovod/issues/75). Still no dice.  
Any further suggestions would be greatly appreciated

**Comment by jegesh** [comment]
After some additional poking around, I discovered that when I set up the horovod environment it worked fine with the examples, but after installing additional dependencies for my application, even the examples stopped working properly (they also showed single-GPU utilization).  So I know it's not an issue with my code, it's the environment. 
Comparing the environments, I see library version differences in the following packages:
gast
icu
ca-certificates
hdf5
pip
openssl
rsa

the following packages are missing from the 'bad' env:
nodejs

The non-working env has a couple dozen packages that the clean, working env doesn't, for the most part gdal, opencv, and their dependencies.

Could any of these libraries be affecting the GPU visibility?

**Comment by jegesh** [comment]
Ok, so it seems the real issue is that I was running python using `sudo` in order to solve a `CUPTI_ERROR_INSUFFICIENT_PRIVILEGES` I was getting and was unable to solve any other way.  Now I'm back to focusing on a better workaround for the `CUPTI_ERROR_INSUFFICIENT_PRIVILEGES` issue

**Comment by johnniev5** [comment]
@tgaddair I also faced the issue, hvd can only find the first single one GPU, but I have two, tested with 'tf.test.is_gpu_available()', works well, both found, but used 'hvd.local_rank()', only GPU:0 found and used, 'hvd.size()' shows only one, I'm using TF1.15.

>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
2021-01-02 18:36:59.259379: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-01-02 18:36:59.279977: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2021-01-02 18:36:59.280378: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5624d3025030 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-02 18:36:59.280419: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-02 18:36:59.280965: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-01-02 18:36:59.449098: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.449473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
2021-01-02 18:36:59.449546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.449836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:02:00.0
2021-01-02 18:36:59.449979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-01-02 18:36:59.450605: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-01-02 18:36:59.451203: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-01-02 18:36:59.451357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-01-02 18:36:59.452096: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-01-02 18:36:59.452595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-01-02 18:36:59.454154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-02 18:36:59.454259: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.454638: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.454966: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.455285: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.455567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2021-01-02 18:36:59.455597: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-01-02 18:36:59.456327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-02 18:36:59.456339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2021-01-02 18:36:59.456347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N 
2021-01-02 18:36:59.456351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N 
2021-01-02 18:36:59.456438: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.456763: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.457083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.457403: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.457698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 7052 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-01-02 18:36:59.457936: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.458263: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-02 18:36:59.458551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:1 with 7471 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080, pci bus id: 0000:02:00.0, compute capability: 7.5)
2021-01-02 18:36:59.459590: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5624d1438ed0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-02 18:36:59.459603: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2021-01-02 18:36:59.459609: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080, Compute Capability 7.5
True
>>> import horovod.tensorflow as hvd
>>> hvd.init()
>>> hvd.local_rank()
0
>>> hvd.size()
1
>>>
