### ISSUE TITLE
ValueError: named_parameters was specified, but one or more model parameters were not named.

### ISSUE THREAD

**Issue by MichaelMonashev** [horovod/horovod#1389]
**Environment:**
1. Framework: PyTorch
2. Framework version: torch 1.2.0
3. Horovod version: horovod 0.18.1
4. MPI version:  openmpi 4.0.1
5. CUDA version: cuda 10.1
6. NCCL version: nccl 2.4.8
7. Python version: Python 3.6.8
8. OS and version: Linux 31607 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
9. GCC version: gcc 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

Execute following commands:
```
git clone https://github.com/MichaelMonashev/style-based-gan-pytorch.git
cd style-based-gan-pytorch
horovodrun -np 1 -H localhost:1 python3 hvd_train.py --mixing --loss r1 --sched 123
```
You will get errors:
```
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "hvd_train.py", line 323, in <module>
[1,0]<stderr>:    g_optimizer = hvd.DistributedOptimizer(g_optimizer, named_parameters=generator.generator.named_parameters())
[1,0]<stderr>:  File "/home/xxx/.local/lib/python3.6/site-packages/horovod/torch/__init__.py", line 252, in DistributedOptimizer
[1,0]<stderr>:    compression, backward_passes_per_step)
[1,0]<stderr>:  File "/home/xxx/.local/lib/python3.6/site-packages/horovod/torch/__init__.py", line 79, in __init__
[1,0]<stderr>:    '%s' % ', '.join(str(id) for id in unnamed_param_ids))
[1,0]<stderr>:ValueError: named_parameters was specified, but one or more model parameters were not named. Python object ids: 140692123238976, 140692123241568, 140692123240128, 140692123241784, 140692123239840, 140692123240920, 140692123239624, 140692123240776, 140692123238760, 140692123241352, 140692123242000, 140692123241136, 140692123240560, 140692123239408, 140692123240344, 140692123239192
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14960,1],0]
  Exit code:    1
```

**Comment by abditag2** [comment]
Hard to stay without seeing the code.

**Comment by tchaton** [comment]
Hey @abditag2,

Any updates on this issue.

Best,
T.C

**Comment by tgaddair** [comment]
Hey @tchaton, the issue here is that some parameters in the model are not named. We can workaround this by either (1) restructuring the model to ensure those parameters are named, or (2) just using `parameters` instead of `named_parameters` when providing to Horovod. This will work so long as the order of the parameters is deterministic across workers (in most cases it is).
