### ISSUE TITLE
pytorch distributed training  which tow GPUs run doesn't work

### ISSUE THREAD

**Issue by molyswu** [horovod/horovod#1411]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:pytorch
3. Horovod version:0.18.1
4. MPI version:3.1.2
5. CUDA version:10.0
6. NCCL version:2.4.8.1
7. Python version:python3.5
8. OS and version:unbuntu16.04
9. GCC version:4.9

I tried to  horovodrun  distributed training my pytorch-horovod project  ,a GPU run is working,
if the machine>=2 gpus have errors:
 $ horovodrun -np 2  -H localhost:2 python3  train_1.py

[1,1]<stdout>:Total loss is  220.58815002441406 ETA is  6:38:39.486213
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_1.py", line 174, in <module>
[1,0]<stderr>:    loss.backward()
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 118, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 93, in backward
[1,0]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/horovod/torch/__init__.py", line 132, in hook
[1,0]<stderr>:    "Gradients were computed more than "
[1,0]<stderr>:AssertionError: Gradients were computed more than backward_passes_per_step times before call to step(). Increase backward_passes_per_step to accumulate gradients locally.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_1.py", line 174, in <module>
[1,1]<stderr>:    loss.backward()
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 118, in backward
[1,1]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 93, in backward
[1,1]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/horovod/torch/__init__.py", line 132, in hook
[1,1]<stderr>:    "Gradients were computed more than "
[1,1]<stderr>:AssertionError: Gradients were computed more than backward_passes_per_step times before call to step(). Increase backward_passes_per_step to accumulate gradients locally.
add code:
1.hvd.init()#init horovod
    torch.manual_seed(opt.seed)
2. if use_cuda
     torch.cuda.set_device(hvd.local_rank())  # A GPU and a Process Allocation  4
       torch.cuda.manual_seed(opt.seed
3.optimizer = hvd.DistributedOptimizer(
    optimizer, named_parameters=model.named_parameters(),
    compression=compression,**kwargs,
   backward_passes_per_step=opt.batches_per_allreduce)

4.optimizer = optim.SGD(model.parameters(), lr=(opt.base_lr *opt.batches_per_allreduce* hvd.size()) ,momentum=opt.momentum, weight_decay=opt.wd)

5.optimizer = hvd.DistributedOptimizer(optimizer,named_parameters=model.named_parameters(),
    compression = hvd.Compression.fp16 if opt.fp16_allreduce else hvd.Compression.none)

6.hvd.broadcast_parameters(model.state_dict(), root_rank=0)
    hvd.broadcast_optimizer_state(optimizer, root_rank=0)

command:
  1 gpu:  horovodrun -np 1  -H localhost:1 python3  train_1.py
  2 gpus: horovodrun -np 2  -H localhost:2 python3  train_1.py

Thank you for your help

**Comment by molyswu** [comment]
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train.py", line 210, in <module>
[1,0]<stderr>:    loss.backward()
[1,0]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
[1,0]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,0]<stderr>:RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 1; 10.73 GiB total capacity; 1006.24 MiB already allocated; 501.62 MiB free; 71.76 MiB cached)

**Comment by molyswu** [comment]
Traceback (most recent call last):
[1,1]<stderr>:  File "train_1.py", line 160, in <module>
[1,1]<stderr>:    optimizer = hvd.DistributedOptimizer(optimizer,named_parameters=net.parameters(),compression = compression,backward_passes_per_step=args.batches_per_allreduce)
[1,1]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/horovod/torch/__init__.py", line 252, in DistributedOptimizer
[1,1]<stderr>:    compression, backward_passes_per_step)
[1,1]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/horovod/torch/__init__.py", line 62, in __init__
[1,1]<stderr>:    raise ValueError('named_parameters should be a sequence of '
[1,1]<stderr>:ValueError: named_parameters should be a sequence of tuples (name, parameter), usually produced by model.named_parameters().
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_1.py", line 160, in <module>
[1,0]<stderr>:    optimizer = hvd.DistributedOptimizer(optimizer,named_parameters=net.parameters(),compression = compression,backward_passes_per_step=args.batches_per_allreduce)
[1,0]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/horovod/torch/__init__.py", line 252, in DistributedOptimizer
[1,0]<stderr>:    compression, backward_passes_per_step)
[1,0]<stderr>:  File "/home/ai/anaconda3/lib/python3.7/site-packages/horovod/torch/__init__.py", line 62, in __init__
[1,0]<stderr>:    raise ValueError('named_parameters should be a sequence of '
[1,0]<stderr>:ValueError: named_parameters should be a sequence of tuples (name, parameter), usually produced by model.named_parameters().
