### ISSUE TITLE
ValueError('Neither MPI nor Gloo support has been built. )

### ISSUE THREAD

**Issue by linjiaqin** [horovod/horovod#1412]
**Environment:**
1. Framework: (TensorFlow，keras)
2. Framework version:  
3. Horovod version: 0.18
4. MPI version: 4.0.0
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. OS and version: ubuntu 14.04
9. GCC version: 4.8

(horovod) hadoop3@cu07:~/openmpi-4.0.0/examples$ mpirun -np 8 hello_c
Hello, world, I am 2 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 5 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 7 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 0 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 1 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 3 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 4 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
Hello, world, I am 6 of 8, (Open MPI v4.0.0, package: Open MPI linjiaqing@cu07 Distribution, ident: 4.0.0, repo rev: v4.0.0, Nov 12, 2018, 110)
(horovod) hadoop3@cu07:~/openmpi-4.0.0/examples$ cd 
(horovod) hadoop3@cu07:~$ cd horovod_test/
(horovod) hadoop3@cu07:~/horovod_test$ horovodrun -np 4 -H localhost:4 python keras_mnist.py
Traceback (most recent call last):
  File "/software/hadoop3/anaconda3/envs/horovod/bin/horovodrun", line 21, in <module>
    run.run()
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/run.py", line 721, in run
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).

**Bug report:**
I have install the openmpi in my clusters. Some nodes worked, but some  raise ValueError('Neither MPI nor Gloo support has been built. )

**Comment by tgaddair** [comment]
Hey @linjiaqin, the error message is coming from `horovodrun`, so it will only test on the machine you're running it on.  It looks like Horovod did not install correctly.  Can you try reinstalling with `HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod` along with any other flags you used before?  If that succeeds, then there may be something else going on.

**Comment by linjiaqin** [comment]
@tgaddair 
hello, I have reinstall horovod with the command you mentioned. But the problem still exists. Some nodes can work. But some nodes can't.
There are 10 nodes in my clusters. And the home directories of every node are the same because we mount the home directories to a shared disk by NFS. That means the home directories of every nodes are the same. Horovod is same too. But the root directories of each nodes are different.  But I have install MPI in those nodes under root directories.   

hadoop3@cu07:~$ HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod
Requirement already satisfied: horovod in ./anaconda3/envs/zoo/lib/python3.6/site-packages (0.18.1)
Requirement already satisfied: six in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from horovod) (1.12.0)
Requirement already satisfied: pyyaml in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from horovod) (5.1.2)
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from horovod) (1.12.3)
Requirement already satisfied: psutil in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from horovod) (5.6.3)
Requirement already satisfied: cloudpickle in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from horovod) (1.2.2)
Requirement already satisfied: pycparser in ./anaconda3/envs/zoo/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.19)
hadoop3@cu07:~$ horovodrun -np 4 -H localhost:4 python keras_mnist.py
Traceback (most recent call last):
  File "/software/hadoop3/anaconda3/envs/zoo/bin/horovodrun", line 21, in <module>
    run.run()
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/run.py", line 721, in run
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).
hadoop3@cu07:~$

**Comment by marcfielding1** [comment]
Err if you're on Ubuntu I've been through a lot of pain, is there a reason you're on 14.04? I you fancy being a guinea pig you could try testing out my [tutorial/PR](https://github.com/horovod/horovod/pull/1422/files?short_path=7537f1f#diff-7537f1fd3b643da36d205172669476c1) although it's geared at 18.04 - it looks like you've got the same kind of version conflicts I was suffering with(i've had the same errors) - FYI I'm not a team member so try this at your own risk. (ie make sure it's a throw away system/image not something you can't afford to start again on.)

**Comment by linjiaqin** [comment]
@tgaddair @marcfielding1 
after using " --verbose". I find thees error information. What should I do next?
tensorflow.python.framework.errors_impl.NotFoundError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so)

**Comment by marcfielding1** [comment]
@linjiaqin Err looks like the version of python and the version of that lib are out of sync see [this](https://github.com/tensorflow/tensorflow/issues/26378) - did you try my suggestion above?

**Comment by linjiaqin** [comment]
@marcfielding1 
I have try your suggestion above, but it occurred the same errors. I use gcc-5.5, openmpi4.0.1.
Are there any problem with the version?

**Comment by marcfielding1** [comment]
Heya, erm so you did a fresh install run through that post, what version of ubuntu are you on?

**Comment by linjiaqin** [comment]
@marcfielding1 
My OS is ubuntu 14.04.
When I delete the conda env, recreate a new one and install with "HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod" .It occur "horovod didn't build with MPI".  These are the logs:
**tensorflow.python.framework.errors_impl.NotFoundError: /software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
Extension tensorflow was NOT built with MPI.**

**Comment by marcfielding1** [comment]
Err actually did you install tensorflow before installing horovod?

**Comment by marcfielding1** [comment]
Err actually did you install tensorflow before installing horovod?

**Comment by linjiaqin** [comment]
@marcfielding1 
yes， I install tensorflow before installing horovod . But when I uninstall tensoflow and horovod. Then i install the horovod again. But It occurs no tensorflow module errors as below.

**gcc -pthread -B /software/hadoop3/anaconda3/envs/horovod/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -I/software/hadoop3/anaconda3/envs/horovod/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /software/hadoop3/anaconda3/envs/horovod/compiler_compat -L/software/hadoop3/anaconda3/envs/horovod/lib -Wl,-rpath=/software/hadoop3/anaconda3/envs/horovod/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /software/hadoop3/anaconda3/envs/horovod/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/software/hadoop3/anaconda3/envs/horovod/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /software/hadoop3/anaconda3/envs/horovod/compiler_compat -L/software/hadoop3/anaconda3/envs/horovod/lib -Wl,-rpath=/software/hadoop3/anaconda3/envs/horovod/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.so
    error: import tensorflow failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-install-7b069awm/horovod/setup.py", line 72, in check_tf_version
        import tensorflow as tf
    ModuleNotFoundError: No module named 'tensorflow'
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /software/hadoop3/anaconda3/envs/horovod/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7b069awm/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7b069awm/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5z0wu5kf/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.**

**Comment by marcfielding1** [comment]
Sorry I deleted that comment re tensorflow installing order, this could be quite a few things, I am going to look at a 14.04 install out of morbid curiosity this weekend, **Are you tied to Ubuntu 14.04?** - **Did you follow step by step the instructions in that draft PR?** - I mean every single step, every single command?

**Comment by XueCangQiuYe** [comment]
hello ,everyone
i got same question, when i run pytorch_mnist.py (official example)

Environment:

Framework: (TensorFlow，pytroch)
Framework version:1.14, 1.12
Horovod version: 0.18
MPI version: 4.0.2
CUDA version:10.0
NCCL version:
Python version: 3.6.8
OS and version: centos7
GCC version: 4.9.4


`[root@vm-gpu-2 horovod_pytorch]# horovodrun -np 2 -H ip1:1,ip2:1 python pytorch_mnist.py
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 736, in run
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).
`
I am sure I have installed openmpi 4.0.2
and also run this command:
`[root@vm-gpu-2 horovod_pytorch]# HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1  pip install --no-cache-dir horovod
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: horovod in /usr/local/lib64/python3.6/site-packages
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: psutil in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: pyyaml in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.0->horovod)
`
how can i fix this problem?

**Comment by tgaddair** [comment]
Hi @XueCangQiuYe, can you try `pip uninstall horovod` and rerun `HOROVOD_WITH_MPI=1 
 HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod`.  It looks like Horovod did not install because it was already installed.

**Comment by hoangcuong2011** [comment]
For some unknown reasons to me I got this issue as well. Nonetheless by uninstalling horovod and installing it again with HOROVOD_WITH_MPI=1 flag helps, as suggested by @tgaddair. Thx @tgaddair

**Comment by discort** [comment]
Having the same issue on ubuntu 20.04

```
(.env) discort@cloud-4:~/package$ echo $LD_LIBRARY_PATH
:/usr/local/cuda/lib64/
(.env) discort@cloud-4:~/package$ HOROVOD_WITH_MPI=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_PYTORCH=1 pip install horovod==0.22.1 --no-cache-dir
Looking in indexes: https://pypi.org/simple, 
Collecting horovod==0.22.1
  Downloading horovod-0.22.1.tar.gz (3.3 MB)
     |████████████████████████████████| 3.3 MB 21.4 MB/s
Requirement already satisfied: cloudpickle in ./.env/lib/python3.8/site-packages (from horovod==0.22.1) (1.6.0)
Requirement already satisfied: psutil in ./.env/lib/python3.8/site-packages (from horovod==0.22.1) (5.8.0)
Requirement already satisfied: pyyaml in ./.env/lib/python3.8/site-packages (from horovod==0.22.1) (5.3.1)
Requirement already satisfied: cffi>=1.4.0 in ./.env/lib/python3.8/site-packages (from horovod==0.22.1) (1.14.6)
Requirement already satisfied: pycparser in ./.env/lib/python3.8/site-packages (from cffi>=1.4.0->horovod==0.22.1) (2.20)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.22.1-cp38-cp38-linux_x86_64.whl size=301436519 sha256=08d3d99dea18827f9605a66a59ec789f21aa9b34855c7603d70ac0cdaecf1468
  Stored in directory: /tmp/pip-ephem-wheel-cache-t98x8iop/wheels/40/87/60/e894d5c7501b8c6cc8a666f7330dac526efeafc355cbf3f62a
Successfully built horovod
Installing collected packages: horovod
Successfully installed horovod-0.22.1
(.env) discort@cloud-4:~/package$ horovodrun --check-build
2021-07-15 12:30:05.066337: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:30:07.243079: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:30:09.423882: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:30:11.611629: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:30:13.811400: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:30:16.009015: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Horovod v0.22.1:

Available Frameworks:
    [ ] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [ ] MPI
    [ ] Gloo
    

(.env) discort@cloud-4:~/package$ horovodrun -np 2 python -m main.py
2021-07-15 12:31:23.085814: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 12:31:25.285057: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/discort/package/.env/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/runner/launch.py", line 770, in run_commandline
    _run(args)
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/runner/launch.py", line 760, in _run
    return _run_static(args)
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/runner/launch.py", line 617, in _run_static
    _launch_job(args, settings, nics, command)
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/runner/launch.py", line 730, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/runner/launch.py", line 708, in run_controller
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).

(.env) discort@cloud-4:~/package$ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.torch as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/torch/__init__.py", line 35, in <module>
    from horovod.torch import elastic
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/torch/elastic/__init__.py", line 17, in <module>
    from horovod.torch.mpi_ops import init, shutdown
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 34, in <module>
    raise e
  File "/home/discort/package/.env/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 31, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /home/discort/package/.env/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaGraphRetainUserObject

(.env) discort@cloud-4:~/package$ ldd .env/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so
  linux-vdso.so.1 (0x00007ffcc97e8000)
  libmpi.so.40 => /usr/local/lib/libmpi.so.40 (0x00007f61b5418000)
  libcudart.so.11.0 => /usr/local/cuda/lib64/libcudart.so.11.0 (0x00007f61b519a000)
  libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f61b5173000)
  libc10.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libc10.so (0x00007f61b4edc000)
  libtorch.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch.so (0x00007f61b4cc8000)
  libtorch_cpu.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so (0x00007f61a2b82000)
  libtorch_python.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_python.so (0x00007f61a179d000)
  libc10_cuda.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so (0x00007f61a156d000)
  libtorch_cuda.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so (0x00007f6161a5f000)
  libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6161a3c000)
  libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6161822000)
  libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f61616d1000)
  libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f61616b6000)
  libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f61614c4000)
  /lib64/ld-linux-x86-64.so.2 (0x00007f61c37a4000)
  libopen-rte.so.40 => /usr/local/lib/libopen-rte.so.40 (0x00007f6161207000)
  libopen-pal.so.40 => /usr/local/lib/libopen-pal.so.40 (0x00007f6160ef2000)
  librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6160ee7000)
  libgomp-a34b3233.so.1 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libgomp-a34b3233.so.1 (0x00007f6160cbb000)
  libcudart-80664282.so.10.2 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libcudart-80664282.so.10.2 (0x00007f6160a3a000)
  libshm.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libshm.so (0x00007f6160833000)
  libnvToolsExt-3965bdd0.so.1 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libnvToolsExt-3965bdd0.so.1 (0x00007f6160629000)
  libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f616060b000)
  libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f61605de000)
  libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f61605d9000)
```

any ideas? @tgaddair

**Comment by discort** [comment]
UPD.
resolved after installing nccl and rebuilding horovod

**Comment by foxbrucecui** [comment]
Hello,Sincerely expect get your help.I also meet this problem,but  run Deepmd-kit in dcu. I just can only use 1 DCU when training models.
I found Horovod in the install from source code.md to support multiple GPU acceleration,
I also found ROCM's compatibility for NCCL https://github.com/ROCmSoftwarePlatform/rccl
I follow it step by step,but it didn't work.
Do you have experience in using multiple DCU training?
Heartfelt thanks.

Framework: (TensorFlow，keras)
Horovod version: 0.23.0
MPI version: 4.0.2
ROCM version:2.9.0
NCCL version:2.11.4
Python version: 3.6
OS and version: Centos 7.6
GCC version: 7.3.1

**Comment by surak** [comment]
I try this on a macOS which has openmpi, and I end up at the same problem with pip.

```bash
$ HOROVOD_CPU_OPERATIONS=GLOO HOROVOD_WITH_MPI=1 HOROVOD_WITH_GLOO=1 HOROVOD_WITH_TENSORFLOW=1  pip install horovod
...
Successfully installed cffi-1.15.1 cloudpickle-2.2.0 horovod-0.26.1 packaging-21.3 psutil-5.9.4 pycparser-2.21 pyparsing-3.0.9 pyyaml-6.0

$ horovodrun -np 2 python3 ./keras_mnist.py                                                                  

Traceback (most recent call last):
  File "/Users/surak/Devel/dl_on_supercomputers/venv/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/Users/surak/Devel/dl_on_supercomputers/venv/lib/python3.10/site-packages/horovod/runner/launch.py", line 837, in run_commandline
    _run(args)
  File "/Users/surak/Devel/dl_on_supercomputers/venv/lib/python3.10/site-packages/horovod/runner/launch.py", line 827, in _run
    return _run_static(args)
  File "/Users/surak/Devel/dl_on_supercomputers/venv/lib/python3.10/site-packages/horovod/runner/launch.py", line 685, in _run_static
    _launch_job(args, settings, nics, command)
  File "/Users/surak/Devel/dl_on_supercomputers/venv/lib/python3.10/site-packages/horovod/runner/launch.py", line 800, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/Users/surak/Devel/dl_on_supercomputers/venv/lib/python3.10/site-packages/horovod/runner/launch.py", line 778, in run_controller
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).
```

**Comment by wwj-2017-1117** [comment]
i meet the same problem，too
