### ISSUE TITLE
Tensorflow 2 GPU Config error

### ISSUE THREAD

**Issue by JohnTaylor2000** [horovod/horovod#1458]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 2 stable
3. Horovod version: horovod/0.18.1-py36-cuda90-tf2
4. MPI version: openmpi/3.1.4-ofed45
5. CUDA version:9.0
6. NCCL version:nccl/2.3.7-cuda90
7. Python version: python/3.6.1  
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

When running on 64 GPUs (16 nodes) the following error occurs:-

   tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range

Does not occur 16 GPUs (4 nodes).

**Comment by tgaddair** [comment]
Hey @JohnTaylor2000, is the `IndexError` coming from `gpus[hvd.local_rank()]`?  Can you try checking the lengths of that list on each on each node?

```
import socket
gpus = tf.config.experimental.list_physical_devices('GPU')
if hvd.local_rank() == 0:
    print(socket.gethostname(), len(gpus))
```

I suspect one of the nodes is reporting a different number of GPUs than the others.

Can you also try running the `tensorflow_mnist.py` example with an earlier version of TensorFlow and see if it produces a similar error?  I'd be curious to see if this behavior is unique to TF 2.0.

**Comment by JohnTaylor2000** [comment]
Travis,

I will give this a try and let you know how I go.

Best wishes,

John

**Comment by uniwuppes** [comment]
I'm getting the same error when trying to run the `tensorflow2_keras_mnist.py` example on 2 nodes with 1 GPU each using `-np 2`.
I added these 2 prints for debugging:
```
if gpus:
    print("physical devices: %d" % len(gpus))
    print("local rank: %d" % hvd.local_rank())
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
```
And I'm getting this output:
```
[1,0]<stdout>:physical devices: 1
[1,0]<stdout>:local rank: 0
[1,1]<stdout>:physical devices: 1
[1,1]<stdout>:local rank: 1
```
Why is local_rank = 1 for the second node?

**Comment by atteggiani** [comment]
Hello @JohnTaylor2000, 

I am encountering the same issue. 
Did you manage to solve it?

**Comment by JohnTaylor2000** [comment]
Sorry, I can't recall the specific solution. A node may have needed rebooting. I use the following code to keep track of the Horovod initialisation:-

hvd.init()

print ('***hvd.size ', hvd.size(),' hvd.rank', hvd.rank(), 'hvd.local_rank() ', hvd.local_rank())

# Horovod: pin GPU to be used to process local rank (one GPU per process)

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
gpus = tf.config.experimental.list_physical_devices('GPU')
print(' gpus = ', gpus)
if hvd.local_rank() == 0:
    print("Socket and len gpus = ",socket.gethostname(), len(gpus))
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

**Comment by JohnTaylor2000** [comment]
The issue will be with slurm and how you request access to the GPUs. I have been using LSF and PBS pro.

**Comment by Himscipy** [comment]
Hi
I am experiencing similar issue as reported here.
```
Traceback (most recent call last):
  File "/rcfs/projects/src/test_TFHVD.py", line 27, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
2021-12-20 17:08:22.422100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "/rcfs/projects/src/test_TFHVD.py", line 27, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
2021-12-20 17:08:22.425091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "/rcfs/project/src/test_TFHVD.py", line 27, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
2021-12-20 17:08:22.426774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```
I am using following versions 
Tensorflow-gpu=2.4.2 (installed via pip)
Horovod=0.21.3 (installed via pip)

```
(horovodEnv) [shar306@ hvd_install]$ horovodrun --check-build
2021-12-20 17:19:28.917474: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-20 17:20:02.439492: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-20 17:20:08.080366: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-20 17:20:10.943063: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-20 17:20:15.700330: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-20 17:20:19.349915: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Horovod v0.21.3:

Available Frameworks:
    [X] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo 
```

Slurm scheduler is used in my case as well and I have tried @JohnTaylor2000  recommendations but no change in the outcome. Any inputs will be really appreciated. Thank you.

**Comment by JohnTaylor2000** [comment]
Did you print out the 'gpus' array and hvd.local_rank()?

gpus = tf.config.experimental.list_physical_devices('GPU') # I assume that this works with your version of TensorFlow
print(' gpus = ', gpus)

**Comment by Himscipy** [comment]
Hi John,

yes, here is the output

```
hvd.local_rank() = 4
 gpus =  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Name: /physical_device:GPU:0   Type: GPU
hvd.local_rank() = 0
 gpus =  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Name: /physical_device:GPU:0   Type: GPU
hvd.local_rank() = 3
 gpus =  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Name: /physical_device:GPU:0   Type: GPU
hvd.local_rank()= 1
 gpus =  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Name: /physical_device:GPU:0   Type: GPU
hvd.local_rank() = 2
```

**Comment by Himscipy** [comment]
For me following things fixed the issue

I added following in my script before importing tensorflow.
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```

I also commented the CUDA_VISIBLE_DEVICE
```
#SBATCH  --job-name=TestHVD
#SBATCH -N 1                       # -N the number of nodes (machines) you want
#SBATCH -t 4:00:00                 # -t the timelimit for the job  HH:MM:SS format
#SBATCH --ntasks-per-node=4 
#SBATCH -n 1                       # -n the number of cpus you want
#SBATCH --gres=gpu:4               # --gres=gpu: the number of gpus you want
#SBATCH --exclusive 
#SBATCH -o ./LOG/RUNTF_HVD_TestOutput-%j.txt        # -o standard output destination
#SBATCH -e ./LOG/RUNTF_HVD_TestError-%j.txt         # -e standard error destination

# Load the Conda Environment...!


mpirun -np 4 \
-bind-to none -map-by slot \
-x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
-mca pml ob1 -mca btl ^openib \
python $PYSCRIPT
```

This fixed the issue and I could use the all the available GPU's.

**Comment by JohnTaylor2000** [comment]
FYI - this is what the print out of my GPUs variable looks like:-

Num GPUs Available:  4
 gpus =  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')]

Note that you are only showing one GPU?

You are have also listed:-
hvd.local_rank() = 4

This would only occur on a system with 5 GPUs on a node. Python indexing has 0,1,2,3 on a 4 GPU system, and 4 would be out of range?

**Comment by TaeyoungHong** [comment]
The simple solution in my case is to use "-npernode" such as
mpirun -np 4 -npernode 2 ~~~ 

This option is the same as #SBATCH --ntasks-per-node=2 in SLURM job script.

**Comment by silpara** [comment]
I was using a single machine with 4 GPUs and facing the same error because each process was only seeing GPU:0. Adding `os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"` solved the problem for me.
