### ISSUE TITLE
AssertionError: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by rb-determined-ai** [horovod/horovod#1564]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) `tensorflow-gpu==1.14.0`
2. Framework version: `tensorflow-gpu==1.14.0`
3. Horovod version: `5fa1d7aea2c89fdfa15a688aa413ea49a480ab38`
4. MPI version: N/A
5. CUDA version: 10.0
6. NCCL version: tip of master
7. Python version: 3.6.9
8. OS and version: Ubuntu 18.04
9. GCC version: 4.8 (I think that's what gets selected)

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Bug report:**

There appears to be some regression introduced by the commit `5fa1d7aea2c89fdfa15a688aa413ea49a480ab38`.  At some point some process is doing something that is apparently not acceptable, and the whole job crashes.  I have no problem with the commit just before it.

I have two GCP ubuntu machines with the configuration above.  Horovod was installed like this:

```
git co --recurse-submodules 5fa1d7aea2c89fdfa15a688aa413ea49a480ab38
env \
    HOROVOD_WITHOUT_MPI=1 \
    HOROVOD_WITH_GLOO=1 \
    HOROVOD_WITH_TENSORFLOW=1 \
    HOROVOD_WITHOUT_PYTORCH=1 \
    HOROVOD_WITHOUT_MXNET=1 \
    HOROVOD_GPU_ALLREDUCE=NCCL \
    pip install . -v
```

Then I ran it like this:

    horovodrun -np 2 -H localhost:1,rb2:1 --network-interface ens8 --gloo --verbose --verbose python3 learn_horovod.py

And here is the full output:

```
Filtering local host names.
Remote host found: rb2
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Interfaces on all the hosts were successfully checked.
Common interface found: ens8
Checking whether extension tensorflow was built with Gloo.
Extension tensorflow was NOT built with Gloo.
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 73, in _target_fn
    ext = importlib.import_module('.' + ext_base_name, 'horovod')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 43, in <module>
    has_gpu = gpu_available('tensorflow')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 103, in gpu_available
    ext_base_name, available_fn, 'running with GPU', verbose) or False
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 90, in _check_extension_lambda
    p.start()
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Checking whether extension torch was built with Gloo.
Extension torch was NOT built with Gloo.
Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/torch/__init__.py", line 28, in <module>
    __file__, 'mpi_lib_v2')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 51, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 73, in _target_fn
    ext = importlib.import_module('.' + ext_base_name, 'horovod')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/torch/__init__.py", line 31, in <module>
    __file__, 'mpi_lib', '_mpi_lib')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 51, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
Checking whether extension mxnet was built with Gloo.
Extension mxnet was NOT built with Gloo.
Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 73, in _target_fn
    ext = importlib.import_module('.' + ext_base_name, 'horovod')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/mxnet/__init__.py", line 23, in <module>
    __file__, 'mpi_lib')
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/common/util.py", line 51, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.mxnet has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_MXNET=1 to debug the build error.
Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/pedl/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/run/run.py", line 860, in run_commandline
    _run(args)
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/run/run.py", line 828, in _run
    _launch_job(args, remote_host_names, settings, common_intfs, command)
  File "/home/rb/miniconda3/envs/pedl/lib/python3.6/site-packages/horovod/run/run.py", line 839, in _launch_job
    raise ValueError('Gloo support has not been built.  If this is not expected, ensure CMake is installed '
ValueError: Gloo support has not been built.  If this is not expected, ensure CMake is installed and reinstall Horovod with HOROVOD_WITH_GLOO=1 to debug the build error.
```

The file `learn_horovod.py` looks like:

```
import sys
import tensorflow as tf

import horovod.tensorflow as hvd

# Initialize Horovod
hvd.init()

# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
print(f"using gpu {hvd.local_rank()}")
config.gpu_options.visible_device_list = str(hvd.local_rank())

# Build dataset
data_ds = tf.data.Dataset.range(1,100).batch(10).repeat()
label_ds = tf.data.Dataset.range(1,100).map(lambda x: 2*x).batch(10).repeat()
ds = tf.data.Dataset.zip({"data":data_ds, "label":label_ds})
# Deref dataset
iterator = ds.make_one_shot_iterator()
record = iterator.get_next()
# Build model
w = tf.get_variable("weight", [1], dtype=tf.float32, initializer=tf.zeros_initializer)
pred = w * tf.cast(record["data"], tf.float32)
loss = tf.losses.mean_squared_error(pred, tf.cast(record["label"], tf.float32))

# Optimizer
opt = tf.train.AdagradOptimizer(0.01 * hvd.size())

# Add Horovod Distributed Optimizer
opt = hvd.DistributedOptimizer(opt)

# Add hook to broadcast variables from rank 0 to all other processes during
# initialization.
hooks = [hvd.BroadcastGlobalVariablesHook(0), tf.train.StopAtStepHook(last_step=4)]

# Make training operation
train_op = opt.minimize(loss, global_step=tf.train.create_global_step())

# Save checkpoints only on worker 0 to prevent other workers from corrupting them.
checkpoint_dir = '/tmp/train_logs' if hvd.rank() == 0 else None

# The MonitoredTrainingSession takes care of session initialization,
# restoring from a checkpoint, saving to a checkpoint, and closing when done
# or an error occurs.
with tf.train.MonitoredTrainingSession(
    checkpoint_dir=checkpoint_dir, config=config, hooks=hooks
) as mon_sess:
    while not mon_sess.should_stop():
        # Perform synchronous training.
        mon_sess.run(train_op)
```

**Comment by abditag2** [comment]
@tgaddair

**Comment by tgaddair** [comment]
Hey @rb-determined-ai, I'm looking into this now.  I'll let you know as soon as I have a fix.

**Comment by tgaddair** [comment]
Hey @rb-determined-ai, thanks for reporting this error.  Can you take a look at #1570 and see if that fixes your issue?

**Comment by rb-determined-ai** [comment]
@tgaddair Thanks for the quick fix!  I had a chance to test it, and I can confirm that this fixes my issue!
