### ISSUE TITLE
RuntimeError: cuda runtime error (10) : invalid device ordinal

### ISSUE THREAD

**Issue by shividhar** [horovod/horovod#1586]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.1+cu100
3. Horovod version: 0.18.2
4. MPI version: 3.1.1
5. CUDA version: 10.0
6. NCCL version: nccl_2.1.2
7. Python version: 3.5.2
8. OS and version: Centos 7.4
9. GCC version: 6.3.0

**Bug report:**
I'm trying to run the `pytorch_synthetic_benchmark.py` script on two nodes each with 1 GPU.

```
[node003:17711] Warning: could not find environment variable "PS1"
[1,0]<stdout>:[1576424636.175486] [node003:17738:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2119.78
[1,1]<stdout>:[1576424636.175812] [node003:17739:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2119.78
[1,0]<stdout>:[1576424636.188890] [node003:17738:0]      ib_device.c:205  UCX  ERROR ibv_query_device() returned 38: Success
[1,1]<stdout>:[1576424636.188988] [node003:17739:0]      ib_device.c:205  UCX  ERROR ibv_query_device() returned 38: Success
[1,1]<stdout>:[1576424636.256925] [node003:17739:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
[1,1]<stdout>:[1576424636.256948] [node003:17739:0]      ib_dev.c:544  MXM  ERROR ibv_query_device() returned 38: Function not implemented
[1,1]<stderr>:[node003:17739:1][bcol_mlnx_p2p_component.c:586:bcol_mlnx_p2p_mxm_init] MLNXP2P mxm_init return error: Input/output error
[1,1]<stderr>:[node003:17739:1][bcol_mlnx_p2p_component.c:438:hmca_bcol_mlnx_p2p_init_query] MLNXP2P failed to init mxm
[1,1]<stderr>:[node003:17739] Error: coll_hcoll_module.c:311 - mca_coll_hcoll_comm_query() Hcol library init failed
[1,0]<stdout>:[1576424636.257444] [node003:17738:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
[1,0]<stdout>:[1576424636.257476] [node003:17738:0]      ib_dev.c:544  MXM  ERROR ibv_query_device() returned 38: Function not implemented
[1,0]<stderr>:[node003:17738:0][bcol_mlnx_p2p_component.c:586:bcol_mlnx_p2p_mxm_init] MLNXP2P mxm_init return error: Input/output error
[1,0]<stderr>:[node003:17738:0][bcol_mlnx_p2p_component.c:438:hmca_bcol_mlnx_p2p_init_query] MLNXP2P failed to init mxm
[1,0]<stderr>:[node003:17738] Error: coll_hcoll_module.c:311 - mca_coll_hcoll_comm_query() Hcol library init failed
[1,1]<stderr>:THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py", line 41, in <module>
[1,1]<stderr>:    torch.cuda.set_device(hvd.local_rank())
[1,1]<stderr>:  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/torch/cuda/__init__.py", line 300, in set_device
[1,1]<stderr>:    torch._C._cuda_setDevice(device)
[1,1]<stderr>:RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:37
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
  Process name: [[36107,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by tgaddair** [comment]
Hey @shividhar, a few questions:

1. Are you setting `CUDA_VISIBLE_DEVICES`?  If so, what is the value?
2. Can you try running `python -c "import torch; torch.cuda.set_device(0)"` on each machine and verify that it works or raises a similar issue.
3. Can you run `nvidia-smi` on each machine and verify that both GPUs are visible?

**Comment by shividhar** [comment]
I wasn't setting `CUDA_VISIBLE_DEVICES`, but even after setting it I get the same error. I set `CUDA_VISIBLE_DEVICES=0`.

No exceptions were raised when I ran `python -c "import torch; torch` on each of the compute nodes.

`nvidia-smi` ran successfully on all the compute nodes and both GPUs were visible.

For additional context I'm ran the command `horovodrun -np 2 -H node003:1,node004:1 --verbose python3 /home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py`. The command is being run through SLURM.

**Comment by shividhar** [comment]
I did some more debugging and for some reason, horovod is executing torch.cuda.set_device(1) with a device number other than specified by `CUDA_VISIBLE_DEVICES ` which causes the program to crash.

**Comment by tgaddair** [comment]
Hey @shividhar, the line that sets the device in the synthetic benchmark is `torch.cuda.set_device(hvd.local_rank())`.  Since you're running with 1 worker per host, this will `hvd.local_rank()` will always be 0.  In general, we recommend not setting `CUDA_VISIBLE_DEVICES` as it can cause communication issues within a host using NCCL.

Can you clarify what value you have set for `CUDA_VISIBLE_DEVICES` vs what device ordinal Horovod is giving to `torch.cuda.set_device`?

One other thing you can try would be to run with `horovodrun --mpi-threads-disable ...` as that may be causing these issues as well.

**Comment by shividhar** [comment]
Hi @tgaddair, to clarify I initially didn't set `CUDA_VISIBLE_DEVICES`, but it doesn't work in either case.

Case 0 (without `CUDA_VISIBLE_DEVICES` set): The device ordinal Horovod sets in `torch._C._cuda_setDevice(device)` is `0` and `1`.
Case 1 (with `CUDA_VISIBLE_DEVICES` set):  The device ordinal Horovod sets in `torch._C._cuda_setDevice(device)` is `0` and `1`

Both cases error out.

Note: Updating OpenMPI to 4.0.2 mitigated some of the errors, but the Horovod error persists.
```
[1,0]<stdout>:[1576433286.754196] [node003:31939:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2386.97
[1,1]<stdout>:[1576433286.755010] [node003:31940:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2386.97
[1,0]<stdout>:[1576433286.767720] [node003:31939:0]      ib_device.c:205  UCX  ERROR ibv_query_device() returned 38: Success
[1,1]<stdout>:[1576433286.767813] [node003:31940:0]      ib_device.c:205  UCX  ERROR ibv_query_device() returned 38: Success
[1,0]<stdout>:[1576433286.836254] [node003:31939:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
[1,0]<stdout>:[1576433286.836281] [node003:31939:0]      ib_dev.c:544  MXM  ERROR ibv_query_device() returned 38: Function not implemented
[1,0]<stderr>:[node003:31939:0][bcol_mlnx_p2p_component.c:586:bcol_mlnx_p2p_mxm_init] MLNXP2P mxm_init return error: Input/output error
[1,0]<stderr>:[node003:31939:0][bcol_mlnx_p2p_component.c:438:hmca_bcol_mlnx_p2p_init_query] MLNXP2P failed to init mxm
[1,0]<stderr>:[node003:31939] Error: coll_hcoll_module.c:311 - mca_coll_hcoll_comm_query() Hcol library init failed
[1,1]<stdout>:[1576433286.836764] [node003:31940:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
[1,1]<stdout>:[1576433286.836794] [node003:31940:0]      ib_dev.c:544  MXM  ERROR ibv_query_device() returned 38: Function not implemented
[1,1]<stderr>:[node003:31940:1][bcol_mlnx_p2p_component.c:586:bcol_mlnx_p2p_mxm_init] MLNXP2P mxm_init return error: Input/output error
[1,1]<stderr>:[node003:31940:1][bcol_mlnx_p2p_component.c:438:hmca_bcol_mlnx_p2p_init_query] MLNXP2P [1,1]<stderr>:failed to init mxm
[1,1]<stderr>:[node003:31940] Error: coll_hcoll_module.c:311 - mca_coll_hcoll_comm_query() Hcol library init failed
```

**Comment by shividhar** [comment]
Hi @tgaddair,
I did some more testing and found out that in the `pytorch_synthetic_benchmark` Horovod was setting the `local_rank` twice on the same host (first 0 and then 1) instead of 0 on both hosts. Will try to debug further.

**Comment by shividhar** [comment]
@tgaddair I figured out my mistake. It was a problem with my SLURM configuration not related to Horovod.

For general reference, I had to specify `--ntasks-per-node=1` to force the command to run exactly once. 

However, the OpenMPI error still stands and upgrading OpenMPI to 4.0+ fixed that issue.

**Comment by tgaddair** [comment]
Thanks for clarifying the fix @shividhar.  Glad you got it working!
