### ISSUE TITLE
AttributeError: module 'horovod.torch' has no attribute 'Average'

### ISSUE THREAD

**Issue by taylorwwebb** [horovod/horovod#1590]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.1
3. Horovod version: 0.18.2
4. MPI version: 4.0.2
5. CUDA version: 10.2
6. NCCL version: 2.5.6
7. Python version: 3.6.9
8. OS and version: ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? NA
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? NA
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
Tried to run the pytorch_mnist.py example, using this command:

horovodrun -np 4 -H localhost:4 python3 ./pytorch_mnist.py

And got this error message:

[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "./pytorch_mnist.py", line 120, in <module>
[1,3]<stderr>:    op=hvd.Adasum if args.use_adasum else hvd.Average)
[1,3]<stderr>:AttributeError: module 'horovod.torch' has no attribute 'Average'
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "./pytorch_mnist.py", line 120, in <module>
[1,2]<stderr>:    op=hvd.Adasum if args.use_adasum else hvd.Average)
[1,2]<stderr>:AttributeError: module 'horovod.torch' has no attribute 'Average'
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "./pytorch_mnist.py", line 120, in <module>
[1,0]<stderr>:    op=hvd.Adasum if args.use_adasum else hvd.Average)
[1,0]<stderr>:AttributeError: module 'horovod.torch' has no attribute 'Average'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "./pytorch_mnist.py", line 120, in <module>
[1,1]<stderr>:    op=hvd.Adasum if args.use_adasum else hvd.Average)
[1,1]<stderr>:AttributeError: module 'horovod.torch' has no attribute 'Average'

Any idea what I might be doing wrong?

**Comment by taylorwwebb** [comment]
When I remove the 'op' argument (op=hvd.Adasum if args.use_adasum else hvd.Average) from the call to hvd.DistributedOptimizer, the script runs just fine, but still curious what's going on here...

**Comment by tgaddair** [comment]
Hey @taylorwwebb, the master branch of Horovod has changes that have not yet been released, including `hvd.Adasum`.  For now, I would use the version of examples from the `v0.18.2` tag [here](https://github.com/horovod/horovod/tree/v0.18.2):

```
git clone --branch v0.18.2 https://github.com/horovod/horovod.git
```

**Comment by taylorwwebb** [comment]
Got it, that one ran just fine, thanks!
