### ISSUE TITLE
Timeline not parsed by chrome tracing

### ISSUE THREAD

**Issue by LaVieEstDure** [horovod/horovod#1595]
**Environment:**
1. Framework: pytorch
2. Framework version: 1.2.0
3. Horovod version: 0.18.2
4. MPI version: 4.0.1
5. CUDA version: 10.1
6. NCCL version: N/A
7. Python version: 3.5.6
8. OS and version: Ubuntu 16.04
9. GCC version: 5.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before? ✅
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? ✅
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? ✅
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? ✅

**Bug report:**
When using multi-node horovod with GPU (-np 2 -H A:1,B:1), the timeline.json produced is not parseable by chrome://tracing (chrome v79.0), failing by giving an error
```
SyntaxError: Unexpected token 
 in JSON at position 721980
    at JSON.parse (<anonymous>)
    at new TraceEventImporter (chrome://tracing/tracing.js:5477:19)
    at Import.createImporter_ (chrome://tracing/tracing.js:1331:8)
    at chrome://tracing/tracing.js:1325:167
    at Task.run (chrome://tracing/tracing.js:2499:95)
    at runAnother (chrome://tracing/tracing.js:2502:371)
    at runTask (chrome://tracing/tracing.js:2307:57)
    at processIdleWork (chrome://tracing/tracing.js:2312:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:2305:81)
```
After some experimentation with JSON validators, it seems to be related to the multi-line tensor representations present in the JSON. [Here's](https://drive.google.com/open?id=14vk1reFv3pii5MxYQaeE7NHCrVdwzgo5) a link to my timeline.

**Comment by LaVieEstDure** [comment]
Oh and stripping the whitespace of the json and joining it back `new_file.write("".join(file.read().strip()))` fixes it.
