### ISSUE TITLE
Running Horovod with exactly 2 GPUs on the same node fails

### ISSUE THREAD

**Issue by shividhar** [horovod/horovod#1634]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.1+cu100
3. Horovod version: 0.18.2
4. MPI version: 3.1.1
5. CUDA version: 10.0
6. NCCL version: nccl_2.1.2
7. Python version: 3.5.2
8. OS and version: Centos 7.4
9. GCC version: 6.3.0

**Your question:**
When I try to run Horovod on a single node with exactly 2 GPUs, NCCL gives the following error
`node205:10645:10653 [0] transport/p2p.cu:431 WARN failed to open CUDA IPC handle : 30 unknown error`.

After which Horovod errors out with
```
Traceback (most recent call last):
  File "/home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py", line 127, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/cm/shared/package/python/3.5.2/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/cm/shared/package/python/3.5.2/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py", line 79, in benchmark_step
    optimizer.step()
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/__init__.py", line 193, in step
    self.synchronize()
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/__init__.py", line 157, in synchronize
    output = synchronize(handle)
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/mpi_ops.py", line 443, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclCommInitRank failed: unhandled cuda error
Traceback (most recent call last):
  File "/home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py", line 127, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/cm/shared/package/python/3.5.2/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/cm/shared/package/python/3.5.2/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py", line 79, in benchmark_step
    optimizer.step()
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/__init__.py", line 193, in step
    self.synchronize()
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/__init__.py", line 157, in synchronize
    output = synchronize(handle)
  File "/var/scratch/sdhar/venv_pytorch/lib/python3.5/site-packages/horovod/torch/mpi_ops.py", line 443, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclCommInitRank failed: unhandled cuda error
```

Strangely enough, if I try to run Horovod using 1, 3, or more GPUs then this error disappears.

I can fix this error with 2 GPUs if I set `NCCL_P2P_DISABLE=1`, but then the GPUs don't directly communicate.

There are similar issues like #148 and #110, but they don't address this issue exactly.

**Comment by tgaddair** [comment]
Hey @shividhar, can you share the `horovodrun` or `mpirun` command you are using?

**Comment by shividhar** [comment]
The `mpirun` command I'm using

```
mpirun -np 2 \
   -H node433:2 \
   -bind-to none -map-by slot \
   -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
   -x NCCL_P2P_DISABLE=0 \
   -mca pml ob1 -mca btl ^openib \
   -mca btl_tcp_if_include eth0 \
   --verbose \
   python3 /home/sdhar/tudelft-research/pytorch/pytorch_synthetic_benchmark.py --batch-size=32
```

**Comment by zrss** [comment]
/cc

i met the same thing, i doubt it's relative to the GPU deivce ...

**Comment by Stonesjtu** [comment]
Afaik, GeForce GPU like 2080ti does not support p2p access anymore.

**Comment by shividhar** [comment]
@tgaddair This issue still persists. Do you have any advice?

**Comment by tgaddair** [comment]
Hey @shividhar, apologies for dropping the ball on this.  Nothing looks out of the ordinary at first glance.  It may help to see the full log, if you can paste it into a gist.

@romerojosh @nvcastet do you have any thoughts on what could cause this NCCL issue?

**Comment by nvcastet** [comment]
@shividhar Having the full log into a gist would help. Are you running baremetal or within container?
Most of the errors I got from NCCL in the past were due to limited shared memory on the container or the box. You can check the size with `df -h /dev/shm`, usually you would want a few GB.
