### ISSUE TITLE
Horovod on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by HussainTaj-W** [horovod/horovod#1663]
**Environment:**
1. Framework: **TensorFlow**
2. Framework version: **2.0.0**
3. Horovod version: **0.18.2**
4. MPI version: **4.0.2**
5. CUDA version: _None_
6. NCCL version: _None_
7. Python version: **3.7.0**
8. OS and version: **Windows 10 (Ubuntu 18.04, WSL)**
9. GCC version: _None_

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A.
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes.

**Question:**
Is it possible to run Horovod on Windows Subsystem for Linux? If so then what am I doing wrong?

**My Setup**

I have two machines running Ubuntu 18.04 WSL on Windows 10. I've followed the official installation instructions from [here.](https://github.com/horovod/horovod#install)

 - I'm working inside an Anaconda environment.
 - ssh passwordless sign-in is properly set up and working.
 - All network interface names (Windows as well as inside WSL) are "eth0".

I'm trying to run [this tensorflow2_keras_mnist](https://github.com/horovod/horovod/blob/master/examples/tensorflow2_keras_mnist.py) example.

**Command**
```
horovodrun -np 2 -H thisMachine:12353,otherMachineOnLAN:12353 python tensorflow2_keras_mnist.py
```

**Observations:**

- The same procedure works if done on two true Ubuntu machines. (No WSL)
- It works fine on a single node.

Stacktrace of exception on two nodes:
```
Traceback (most recent call last):
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/bin/horovodrun", line 21, in <module>
    run.run()
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/run.py", line 692, in run
    settings, fn_cache=fn_cache)
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/run.py", line 236, in _driver_fn
    settings.num_hosts)]
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/run.py", line 235, in <listcomp>
    settings.verbose) for index in range(
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/task/task_service.py", line 72, in __init__
    retries=retries)
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/common/service/task_service.py", line 133, in __init__
    retries=retries)
  File "/home/spark_cluster/anaconda3/envs/spark_cluster_env/lib/python3.7/site-packages/horovod/run/common/util/network.py", line 164, in __init__
    'Linux.'.format(service_name=service_name, addresses=addresses))
horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to horovodrun task service #1 on any of the following addresses: {'eth0': [('192.168.10.24', 6215)]}.

One possible cause of this problem is that horovodrun currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
```

**Comment by tgaddair** [comment]
Hey @HussainTaj-W, can you print the output of running `ifconfig -a` on `otherMachineOnLAN`?

**Comment by HussainTaj-W** [comment]
@tgaddair, sure, here's the output.

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.15  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::103:fbe3:2a71:4ea3  prefixlen 64  scopeid 0x0<global>
        ether f0:4d:a2:30:4b:ee  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=64<RUNNING>  mtu 1500
        inet 169.254.133.70  netmask 255.255.0.0
        inet6 fe80::397a:4959:1a4f:8546  prefixlen 64  scopeid 0x0<global>
        ether 5e:5f:05:3e:ad:e1  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x0<global>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by zenetio** [comment]
I think this will not work in WSL because the current version os WSL still does not recognize the GPU installed.
