### ISSUE TITLE
DUPLICATE_NAME_ERROR when training a GAN system with mxnet

### ISSUE THREAD

**Issue by feevos** [horovod/horovod#1679]
Dear all, 

I am trying to train a "modified" GAN system, based on mxnet. It is basically a domain adaptation problem, where there are two networks, say a Generator G, and a discriminator T.  The whole training process is wrapped in a class, where it holds the trainers and the networks. This is a portion of the code where I define relative horovod+mxnet functions/trainers etc: 

```python
        # @@@@@@@@@@@@@@@@@@@ DEFINE THESE IN CONFIGURATION DICTIONARY @@@@@@@@@@@@@@@@@@@
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@        
        self.netG =  self.config[C.C_MODEL_G]# Features NET
        self.netT =  self.config[C.C_MODEL_T] # Talahassee network 

        self.ctxG =  self.config[C.C_CTX_G]
        self.ctxT =  self.config[C.C_CTX_T]


        # Initialize networks -- takes care the case where there is no flname to load params.
        self._initialize_network(self.netG, self.config[C.C_INITIALIZER_G], self.ctxG, self.config[C.C_FLNM_G_LOAD_PARAMS])
        self._initialize_network(self.netT, self.config[C.C_INITIALIZER_T], self.ctxT, self.config[C.C_FLNM_T_LOAD_PARAMS])

        # This should take place ONLY if the parameters were randomly initialized 
        # @@@@@@@@@@@@ HVD BROADCAST ALL PARAMETERS TO ALL WORKERRS @@@@@@@@@@@@@@@
        if self.config[C.C_FLNM_G_LOAD_PARAMS] is None and self.netG.collect_params() is not None:
                hvd.broadcast_parameters(self.netG.collect_params(), root_rank=0)

        if self.config[C.C_FLNM_T_LOAD_PARAMS] is None and self.netT.collect_params() is not None:
                hvd.broadcast_parameters(self.netT.collect_params(), root_rank=0)
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@




        # Initialize Trainer object - if you want to load previously saved states. 
        # TODO: Add functional definition 
        #### self.trainer = self.init_trainer(flname_states=self.config[C.C_FLNM_LOAD_STATES])
        self.optG = mx.optimizer.create(self.config[C.C_OPTIMIZER_G_NAME], **self.config[C.C_TRAINER_G_PARAMS])
        self.trainerG =  hvd.DistributedTrainer(self.netG.collect_params(), self.optG)

        self.optT = mx.optimizer.create(self.config[C.C_OPTIMIZER_T_NAME], **self.config[C.C_TRAINER_T_PARAMS])
        self.trainerT =  hvd.DistributedTrainer(self.netT.collect_params(), self.optT)

        # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

```

and this is the step forward_backward operation that trains the system. 

```python
    def _forward_backward_update_TS_MCTX(self, data1, data2, labelG, labelT, labelTtrick):
        """
        self.netG is loaded into self.ctxG, and self.netT onto self.ctxT. _data, _label are initially on context cpu()
        """
        # manually zero grad for second update     

        # @@@@@@@@@@@@@@@@ Train self.netG @@@@@@@@@@@@@@@@@@@@@@@@@@@
        self._zero_grad(self.netG)
        # Train first G using Tanimoto loss on data.
        data1 = data1.as_in_context(self.ctxG)
        data2 = data2.as_in_context(self.ctxG)
        labelG = labelG.as_in_context(self.ctxG)
        with autograd.record():
            # First argument is PREDICTIONS, second LABELS
            preds, featuresG = self.netG(data1,data2)
            lossG = self.lossG(preds, labelG)


            #print ("lossG stuff::{0}, {1}".format([pred.shape for pred in preds], featuresG.shape))

        lossG.backward()
        self.trainerG.step( self.config[C.C_BATCH_SIZE] )
        # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


        # ************* Train Talahassee ****************************  
        self._zero_grad(self.netT)
        with autograd.record():
            featuresGT =  featuresG.detach().as_in_context(self.ctxT)
            listOfpredsT =  self.netT(featuresGT)

            #print ("lossT stuff::predsT {0}, labelT{1}".format([pred.shape for pred in listOfpredsT ], labelT.shape))
            labelT = labelT.as_in_context(self.ctxT)
            lossT = self.lossTG( listOfpredsT, labelT)
        lossT.backward()
        self.trainerT.step( self.config[C.C_BATCH_SIZE] )
        # This is outside the autograd.record state 
        # ***********************************************************


        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        # Train G to make Tallahassee make a mistake.
        self._zero_grad(self.netG)
        with autograd.record():
            _, newfeatures = self.netG(data1,data2)
            newfeatures = newfeatures.as_in_context(self.ctxT)
            predsT =  self.netT(newfeatures)
            predsT2 = [pred.as_in_context(self.ctxG) for pred in predsT]
            labelTtrick = labelTtrick.as_in_context(self.ctxG)
            lossTG = self.lossTG(predsT2, labelTtrick)
        lossTG.backward()
        self.trainerG.step(self.config[C.C_BATCH_SIZE])
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


        lossG = lossG.as_in_context (mx.cpu(hvd.local_rank()))
        lossT = lossT.as_in_context (mx.cpu(hvd.local_rank()))
        lossTG = lossTG.as_in_context (mx.cpu(hvd.local_rank()))

        #print (lossG.shape)
        #print (lossT.shape)
        #print (lossTG.shape)



        return lossG.mean().asscalar(), lossT.mean().asscalar(), lossTG.mean().asscalar() # Releases memory 
```
I set up the distributed network contexts in a way that the Generator lives in even GPU number, and Discriminator T in odd: 
```python
        self[C.C_CTX_G]             = mx.gpu(hvd.local_rank() * 2 + 0)  if len( list( mx.test_utils.list_gpus()) ) > 0 else mx.cpu(hvd.local_rank()*2+0)
        self[C.C_CTX_T]             = mx.gpu(hvd.local_rank() * 2 + 1)  if len( list( mx.test_utils.list_gpus()) ) > 0 else mx.cpu(hvd.local_rank()*2+0)
```
In my tests I run on a single node with 4 GPUs, split in 2 sets of two GPUs (due to memory issues). 
The parts of the submit script (SLURM) is: 

```shell
#!/bin/bash

#SBATCH --job-name="Tlhse"

## debugging
#SBATCH --nodes=1
#SBATCH -t 00:10:00

### True run
#####SBATCH --nodes=24
#####SBATCH -t 23:40:00

#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=2 #####  Specifies how many hvd.local_rank() exist, for these models 2, since a model is split accross 2 gpus
#SBATCH --mem=16gb

#SBATCH --mail-type=ALL
#SBATCH --mail-user=foivos.diakogiannis@data61.csiro.au

##### Number of total processes 
echo " "
echo " Nodelist       := " $SLURM_JOB_NODELIST
echo " Number of nodes:= " $SLURM_JOB_NUM_NODES
echo " NGPUs per node := " $SLURM_GPUS_PER_NODE 
echo " Ntasks per node:= "  $SLURM_NTASKS_PER_NODE
echo " Ntasks         := "  $SLURM_NTASKS
echo " "

#### Load modules 
module load cuda/10.1.168
module load nccl/2.4.8-cuda101
module load cudnn/v7.6.4-cuda101
module load gcc/9.2.0
module load openmpi/4.0.0-simple-gcc ### Working 
module load hpc-x/2.4.0

module list

####    Use MPI for communication with Horovod
export HOROVOD_GPU_ALLREDUCE=MPI
export HOROVOD_GPU_ALLGATHER=MPI
export HOROVOD_GPU_BROADCAST=MPI

####   Produce a timeline for debugging purposes
####export HOROVOD_TIMELINE=./timeline.json ### Do not use for production runs, it produces very large files 
export NCCL_DEBUG=DEBUG

export HOROVOD_CACHE_CAPACITY=4096

ulimit -s 20480 ####### Horovod recommends 10240 for this

echo "Running on multiple nodes and GPU devices"
echo ""
echo "Run started at:- "
date

##### Actual executable 
####mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_TIMELINE  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -x HOROVOD_MPI_THREADS_DISABLE=1 -mca pml ob1 -mca btl ^openib python ./mxnet_mnist.py ######## SUCCESSS -- slower with THREADS_DISABLE. 

mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_CACHE_CAPACITY  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib python ./main.py ######## SUCCESSS 

echo "Run completed at:- "
date
```

Now I get the following error (some times I get python memory map error, this is random). 
```shell
[22:03:09] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[22:03:09] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[22:03:21] src/operator/nn/./cudnn/cudnn_pooling-inl.h:398: 0D pooling is not supported by cudnn, MXNet 0D pooling is applied.
[22:03:21] src/operator/nn/./cudnn/cudnn_pooling-inl.h:398: 0D pooling is not supported by cudnn, MXNet 0D pooling is applied.
[22:03:22] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[22:03:22] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    trainer.train()
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 319, in train
    lossG, lossT, lossTG  = self.step_epoch(e,lr_policy)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 276, in step_epoch
    lossG, lossT, lossTG = self.step_batch(d1, d2, lG, lT, lTtrick)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 246, in step_batch
    losses = self._forward_backward_update_TS_MCTX(data1, data2, labelG, labelT, labelTtrick)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 234, in _forward_backward_update_TS_MCTX
    return lossG.mean().asscalar(), lossT.mean().asscalar(), lossTG.mean().asscalar() # Releases memory
  File "/scratch1/dia021/Software/mxnet/ndarray/ndarray.py", line 2385, in asscalar
    return self.asnumpy()[0]
  File "/scratch1/dia021/Software/mxnet/ndarray/ndarray.py", line 2367, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/scratch1/dia021/Software/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    trainer.train()
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 319, in train
    lossG, lossT, lossTG  = self.step_epoch(e,lr_policy)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 276, in step_epoch
    lossG, lossT, lossTG = self.step_batch(d1, d2, lG, lT, lTtrick)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 246, in step_batch
    losses = self._forward_backward_update_TS_MCTX(data1, data2, labelG, labelT, labelTtrick)
  File "/home/dia021/Projects/WA_l8SAR_2018/Talahassee/hvd_F256_d5_ts_group_cmtsk/agoge_base_da_hvd.py", line 234, in _forward_backward_update_TS_MCTX
    return lossG.mean().asscalar(), lossT.mean().asscalar(), lossTG.mean().asscalar() # Releases memory
  File "/scratch1/dia021/Software/mxnet/ndarray/ndarray.py", line 2385, in asscalar
    return self.asnumpy()[0]
  File "/scratch1/dia021/Software/mxnet/ndarray/ndarray.py", line 2367, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/scratch1/dia021/Software/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

```

I've tracked down the code and it seems this is related to the DUPLICATE_NAME_ERROR. This is quite similar with the pytorch implementation error from #784 but I haven't managed to solve it. By the way, I can train standard models in a distributed way successfully. 

Any suggestions, most welcome. 
Thank you very much for your time.

**Comment by feevos** [comment]
Some additional info: the problem appears only when I request Generator and Discriminator to live in different contexts (i.e. gpus). In this case, neither setting ```grad_req```  to 'null' (as suggested in #784) worked or solved the problem.  If I manage to fit both Generator and Discriminator on the same GPU everything is running fine.

**Comment by denfromufa** [comment]
@feevos don't you need to explicitly communicate the losses between generator and discriminator on separate GPU workers?

**Comment by feevos** [comment]
@denfromufa  not the losses, the corresponding layers that the losses depend on. I do that in the code snipet above. For the record, I managed to squeeze all of the networks in a single GPU, and then the naming problem went away.
