### ISSUE TITLE
DataType string not in list of allowed values variables -- ctr model(embedding+fc)

### ISSUE THREAD

**Issue by ivankxt** [horovod/horovod#1734]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13.1
3. Horovod version: 0.19
4. MPI version:4.0.0
5. CUDA version: release 10.0, V10.0.130
6. NCCL version: 2.4
7. Python version: 3.6
8. OS and version: Ubuntu 16.04.4 LTS
9. GCC version: 4.9.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
I'm running ctr model(embedding+fc) implementation adopted for Horovod on gpu cluster (one 
machine with 2 gpus) and I get the following error：
By the way, the code is working on the local machine when horovod codes removed. 

`Traceback (most recent call last):
  File "bin/model_trainer.py", line 714, in <module>
    tf.app.run()
  File "/opt/train/lib/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bin/model_trainer.py", line 708, in main
    model_trainer.train(FLAGS.model_dir, files)
  File "bin/model_trainer.py", line 334, in train
    bcast = hvd.broadcast_global_variables(0)
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 175, in broadcast_global_variables
    return broadcast_variables(_global_variables(), root_rank)
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 148, in broadcast_variables
    return broadcast_group(variables, root_rank)
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 134, in broadcast_group
    for var in variables])
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 134, in <listcomp>
    for var in variables])
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 183, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 256, in horovod_broadcast
  File "/opt/train/lib/tensorflow/python/framework/op_def_library.py", line 610, in _apply_op_helper
    param_name=input_name)
  File "/opt/train/lib/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'tensor' has DataType string not in list of allowed values: uint8, int8, uint16, int16, int32, int64, float16, float32, float64, bool
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[61494,1],0]
  Exit code:    1
-------------------------------------------------------------------------- `

**Comment by tgaddair** [comment]
Hey @ivankxt, can you provide a minimal reproducible example for us to run?  It's tough to say for sure what the issue is without having access to the model definition.  It looks like there's a string global variable somewhere that cannot be converted into a tensor, but I'm not sure how that string came to be represented as a global variable in your model.

**Comment by ivankxt** [comment]
> Hey @ivankxt, can you provide a minimal reproducible example for us to run? It's tough to say for sure what the issue is without having access to the model definition. It looks like there's a string global variable somewhere that cannot be converted into a tensor, but I'm not sure how that string came to be represented as a global variable in your model.


Hello @tgaddair,  my project is  complicated and it is difficult to provide a separate demo for you to run.
However, I check my code again, and found a node defined as a string:

> '_pron_config_variable': <tf.Variable 'pron_config_variable:0' shape=() dtype=string_ref>,

we print the global_variables:
print('global_variables:', global_variables())
the output is:
> <tf.Variable 'pron_config_variable:0' shape=() dtype=string_ref>, <tf.Variable 'pron
_config_variable/Variable:0' shape=() dtype=string_ref>

therefore, we remove the define of pron_config_variable, such as:
```python
# pron_config_variable, _ = model_ops.create_option_variable()
# nodes["_pron_config_variable"] = pron_config_variable
```
And we run our project again, the previous errors "TypeError: Value passed to parameter 'tensor' has DataType string not in list of allowed values: uint8, int8, uint16, int16, int32, int64, float16, float32, float64, bool"  are gone, but we got another errors:
```
Traceback (most recent call last):
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value embedding/embedding/gender_embedding_1/Adam_1
         [[{{node embedding/embedding/gender_embedding_1/Adam_1/read}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/model_trainer_hvd.py", line 740, in <module>
    tf.app.run()
  File "/opt/train/lib/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bin/model_trainer_hvd.py", line 734, in main
    model_trainer.train(FLAGS.model_dir, files)
  File "bin/model_trainer_hvd.py", line 351, in train
    self.session.run(bcast)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value embedding/embedding/gender_embedding_1/Adam_1
         [[node embedding/embedding/gender_embedding_1/Adam_1/read (defined at /opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:304) ]]

Caused by op 'embedding/embedding/gender_embedding_1/Adam_1/read', defined at:
  File "bin/model_trainer_hvd.py", line 740, in <module>
    tf.app.run()
  File "/opt/train/lib/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bin/model_trainer_hvd.py", line 713, in main
    model_trainer.build_model(FLAGS.study_option)
  File "bin/model_trainer_hvd.py", line 242, in build_model
    self.nodes = get_nodes(self.study_option, True)
  File "bin/model_trainer_hvd.py", line 122, in get_nodes
    dataset_output_name, build_dataset)
  File "/opt/train/lib/nabu/python/learner_ops.py", line 292, in create_simple_learner
    train_op = opt.minimize(nodes[loss_name], global_step=global_step)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 414, in minimize
    name=name)
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 304, in apply_gradients
    return self._optimizer.apply_gradients(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 596, in apply_gradients
    self._create_slots(var_list)
  File "/opt/train/lib/tensorflow/python/training/adam.py", line 136, in _create_slots
    self._zeros_slot(v, "v", self._name)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 1154, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 183, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 157, in create_slot_with_initializer
    dtype)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 1479, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 1220, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 547, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 499, in _true_getter
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 911, in _get_single_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 2495, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 1395, in __init__
    constraint=constraint)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 1557, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/opt/train/lib/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/array_ops.py", line 81, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/opt/train/lib/tensorflow/python/ops/gen_array_ops.py", line 3890, in identity
    "Identity", input=input, name=name)
  File "/opt/train/lib/tensorflow/python/framework/op_def_library.py", line 792, in _apply_op_helper
    op_def=op_def)
  File "/opt/train/lib/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/train/lib/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value embedding/embedding/gender_embedding_1/Adam_1
         [[node embedding/embedding/gender_embedding_1/Adam_1/read (defined at /opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:304) ]]

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value embedding/embedding/game_type_embedding_1/Adam_1
         [[{{node embedding/embedding/game_type_embedding_1/Adam_1/read}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/model_trainer_hvd.py", line 740, in <module>
    tf.app.run()
  File "/opt/train/lib/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bin/model_trainer_hvd.py", line 734, in main
    model_trainer.train(FLAGS.model_dir, files)
  File "bin/model_trainer_hvd.py", line 351, in train
    self.session.run(bcast)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/opt/train/lib/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value embedding/embedding/game_type_embedding_1/Adam_1
         [[node embedding/embedding/game_type_embedding_1/Adam_1/read (defined at /opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:304) ]]

Caused by op 'embedding/embedding/game_type_embedding_1/Adam_1/read', defined at:
  File "bin/model_trainer_hvd.py", line 740, in <module>
    tf.app.run()
  File "/opt/train/lib/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bin/model_trainer_hvd.py", line 713, in main
    model_trainer.build_model(FLAGS.study_option)
  File "bin/model_trainer_hvd.py", line 242, in build_model
    self.nodes = get_nodes(self.study_option, True)
  File "bin/model_trainer_hvd.py", line 122, in get_nodes
    dataset_output_name, build_dataset)
  File "/opt/train/lib/nabu/python/learner_ops.py", line 292, in create_simple_learner
    train_op = opt.minimize(nodes[loss_name], global_step=global_step)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 414, in minimize
    name=name)
  File "/opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 304, in apply_gradients
    return self._optimizer.apply_gradients(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 596, in apply_gradients
    self._create_slots(var_list)
  File "/opt/train/lib/tensorflow/python/training/adam.py", line 136, in _create_slots
    self._zeros_slot(v, "v", self._name)
  File "/opt/train/lib/tensorflow/python/training/optimizer.py", line 1154, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 183, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 157, in create_slot_with_initializer
    dtype)
  File "/opt/train/lib/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 1479, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 1220, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 547, in get_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 499, in _true_getter
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 911, in _get_single_variable
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variable_scope.py", line 2495, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 1395, in __init__
    constraint=constraint)
  File "/opt/train/lib/tensorflow/python/ops/variables.py", line 1557, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/opt/train/lib/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/ops/array_ops.py", line 81, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/opt/train/lib/tensorflow/python/ops/gen_array_ops.py", line 3890, in identity
    "Identity", input=input, name=name)
  File "/opt/train/lib/tensorflow/python/framework/op_def_library.py", line 792, in _apply_op_helper
    op_def=op_def)
  File "/opt/train/lib/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/train/lib/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/train/lib/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value embedding/embedding/game_type_embedding_1/Adam_1
         [[node embedding/embedding/game_type_embedding_1/Adam_1/read (defined at /opt/train/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:304) ]]

--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[17963,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```
In our project, the  define of "gender_embedding" is using our own custom op such as "PronGather" as shown below：
```
'gender_embedding_0': <tf.Tensor 'embedding_82/PronGather:0' shape=(?, 1, 3) dtype=float32>
'gender_embedding_1': <tf.Tensor 'embedding_83/PronGather:0' shape=(?, 1, 3) dtype=float32>
'gender_embedding_concat': <tf.Tensor 'concat_18:0' shape=(?, 2, 3) dtype=float32>
'gender_embedding_reduce': <tf.Tensor 'Sum_39:0' shape=(?, 3) dtype=float32>
```

Could you give me some advice how to slove the problem ? 
Thank You!
