### ISSUE TITLE
Broken Mac OS package

### ISSUE THREAD

**Issue by kahrabian** [horovod/horovod#1769]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4.0
3. Horovod version: 0.19.0
4. MPI version: 4.0.2
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.8.1
8. OS and version: Mac OS 10.15.3 (19D76)
9. GCC version: 9.2.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?  Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?  Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
While running `horovodrun --check-build` the following error occurs:

```
Traceback (most recent call last):
  File "/Users/kahrabian/miniconda3/envs/gg/bin/horovodrun", line 18, in <module>
    from horovod.run.run import run_commandline
  File "/Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/horovod/run/__init__.py", line 16, in <module>
    from .run import run
  File "/Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/horovod/run/run.py", line 26, in <module>
    from psutil import net_if_addrs
  File "/Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/psutil/__init__.py", line 161, in <module>
    from . import _psosx as _psplatform
  File "/Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so, 2): Symbol not found: ___CFConstantStringClassReference
  Referenced from: /Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/kahrabian/miniconda3/envs/gg/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so
```

I recently upgrade my OS and the library stopped working after this upgrade.

**Comment by kahrabian** [comment]
I think this is an issue with python 3.8, not the Mac OS, so I'll close this issue for now.
