### ISSUE TITLE
Error while trying to run on more than 4 CPU cores

### ISSUE THREAD

**Issue by anweshpanda** [horovod/horovod#1834]
Hi
I am using horovod with pytorch and trying to run the pytorch_mnist.py which is an example given .
I am able to run in successfully for number of cpu cores<=4 by using the command :
horovodrun -np 4   python pytorch_mnist.py
However while trying to run on more than 4 cpu cores I am getting the following error:
```

2020-03-30 12:44:09.734470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-03-30 12:44:11.967031: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.7
2020-03-30 12:44:11.970411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.7
[1,4]<stdout>:Using downloaded and verified file: data-4/MNIST/raw/train-images-idx3-ubyte.gz
[1,4]<stdout>:Extracting data-4/MNIST/raw/train-images-idx3-ubyte.gz to data-4/MNIST/raw
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "pytorch_mnist.py", line 127, in <module>
[1,0]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,0]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/__init__.py", line 470, in broadcast_parameters
[1,0]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,0]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 433, in broadcast_async_
[1,0]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,0]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 343, in _broadcast_async
[1,0]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,0]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "pytorch_mnist.py", line 127, in <module>
[1,1]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,1]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/__init__.py", line 470, in broadcast_parameters
[1,1]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,1]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 433, in broadcast_async_
[1,1]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,1]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 343, in _broadcast_async
[1,1]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,1]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "pytorch_mnist.py", line 127, in <module>
[1,2]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,2]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/__init__.py", line 470, in broadcast_parameters
[1,2]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,2]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 433, in broadcast_async_
[1,2]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,2]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 343, in _broadcast_async
[1,2]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,2]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "pytorch_mnist.py", line 127, in <module>
[1,3]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,3]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/__init__.py", line 470, in broadcast_parameters
[1,3]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,3]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 433, in broadcast_async_
[1,3]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,3]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 343, in _broadcast_async
[1,3]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,3]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "pytorch_mnist.py", line 71, in <module>
[1,4]<stderr>:    transforms.Normalize((0.1307,), (0.3081,))
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
[1,4]<stderr>:    self.download()
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 135, in download
[1,4]<stderr>:    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename)
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 252, in download_and_extract_archive
[1,4]<stderr>:    extract_archive(archive, extract_root, remove_finished)
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 229, in extract_archive
[1,4]<stderr>:    out_f.write(zip_f.read())
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/gzip.py", line 287, in read
[1,4]<stderr>:    return self._buffer.read(size)
[1,4]<stderr>:  File "/home/mas/20/cdsanwesk/miniconda3/envs/fresh_env/lib/python3.7/gzip.py", line 493, in read
[1,4]<stderr>:    raise EOFError("Compressed file ended before the "
[1,4]<stderr>:EOFError: Compressed file ended before the end-of-stream marker was reached
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[42246,1],1]
  Exit code:    1
--------------------------------------------------------------------------

```

Can anyone please help?

**Comment by abditag2** [comment]
I was not able to recreate this error on my local environment.
From your errors, it seems that one of your ranks has trouble decompressing the dataset. I'd suggest use a few print statements to identify what happens exactly.

**Comment by anweshpanda** [comment]
So I am getting the error exactly in this line:
train_dataset = \
    datasets.MNIST('data-%d' % hvd.rank(), train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))

**Comment by tgaddair** [comment]
Hey @anweshpanda, looks like the MNIST dataset got corrupted when downloading for rank 3 somehow.  Can you try doing the following to fix it:

```
rm -rf data-3
cp -r data-0 data-3
```

Basically, replace the corrupted copy of the dataset with an uncorrupted copy.

**Comment by anweshpanda** [comment]
Thanks a lot @tgaddair .It worked.

**Comment by tgaddair** [comment]
Excellent!  I'll go ahead and close this issue for now.
