### ISSUE TITLE
MPI connect error

### ISSUE THREAD

**Issue by csdingbin** [horovod/horovod#1916]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)Horovod with Pytorch in Spark
2. Framework version:torch1.3.1,Spark2.4.4
3. Horovod version:0.19
4. MPI version:4.0.3
5. Python version:3.7.5
6. OS and version:
7. GCC version:5.4.0

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.
On my cluster, I can successfully use horovodrun and mpirun to run python file. Such as:
horovodrun --verbose -np 4  --network-interface "p785p2" -H hdfs1:2,hdfs2:2 python ~/jupyter/Bin/horovod/pytorch_horovod.py

and the verbose:
mpirun --allow-run-as-root --tag-output -np 4 -H hdfs1:2,hdfs2:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include p785p2 -x NCCL_SOCKET_IFNAME=p785p2  -x ACTIVATOR_HOME -x CLASSPATH -x HADOOP_COMMON_HOME -x HADOOP_COMMON_LIB_NATIVE_DIR -x HADOOP_CONF_DIR -x HADOOP_HDFS_HOME -x HADOOP_HOME -x HADOOP_INSTALL -x HADOOP_MAPRED_HOME -x HADOOP_OPTS -x HOME -x HOROVOD_CCL_BGT_AFFINITY -x HOROVOD_GLOO_TIMEOUT_SECONDS -x HOROVOD_NUM_NCCL_STREAMS -x HOROVOD_STALL_CHECK_TIME_SECONDS -x HOROVOD_STALL_SHUTDOWN_TIME_SECONDS -x JAVA_HOME -x JRE_HOME -x LANG -x LANGUAGE -x LOGNAME -x MAIL -x PATH -x PWD -x PYSPARK_DRIVER_PYTHON -x PYSPARK_PYTHON -x PYTHONPATH -x SCALA_HOME -x SHELL -x SHLVL -x SPARK_CONF_DIR -x SPARK_HOME -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x TZ -x USER -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x YARN_HOME -x _ -x http_proxy -x https_proxy  python /home/sparkuser/jupyter/Bin/horovod/pytorch_horovod.py

This can run on cluster(two nodes). But when I run using horovod in Spark. We can successfully run on local mode  on single node. But failed on standalone and yarn node on two nodes using Spark-submit.

some code below:

conf = SparkConf().setAppName('pytorch_spark_mnist').setMaster('spark://hdfs1:7077').set('spark.sql.shuffle.partitions', '16')
spark = SparkSession.builder.config(conf=conf).getOrCreate()

num_proc=4
backend = SparkBackend(num_proc, nic="p785p2",verbose=2)

#.type(torch.LongTensor)
torch_estimator = hvd.TorchEstimator(backend=backend,
                                     store=store,
                                     model=model,
                                     optimizer=optimizer,
                                     loss=lambda input, target: loss(input, target),
                                     input_shapes=[[5,1], [1], [1], [1], [1]],
                                     feature_cols=feature_cols,
                                     label_cols=['label'],
                                     batch_size=batch_size,
                                     epochs=num_epoch,
                                     verbose=1)
    

and output the error of :

Initial Spark task registration is complete.
Spark task-to-task address registration is complete.
mpirun --allow-run-as-root --tag-output -np 4 -H hdfs1-60e666c26b550d3fb1f4670465fc783f:2,hdfs2-b788dd2e677ebc9138507de4c053dd76:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include p785p2 -x NCCL_SOCKET_IFNAME=p785p2  -x ACTIVATOR_HOME -x ANALYTICS_ZOO_HOME -x CLASSPATH -x HADOOP_COMMON_HOME -x HADOOP_COMMON_LIB_NATIVE_DIR -x HADOOP_CONF_DIR -x HADOOP_HDFS_HOME -x HADOOP_HOME -x HADOOP_INSTALL -x HADOOP_MAPRED_HOME -x HADOOP_OPTS -x HOME -x JAVA_HOME -x JRE_HOME -x KMP_DUPLICATE_LIB_OK -x KMP_INIT_AT_FORK -x LANG -x LANGUAGE -x LD_LIBRARY_PATH -x LOCAL_DIRS -x LOGNAME -x MAIL -x NLSPATH -x PATH -x PWD -x PYSPARK_DRIVER_PYTHON -x PYSPARK_GATEWAY_PORT -x PYSPARK_GATEWAY_SECRET -x PYSPARK_PYTHON -x PYTHONHASHSEED -x PYTHONPATH -x PYTHONUNBUFFERED -x SCALA_HOME -x SHELL -x SHLVL -x SPARK_CONF_DIR -x SPARK_ENV_LOADED -x SPARK_HOME -x SPARK_LOCAL_DIRS -x SPARK_MASTER_HOST -x SPARK_MASTER_IP -x SPARK_MASTER_PORT -x SPARK_SCALA_VERSION -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x TZ -x USER -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x XFILESEARCHPATH -x YARN_CONF_DIR -x YARN_HOME -x _HOROVOD_SECRET_KEY -x http_proxy -x https_proxy  -x NCCL_DEBUG=INFO -mca plm_rsh_agent "/home/sparkuser/anaconda3/bin/python3.7 -m horovod.spark.driver.mpirun_rsh gASVIQAAAAAAAAB9lIwGcDc4NXAylF2UjAkxMC4xNi40LjSUTcYyhpRhcy4= gASVxwIAAAAAAACMIGhvcm92b2QucnVuLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMB3ZlcmJvc2WUSwKMCHNzaF9wb3J0lE6MDmV4dHJhX21waV9hcmdzlE6MCHRjcF9mbGFnlE6MDGJpbmRpbmdfYXJnc5ROjANrZXmUQyBCgYPjhQaz5hX0GDUxZWAdihkmNki61SUiKeHgEEU9b5SMB3RpbWVvdXSUjB9ob3Jvdm9kLnJ1bi5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HXqg3OUvkbjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowJbnVtX2hvc3RzlE6MCG51bV9wcm9jlEsEjAVob3N0c5SMUWhkZnMxLTYwZTY2NmMyNmI1NTBkM2ZiMWY0NjcwNDY1ZmM3ODNmOjIsaGRmczItYjc4OGRkMmU2NzdlYmM5MTM4NTA3ZGU0YzA1M2RkNzY6MpSMD291dHB1dF9maWxlbmFtZZROjA1ydW5fZnVuY19tb2RllIiMA25pY5SMBnA3ODVwMpR1Yi4=" /home/sparkuser/anaconda3/bin/python3.7 -m horovod.spark.task.mpirun_exec_fn gASVIQAAAAAAAAB9lIwGcDc4NXAylF2UjAkxMC4xNi40LjSUTcYyhpRhcy4= gASVQQcAAAAAAACMIGhvcm92b2QucnVuLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMB3ZlcmJvc2WUSwKMCHNzaF9wb3J0lE6MDmV4dHJhX21waV9hcmdzlFh1BAAAIC14IE5DQ0xfREVCVUc9SU5GTyAtbWNhIHBsbV9yc2hfYWdlbnQgIi9ob21lL3NwYXJrdXNlci9hbmFjb25kYTMvYmluL3B5dGhvbjMuNyAtbSBob3Jvdm9kLnNwYXJrLmRyaXZlci5tcGlydW5fcnNoIGdBU1ZJUUFBQUFBQUFBQjlsSXdHY0RjNE5YQXlsRjJVakFreE1DNHhOaTQwTGpTVVRjWXlocFJoY3k0PSBnQVNWeHdJQUFBQUFBQUNNSUdodmNtOTJiMlF1Y25WdUxtTnZiVzF2Ymk1MWRHbHNMbk5sZEhScGJtZHpsSXdJVTJWMGRHbHVaM09VazVRcGdaUjlsQ2lNQjNabGNtSnZjMldVU3dLTUNITnphRjl3YjNKMGxFNk1EbVY0ZEhKaFgyMXdhVjloY21kemxFNk1DSFJqY0Y5bWJHRm5sRTZNREdKcGJtUnBibWRmWVhKbmM1Uk9qQU5yWlhtVVF5QkNnWVBqaFFhejVoWDBHRFV4WldBZGloa21Oa2k2MVNVaUtlSGdFRVU5YjVTTUIzUnBiV1Z2ZFhTVWpCOW9iM0p2ZG05a0xuSjFiaTVqYjIxdGIyNHVkWFJwYkM1MGFXMWxiM1YwbEl3SFZHbHRaVzkxZEpTVGxDbUJsSDJVS0l3TFgzUnBiV1Z2ZFhSZllYU1VSMEhYcWczT1V2a2JqQWhmYldWemMyRm5aWlJZRGdFQUFGUnBiV1ZrSUc5MWRDQjNZV2wwYVc1bklHWnZjaUI3WVdOMGFYWnBkSGw5TGlCUWJHVmhjMlVnWTJobFkyc2dkR2hoZENCNWIzVWdhR0YyWlNCbGJtOTFaMmdnY21WemIzVnlZMlZ6SUhSdklISjFiaUJoYkd3Z1NHOXliM1p2WkNCd2NtOWpaWE56WlhNdUlFVmhZMmdnU0c5eWIzWnZaQ0J3Y205alpYTnpJSEoxYm5NZ2FXNGdZU0JUY0dGeWF5QjBZWE5yTGlCWmIzVWdiV0Y1SUc1bFpXUWdkRzhnYVc1amNtVmhjMlVnZEdobElITjBZWEowWDNScGJXVnZkWFFnY0dGeVlXMWxkR1Z5SUhSdklHRWdiR0Z5WjJWeUlIWmhiSFZsSUdsbUlIbHZkWElnVTNCaGNtc2djbVZ6YjNWeVkyVnpJR0Z5WlNCaGJHeHZZMkYwWldRZ2IyNHRaR1Z0WVc1a0xwUjFZb3dKYm5WdFgyaHZjM1J6bEU2TUNHNTFiVjl3Y205amxFc0VqQVZvYjNOMGM1U01VV2hrWm5NeExUWXdaVFkyTm1NeU5tSTFOVEJrTTJaaU1XWTBOamN3TkRZMVptTTNPRE5tT2pJc2FHUm1jekl0WWpjNE9HUmtNbVUyTnpkbFltTTVNVE00TlRBM1pHVTBZekExTTJSa056WTZNcFNNRDI5MWRIQjFkRjltYVd4bGJtRnRaWlJPakExeWRXNWZablZ1WTE5dGIyUmxsSWlNQTI1cFk1U01CbkEzT0RWd01wUjFZaTQ9IpSMCHRjcF9mbGFnlE6MDGJpbmRpbmdfYXJnc5ROjANrZXmUQyBCgYPjhQaz5hX0GDUxZWAdihkmNki61SUiKeHgEEU9b5SMB3RpbWVvdXSUjB9ob3Jvdm9kLnJ1bi5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HXqg3OUvkbjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowJbnVtX2hvc3RzlE6MCG51bV9wcm9jlEsEjAVob3N0c5SMUWhkZnMxLTYwZTY2NmMyNmI1NTBkM2ZiMWY0NjcwNDY1ZmM3ODNmOjIsaGRmczItYjc4OGRkMmU2NzdlYmM5MTM4NTA3ZGU0YzA1M2RkNzY6MpSMD291dHB1dF9maWxlbmFtZZROjA1ydW5fZnVuY19tb2RllIiMA25pY5SMBnA3ODVwMpR1Yi4=
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[25256,0],2] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
20/04/28 21:51:32 INFO scheduler.DAGScheduler: Asked to cancel job group horovod.spark.run.0
20/04/28 21:51:32 INFO scheduler.TaskSchedulerImpl: Cancelling stage 3
20/04/28 21:51:32 INFO scheduler.TaskSchedulerImpl: Killing all running tasks in stage 3: Stage cancelled
20/04/28 21:51:32 INFO scheduler.TaskSchedulerImpl: Stage 3 was cancelled
20/04/28 21:51:32 INFO scheduler.DAGScheduler: ResultStage 3 (collect at /home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/__init__.py:93) failed in 2.719 s due to Job 3 cancelled part of cancelled job group horovod.spark.run.0
20/04/28 21:51:32 INFO scheduler.DAGScheduler: Job 3 failed: collect at /home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/__init__.py:93, took 2.724534 s
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/sparkuser/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/sparkuser/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/__init__.py", line 93, in run_spark
    result = procs.mapPartitionsWithIndex(_make_mapper(driver.addresses(), settings)).collect()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 3 cancelled part of cancelled job group horovod.spark.run.0
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
        at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1824)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:906)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
        at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:906)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2079)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
        at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
        at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)

Traceback (most recent call last):
  File "/home/sparkuser/jupyter/Bin/horovod/pytorch_horovod.py", line 218, in <module>
    torch_model = torch_estimator.fit(train_df).setOutputCols(['label_prob'])
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 83, in _fit
    backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/torch/estimator.py", line 249, in _fit_on_prepared_data
    env={})
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/common/backend.py", line 87, in run
    **self._kwargs)
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/spark/__init__.py", line 223, in run
    mpi_run(settings, common_intfs, env, command, stdout=stdout, stderr=stderr, run_func=run_func)
  File "/home/sparkuser/anaconda3/lib/python3.7/site-packages/horovod/run/mpi_run.py", line 154, in mpi_run
    raise RuntimeError("mpirun failed with exit code {exit_code}".format(exit_code=exit_code))
RuntimeError: mpirun failed with exit code 230
20/04/28 21:51:32 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 3.0 (TID 11, 10.16.4.4, executor 7): TaskKilled (Stage cancelled)
20/04/28 21:51:32 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 3.0 (TID 12, 10.16.4.8, executor 0): TaskKilled (Stage cancelled)
20/04/28 21:51:32 INFO spark.SparkContext: Invoking stop() from shutdown hook
20/04/28 21:51:32 INFO server.AbstractConnector: Stopped Spark@3208ca25{HTTP/1.1,[http/1.1]}{0.0.0.0:4050}
20/04/28 21:51:32 INFO ui.SparkUI: Stopped Spark web UI at http://hdfs1:4050
20/04/28 21:51:32 INFO cluster.StandaloneSchedulerBackend: Shutting down all executors
20/04/28 21:51:32 INFO cluster.CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
20/04/28 21:51:32 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/04/28 21:51:32 INFO memory.MemoryStore: MemoryStore cleared
20/04/28 21:51:32 INFO storage.BlockManager: BlockManager stopped
20/04/28 21:51:32 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
20/04/28 21:51:32 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/04/28 21:51:32 INFO spark.SparkContext: Successfully stopped SparkContext
20/04/28 21:51:32 INFO util.ShutdownHookManager: Shutdown hook called
20/04/28 21:51:32 INFO util.ShutdownHookManager: Deleting directory /opt/spark-2.4.4-bin-hadoop2.7/shuffle_data/spark-a5b3b5b6-e700-45db-8cc9-271e06083b21/pyspark-4257d8af-82ce-4392-9962-835b14c65b20
20/04/28 21:51:32 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-0033e9e2-b80d-44c9-8b38-f78b9d178d53
20/04/28 21:51:32 INFO util.ShutdownHookManager: Deleting directory /opt/spark-2.4.4-bin-hadoop2.7/shuffle_data/spark-a5b3b5b6-e700-45db-8cc9-271e06083b21

This is something that should be reported to the developers.
So how to solve this issue?

**Comment by tgaddair** [comment]
Hey @csdingbin, my understanding is that this kind of error typically indicates that the version of MPI running `mpirun` is different from the version running on the workers (see https://github.com/open-mpi/ompi/issues/7015).  Can you check that all hosts have the same version of MPI?
