### ISSUE TITLE
NanLossDuringTrainingError with NCCL 2.7 and CUDA 11

### ISSUE THREAD

**Issue by changlan** [horovod/horovod#2044]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.15
3. Horovod version: 0.19.4
4. MPI version: OpenMPI 4.0.2
5. CUDA version: 11.0
6. NCCL version: 2.7.1
7. Python version: 3.7.6
8. Spark / PySpark version:
9. OS and version:
10. GCC version: 6.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Horovod was built on a machine with CUDA 11 and NCCL 2.7 `sudo HOROVOD_NCCL_HOME=/usr/local/nccl2 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL /opt/conda/bin/pip install horovod`. Running the ResNet-50 training script from Nvidia's [DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets) produced the following error:
```
Traceback (most recent call last):
  File "DeepLearningExamples/TensorFlow/Classification/ConvNets/main.py", line 96, in <module>
    is_benchmark=FLAGS.mode == 'training_benchmark',
  File "/home/perfkit/DeepLearningExamples/TensorFlow/Classification/ConvNets/runtime/runner.py", line 495, in train
    hooks=training_hooks,
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1426, in run
    run_metadata=run_metadata))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 761, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
Same test works fine in CUDA 10 + NCCL 2.5.

**Comment by tgaddair** [comment]
Thanks for reporting this issue, @changlan.  I'm not aware of any incompatibilities with CUDA 11 or NCCL 2.7, but we haven't run extensive tests with those version yet.  I'll see if I can reproduce the error.

Have you tried running any of our other example scripts like [tensorflow_mnist.py](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py), and do you see similar issues?

@romerojosh @nvcastet have you run any tests with NCCL 2.7 or CUDA 11?

**Comment by nvcastet** [comment]
I have not tried it.

**Comment by nluehr** [comment]
@changlan Did you also build TF 1.15 against CUDA 11?

**Comment by changlan** [comment]
@nluehr Yes, it was built against CUDA 11.

**Comment by lzhengchun** [comment]
@tgaddair is there a timeline to support cuda11?

**Comment by tgaddair** [comment]
Hey @lzhengchun, we do support CUDA 11, and now have our CI system setup to test against it automatically.  I suspect in your case there may be something else going on here.  Can you share the results of running `horovodrun --check-build`?  If it shows that you do not have NCCL enabled, can you try re-installing Horovod with `pip uninstall -y horovod && HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod`?

**Comment by lzhengchun** [comment]
> Hey @lzhengchun, we do support CUDA 11, and now have our CI system setup to test against it automatically. I suspect in your case there may be something else going on here. Can you share the results of running `horovodrun --check-build`? If it shows that you do not have NCCL enabled, can you try re-installing Horovod with `pip uninstall -y horovod && HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod`?

Thanks @tgaddair this problem has been solved by rebuilding Horovod with latest NCCL and CUDA 11
