### ISSUE TITLE
Horovod on Spark fails to load token from HADOOP_TOKEN_FILE_LOCATION

### ISSUE THREAD

**Issue by aliatprotopia** [horovod/horovod#2078]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): Tensorflow/Keras
2. Framework version: 2.2.0
3. Horovod version: 0.19.5
4. MPI version: Gloo
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7
8. Spark / PySpark version: 2.4.4
9. OS and version: Amazon Linux 2
10. GCC version: N/A

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Y

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

I am running Horovod on Spark in EMR 6.0.0. I am using Gloo and try to train Tensorflow/Keras. I get this error on the executors side:

2020-07-06 04:19:12,515 WARN fs.FileSystem: Cannot load filesystem: java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.viewfs.ViewFileSystem could not be instantiated
2020-07-06 04:19:12,515 WARN fs.FileSystem: java.io.FileNotFoundException: Source file /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000001/container_tokens from HADOOP_TOKEN_FILE_LOCATION not found
2020-07-06 04:19:12,532 WARN fs.FileSystem: Cannot load filesystem: java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.viewfs.ViewFileSystem could not be instantiated
2020-07-06 04:19:12,532 WARN fs.FileSystem: java.io.FileNotFoundException: Source file /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000001/container_tokens from HADOOP_TOKEN_FILE_LOCATION not found
hdfsBuilderConnect(forceNewInstance=1, nn=default, port=8020, kerbTicketCachePath=(NULL), userName=(NULL)) error:
FileNotFoundException: Source file /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000001/container_tokens from HADOOP_TOKEN_FILE_LOCATION not foundjava.io.FileNotFoundException: Source file /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000001/container_tokens from HADOOP_TOKEN_FILE_LOCATION not found
	at org.apache.hadoop.security.UserGroupInformation.createLoginUser(UserGroupInformation.java:752)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:660)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:571)
	at org.apache.hadoop.security.UserGroupInformation.getBestUGI(UserGroupInformation.java:591)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:501)
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dev/shm/python_packages/horovod/spark/task/gloo_exec_fn.py", line 30, in <module>
    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
  File "/dev/shm/python_packages/horovod/spark/task/gloo_exec_fn.py", line 23, in main
    task_exec(driver_addresses, settings, 'HOROVOD_RANK')
  File "/dev/shm/python_packages/horovod/spark/task/__init__.py", line 53, in task_exec
    result = fn(*args, **kwargs)
  File "/dev/shm/python_packages/horovod/spark/keras/remote.py", line 194, in train
    **reader_factory_kwargs) as train_reader:
  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 248, in make_batch_reader
    filesystem, dataset_path_or_paths = get_filesystem_and_path_or_paths(dataset_url_or_urls, hdfs_driver)
  File "/usr/local/lib/python3.7/site-packages/petastorm/fs_utils.py", line 220, in get_filesystem_and_path_or_paths
    fs = FilesystemResolver(url_list[0], hdfs_driver=hdfs_driver).filesystem()
  File "/usr/local/lib/python3.7/site-packages/petastorm/fs_utils.py", line 123, in __init__
    self._filesystem = connector.hdfs_connect_namenode(self._parsed_dataset_url, hdfs_driver, user=user)
  File "/usr/local/lib/python3.7/site-packages/petastorm/hdfs/namenode.py", line 272, in hdfs_connect_namenode
    return pyarrow.hdfs.connect(hostname, url.port or 8020, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/pyarrow/hdfs.py", line 215, in connect
    extra_conf=extra_conf)
  File "/usr/local/lib64/python3.7/site-packages/pyarrow/hdfs.py", line 40, in __init__
    self._connect(host, port, user, kerb_ticket, driver, extra_conf)
  File "pyarrow/io-hdfs.pxi", line 105, in pyarrow.lib.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: HDFS connection failed

**Comment by EnricoMi** [comment]
Hi @aliatprotopia, can you please elaborate on how you start Horovod on Spark, like the full `horovod.spark.run(...)` command or do you use the `hvd.KerasEstimator`? Can you run the training with `verbose=3` and provide me some output from the Spark Worker like `Task service executes command:` and `Task service env:`? Thanks!

**Comment by aliatprotopia** [comment]
I use `hvd.KerasEstimator().fit()` and I used `verbose=2` (not 3) and got these. Do you want me run with 3?

`Task service executes command: HOROVOD_RANK=0 HOROVOD_SIZE=2 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=2 HOROVOD_CROSS_RANK=0 HOROVOD_CROSS_SIZE=1  PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.3.226.50 HOROVOD_GLOO_RENDEZVOUS_PORT=6402 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=eth0 NCCL_SOCKET_IFNAME=eth0,lo /usr/bin/python3 -m horovod.spark.task.gloo_exec_fn`

also `Task service env:` is a super long list of stuff; do you need any specific variable from the list? This one might be relevant:

Task service env: HADOOP_TOKEN_FILE_LOCATION = /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000001/container_tokens

**Comment by EnricoMi** [comment]
Exactly that one, so the training script is executed with `HADOOP_TOKEN_FILE_LOCATION`, it is available to you script, and `pyarrows/hdfs.py` is picking it up. It looks like that file does not exist (as the exception above does say). Does HDFS access work for your Spark cluster and other apps on it?

**Comment by aliatprotopia** [comment]
I think the problem is that `HADOOP_TOKEN_FILE_LOCATION` is a `local` path by default not `hdfs` path. And yes, I can ssh to the host and run other spark tasks; I also see the token exists on the `local` path. So, I believe the exception is because it is looking into `hdfs` and not `local` path for the token and Spark by default puts the `local` path in `HADOOP_TOKEN_FILE_LOCATION`. Do you know how I can fix this?

**Comment by EnricoMi** [comment]
What makes you think Spark looks into HDFS for that path? Looking at your stacktrace, Spark is not involved here. Your training script is running in a python process, which uses petastorm and pyarrow to access hdfs. That one uses the env variable to locate the file.

Some more questions to understand your setup: How do you connect your python script with your Spark cluster? Do you use `spark-submit`? Can you run a `spark-shell` from the same location and read something from HDFS, e.g. `spark.read.parquet("hdfs://path/file.parquet").show`? If Spark can access HDFS, then your python code running in the same environment should also be able to access that.

Can you watch out for some more `Task service env:` rows talking about current working directories?

**Comment by aliatprotopia** [comment]
I did not say Spark looks into HDFS. I am saying Spark creates that token on `local` path; I *think* pyarrow is considering that as an hdfs path. Maybe I am wrong.

I use `spark-submit` and in fact the `utils.prepare_data` function from `Horovod` works fine. It copies data from S3 to HDFS and breaks it down into train and validation. I see those two folders on HDFS. Also, I just tried to read those folders in `spark-shell` and that worked fine too.

As for the env: the folder is different from `HADOOP_TOKEN_FILE_LOCATION` in that the container number of the worker was 3, so this path ends with `000003` where as the token path has the master container id of 1 and ends with `000001`; do you think this is the problem?
`Task service env: HOROVOD_SPARK_WORK_DIR = /mnt3/yarn/usercache/hadoop/appcache/application_1594008786728_0002/container_1594008786728_0002_02_000003`

**Comment by aliatprotopia** [comment]
Actually looking closer, I realized that the token is under `container_1594008786728_0002_02_000003` (3 at the end) folder while `HADOOP_TOKEN_FILE_LOCATION` points to `container_1594008786728_0002_02_000001` (1 at the end). So, `HADOOP_TOKEN_FILE_LOCATION` is set wrong or maybe copied from the master node to executor nodes without change. Do you know how we can fix it?

**Comment by EnricoMi** [comment]
Worker and driver all should have the same application id `application_1594008786728_0002` and the same container id prefix, here `container_1594008786728_0002`. The rest of the container id is different, because worker and driver are different containers. When Spark creates a new executor in a worker, it copies the token over to that new containers path. So every container has its own copy of that token file. Is the worker accessing the worker's token file or the driver's file? You should be able to see in Yarn or Spark UI which container id is which part of your Spark app.

The `HOROVOD_SPARK_WORK_DIR` is the current working directory of the driver, which is sent to the spark workers for other purposes (to add it to PYTHONPATH for instance).

**Comment by aliatprotopia** [comment]
It seems that worker is trying to reach to driver's path for the token. The token is actually under `$HOROVOD_SPARK_WORK_DIR/container_tokens` and `HOROVOD_SPARK_WORK_DIR` ends with worker's container id (in this case `000003`). However, `HADOOP_TOKEN_FILE_LOCATION` points to a path that ends with the drivers id (in this case `000001`). That is I think why it says file does not exist. It is looking under wrong folder. Could this be caused by Horovod sending environment variables from driver to workers? My guess is that on the driver, it is pointing to the right folder, but for workers that folder is wrong.

**Comment by xiaodaxia** [comment]
@aliatprotopia How did you solve your problem? I think I met the same problem. That is, the worker is looking under wrong folder. And I think it is **indeed** caused by horovod sending the environment variables from driver to works. So how do you solve the problem.
