### ISSUE TITLE
ValueError: Process number should not be larger than total available slots.

### ISSUE THREAD

**Issue by vinhdiesal** [horovod/horovod#2090]
I have installed the GPU version of horovod with NCCL 2 on my local machines. 

When I run the following command in the terminal:
`horovodrun -np 4 -H localhost:0 192.168.1.191:2 192.168.1.119:2 python Convolution\ Network\ MNIST.py`

`192.168.1.191` and `192.168.1.119` have 2 NVIDIA GPUs each which is why the :2.

I get the following error:
```
Traceback (most recent call last):
  File "/home/vinhdiesal/anaconda3/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 723, in run_commandline
    _run(args)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 656, in _run
    _launch_job(args, remote_host_names, settings, nics, command)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 717, in _launch_job
    args.verbose)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 694, in run_controller
    gloo_run()
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 706, in gloo_run_fn
    gloo_run(settings, remote_host_names, nics, env, driver_ip, command)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 312, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 250, in launch_gloo
    host_alloc_plan = _allocate(settings.hosts, settings.num_proc)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 103, in _allocate
    raise ValueError("Process number should not be larger than "
ValueError: Process number should not be larger than total available slots.
```
I attached the python script which tests out MNIST.
[Convolution Network MNIST.py.zip](https://github.com/horovod/horovod/files/4899826/Convolution.Network.MNIST.py.zip)

**Comment by tgaddair** [comment]
Hey @vinhdiesal, can you try dropping `localhost:0` from your command line?

**Comment by vinhdiesal** [comment]
`horovodrun -np 4 -H 192.168.1.191:2 192.168.1.119:2 python Convolution\ Network\ MNIST.py`
results in the same error: 
I did install with GPU.
```
(base) vinhdiesal@vinhdiesal:~/Documents$ horovodrun -np 2 -H 192.168.1.191:1 192.168.1.119:1 python Convolution\ Network\ MNIST.py 
2020-07-09 18:47:43.186035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-07-09 18:47:45.112437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/vinhdiesal/anaconda3/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 723, in run_commandline
    _run(args)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 656, in _run
    _launch_job(args, remote_host_names, settings, nics, command)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 717, in _launch_job
    args.verbose)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 694, in run_controller
    gloo_run()
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/runner.py", line 706, in gloo_run_fn
    gloo_run(settings, remote_host_names, nics, env, driver_ip, command)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 312, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 250, in launch_gloo
    host_alloc_plan = _allocate(settings.hosts, settings.num_proc)
  File "/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 103, in _allocate
    raise ValueError("Process number should not be larger than "
ValueError: Process number should not be larger than total available slots.
```

**Comment by vinhdiesal** [comment]
any updates?

**Comment by vinhdiesal** [comment]
Due to lack of response and difficulty will close and continue with Ray for distributed machine learning.
