### ISSUE TITLE
Horovod fails when it tries to read from HDFS in DataProc

### ISSUE THREAD

**Issue by arunraman** [horovod/horovod#2093]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.15
3. Horovod version: 0.19
4. MPI version: OpenMPI-Bin
5. CUDA version: cuda_10.0.130_410.48_linux
6. NCCL version: 2.4.8
7. Python version: mpirun (Open MPI) 2.1.1
8. Spark / PySpark version: Spark 3.0
9. OS and version: 2.0.0-RC1-ubuntu18 (GCP Dataproc)
10. GCC version:7.5.0

I am currently working on getting the Horovod running inside the Spark Cluster in the Dataproc. I am using the 2.0.0-RC1-ubuntu18 image. We are using this example form Horovod 

https://github.com/horovod/horovod/blob/master/examples/keras_spark3_rossmann.py

We modified the code a little bit to take read the data from GCS and write the output the HDFS store. But the Horovod is not able to read from the HDFS store and is failing at this line 

`keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])`

The stack trace of the failure 

`hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
java.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
Traceback (most recent call last):
  File "/tmp/537ae15236734a5c8b9e60faac43c629/sparkjob1.py", line 335, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 636, in prepare_data
    num_partitions, num_processes, verbose)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 572, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 413, in get_simple_meta_from_parquet
    raise ValueError("{} path does not exist in the store".format(train_data_path))
ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store`

Even though I can see the files available in the HDFS:

`$ hadoop  fs -ls /tmp/horovod/intermediate_train_data.0
Found 17 items
-rw-r--r--   2 root hadoop          0 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/_SUCCESS
-rw-r--r--   2 root hadoop    1027422 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00000-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021719 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00001-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025107 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00002-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1019034 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00003-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024424 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00004-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021981 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00005-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1023346 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00006-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021876 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00007-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024823 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00008-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026777 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00009-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033677 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00010-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1034280 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00011-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026418 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00012-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026736 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00013-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033822 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00014-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025689 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00015-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet`

**Comment by tgaddair** [comment]
Hey @arunraman, sorry for the late response.  May be an issue with how we're handling our paths somewhere.  

@abditag2, can you take a look?

**Comment by arunraman** [comment]
@abditag2 Any update on the issue?

**Comment by tgaddair** [comment]
@arunraman one thing to try would be to see if you can find the file using `pyarrow` (which is what we use internally to do this lookup):

```
fs = pa.hdfs.connect(driver='libhdfs')
fs.exists('/tmp/horovod/intermediate_train_data.0')
```

**Comment by arunraman** [comment]
Couple of updates I changed the util.py using the fix from here 

https://github.com/horovod/horovod/pull/1967/files

Now my parquet are not even getting written to the hdfs.  I am hitting this error 

`Traceback (most recent call last):
  File "/tmp/ec8b2d5bd02b4f47bf0ee9e6afe2969e/sparkjob1.py", line 336, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 640, in prepare_data
    num_partitions, num_processes, verbose)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 576, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 460, in get_simple_meta_from_parquet
    train_data = store.get_parquet_dataset(train_data_path)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/store.py", line 176, in get_parquet_dataset
    return pq.ParquetDataset(self.get_localized_path(path), filesystem=self.get_filesystem())
  File "/opt/conda/default/lib/python3.7/site-packages/pyarrow/parquet.py", line 1060, in __init__
    self.validate_schemas()
  File "/opt/conda/default/lib/python3.7/site-packages/pyarrow/parquet.py", line 1092, in validate_schemas
    self.schema = self.pieces[0].get_metadata().schema
IndexError: list index out of range
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [ec8b2d5bd02b4f47bf0ee9e6afe2969e] failed with error:
Job failed with message [IndexError: list index out of range].

For the pyarrow error I don't get some warning but I think I can ignore that 

```
>>> fs = pa.hdfs.connect(driver='libhdfs')
2020-07-17 19:33:12,315 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-07-17 19:33:13,149 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
```

**Comment by arunraman** [comment]
Ok i noticed the something here, I am using the 

https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_estimator.py

and this doesn't use any pyarrow. 

But when  I import pyarrow to check the day I can see that 

`>>> import pyarrow as pa
>>> fs = pa.hdfs.connect(driver='libhdfs')
2020-07-17 20:58:01,488 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-07-17 20:58:02,340 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
>>> fs.exists('/tmp/horovod/intermediate_train_data.0')`

**Comment by arunraman** [comment]
This is the error when I get 

`_check_url: hdfs://
Done with this
hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Messagejava.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
        at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
Traceback (most recent call last):
  File "/tmp/d28ed9e680744356ae0fa4909972b2da/sparkJobEstimator.py", line 335, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 636, in prepare_data
    num_partitions, num_processes, verbose)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 572, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 413, in get_simple_meta_from_parquet
    raise ValueError("{} path does not exist in the store".format(train_data_path))
ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [d28ed9e680744356ae0fa4909972b2da] failed with error:
Job failed with message [ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store]. Additional details can be found at:
`

**Comment by tgravescs** [comment]
this is likely the same issue I ran into: https://issues.apache.org/jira/browse/ARROW-9019?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by EnricoMi** [comment]
Your error says: `org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message`, so I think it is a version mismatch of one of the jars Spark is using. Which hadoop version do your images have and which hadoop version does your Spark 3.0 expect?

**Comment by EnricoMi** [comment]
Your linked issue is already looking at this: https://github.com/GoogleCloudDataproc/initialization-actions/issues/779#issuecomment-660398028

**Comment by EnricoMi** [comment]
When you install pyspark over pip, it brings in its own Spark jars and dependencies, e.g. lib/python3.6/site-packages/pyspark/jars. Not sure how pyspark sorts out which jars to use, those or the jars installed on the system but maybe worth checking. In the Spark UI there is an environment tab which lists all jars used by the Spark process. Maybe that helps.
