### ISSUE TITLE
ncclCommInitRank failed: internal error

### ISSUE THREAD

**Issue by xasopheno** [horovod/horovod#2113]
**Environment:**
1. Framework:  Pytorch : 
2. Framework version: 1.5.0
3. Horovod version: 0.19.5
4. MPI version: 4.0.4
5. CUDA version: 11.0
6. NCCL version: 10.2, V10.2.89 
7. Python version: 3.7,4
8. Spark / PySpark version: N/A
9. OS and version: Arch Linux 
10. GCC version: 10.1.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

Trying to run the minst example with 2 gpus (output from nvidia-smi at bottom), but it's failing with ncclCommInitRank failed: internal error. I'm able to train on each GPU individually. Out put from the following command below:

`NCCL_DEBUG=INFO mpirun -np 2 python mnist.py`

Thanks for taking a look. 

```
xasopheno:4605:4619 [0] NCCL INFO Bootstrap : Using [0]wlp4s0:192.168.1.164<0>
xasopheno:4605:4619 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

xasopheno:4605:4619 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
xasopheno:4605:4619 [0] NCCL INFO NET/Socket : Using [0]wlp4s0:192.168.1.164<0>
xasopheno:4605:4619 [0] NCCL INFO Using network Socket
NCCL version 2.6.4+cuda10.2
xasopheno:4606:4620 [1] NCCL INFO Bootstrap : Using [0]wlp4s0:192.168.1.164<0>
xasopheno:4606:4620 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

xasopheno:4606:4620 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
xasopheno:4606:4620 [1] NCCL INFO NET/Socket : Using [0]wlp4s0:192.168.1.164<0>
xasopheno:4606:4620 [1] NCCL INFO Using network Socket

xasopheno:4605:4619 [0] graph/xml.h:221 NCCL WARN KV Convert to int : could not find value of '8.0 GT/s PCIe' in dictionary
xasopheno:4605:4619 [0] NCCL INFO graph/topo.cc:361 -> 3
xasopheno:4605:4619 [0] NCCL INFO graph/topo.cc:397 -> 3
xasopheno:4605:4619 [0] NCCL INFO graph/topo.cc:469 -> 3
xasopheno:4605:4619 [0] NCCL INFO graph/topo.cc:569 -> 3
xasopheno:4605:4619 [0] NCCL INFO init.cc:606 -> 3
xasopheno:4605:4619 [0] NCCL INFO init.cc:860 -> 3
xasopheno:4605:4619 [0] NCCL INFO init.cc:895 -> 3
xasopheno:4605:4619 [0] NCCL INFO init.cc:906 -> 3

xasopheno:4606:4620 [1] graph/xml.h:221 NCCL WARN KV Convert to int : could not find value of '8.0 GT/s PCIe' in dictionary
xasopheno:4606:4620 [1] NCCL INFO graph/topo.cc:361 -> 3
xasopheno:4606:4620 [1] NCCL INFO graph/topo.cc:397 -> 3
xasopheno:4606:4620 [1] NCCL INFO graph/topo.cc:469 -> 3
xasopheno:4606:4620 [1] NCCL INFO graph/topo.cc:569 -> 3
xasopheno:4606:4620 [1] NCCL INFO init.cc:606 -> 3
xasopheno:4606:4620 [1] NCCL INFO init.cc:860 -> 3
xasopheno:4606:4620 [1] NCCL INFO init.cc:895 -> 3
xasopheno:4606:4620 [1] NCCL INFO init.cc:906 -> 3
mnist.py:52: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
mnist.py:52: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
Traceback (most recent call last):
  File "mnist.py", line 190, in <module>
    train(epoch)
  File "mnist.py", line 66, in train
    optimizer.step()
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/__init__.py", line 177, in synchronize
    output = synchronize(handle)
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclCommInitRank failed: internal error
Traceback (most recent call last):
  File "mnist.py", line 190, in <module>
    train(epoch)
  File "mnist.py", line 66, in train
    optimizer.step()
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/__init__.py", line 177, in synchronize
    output = synchronize(handle)
  File "/home/danny/.local/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclCommInitRank failed: internal error
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[7896,1],0]
  Exit code:    1
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:0A:00.0  On |                  N/A |
| 24%   40C    P8    11W / 250W |    360MiB / 11175MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 23%   38C    P8     9W / 250W |      7MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by tgaddair** [comment]
Hey @xasopheno, does this error also occur when using `horovodrun`?  And can you verify that `CUDA_VISIBLE_DEVICES` is not set?

It looks to me like NCCL is trying to use the same device on both ranks.

**Comment by xasopheno** [comment]
Thank you for your help, @tgaddair.
Built following this guide:
https://medium.com/@luca.diliello/install-horovod-on-arch-and-manjaro-linux-with-pytorch-and-gpu-support-e940ffde40ab

I have the same error running:
`NCCL_DEBUG=INFO horovodrun -np 2 python mnist.py` 
and
`NCCL_DEBUG=INFO mpirun -np 2 python mnist.py` 

on the other hand:
`horovodrun -np 2 python adasum.py`
using `adasum.py` from the examples works fine. 

I don't believe CUDA_VISIBLE_DEVICES is set. 

Any ideas?

**Comment by sjeaugey** [comment]
What is the system you are running on @xasopheno ? In particular, what OS (manjaro linux?), what kernel version ?

Can you set `NCCL_TOPO_DUMP_FILE=system.xml` and see if you can generate a topology dump ? One workaround could be to generate the topology XML, replace "8.0 GT/s PCIe" by "8 GT/s" then inject it back with `NCCL_TOPO_FILE=system.xml`. But there might be other things to fix so I'd like to see what it looks like.

Finally, feel free to open a bug on the NCCL github project. Thanks.

**Comment by wuyujiji** [comment]
excuse me, @xasopheno ,did you solve this problem? I met the same problem.

**Comment by sjeaugey** [comment]
@wuyujiji if you could post the output of `uname -r` and also run again with `NCCL_TOPO_DUMP_FILE=system.xml` and post the generated `system.xml` file here, that would be very useful. Thanks !

**Comment by MakoXiao** [comment]
I met the same problem use docker. when add --shm-size=1024m  to start container, solve the problem

**Comment by sjeaugey** [comment]
@MakoXiao  adding `--shm-size=1024m` is a good solution when NCCL fails to create shared memory.

Setting `NCCL_DEBUG=WARN` should have printed an explicit error message that creating shared memory failed.

@Arij-Aladel got an "Invalid usage"  error which means it was probably some different issue. Again, setting `NCCL_DEBUG=WARN` should have printed what the problem was and hopefully helped solve the problem.
