### ISSUE TITLE
Unconnected Gradient

### ISSUE THREAD

**Issue by rajexplo** [horovod/horovod#2120]
Hello All-
I was trying to use TF2.0 api `self.model.trainable_variables,unconnected_gradients=tf.UnconnectedGradients.ZERO)`
with `tape = hvd.DistributedGradientTape(tape)`.
It throws an error that `keyword =unconnected_gradients is not defined`.
Any idea and thoughts will be really appreciated.

Thanks!
Raj

**Comment by tgaddair** [comment]
Hey @rajexplo, could you provide a minimal example I can run to repro the issue, as well as the full stack trace?

**Comment by rajexplo** [comment]
@tgaddair Thank you! Sure I will post these.

**Comment by rajexplo** [comment]
@tgaddair here is the detailed stack trace
```Traceback (most recent call last):
  File "run_pinn.py", line 94, in <module>
    data_mask=(True,True,True,False))
  File "/autofs/nccs-svm1_proj/eng120/test_work/LES/pinn.py", line 373, in train
    ba)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 3211, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-3/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /autofs/nccs-svm1_proj/eng120/test_work/LES/pinn.py:432 training_step  *
        gradients_data = tape.gradient(loss_data,

    TypeError: tf__gradient() got an unexpected keyword argument 'unconnected_gradients''''

**Comment by rajexplo** [comment]
Hi @tgaddair , I just had a question on `horovod.braodcast_variables`, This only broadcast the iterable objects. How to broadcast a float or integer declares as `tf.variable`.
