### ISSUE TITLE
Horovod pyarrow IndexError: list index out of range

### ISSUE THREAD

**Issue by ZhenyiLin** [horovod/horovod#2193]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.14
3. Horovod version: 0.19.5
4. MPI version: 4.0.4
5. CUDA version: NA
6. NCCL version: NA
7. Python version: 3.6
8. Spark / PySpark version: 2.4.4
9. OS and version: Amazon Linux
10. GCC version: 7.2.1

The nmist example. error is on the model fitting:
```
>>> #store = Store.create("hdfs:///user/hvd")
... # Train a Horovod Spark Estimator on the DataFrame
... keras_estimator = hvd.KerasEstimator(num_proc=1,
...                                      store=store,
...                                      model=model,
...                                      optimizer=optimizer,
...                                      loss=loss,
...                                      metrics=['accuracy'],
...                                      feature_cols=['features'],
...                                      label_cols=['label_vec'],
...                                      batch_size=256,
...                                      epochs=10,
...                                      verbose=3)
>>>
>>> keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])
num_partitions=10
writing dataframes
train_data_path=file:///var/lib/hvd/intermediate_train_data.0
val_data_path=file:///var/lib/hvd/intermediate_val_data.0
train_partitions=10
zl file:///var/lib/hvd/intermediate_train_data.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/home/hadoop/conda/envs/py36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/util.py", line 637, in prepare_data
    num_partitions, num_processes, verbose)
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/util.py", line 573, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/util.py", line 457, in get_simple_meta_from_parquet
    train_data = store.get_parquet_dataset(train_data_path)
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/horovod/spark/common/store.py", line 176, in get_parquet_dataset
    return pq.ParquetDataset(self.get_localized_path(path), filesystem=self.get_filesystem())
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/pyarrow/parquet.py", line 1060, in __init__
    self.validate_schemas()
  File "/home/hadoop/conda/envs/py36/lib/python3.6/site-packages/pyarrow/parquet.py", line 1092, in validate_schemas
    self.schema = self.pieces[0].get_metadata().schema
IndexError: list index out of range
```

I have 1 master node and 1 worker node and the Spark is running in the client mode. 
When I checked the `intermediate_train_data.X` folder. In the master node, it has a `_SUCCESS` file; In the worker node, it has `_tempory` file.  It seems the writing process hasn't been completed yet in the worker node.

**Comment by tgaddair** [comment]
Hey @ZhenyiLin, I believe Databricks ran into this issue when implementing the Spark Dataset Converter for Petastorm (https://github.com/uber/petastorm/pull/496).  

We have a PR in progress to migrate to the Spark Dataset Converter API, which should hopefully resolve this issue: #2091.

@WeichenXu123, can you confirm that the Spark Dataset Converter should  avoid this race condition?

**Comment by ZhenyiLin** [comment]
@tgaddair  @WeichenXu123  
Thanks for the technical support. We are configing and testing Horovod in AWS EMR.

Some more information to share:
1) The error makes the Horovod run unstable. It is Not always failed. Sometimes it works fine but sometimes not
2) a) Repartitioning the Spark Dataframe into smaller partitions; b) change Spark Resources may help avoid the error coming up, but the error appears randomly and I have to manually do this.

**Comment by MsAlEhR** [comment]
Hi, @tgaddair I have exactly the same issue in running keras_spark_mnist.py on a spark cluster.
Following is what I see.
`writing dataframes train_data_path=file:///home/spark/sample_code/horovod_keras_spark_mnist/intermediate_train_data.0 val_data_path=file:///home/spark/sample_code/horovod_keras_spark_mnist/intermediate_val_data.0 train_partitions=80 Traceback (most recent call last): File "keras_spark_mnist.py", line 125, in <module> keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob']) File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/estimator.py", line 35, in fit return super(HorovodEstimator, self).fit(df, params) File "/home/spark/anaconda3/lib/python3.8/site-packages/pyspark/ml/base.py", line 161, in fit return self._fit(dataset) File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/estimator.py", line 68, in _fit with util.prepare_data(backend.num_processes(), File "/home/spark/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__ return next(self.gen) File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/util.py", line 668, in prepare_data dataset_idx = _get_or_create_dataset(key, store, df, feature_columns, label_columns, File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/util.py", line 605, in _get_or_create_dataset train_rows, val_rows, pq_metadata, avg_row_size = get_simple_meta_from_parquet( File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/util.py", line 490, in get_simple_meta_from_parquet train_data = store.get_parquet_dataset(train_data_path) File "/home/spark/anaconda3/lib/python3.8/site-packages/horovod/spark/common/store.py", line 213, in get_parquet_dataset return pq.ParquetDataset(self.get_localized_path(path), filesystem=self.fs) File "/home/spark/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 1364, in __init__ self.validate_schemas() File "/home/spark/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 1395, in validate_schemas self.schema = self._pieces[0].get_metadata().schema IndexError: list index out of range'
