### ISSUE TITLE
Exception: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by xzswater** [horovod/horovod#2225]
**Environment:**
Framework: (TensorFlow, Keras, PyTorch, MXNet): tensorflow
Framework version: 2.3.0
Horovod version: 0.19.5
MPI version: 3.1.0
CUDA version: 10.1.243
NCCL version: 2.4.7
Python version: 3.6.10
OS and version: CentOS 6.10
GCC version: 8.2.0

**Bug report:**

horovodrun -np 1 -H localhost:1 ../../pyenv/bin/python3 main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/demo_train2/*.tfrecord \
    --validation_file_pattern=tfrecord/demo_test2/*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=efficientdet-d0-finetune \
    --ckpt=efficientdet-d0 \
    --train_batch_size=2 \
    --eval_batch_size=2 --eval_samples=500 \
    --num_examples_per_epoch=5000 --num_epochs=20 \
    --hparams=aicv_config.yaml \
    --strategy=horovod

2020-09-02 17:46:07.848489: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-02 17:46:10.120206: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
**Exception happened during safe_shell_exec, exception message: module '__main__' has no attribute '__spec__'**
Traceback (most recent call last):
  File "/root/efficientdet/pyenv/bin/horovodrun", line 4, in <module>
    __import__('pkg_resources').run_script('horovod==0.19.5', 'horovodrun')
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/EGG-INFO/scripts/horovodrun", line 21, in <module>
    run_commandline()
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/runner.py", line 723, in run_commandline
    _run(args)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/runner.py", line 656, in _run
    _launch_job(args, remote_host_names, settings, nics, command)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/runner.py", line 717, in _launch_job
    args.verbose)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/runner.py", line 694, in run_controller
    gloo_run()
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/runner.py", line 706, in gloo_run_fn
    gloo_run(settings, remote_host_names, nics, env, driver_ip, command)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/gloo_run.py", line 312, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/horovod-0.19.5-py3.6-linux-x86_64.egg/horovod/run/gloo_run.py", line 304, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 1

**Comment by tgaddair** [comment]
Hey @xzswater, does your script include a `if __name__ == '__main__':` line like [this](https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L110)?

Can you share a minimal example that reproduces the issue?

**Comment by xzswater** [comment]
> Hey @xzswater, does your script include a `if __name__ == '__main__':` line like [this](https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L110)?
> 
> Can you share a minimal example that reproduces the issue?

@tgaddair  Yes, it does.
https://github.com/google/automl/blob/master/efficientdet/main.py#L381
![image](https://user-images.githubusercontent.com/52267702/92065223-da9ea800-edd1-11ea-9ea5-8a081e596072.png)

the flags of install horovod are:
export HOROVOD_WITH_GLOO=1
**export HOROVOD_WITHOUT_MPI=1**


Finally, i reinstall horovod by:
export HOROVOD_WITH_GLOO=1
**export HOROVOD_WITH_MPI=1**

Then, it works.

**Comment by tgaddair** [comment]
The issue you're seeing is related to Python multiprocessing, which is used by our Gloo controller.  When you enable MPI, it is used as the default instead of Gloo.  So that's why you no longer see this issue.

I have never seen this error myself, but this sort of error is known to occur in some situations when using Python's multiprocessing spawn API (examples [here](https://stackoverflow.com/questions/45720153/python-multiprocessing-error-attributeerror-module-main-has-no-attribute)).  I'll see if there's something we can do to mitigate this on our end, but this is likely outside of our control (the problem lies with Python multiprocessing, most likely).

Usually, it can be resolved by restructuring the Python script so that certain parts are or are not executed when the subprocess is spawned.

I'll take a look at the example linked and see if I can reproduce the error, but glad you have a workaround using MPI.
