### ISSUE TITLE
DataLoader worker (pid(s) 372) exited unexpectedly

### ISSUE THREAD

**Issue by JBlade97** [horovod/horovod#2255]
**Environment:**
Using horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1

CPU:

After attempting to run pytorch_mnist.py on my 3 GPU machine I have experienced an issue whcih produces this code after running this command which only uses one GPU 

`horovodrun -np 3  -H localhost:3 python keras_mnist_advanced.py`

this was the output:
```

root@8acf34b9d899:/examples# horovodrun -np 1 -H localhost:1 python pytorch_mnist.py 
2020-09-10 07:29:57.014657: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[1,0]<stdout>:Train Epoch: 1 [0/60000 (0%)]	Loss: 2.319920
[1,0]<stdout>:Train Epoch: 1 [640/60000 (1%)]	Loss: 2.322078
[1,0]<stdout>:Train Epoch: 1 [1280/60000 (2%)]	Loss: 2.313210
[1,0]<stdout>:Train Epoch: 1 [1920/60000 (3%)]	Loss: 2.290465
[1,0]<stdout>:Train Epoch: 1 [2560/60000 (4%)]	Loss: 2.284353
[1,0]<stdout>:Train Epoch: 1 [3200/60000 (5%)]	Loss: 2.306196
[1,0]<stdout>:Train Epoch: 1 [3840/60000 (6%)]	Loss: 2.284096
[1,0]<stdout>:Train Epoch: 1 [4480/60000 (7%)]	Loss: 2.256881
[1,0]<stdout>:Train Epoch: 1 [5120/60000 (9%)]	Loss: 2.296729
[1,0]<stdout>:Train Epoch: 1 [5760/60000 (10%)]	Loss: 2.208463
[1,0]<stdout>:Train Epoch: 1 [6400/60000 (11%)]	Loss: 2.200152
[1,0]<stdout>:Train Epoch: 1 [7040/60000 (12%)]	Loss: 2.165307
[1,0]<stdout>:Train Epoch: 1 [7680/60000 (13%)]	Loss: 2.167025
[1,0]<stdout>:Train Epoch: 1 [8320/60000 (14%)]	Loss: 2.197203
[1,0]<stdout>:Train Epoch: 1 [8960/60000 (15%)]	Loss: 2.056466
[1,0]<stdout>:Train Epoch: 1 [9600/60000 (16%)]	Loss: 1.983276
[1,0]<stdout>:Train Epoch: 1 [10240/60000 (17%)]	Loss: 1.973536
[1,0]<stdout>:Train Epoch: 1 [10880/60000 (18%)]	Loss: 1.790172
[1,0]<stdout>:Train Epoch: 1 [11520/60000 (19%)]	Loss: 1.906904
[1,0]<stdout>:Train Epoch: 1 [12160/60000 (20%)]	Loss: 1.557326
[1,0]<stdout>:Train Epoch: 1 [12800/60000 (21%)]	Loss: 1.502043
[1,0]<stdout>:Train Epoch: 1 [13440/60000 (22%)]	Loss: 1.493139
[1,0]<stdout>:Train Epoch: 1 [14080/60000 (23%)]	Loss: 1.159590
[1,0]<stdout>:Train Epoch: 1 [14720/60000 (25%)]	Loss: 1.192405
[1,0]<stdout>:Train Epoch: 1 [15360/60000 (26%)]	Loss: 1.201173
[1,0]<stdout>:Train Epoch: 1 [16000/60000 (27%)]	Loss: 1.277368
[1,0]<stdout>:Train Epoch: 1 [16640/60000 (28%)]	Loss: 1.117633
[1,0]<stdout>:Train Epoch: 1 [17280/60000 (29%)]	Loss: 1.052001
[1,0]<stdout>:Train Epoch: 1 [17920/60000 (30%)]	Loss: 1.199468
[1,0]<stdout>:Train Epoch: 1 [18560/60000 (31%)]	Loss: 0.977148
[1,0]<stdout>:Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.949219
[1,0]<stdout>:Train Epoch: 1 [19840/60000 (33%)]	Loss: 0.951569
[1,0]<stdout>:Train Epoch: 1 [20480/60000 (34%)]	Loss: 1.109044
[1,0]<stdout>:Train Epoch: 1 [21120/60000 (35%)]	Loss: 0.943313
[1,0]<stdout>:Train Epoch: 1 [21760/60000 (36%)]	Loss: 0.840986
[1,0]<stdout>:Train Epoch: 1 [22400/60000 (37%)]	Loss: 0.765999
[1,0]<stdout>:Train Epoch: 1 [23040/60000 (38%)]	Loss: 0.675712
[1,0]<stdout>:Train Epoch: 1 [23680/60000 (39%)]	Loss: 0.611269
[1,0]<stdout>:Train Epoch: 1 [24320/60000 (41%)]	Loss: 0.707863
[1,0]<stdout>:Train Epoch: 1 [24960/60000 (42%)]	Loss: 0.734542
[1,0]<stdout>:Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.902080
[1,0]<stdout>:Train Epoch: 1 [26240/60000 (44%)]	Loss: 0.821693
[1,0]<stdout>:Train Epoch: 1 [26880/60000 (45%)]	Loss: 0.602137
[1,0]<stdout>:Train Epoch: 1 [27520/60000 (46%)]	Loss: 0.921258
[1,0]<stdout>:Train Epoch: 1 [28160/60000 (47%)]	Loss: 0.716877
[1,0]<stdout>:Train Epoch: 1 [28800/60000 (48%)]	Loss: 0.654385
[1,0]<stdout>:Train Epoch: 1 [29440/60000 (49%)]	Loss: 0.624213
[1,0]<stdout>:Train Epoch: 1 [30080/60000 (50%)]	Loss: 0.661919
[1,0]<stdout>:Train Epoch: 1 [30720/60000 (51%)]	Loss: 0.718396
[1,0]<stdout>:Train Epoch: 1 [31360/60000 (52%)]	Loss: 0.681452
[1,0]<stdout>:Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.714979
[1,0]<stdout>:Train Epoch: 1 [32640/60000 (54%)]	Loss: 0.610486
[1,0]<stdout>:Train Epoch: 1 [33280/60000 (55%)]	Loss: 0.564538
[1,0]<stdout>:Train Epoch: 1 [33920/60000 (57%)]	Loss: 0.485014
[1,0]<stdout>:Train Epoch: 1 [34560/60000 (58%)]	Loss: 0.882546
[1,0]<stdout>:Train Epoch: 1 [35200/60000 (59%)]	Loss: 0.847247
[1,0]<stdout>:Train Epoch: 1 [35840/60000 (60%)]	Loss: 0.636450
[1,0]<stdout>:Train Epoch: 1 [36480/60000 (61%)]	Loss: 0.506960
[1,0]<stdout>:Train Epoch: 1 [37120/60000 (62%)]	Loss: 0.638069
[1,0]<stdout>:Train Epoch: 1 [37760/60000 (63%)]	Loss: 0.534816
[1,0]<stdout>:Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.405889
[1,0]<stdout>:Train Epoch: 1 [39040/60000 (65%)]	Loss: 0.648296
[1,0]<stdout>:Train Epoch: 1 [39680/60000 (66%)]	Loss: 0.299071
[1,0]<stdout>:Train Epoch: 1 [40320/60000 (67%)]	Loss: 0.764174
[1,0]<stdout>:Train Epoch: 1 [40960/60000 (68%)]	Loss: 0.699550
[1,0]<stdout>:Train Epoch: 1 [41600/60000 (69%)]	Loss: 0.747515
[1,0]<stdout>:Train Epoch: 1 [42240/60000 (70%)]	Loss: 0.588037
[1,0]<stdout>:Train Epoch: 1 [42880/60000 (71%)]	Loss: 0.472082
[1,0]<stdout>:Train Epoch: 1 [43520/60000 (72%)]	Loss: 0.557491
[1,0]<stdout>:Train Epoch: 1 [44160/60000 (74%)]	Loss: 0.617174
[1,0]<stdout>:Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.432833
[1,0]<stdout>:Train Epoch: 1 [45440/60000 (76%)]	Loss: 0.444908
[1,0]<stdout>:Train Epoch: 1 [46080/60000 (77%)]	Loss: 0.554831
[1,0]<stdout>:Train Epoch: 1 [46720/60000 (78%)]	Loss: 0.492551
[1,0]<stdout>:Train Epoch: 1 [47360/60000 (79%)]	Loss: 0.407582
[1,0]<stdout>:Train Epoch: 1 [48000/60000 (80%)]	Loss: 0.632556
[1,0]<stdout>:Train Epoch: 1 [48640/60000 (81%)]	Loss: 0.476061
[1,0]<stdout>:Train Epoch: 1 [49280/60000 (82%)]	Loss: 0.756815
[1,0]<stdout>:Train Epoch: 1 [49920/60000 (83%)]	Loss: 0.537466
[1,0]<stdout>:Train Epoch: 1 [50560/60000 (84%)]	Loss: 0.562284
[1,0]<stdout>:Train Epoch: 1 [51200/60000 (85%)]	Loss: 1.036752
[1,0]<stdout>:Train Epoch: 1 [51840/60000 (86%)]	Loss: 0.561211
[1,0]<stdout>:Train Epoch: 1 [52480/60000 (87%)]	Loss: 0.449658
[1,0]<stdout>:Train Epoch: 1 [53120/60000 (88%)]	Loss: 0.504039
[1,0]<stdout>:Train Epoch: 1 [53760/60000 (90%)]	Loss: 0.627796
[1,0]<stdout>:Train Epoch: 1 [54400/60000 (91%)]	Loss: 0.405917
[1,0]<stdout>:Train Epoch: 1 [55040/60000 (92%)]	Loss: 0.597174
[1,0]<stdout>:Train Epoch: 1 [55680/60000 (93%)]	Loss: 0.488670
[1,0]<stdout>:Train Epoch: 1 [56320/60000 (94%)]	Loss: 0.264431
[1,0]<stdout>:Train Epoch: 1 [56960/60000 (95%)]	Loss: 0.654959
[1,0]<stdout>:Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.554720
[1,0]<stdout>:Train Epoch: 1 [58240/60000 (97%)]	Loss: 0.443470
[1,0]<stdout>:Train Epoch: 1 [58880/60000 (98%)]	Loss: 0.458032
[1,0]<stdout>:Train Epoch: 1 [59520/60000 (99%)]	Loss: 0.319679
[1,0]<stderr>:pytorch_mnist.py:52: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
[1,0]<stderr>:  return F.log_softmax(x)
[1,0]<stderr>:ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
[1,0]<stderr>:[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
[1,0]<stderr>:    data = self._data_queue.get(timeout=timeout)
[1,0]<stderr>:  File "/usr/lib/python3.7/queue.py", line 178, in get
[1,0]<stderr>:    raise Empty
[1,0]<stderr>:_queue.Empty
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "pytorch_mnist.py", line 189, in <module>
[1,0]<stderr>:    test()
[1,0]<stderr>:  File "pytorch_mnist.py", line 85, in test
[1,0]<stderr>:    for data, target in test_loader:
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
[1,0]<stderr>:    data = self._next_data()
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 974, in _next_data
[1,0]<stderr>:    idx, data = self._get_data()
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 931, in _get_data
[1,0]<stderr>:    success, data = self._try_get_data()
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
[1,0]<stderr>:    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
[1,0]<stderr>:RuntimeError: DataLoader worker (pid(s) 372) exited unexpectedly
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[3599,1],0]
  Exit code:    1

```

My machine specifications are:

MSI NVIDIA GeForce RTX 2070 SUPER 8GB VENTUS GP OC (quantity 3)

GIGABYTE Z390 DESIGNARE Intel Z390 ATX Motherboard

HyperX FURY 16GB DDR4 2666Mhz Memory For Desktop (quantity: 2)

**Comment by tgaddair** [comment]
Hey @JBlade97, can you try setting `num_workers=0` in the DataLoader config?  Might be a multiprocessing issue similar to #2053.
