### ISSUE TITLE
install horovod==0.20.0 failed

### ISSUE THREAD

**Issue by jiaqianjing** [horovod/horovod#2276]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow

2. Framework version:
tensorflow-gpu==1.15.0

3. Horovod version:
horovod==0.20.0 

4. MPI version:
4.0.1

5. CUDA version:
10.0.130

6. NCCL version:
2.5.6

7. Python version:
Python 3.6.8

8. OS and version:
CentOS Linux 7

9. GCC version:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

Exec cmd:
```shell
HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod==0.20.0
```

Eorror logs:
```
    [ 60%] Building CXX object third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o
    cd /var/tmp/pip-install-hj8w78_g/horovod/build/temp.linux-x86_64-3.6/third_party/compatible_gloo/gloo && /usr/bin/c++  -DEIGEN_MPL2_ONLY=1 -DGLOO_USE_MPI=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_MPI=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLGATHER=78 -DHOROVOD_GPU_ALLREDUCE=78 -DHOROVOD_GPU_ALLTOALL=78 -DHOROVOD_GPU_BROADCAST=78 -D_GLIBCXX_USE_CXX11_ABI=0 -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/HTTPRequest/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/assert/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/config/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/core/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/detail/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/iterator/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/lockfree/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/mpl/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/parameter/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/predef/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/preprocessor/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/static_assert/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/type_traits/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/boost/utility/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/eigen -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/flatbuffers/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/lbfgs/include -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo -I/var/tmp/pip-install-hj8w78_g/horovod/third_party/compatible_gloo -I/var/tmp/pip-install-hj8w78_g/horovod/build/temp.linux-x86_64-3.6/third_party/compatible_gloo -isystem /usr/local/cuda/include  -pthread -fPIC -O3 -Wall -ftree-vectorize -g -mf16c -mavx -mfma -std=c++11 -fPIC -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o -c /var/tmp/pip-install-hj8w78_g/horovod/third_party/compatible_gloo/gloo/transport/tcp/context.cc
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/compatible_gloo/gloo/transport/tcp/address.cc:9:0:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/buffer.h:20,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/buffer.cc:9:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/address.cc.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/buffer.h:20,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/compatible_gloo/gloo/transport/tcp/buffer.cc:9:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    gmake[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o] Error 1
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/buffer.cc.o] Error 1
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/device.cc:20:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/context.cc:14:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    In file included from /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /var/tmp/pip-install-hj8w78_g/horovod/third_party/compatible_gloo/gloo/transport/tcp/context.cc:14:
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /var/tmp/pip-install-hj8w78_g/horovod/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    gmake[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o] Error 1
    gmake[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/context.cc.o] Error 1
    gmake[2]: Leaving directory `/var/tmp/pip-install-hj8w78_g/horovod/build/temp.linux-x86_64-3.6'
    gmake[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/all] Error 2
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o] Error 1
    gmake[2]: Leaving directory `/var/tmp/pip-install-hj8w78_g/horovod/build/temp.linux-x86_64-3.6'
    gmake[1]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/all] Error 2
    gmake[1]: Leaving directory `/var/tmp/pip-install-hj8w78_g/horovod/build/temp.linux-x86_64-3.6'
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/tmp/pip-install-hj8w78_g/horovod/setup.py", line 166, in <module>
        'horovodrun = horovod.runner.launch:run_commandline'
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/local/lib64/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/var/tmp/pip-install-hj8w78_g/horovod/setup.py", line 87, in build_extensions
        cwd=self.build_temp)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/tmp/pip-install-hj8w78_g/horovod/setup.py'"'"'; __file__='"'"'/var/tmp/pip-install-hj8w78_g/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /var/tmp/pip-record-9m7vtz7d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/horovod Check the logs for full command output.
```

**Comment by lengoanhcat** [comment]
Could you check whether any other flags HOROVOD_ALL_REDUCE=NCCL are set not ? If they are set in your bash environment, please unset them before reinstalling horovod by pip. Hope it would help.

**Comment by jiaqianjing** [comment]
> HOROVOD_ALL_REDUCE
3q. But not work.

**Comment by jiaqianjing** [comment]
> Could you check whether any other flags HOROVOD_ALL_REDUCE=NCCL are set not ? If they are set in your bash environment, please unset them before reinstalling horovod by pip. Hope it would help.

3Q. But not work.

**Comment by lengoanhcat** [comment]
If you are able to use anaconda, you can use this guideline to install horovod https://github.com/kaust-vislab/horovod-gpu-data-science-project. It would help avoid many installation problems. 

Just have to change a bit in the environment.yaml to install horovod after pytorch

```
name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cmake=3.17
  - cudatoolkit=10.1
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.1
  - jupyterlab=2.2
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.5
  - nodejs=14
  - nvcc_linux-64=10.1
  - pip=20.1
  - python=3.7
  - pytorch=1.5
  - tensorboard=2.1
  - torchvision=0.6  
  - pip:
    - mxnet-cu101mkl==1.6.* # makes sure frameworks are installed prior to horovod
    - tensorflow-gpu==2.1.*
    - -r file:requirements.txt
```

**Comment by ft3020997** [comment]
HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 pip install --no-cache-dir horovod

You could try this command below.

The error logs showed this issue may be caused by gloo install, if you don't need gloo you can set "HOROVOD_WITHOUT_GLOO=1"

**Comment by jiaqianjing** [comment]
3Q @ft3020997
