### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_train_data_path'

### ISSUE THREAD

**Issue by WangHeguan** [horovod/horovod#2302]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:0.19.5
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:3.7
8. OS and version:mac os
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Traceback (most recent call last):
  File "/Users/heguanwang/Documents/code/spark-keras/lstm_horovod.py", line 90, in <module>
    keras_model = keras_estimator.fit(sdf)
  File "/Users/heguanwang/Library/Python/3.7/lib/python/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/local/lib/python3.7/site-packages/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)
  File "/Users/heguanwang/Library/Python/3.7/lib/python/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/heguanwang/Library/Python/3.7/lib/python/site-packages/horovod/spark/common/util.py", line 632, in prepare_data
    key = _training_cache.create_key(df, store, validation)
  File "/Users/heguanwang/Library/Python/3.7/lib/python/site-packages/horovod/spark/common/cache.py", line 29, in create_key
    return df.__hash__(), store.get_train_data_path(), store.get_val_data_path(), validation
AttributeError: 'NoneType' object has no attribute 'get_train_data_path'

**Comment by tgaddair** [comment]
Hey @WangHeguan, did you pass a value to parameter `store` as in `KerasEstimator(store=...)`?

**Comment by OscarDPan** [comment]
Hi I have the same problem. Do I have to pass a value to store? Isn't it optional?

**Comment by tgaddair** [comment]
Hey @OscarDPan, we have plans to make it optional in the future (see #2091).

For now, you can create a local store in `/tmp` pretty easily with `Store.create('/tmp`)` as shown [here](https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py#L55).
