### ISSUE TITLE
'Could not find _common_metadata file. Use materialize_dataset(..) in'

### ISSUE THREAD

**Issue by WangHeguan** [horovod/horovod#2313]
**Environment:**
1. Framework: TensorFlow,==2.3.0
2. Framework version:
3. Horovod version:0.20.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:3.7
8. Spark / PySpark version:2.4.0
9. OS and version:
10. GCC version:
11. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
[1,9]<stderr>:Traceback (most recent call last):
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,9]<stderr>:    return get_schema(dataset)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema
[1,9]<stderr>:    'Could not find _common_metadata file. Use materialize_dataset(..) in'
[1,9]<stderr>:petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
[1,9]<stderr>:
[1,9]<stderr>:During handling of the above exception, another exception occurred:
[1,9]<stderr>:
[1,9]<stderr>:Traceback (most recent call last):
[1,9]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,9]<stderr>:    "__main__", mod_spec)
[1,9]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[1,9]<stderr>:    exec(code, run_globals)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,9]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,9]<stderr>:    [1,9]<stderr>:task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')[1,9]<stderr>:
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,9]<stderr>:    result = fn(*args, **kwargs)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 208, in train
[1,9]<stderr>:    **reader_factory_kwargs) as train_reader:
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 300, in make_batch_reader
[1,9]<stderr>:    filters=filters)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 380, in __init__
[1,9]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 411, in infer_or_load_unischema
[1,9]<stderr>:    return Unischema.from_arrow_schema(dataset)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/unischema.py", line 336, in from_arrow_schema
[1,9]<stderr>:    arrow_field = compat_schema_field(arrow_schema, column_name)
[1,9]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/compat.py", line 80, in compat_schema_field
[1,9]<stderr>:    return schema.field(name)
[1,9]<stderr>:AttributeError[1,9]<stderr>:: 'pyarrow.lib.Schema' object has no attribute 'field'
[1,0]<stderr>:2020-09-22 21:22:14.085374: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,0]<stderr>:    return get_schema(dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema
[1,0]<stderr>:    'Could not find _common_metadata file. Use materialize_dataset(..) in'
[1,0]<stderr>:petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,0]<stderr>:    "__main__", mod_spec)
[1,0]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[1,0]<stderr>:    exec(code, run_globals)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,0]<stderr>:    [1,0]<stderr>:task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,0]<stderr>:    result = fn(*args, **kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 208, in train
[1,0]<stderr>:    **reader_factory_kwargs) as train_reader:
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 300, in make_batch_reader
[1,0]<stderr>:    filters=filters)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 380, in __init__
[1,0]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 411, in infer_or_load_unischema
[1,0]<stderr>:    return Unischema.from_arrow_schema(dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/unischema.py", line 336, in from_arrow_schema
[1,0]<stderr>:    arrow_field = compat_schema_field(arrow_schema, column_name)[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/compat.py", line 80, in compat_schema_field
[1,0]<stderr>:    return schema.field(name)
[1,0]<stderr>:AttributeError: 'pyarrow.lib.Schema' object has no attribute 'field'
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,4]<stderr>:    return get_schema(dataset)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema
[1,4]<stderr>:    'Could not find _common_metadata file. Use materialize_dataset(..) in'
[1,4]<stderr>:petastorm.etl.dataset_metadata.PetastormMetadataError[1,4]<stderr>:: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
[1,4]<stderr>:
[1,4]<stderr>:During handling of the above exception, another exception occurred:
[1,4]<stderr>:
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,4]<stderr>:    "__main__", mod_spec)
[1,4]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[1,4]<stderr>:    exec(code, run_globals)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,4]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,4]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,4]<stderr>:    result = fn(*args, **kwargs)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 208, in train
[1,4]<stderr>:    **reader_factory_kwargs) as train_reader:
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 300, in make_batch_reader
[1,4]<stderr>:    filters=filters)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 380, in __init__
[1,4]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 411, in infer_or_load_unischema
[1,4]<stderr>:    return Unischema.from_arrow_schema(dataset)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/unischema.py", line 336, in from_arrow_schema
[1,4]<stderr>:    arrow_field = compat_schema_field(arrow_schema, column_name)
[1,4]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/compat.py", line 80, in compat_schema_field
[1,4]<stderr>:    return schema.field(name)
[1,4]<stderr>:AttributeError: 'pyarrow.lib.Schema' object has no attribute 'field'
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,2]<stderr>:    [1,2]<stderr>:return get_schema(dataset)[1,2]<stderr>:
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema
[1,2]<stderr>:    [1,2]<stderr>:'Could not find _common_metadata file. Use materialize_dataset(..) in'[1,2]<stderr>:
[1,2]<stderr>:petastorm.etl.dataset_metadata.PetastormMetadataError[1,2]<stderr>:: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
[1,2]<stderr>:
[1,2]<stderr>:During handling of the above exception, another exception occurred:
[1,2]<stderr>:
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,2]<stderr>:    "__main__", mod_spec)
[1,2]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[1,2]<stderr>:    exec(code, run_globals)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,2]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,2]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,2]<stderr>:    result = fn(*args, **kwargs)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 208, in train
[1,2]<stderr>:    **reader_factory_kwargs) as train_reader:
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 300, in make_batch_reader
[1,2]<stderr>:    filters=filters)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 380, in __init__
[1,2]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 411, in infer_or_load_unischema
[1,2]<stderr>:    return Unischema.from_arrow_schema(dataset)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/unischema.py", line 336, in from_arrow_schema
[1,2]<stderr>:    arrow_field = compat_schema_field(arrow_schema, column_name)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/compat.py", line 80, in compat_schema_field
[1,2]<stderr>:    return schema.field(name)
[1,2]<stderr>:AttributeError: 'pyarrow.lib.Schema' object has no attribute 'field'
[1,8]<stderr>:Traceback (most recent call last):
[1,8]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,8]<stderr>:    return get_schema(dataset)
[1,8]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema

**Comment by tgaddair** [comment]
Hey @WangHeguan, can you tell me a little more about what you're doing?  Are you able to successfully run one of our example, like [keras_spark_mnist.py](https://github.com/horovod/horovod/blob/master/examples/keras_spark_mnist.py)?

**Comment by WangHeguan** [comment]
@tgaddair I just run keras_spark_mnist.py then this error happend

**Comment by alisoleimani** [comment]
Something changed in petastorm package I fixed this issue by using an older version petastorm==0.9.6
