### ISSUE TITLE
petastorm.etl.dataset_metadata.[1,0]<stderr>:PetastormMetadataError: Could not find _common_metadata file. 

### ISSUE THREAD

**Issue by WangHeguan** [horovod/horovod#2314]
**Environment:**
1. Framework: TensorFlow,==2.3.0
2. Framework version:
3. Horovod version:0.20.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:3.7
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I run the example keras_spark_mnist.py

the erros:
2020-09-23 14:05:32.891866: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-23 14:05:32.926845: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd17a19d580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-23 14:05:32.926857: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
num_partitions=10
writing dataframes
train_data_path=file:///usr/local/hadoop-2.7.7/tmp/dfs/name/intermediate_train_data.0
val_data_path=file:///usr/local/hadoop-2.7.7/tmp/dfs/name/intermediate_val_data.0
train_partitions=10
train_rows=53932
[Stage 3:>                                                          (0 + 1) / 1][1,0]<stderr>:2020-09-23 14:12:12.770484: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2020-09-23 14:12:12.782335: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ff6f6fe4d80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2020-09-23 14:12:12.782348: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,0]<stderr>:2020-09-23 14:12:12.958243: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 407, in infer_or_load_unischema
[1,0]<stderr>:    return get_schema(dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 361, in get_schema
[1,0]<stderr>:    'Could not find _common_metadata file. Use materialize_dataset(..) in'
[1,0]<stderr>:petastorm.etl.dataset_metadata.[1,0]<stderr>:PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,0]<stderr>:    "__main__", mod_spec)
[1,0]<stderr>:  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[1,0]<stderr>:    exec(code, run_globals)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,0]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,0]<stderr>:    result = fn(*args, **kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 208, in train
[1,0]<stderr>:    **reader_factory_kwargs) as train_reader:
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 300, in make_batch_reader
[1,0]<stderr>:    filters=filters)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/reader.py", line 380, in __init__
[1,0]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 411, in infer_or_load_unischema
[1,0]<stderr>:    return Unischema.from_arrow_schema(dataset)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/unischema.py", line 336, in from_arrow_schema
[1,0]<stderr>:    arrow_field = compat_schema_field(arrow_schema, column_name)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/site-packages/petastorm/compat.py", line 80, in compat_schema_field
[1,0]<stderr>:    return schema.field(name)
[1,0]<stderr>:AttributeError: [1,0]<stderr>:'pyarrow.lib.Schema' object has no attribute 'field'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------

**Comment by tgaddair** [comment]
Hey @WangHeguan, I noticed that you're using TensorFlow 2.  In the past, there were some compatibility issues with Petastorm and TF 2.  I'll try reproducing this locally and get back to you.  It may be we need to change some things to make the KerasEstimator work in TF 2 with Petastorm.
