### ISSUE TITLE
Horovod with oneCCL failed

### ISSUE THREAD

**Issue by zhao1157** [horovod/horovod#2321]
I rebuilt horovod inside a horovod docker container which was built using the latest `Dockerfile.gpu`. The instructions I followed are [here](https://github.com/horovod/horovod/blob/master/docs/oneccl.md). While building horovod, the following information may be helpful for debugging the failure at the end.

>-- Found MPI_C: /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/libmpifort.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- MPI include path: /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/include
-- MPI libraries: /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/libmpicxx.so/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/libmpifort.so/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release/libmpi.so/usr/lib/x86_64-linux-gnu/librt.so/usr/lib/x86_64-linux-gnu/libpthread.so/usr/lib/x86_64-linux-gnu/libdl.so

>-- Set default CPU operation to CCL
-- Found Tensorflow: -L/usr/local/lib/python3.7/dist-packages/tensorflow;-l:libtensorflow_framework.so.2 (found suitable version "2.3.0", minimum required is "1.15.0")
-- Gloo build as STATIC library
-- MPI include path: /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/include
-- MPI libraries: /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/libmpicxx.so/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/libmpifort.so/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release/libmpi.so/usr/lib/x86_64-linux-gnu/librt.so/usr/lib/x86_64-linux-gnu/libpthread.so/usr/lib/x86_64-linux-gnu/libdl.so

After installation, `horovodrun --check-build` showed
>Horovod v0.20.0:

Available Frameworks:
    [X] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [X] CCL
    [X] MPI
    [X] Gloo

But when running a tensorflow training script, I got the following messges
>Unknown MPI implementation given in output of mpirun --version:
Intel(R) MPI Library for Linux* OS, Version 2019 Update 8 Build 20200624 (id: 4f16ad915)
Copyright 2003-2020, Intel Corporation.

>Unknown MPI implementation given in output of mpirun --version:
Intel(R) MPI Library for Linux* OS, Version 2019 Update 8 Build 20200624 (id: 4f16ad915)
Copyright 2003-2020, Intel Corporation.

>Unknown MPI implementation given in output of mpirun --version:
Intel(R) MPI Library for Linux* OS, Version 2019 Update 8 Build 20200624 (id: 4f16ad915)
Copyright 2003-2020, Intel Corporation.

>Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 33, in <module>
    sys.exit(load_entry_point('horovod==0.20.0', 'console_scripts', 'horovodrun')())
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 723, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 713, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 571, in _run_static
    _launch_job(args, settings, nics, command)
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 686, in _launch_job
    args.verbose)
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 657, in run_controller
    mpi_run()
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/launch.py", line 678, in mpi_run_fn
    mpi_run(settings, nics, env, command)
  File "/usr/local/lib/python3.7/dist-packages/horovod-0.20.0-py3.7-linux-x86_64.egg/horovod/runner/mpi_run.py", line 143, in mpi_run
    raise Exception(_MPI_NOT_FOUND_ERROR_MSG)
Exception: horovod does not find an installed MPI.

>Choose one of:
>1. Install Open MPI 4.0.0+ or IBM Spectrum MPI or MPICH and re-install Horovod (use --no-cache-dir pip option).
>2. Run distributed training script using the standard way provided by your MPI distribution (usually mpirun, srun, or jsrun).
>3. Use built-in gloo option (horovodrun --gloo ...).

It looks like horovod could not find MPI, but during compiling it said MPI was found. Could you please guide me to fix this issue?

**Comment by tgaddair** [comment]
Hey @zhao1157, looks like your version of MPI is not one we officially support in `horovodrun` at the moment.  Are you able to run with `mpirun` as described [here](https://github.com/horovod/horovod/blob/master/docs/mpi.rst)?

**Comment by zhao1157** [comment]
@tgaddair `mpirun -np num_process python train.py` works, and the other flags does not work. What is the supported version of `oneCCL/intel MPI` with `horovodrun` when the installation guide was written?

**Comment by zhao1157** [comment]
@tgaddair Are there any other recommended MPI flags when using `oneCCL`?

**Comment by fschlimb** [comment]
I ran into similar issues. mpi_run.py does not support newer MPICH versions (e.g. 3.3.2) and it does not recognize Intel MPI. The latter would lead to the above message. The former complains about unsupported flags like '-x' and '--allow-run-as-root'.

**Comment by tgaddair** [comment]
@shirosankaku can you help out with this oneCCL issue?

**Comment by fschlimb** [comment]
I do not think this is a CCL issue. At least in my case mpi_run.py needs to be adjusted to support the MPI  in question.
At compile time a different mechanism is used to find MPI than at runtime.

**Comment by shirosankaku** [comment]
@tgaddair yes, we're working on it

**Comment by shailensobhee** [comment]
@tgaddair Do you have an update on the Pull Request #2433, related to this issue? 
Thanks!

**Comment by tgaddair** [comment]
Hey @shailensobhee, I went ahead and landed #2433 to unblock, let me know if it addresses the issue.

@shirosankaku, can you confirm that this issue is resolved by your PR?
