### ISSUE TITLE
Horovod throws UnicodeDecodeError when using tqdm

### ISSUE THREAD

**Issue by hhaoyan** [horovod/horovod#2367]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.2.0
3. Horovod version: 0.19.5
4. MPI version: None
5. CUDA version: 10.0
6. NCCL version: 2.7.8.1
7. Python version: 3.6.12
8. Spark / PySpark version: None
9. OS and version: Linux 4.14.105-1-tlinux3-0010
10. GCC version: 5.2.0
11. CMake version: 2.8.12.2

**What happened?**
When using `horovod` together with `tqdm`, `horovod` throws `UnicodeDecodeError` when `tqdm` is progressing the bar display:

```
Tue Oct 13 10:54:25 2020[0]<stderr>:[10/13/2020 10:54:25 - INFO - __main__ -   start running validation...
Tue Oct 13 10:54:25 2020[0]<stderr>:  0%|          | 0/1327 [00:00<?, ?it/s]
Tue Oct 13 10:55:56 2020[0]<stderr>:
Exception in thread Thread-17:derr>: 65%|██████▌   | 866/1327 [01:17<00:47,  9.80it/s]
Traceback (most recent call last):
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py", line 104, in forward_stream
    text = text.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 999: unexpected end of data

Tue Oct 13 10:58:56 2020[3]<stderr>:[2020-10-13 10:58:56.365049: E /dockerdata/app/tmp/pip-install-998q9kn4/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/dockerdata/app/tmp/pip-install-998q9kn4/horovod/third_party/compatible_gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 30000ms for recv operation to complete
Tue Oct 13 10:58:56 2020[2]<stderr>:[2020-10-13 10:58:56.366492: E /dockerdata/app/tmp/pip-install-998q9kn4/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/dockerdata/app/tmp/pip-install-998q9kn4/horovod/third_party/compatible_gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 30000ms for recv operation to complete
Tue Oct 13 10:58:56 2020[1]<stderr>:[2020-10-13 10:58:56.366674: E /dockerdata/app/tmp/pip-install-998q9kn4/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/dockerdata/app/tmp/pip-install-998q9kn4/horovod/third_party/compatible_gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 30000ms for send operation to complete
Tue Oct 13 10:58:56 2020[3]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:56 2020[1]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:56 2020[3]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 622, in synchronize
Tue Oct 13 10:58:56 2020[2]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:56 2020[3]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
Tue Oct 13 10:58:56 2020[2]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 622, in synchronize
Tue Oct 13 10:58:56 2020[3]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Tue Oct 13 10:58:56 2020[1]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 622, in synchronize
Tue Oct 13 10:58:56 2020[3]<stderr>:
Tue Oct 13 10:58:56 2020[1]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
Tue Oct 13 10:58:56 2020[2]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
Tue Oct 13 10:58:57 2020[3]<stderr>:During handling of the above exception, another exception occurred:
Tue Oct 13 10:58:57 2020[2]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Tue Oct 13 10:58:57 2020[1]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Tue Oct 13 10:58:57 2020[3]<stderr>:
Tue Oct 13 10:58:57 2020[1]<stderr>:
Tue Oct 13 10:58:57 2020[2]<stderr>:
Tue Oct 13 10:58:57 2020[3]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:57 2020[2]<stderr>:During handling of the above exception, another exception occurred:
Tue Oct 13 10:58:57 2020[1]<stderr>:During handling of the above exception, another exception occurred:
Tue Oct 13 10:58:57 2020[3]<stderr>:  File "train_vcr.py", line 332, in <module>
Tue Oct 13 10:58:57 2020[1]<stderr>:
Tue Oct 13 10:58:57 2020[3]<stderr>:    main(parse_cmd_args(TrainingOpts))
Tue Oct 13 10:58:57 2020[1]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:57 2020[3]<stderr>:  File "train_vcr.py", line 260, in main
Tue Oct 13 10:58:57 2020[1]<stderr>:  File "train_vcr.py", line 332, in <module>
Tue Oct 13 10:58:57 2020[3]<stderr>:    val_log = validate(model, val_dataloader)
Tue Oct 13 10:58:57 2020[1]<stderr>:    main(parse_cmd_args(TrainingOpts))
Tue Oct 13 10:58:57 2020[3]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
Tue Oct 13 10:58:57 2020[1]<stderr>:  File "train_vcr.py", line 260, in main
Tue Oct 13 10:58:57 2020[3]<stderr>:    return func(*args, **kwargs)
Tue Oct 13 10:58:57 2020[1]<stderr>:    val_log = validate(model, val_dataloader)
Tue Oct 13 10:58:58 2020[3]<stderr>:  File "train_vcr.py", line 310, in validate
Tue Oct 13 10:58:58 2020[1]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
Tue Oct 13 10:58:57 2020[2]<stderr>:
Tue Oct 13 10:58:58 2020[3]<stderr>:    qa_loss = sum(all_gather_list(qa_loss))
Tue Oct 13 10:58:58 2020[1]<stderr>:    return func(*args, **kwargs)
Tue Oct 13 10:58:58 2020[2]<stderr>:Traceback (most recent call last):
Tue Oct 13 10:58:58 2020[1]<stderr>:  File "train_vcr.py", line 310, in validate
Tue Oct 13 10:58:58 2020[2]<stderr>:  File "train_vcr.py", line 332, in <module>
Tue Oct 13 10:58:58 2020[3]<stderr>:  File "/data/cdp_algo_ceph_ssd/users/haoyanhuo/vcr/utils/distributed.py", line 233, in all_gather_list
Tue Oct 13 10:58:58 2020[2]<stderr>:    main(parse_cmd_args(TrainingOpts))
Tue Oct 13 10:58:58 2020[3]<stderr>:    max_size = hvd.allgather(torch.tensor([enc_size]).cuda()).max().item()
Tue Oct 13 10:58:58 2020[1]<stderr>:    qa_loss = sum(all_gather_list(qa_loss))
Tue Oct 13 10:58:58 2020[2]<stderr>:  File "train_vcr.py", line 260, in main
Tue Oct 13 10:58:58 2020[3]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 365, in allgather
Tue Oct 13 10:58:58 2020[2]<stderr>:    val_log = validate(model, val_dataloader)
Tue Oct 13 10:58:58 2020[3]<stderr>:    return HorovodAllgather.apply(tensor, name)
Tue Oct 13 10:58:58 2020[1]<stderr>:  File "/data/cdp_algo_ceph_ssd/users/haoyanhuo/vcr/utils/distributed.py", line 233, in all_gather_list
Tue Oct 13 10:58:58 2020[2]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
Tue Oct 13 10:58:58 2020[1]<stderr>:    max_size = hvd.allgather(torch.tensor([enc_size]).cuda()).max().item()
Tue Oct 13 10:58:58 2020[3]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 328, in forward
Tue Oct 13 10:58:59 2020[2]<stderr>:    return func(*args, **kwargs)
Tue Oct 13 10:58:59 2020[3]<stderr>:    return synchronize(handle)
Tue Oct 13 10:58:59 2020[2]<stderr>:  File "train_vcr.py", line 310, in validate
Tue Oct 13 10:58:59 2020[3]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 626, in synchronize
Tue Oct 13 10:58:59 2020[2]<stderr>:    qa_loss = sum(all_gather_list(qa_loss))
Tue Oct 13 10:58:59 2020[3]<stderr>:    raise HorovodInternalError(e)
Tue Oct 13 10:58:59 2020[2]<stderr>:  File "/data/cdp_algo_ceph_ssd/users/haoyanhuo/vcr/utils/distributed.py", line 233, in all_gather_list
Tue Oct 13 10:58:59 2020[3]<stderr>:horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was causedby an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finishedexecution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Tue Oct 13 10:58:59 2020[1]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 365, in allgather
Tue Oct 13 10:58:59 2020[2]<stderr>:    max_size = hvd.allgather(torch.tensor([enc_size]).cuda()).max().item()
Tue Oct 13 10:58:59 2020[2]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 365, in allgather
Tue Oct 13 10:58:59 2020[1]<stderr>:    return HorovodAllgather.apply(tensor, name)
Tue Oct 13 10:58:59 2020[1]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 328, in forward
Tue Oct 13 10:58:59 2020[2]<stderr>:    return HorovodAllgather.apply(tensor, name)
Tue Oct 13 10:58:59 2020[2]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 328, in forward
Tue Oct 13 10:58:59 2020[1]<stderr>:    return synchronize(handle)
Tue Oct 13 10:58:59 2020[1]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 626, in synchronize
Tue Oct 13 10:58:59 2020[2]<stderr>:    return synchronize(handle)
Tue Oct 13 10:58:59 2020[1]<stderr>:    raise HorovodInternalError(e)
Tue Oct 13 10:59:00 2020[2]<stderr>:  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 626, in synchronize
Tue Oct 13 10:59:00 2020[1]<stderr>:horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was causedby an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finishedexecution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Tue Oct 13 10:59:00 2020[2]<stderr>:    raise HorovodInternalError(e)
Tue Oct 13 10:59:00 2020[2]<stderr>:horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was causedby an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finishedexecution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
```

**Reasons for this issue**
This is due to a truncated (since `horovod` only captures 1000 bytes) UTF8 code. For example, the above error was due to a truncated black box character `0xe2 0x96 0x88` used by `tqdm` to indicate progress. The following is an example of the bytes produced by `tqdm`. Pay attention to bytes `0x00059960-0x00059970`:
```
...
00059930  30 5d 3c 73 74 64 65 72  72 3e 3a 0d 54 75 65 20  |0]<stderr>:.Tue |
00059940  4f 63 74 20 31 33 20 31  30 3a 35 35 3a 35 35 20  |Oct 13 10:55:55 |
00059950  32 30 32 30 5b 30 5d 3c  73 74 64 65 72 72 3e 3a  |2020[0]<stderr>:|
00059960  20 36 35 25 7c e2 96 88  e2 96 88 e2 96 88 e2 96  | 65%|...........|
00059970  88 e2 96 88 e2 96 88 e2  96 8d 20 20 20 7c 20 38  |..........   | 8|
00059980  35 38 2f 31 33 32 37 20  5b 30 31 3a 31 37 3c 30  |58/1327 [01:17<0|
00059990  30 3a 34 34 2c 20 31 30  2e 34 33 69 74 2f 73 5d  |0:44, 10.43it/s]|
000599a0  1b 5b 41 1b 5b 41 0a 54  75 65 20 4f 63 74 20 31  |.[A.[A.Tue Oct 1|
000599b0  33 20 31 30 3a 35 35 3a  35 35 20 32 30 32 30 5b  |3 10:55:55 2020[|
000599c0  30 5d 3c 73 74 64 65 72  72 3e 3a 0a 54 75 65 20  |0]<stderr>:.Tue |
...
```

I think `horovod` needs a better way of handling program outputs, either pipe them in binary or delay the decoding of partially captured UTF8 codes.

**Comment by LiuShixing** [comment]
how to solve this bug?

**Comment by hhaoyan** [comment]
> how to solve this bug?

A quick fix: `tqdm(ascii=True)` to eliminate UTF8 outputs.

The better way: Replace all `str`s in `forward_stream` with `bytes`.

**Comment by LiuShixing** [comment]
> > how to solve this bug?
> 
> A quick fix: `tqdm(ascii=True)` to eliminate UTF8 outputs.
> 
> The better way: Replace all `str`s in `forward_stream` with `bytes`.

thanks!

**Comment by tgaddair** [comment]
Thanks for raising this issue @hhaoyan.  Do you have a small repro script I can run to demonstrate the error?

**Comment by hhaoyan** [comment]
> Thanks for raising this issue @hhaoyan. Do you have a small repro script I can run to demonstrate the error?

Here is a simple script that reproduces this error:

```python
from horovod import torch as hvd
import time

hvd.init()
while True:
    print(b'\xe2\x96\x88'.decode('utf8')*334)
    time.sleep(1)
```

From terminal, run:

```bash
$ horovodrun -n 2 pythontest.py
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/run/common/util/safe_shell_exec.py", line 98, in forward_stream
    text = text.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 999: unexpected end of data
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/anaconda3/envs/vcr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/anaconda3/envs/vcr/lib/python3.6/site-packages/horovod/run/common/util/safe_shell_exec.py", line 98, in forward_stream
    text = text.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 999: unexpected end of data
```

**Comment by EnricoMi** [comment]
> how to solve this bug?

Alternative would be not to truncate on 1000 bytes but 1000 characters. Where is this 1000 truncation happening?

**Comment by hhaoyan** [comment]
> > how to solve this bug?
> 
> Alternative would be not to truncate on 1000 bytes but 1000 characters. Where is this 1000 truncation happening?

https://github.com/horovod/horovod/blob/master/horovod/runner/common/util/safe_shell_exec.py#L99

If subprocess throws some illegal UTF8 bytes, then I guess there is no way to truncate in characters?

I temporarily fixed it by using bytes IO for all pipes, stdout/stderr and it seems to be working for me.

**Comment by EnricoMi** [comment]
I think the simplest fix is to use `text.decode` with `errors = 'ignore'`, which makes it ignore incomplete / invalid UTF8 characters: https://docs.python.org/3.6/howto/unicode.html#the-string-type

https://github.com/horovod/horovod/blob/master/horovod/runner/common/util/safe_shell_exec.py#L104 would then read:

    text = text.decode('utf-8', errors='ignore')

**Comment by tgaddair** [comment]
Good suggestion, @EnricoMi.  Do you have the bandwidth to put together a PR?

**Comment by EnricoMi** [comment]
After looking at the `forward_stream` method a bit closer, using `errors='ignore'` is not the right thing to do here. We are not truncating the stream at 1000 bytes, but we are chunking it into 1000 bytes chunks to line buffer it. We would lose the character at the chunk boundary. I will rework the line buffering.

**Comment by EnricoMi** [comment]
@tgaddair: is it required for `forward_stream` to work with both, byte streams and text streams? Given we are calling this from `execute` on pipe connections, we can guarantee it is one of them. Would simplify things.

```
        if not isinstance(text, str):
            text = text.decode('utf-8')
```

https://github.com/horovod/horovod/blob/master/horovod/runner/common/util/safe_shell_exec.py#L103

**Comment by tgaddair** [comment]
@EnricoMi it may not be necessary to decode the stream data, I do not remember why we needed to do that originally, but we can always decode on the other end of the stream when necessary.

**Comment by EnricoMi** [comment]
Even better!

**Comment by EnricoMi** [comment]
Waiting for #2388 to land which simplifies unit test assertions without timestamps.

**Comment by hhaoyan** [comment]
> We have to encode it in `forward_stream` to be able to prepend timestamp, prefix and index to each line:
> 
> ```
> return '{time}[{rank}]<{prefix}>:{line}'.format(...)
> ```
> 
> I think this justifies expecting the stream to be a text stream.

Maybe the prefix strings can be formatted and encoded into UTF8, then we can simply join two byte strings?

**Comment by EnricoMi** [comment]
That is a good idea, that would then only require the source stream to be split on new lines, no matter if being a byte or text stream. If a byte stream, prepend each line as described by you, if a text stream, prepend with the prefix as a string. Will try that.

**Comment by EnricoMi** [comment]
Well, since we fall back to `sys.stdout` and `sys.stderr` when no `stdout` and `stderr` are given, respectively, `stdout` and `stderr`must be text streams only. So `forward_stream` will only be called with text streams and therefore `dst_stream` is also text stream. This simplifies code.

**Comment by EnricoMi** [comment]
PR #2398 ready for review.

**Comment by EnricoMi** [comment]
The correct and minimal fix is to use an incremental UTF8 decoder rather than decoding that byte chunk on its own:

    # the incremental encoder allows us to decode chunks of utf8 bytes
    # with utf8 characters spread across the boundary chunks
    decoder = codecs.getincrementaldecoder('utf8')()

and

    # turn the bytes into string decoding them as utf8
    # we need to use an incremental decoder as characters can span multiple bytes
    # where the last character might not be completely in buf
    # see https://github.com/horovod/horovod/issues/2367
    text = decoder.decode(buf or b'', final=not buf)

The incremental decoder has an internal state and keeps the non-decoded bytes at the end of the chunk for decoding the next chunk.
