### ISSUE TITLE
horovod on Spark crash using Gloo when executors more than 12

### ISSUE THREAD

**Issue by qs-zh** [horovod/horovod#2419]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.5.0
3. Horovod version: v0.20.3
4. MPI version: NA
5. CUDA version: NA
6. NCCL version: NA
7. Python version: 3.6
8. Spark / PySpark version: 2.4.6
9. OS and version: Ubuntu 16.04.6
10. GCC version: 5.4.0
11. CMake version: 3.17.1

**Bug report:**
Hi I'm doing model training on cpu machines using horovod on spark with Gloo.
horovod is installed using the following command:
```
HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1 pip install horovod
```
Model training is working fine when the number of executors are <=12. But when I increase the number of executors, I'll receive the following error:
at driver node:

```
Checking whether extension tensorflow was built with Gloo.
Extension tensorflow was built with Gloo.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/spark/runner.py", line 158, in run_spark
    result = procs.mapPartitionsWithIndex(mapper).collect()
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 0 cancelled part of cancelled job group horovod.spark.run.0
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1890)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1825)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:909)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:909)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:909)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:909)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2080)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2049)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:740)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2081)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2102)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2121)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2146)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


Traceback (most recent call last):
  ...
    use_gloo=True,
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/spark/runner.py", line 320, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/spark/runner.py", line 173, in _launch_job
    settings.verbose)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/runner/launch.py", line 637, in run_controller
    gloo_run()
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/spark/runner.py", line 170, in <lambda>
    run_controller(use_gloo, lambda: gloo_run(settings, nics, driver, env),
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/spark/gloo_run.py", line 63, in gloo_run
    launch_gloo(command, exec_command, settings, nics, {}, server_ip)
  File "/data2/yarn/nm/usercache/ld-dev/appcache/application_1603883037311_28420/container_e1322_1603883037311_28420_01_000008/Python/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 266, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 6
Exit code: 134
```

most executor nodes will have this error message: 
```
terminate called after throwing an instance of 'gloo::IoException'
  what():  [/tmp/pip-req-build-1nongu57/horovod/common/gloo/http_store.cc:53] [/tmp/pip-req-build-1nongu57/horovod/common/gloo/http_store.cc:53] Wait timeout for key(s): 18
Aborted
```
The key value `18` in the error log may change when running at a different time.

some executor node have this error message:
```
terminate called after throwing an instance of 'gloo::IoException'
  what():  [/tmp/pip-req-build-1nongu57/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:898] Connect timeout [15.137.78.220]:52676
Aborted
```

**Comment by tgaddair** [comment]
Hey @qs-zh, can you share how many executors and executor-cores you're using in your cluster config, as well as the `horovod.spark.run` command?  I'm wondering if this is a resourcing issue.

cc @EnricoMi

**Comment by qs-zh** [comment]
Hi @tgaddair , the executor-cores is 1. For the number of executors, when I'm using 15 or 20 or more, the above error will happen. When I'm using 5 or 10 or 12, there is lower chance for this error to happen. Previously I thought it will never happen when executors <= 12 until today I tried 8 executors also got this error. It seems the more executors, the higher chance for this error to happen.
My `horovod.spark.run` command is:
```
horovod.spark.run(
    fn, 
    num_proc=num_executors * executor_cores, 
    start_timeout=3600, 
    args=(main_py, applicationId,) + tuple([sys.argv[2] + extra_argv, sys.argv[3:]]),
    verbose=2,
    use_gloo=True,
)
```

**Comment by EnricoMi** [comment]
@tgaddair what is that exception in `horovod/common/gloo/http_store.cc:53` telling us? Is that a timeout in the rendezvous server, because some gloo worker cannot connect? Might this be there are insufficient threads or resources on the driver to support that number of workers?

@qs-zh might it be the case that some machines cannot connect to the driver machine at all? Do the worker-side exceptions always occur on the same machines? Can you provide some more relevant stack traces? How many machines are involved? What is your Spark cluster setup?

**Comment by qs-zh** [comment]
Hi @EnricoMi , thanks for the advice. My cluster has more than a hundred machines. Let me try running a few more times to verify whether it always occur on the same group of machines and double check on machine connectivity.
For stack traces, the logs in the first comment are all I have.

**Comment by qs-zh** [comment]
Hi @EnricoMi Apart from machine connection issue, is there any other possible reasons that could cause this error? 
Is it possible to get a more detailed log about this error?

**Comment by tgaddair** [comment]
Hey @qs-zh, my best guess at the moment is that the more workers you add, the longer it's taking for them all to schedule as a gang, leading to timeouts during the rendezvous.  The default timeout is 30 seconds, but this can be bumped up by setting the environment variable `HOROVOD_GLOO_TIMEOUT_SECONDS`.  Can you try setting this equal to something like 60 or even higher and see if it has an effect?

**Comment by EnricoMi** [comment]
@tgaddair his code uses `horovod.spark.run(start_timeout=3600, ...)` which refers to only the Spark timeout. If the issue he is seeing is really due to the Gloo timeout, then we should use the SPark timeout also for gloo when `use_gloo=True`.

**Comment by qs-zh** [comment]
Hi @tgaddair and @EnricoMi , after increasing environment variable `HOROVOD_GLOO_TIMEOUT_SECONDS`, the problem is solved. Thanks a lot for your help!
Yes, it would be great if `HOROVOD_GLOO_TIMEOUT_SECONDS` can be shown in the error log when timeout happens.

**Comment by EnricoMi** [comment]
Added the env variable name to the thrown exception in #2436.
