### ISSUE TITLE
multi server training not successful

### ISSUE THREAD

**Issue by wangxianliang** [horovod/horovod#2421]
**Environment:**
1. Framework: TensorFlow
2. Framework version:
2.3
3. Horovod version:
up-to-date
4. MPI version:
5. CUDA version:
10.1
6. NCCL version:
2.7.8
7. Python version:
3.8
8. OS and version:
ubuntu 18.04

Running `horovodrun -np 2 -H localhost:1,192.168.21.27:1`, but having the following error:

```
Launching horovod task function was not successful:
Traceback (most recent call last):
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/site-packages/horovod/runner/task_fn.py", line 66, in <module>
    _task_fn(index, num_hosts, driver_addresses, settings)
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/site-packages/horovod/runner/task_fn.py", line 37, in _task_fn
    next_task = task_service.HorovodRunTaskClient(
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/site-packages/horovod/runner/task/task_service.py", line 68, in __init__
    super(HorovodRunTaskClient, self).__init__(
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/site-packages/horovod/runner/common/service/task_service.py", line 246, in __init__
    super(BasicTaskClient, self).__init__(service_name,
  File "/home/local/anaconda3/envs/tf_gpu230/lib/python3.8/site-packages/horovod/runner/common/util/network.py", line 162, in __init__
    raise NoValidAddressesFound(
horovod.runner.common.util.network.NoValidAddressesFound: Horovod was unable to connect to horovod task service #1 on any of the following addresses: {'lo': [('127.0.0.1', 14902)], 'eno1': [('192.168.210.61', 14902)], 'eno2': [('192.168.21.27', 14902)]}.

One possible cause of this problem is that horovod currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
```

I have set ssh login with no password.

**Comment by tgaddair** [comment]
Hey @wangxianliang, can you run `ifconfig` on both hosts and share the results?

**Comment by wangxianliang** [comment]
```
localhost:
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 192.168.21.50  netmask 255.255.255.0  broadcast 192.168.21.255
        inet6 fe80::a8de:b2ff:fe92:5af0  prefixlen 64  scopeid 0x20<link>
        ether aa:de:b2:92:5a:f0  txqueuelen 1000  (Ethernet)
        RX packets 190717134793  bytes 213904895992773 (213.9 TB)
        RX errors 0  dropped 105317  overruns 0  frame 0
        TX packets 143649335635  bytes 191236388710331 (191.2 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp129s0f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.210.50  netmask 255.255.255.0  broadcast 192.168.210.255
        inet6 fe80::ae1f:6bff:fe98:6b61  prefixlen 64  scopeid 0x20<link>
        ether ac:1f:6b:98:6b:61  txqueuelen 1000  (Ethernet)
        RX packets 12990893  bytes 7945862549 (7.9 GB)
        RX errors 0  dropped 876863  overruns 0  frame 0
        TX packets 15338850  bytes 12641250065 (12.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfbe00000-fbe1ffff  

ens4f0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether aa:de:b2:92:5a:f0  txqueuelen 1000  (Ethernet)
        RX packets 18095590209  bytes 25131334052939 (25.1 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 71855960441  bytes 95665322802417 (95.6 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens4f1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether aa:de:b2:92:5a:f0  txqueuelen 1000  (Ethernet)
        RX packets 172621544584  bytes 188773561939834 (188.7 TB)
        RX errors 0  dropped 105317  overruns 0  frame 0
        TX packets 71793375194  bytes 95571065907914 (95.5 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 18952770805  bytes 1834357579390 (1.8 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18952770805  bytes 1834357579390 (1.8 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

192.168.21.27:
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.210.61  netmask 255.255.255.0  broadcast 192.168.210.255
        inet6 fe80::8ee3:2d79:509f:814f  prefixlen 64  scopeid 0x20<link>
        ether ac:1f:6b:a1:00:92  txqueuelen 1000  (Ethernet)
        RX packets 224887744  bytes 51569335071 (51.5 GB)
        RX errors 0  dropped 1305397  overruns 0  frame 0
        TX packets 443332609  bytes 498963632587 (498.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.21.27  netmask 255.255.255.0  broadcast 192.168.21.255
        inet6 fe80::58b2:2894:a8cf:3166  prefixlen 64  scopeid 0x20<link>
        ether ac:1f:6b:a1:00:93  txqueuelen 1000  (Ethernet)
        RX packets 2305185  bytes 423378859 (423.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 452083  bytes 45581162 (45.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4852439784  bytes 468541623106 (468.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4852439784  bytes 468541623106 (468.5 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by tgaddair** [comment]
Hey @wangxianliang, looks like the hosts have different network interface names.  You could try renaming them to match, or specify the interfaces you wish to use directly with (for example) `horovodrun --network-interface "eno1,enp129s0f1 ...`.

**Comment by wangxianliang** [comment]
> Hey @wangxianliang, looks like the hosts have different network interface names. You could try renaming them to match, or specify the interfaces you wish to use directly with (for example) `horovodrun --network-interface "eno1,enp129s0f1" ...`.

It works, thank you very much.

**Comment by tgaddair** [comment]
Awesome!  I'll go ahead and close this issue, then.
