### ISSUE TITLE
Horovod has been shut down?

### ISSUE THREAD

**Issue by harryxu-yscz** [horovod/horovod#243]
I am running tensorflow-gpu scripts on a k80 machine and the command I used was `mpirun -np 3 python run.py <flags>`; to specify which gpus to use, I set `os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2'`. 

Error logs:

```
Caused by op 'HorovodBroadcast_is_train_0', defined at:
  File "run.py", line 429, in <module>
    run()
  File "run.py", line 421, in run
    train(args)
  File "run.py", line 240, in train
    dropout_keep_prob=args.dropout_keep_prob)
  File "/models/multi_rc_model.py", line 596, in train
    bcast = hvd.broadcast_global_variables(0)

AbortedError (see above for traceback): Horovod has been shut down. This has been ca
used by an exception on one of the rank or an attempt to allreduce, allgather or bro
adcast a tensor after one of the ranks has finished execution.
```

Didn't see this when I ran on my 2*1080 gpus... not sure what went wrong. Please suggest. Thanks in advance!

**Comment by alsrgv** [comment]
@harryxu-yscz, are there any exceptions before this error?  What's the very first exception in the log?

**Comment by harryxu-yscz** [comment]
@alsrgv Thanks for the swift reply...

here are the full tracebacks:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Horovod has been shut down. This has been caused by an exception on one of the rank or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks has finished execution.
         [[Node: HorovodBroadcast_is_train_0 = HorovodBroadcast[T=DT_BOOL, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](is_train/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 429, in <module>
    run()
  File "run.py", line 421, in run
    train(args)
  File "run.py", line 240, in train
    dropout_keep_prob=args.dropout_keep_prob)
  File "/models/multi_rc_model.py", line 600, in train
    bcast.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2285, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4936, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Horovod has been shut down. This has been caused by an exception on one of the rank or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks has finished execution.
         [[Node: HorovodBroadcast_is_train_0 = HorovodBroadcast[T=DT_BOOL, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](is_train/read)]]

Caused by op 'HorovodBroadcast_is_train_0', defined at:
  File "run.py", line 429, in <module>
    run()
  File "run.py", line 421, in run
    train(args)
  File "run.py", line 240, in train
    dropout_keep_prob=args.dropout_keep_prob)
  File "/models/tensorflow/multi_rc_model.py", line 596, in train
    bcast = hvd.broadcast_global_variables(0)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 93, in broadcast_global_variables
    for var in tf.global_variables()])
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 93, in <listcomp>
    for var in tf.global_variables()])
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/mpi_ops.py", line 119, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 94, in horovod_broadcast
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

AbortedError (see above for traceback): Horovod has been shut down. This has been caused by an exception on one of the rank or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks has finished execution.
         [[Node: HorovodBroadcast_is_train_0 = HorovodBroadcast[T=DT_BOOL, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](is_train/read)]]
```
The code is run in a docker container built according to horovod `Dockerfile`

**Comment by alsrgv** [comment]
@harryxu-yscz, can you share the full log from `mpirun`?  `Horovod has been shut down.` should happen only after some failure already has happened.

**Comment by harryxu-yscz** [comment]
@alsrgv It turned out I did not expose 1 gpu in the environment variable... Sorry about my stupidity. Now the training seems fine except these `Read -1, expected xxx` statements: 

```
2018-04-14 00:47:41,650 - brc - INFO - Time to build graph: 4.352917432785034 s
2018-04-14 00:47:41,663 - brc - INFO - Time to build graph: 4.4049458503723145 s
2018-04-14 00:47:43,857 - brc - INFO - Training the model for epoch 1
2018-04-14 00:47:43,859 - brc - INFO - Training the model for epoch 1
[062fc37504b7:00351] Read -1, expected 268960, errno = 1
[062fc37504b7:00350] Read -1, expected 309760, errno = 1

062fc37504b7:350:457 [0] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
062fc37504b7:350:457 [0] INFO Using internal Network Socket
062fc37504b7:350:457 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
062fc37504b7:350:457 [0] INFO NET : Using interface eth0:172.17.0.3<0>
062fc37504b7:350:457 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.1.15+cuda9.0

062fc37504b7:351:461 [1] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
062fc37504b7:351:461 [1] INFO Using internal Network Socket
062fc37504b7:351:461 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
062fc37504b7:351:461 [1] INFO NET : Using interface eth0:172.17.0.3<0>
062fc37504b7:351:461 [1] INFO NET/Socket : 1 interfaces found
062fc37504b7:350:457 [0] INFO Using 512 threads
062fc37504b7:350:457 [0] INFO Min Comp Cap 3
062fc37504b7:350:457 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
062fc37504b7:350:457 [0] INFO Ring 00 :    0   1
062fc37504b7:351:461 [1] INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC
062fc37504b7:350:457 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
062fc37504b7:350:457 [0] INFO Launch mode Parallel
[062fc37504b7:00350] Read -1, expected 5209, errno = 1
[062fc37504b7:00351] Read -1, expected 26896000, errno = 1
[062fc37504b7:00350] Read -1, expected 30976000, errno = 1
[062fc37504b7:00351] Read -1, expected 259200, errno = 1
[062fc37504b7:00350] Read -1, expected 186880, errno = 1
[062fc37504b7:00351] Read -1, expected 25920000, errno = 1
[062fc37504b7:00350] Read -1, expected 18688000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 286880, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 28688000, errno = 1
[062fc37504b7:00351] Read -1, expected 225440, errno = 1
[062fc37504b7:00350] Read -1, expected 205440, errno = 1
[062fc37504b7:00351] Read -1, expected 22544000, errno = 1
[062fc37504b7:00350] Read -1, expected 20544000, errno = 1
[062fc37504b7:00351] Read -1, expected 267840, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 26784000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 84160, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 8416000, errno = 1
[062fc37504b7:00351] Read -1, expected 284160, errno = 1
[062fc37504b7:00350] Read -1, expected 225600, errno = 1
[062fc37504b7:00351] Read -1, expected 28416000, errno = 1
[062fc37504b7:00350] Read -1, expected 22560000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 284320, errno = 1
[062fc37504b7:00350] Read -1, expected 259680, errno = 1
[062fc37504b7:00351] Read -1, expected 28432000, errno = 1
[062fc37504b7:00350] Read -1, expected 25968000, errno = 1
[062fc37504b7:00351] Read -1, expected 279040, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 27904000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 320800, errno = 1
[062fc37504b7:00350] Read -1, expected 250080, errno = 1
[062fc37504b7:00351] Read -1, expected 32080000, errno = 1
[062fc37504b7:00350] Read -1, expected 25008000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 298720, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 29872000, errno = 1
[062fc37504b7:00351] Read -1, expected 321280, errno = 1
[062fc37504b7:00350] Read -1, expected 186240, errno = 1
[062fc37504b7:00351] Read -1, expected 32128000, errno = 1
[062fc37504b7:00350] Read -1, expected 18624000, errno = 1
[062fc37504b7:00351] Read -1, expected 216160, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 21616000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
[062fc37504b7:00351] Read -1, expected 253920, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 25392000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
[062fc37504b7:00351] Read -1, expected 250240, errno = 1
[062fc37504b7:00350] Read -1, expected 229120, errno = 1
[062fc37504b7:00351] Read -1, expected 25024000, errno = 1
[062fc37504b7:00350] Read -1, expected 22912000, errno = 1
[062fc37504b7:00351] Read -1, expected 295840, errno = 1
[062fc37504b7:00350] Read -1, expected 269600, errno = 1
[062fc37504b7:00351] Read -1, expected 29584000, errno = 1
[062fc37504b7:00350] Read -1, expected 26960000, errno = 1
[062fc37504b7:00351] Read -1, expected 237120, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 23712000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 282240, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 28224000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 285920, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 28592000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 284480, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 28448000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 295680, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 29568000, errno = 1
[062fc37504b7:00351] Read -1, expected 268800, errno = 1
[062fc37504b7:00350] Read -1, expected 311360, errno = 1
[062fc37504b7:00351] Read -1, expected 26880000, errno = 1
[062fc37504b7:00350] Read -1, expected 31136000, errno = 1
[062fc37504b7:00351] Read -1, expected 281920, errno = 1
[062fc37504b7:00350] Read -1, expected 104960, errno = 1
[062fc37504b7:00351] Read -1, expected 28192000, errno = 1
[062fc37504b7:00350] Read -1, expected 10496000, errno = 1
[062fc37504b7:00351] Read -1, expected 301440, errno = 1
[062fc37504b7:00350] Read -1, expected 272800, errno = 1
[062fc37504b7:00351] Read -1, expected 30144000, errno = 1
[062fc37504b7:00350] Read -1, expected 27280000, errno = 1
[062fc37504b7:00351] Read -1, expected 194080, errno = 1
[062fc37504b7:00350] Read -1, expected 238560, errno = 1
[062fc37504b7:00351] Read -1, expected 19408000, errno = 1
[062fc37504b7:00350] Read -1, expected 23856000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 277920, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 27792000, errno = 1
[062fc37504b7:00351] Read -1, expected 321280, errno = 1
[062fc37504b7:00350] Read -1, expected 237600, errno = 1
[062fc37504b7:00351] Read -1, expected 32128000, errno = 1
[062fc37504b7:00350] Read -1, expected 23760000, errno = 1
[062fc37504b7:00351] Read -1, expected 245920, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 24592000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 196160, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 19616000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 282080, errno = 1
[062fc37504b7:00350] Read -1, expected 137440, errno = 1
[062fc37504b7:00351] Read -1, expected 28208000, errno = 1
[062fc37504b7:00350] Read -1, expected 13744000, errno = 1
[062fc37504b7:00351] Read -1, expected 120000, errno = 1
[062fc37504b7:00350] Read -1, expected 279520, errno = 1
[062fc37504b7:00351] Read -1, expected 12000000, errno = 1
[062fc37504b7:00350] Read -1, expected 27952000, errno = 1
[062fc37504b7:00351] Read -1, expected 223840, errno = 1
[062fc37504b7:00350] Read -1, expected 271840, errno = 1
[062fc37504b7:00351] Read -1, expected 22384000, errno = 1
[062fc37504b7:00350] Read -1, expected 27184000, errno = 1
[062fc37504b7:00351] Read -1, expected 276960, errno = 1
[062fc37504b7:00350] Read -1, expected 213920, errno = 1
[062fc37504b7:00351] Read -1, expected 27696000, errno = 1
[062fc37504b7:00350] Read -1, expected 21392000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 192320, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 19232000, errno = 1
[062fc37504b7:00351] Read -1, expected 227520, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 22752000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
[062fc37504b7:00351] Read -1, expected 290560, errno = 1
[062fc37504b7:00350] Read -1, expected 246720, errno = 1
[062fc37504b7:00351] Read -1, expected 29056000, errno = 1
[062fc37504b7:00350] Read -1, expected 24672000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 261280, errno = 1
[062fc37504b7:00350] Read -1, expected 287680, errno = 1
[062fc37504b7:00351] Read -1, expected 26128000, errno = 1
[062fc37504b7:00350] Read -1, expected 28768000, errno = 1
[062fc37504b7:00351] Read -1, expected 284160, errno = 1
[062fc37504b7:00350] Read -1, expected 275680, errno = 1
[062fc37504b7:00351] Read -1, expected 28416000, errno = 1
[062fc37504b7:00350] Read -1, expected 27568000, errno = 1
[062fc37504b7:00351] Read -1, expected 134560, errno = 1
[062fc37504b7:00350] Read -1, expected 276960, errno = 1
[062fc37504b7:00351] Read -1, expected 13456000, errno = 1
[062fc37504b7:00350] Read -1, expected 27696000, errno = 1
[062fc37504b7:00351] Read -1, expected 269280, errno = 1
[062fc37504b7:00350] Read -1, expected 181280, errno = 1
[062fc37504b7:00351] Read -1, expected 26928000, errno = 1
[062fc37504b7:00350] Read -1, expected 18128000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 177440, errno = 1
^A[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 17744000, errno = 1
[062fc37504b7:00351] Read -1, expected 217440, errno = 1
[062fc37504b7:00350] Read -1, expected 279360, errno = 1
[062fc37504b7:00351] Read -1, expected 21744000, errno = 1
[062fc37504b7:00350] Read -1, expected 27936000, errno = 1
[062fc37504b7:00351] Read -1, expected 270560, errno = 1
[062fc37504b7:00350] Read -1, expected 261600, errno = 1
[062fc37504b7:00351] Read -1, expected 27056000, errno = 1
[062fc37504b7:00350] Read -1, expected 26160000, errno = 1
[062fc37504b7:00351] Read -1, expected 260960, errno = 1
[062fc37504b7:00350] Read -1, expected 278560, errno = 1
[062fc37504b7:00351] Read -1, expected 26096000, errno = 1
[062fc37504b7:00350] Read -1, expected 27856000, errno = 1
[062fc37504b7:00351] Read -1, expected 286720, errno = 1
[062fc37504b7:00350] Read -1, expected 280160, errno = 1
[062fc37504b7:00351] Read -1, expected 28672000, errno = 1
[062fc37504b7:00350] Read -1, expected 28016000, errno = 1
[062fc37504b7:00351] Read -1, expected 321280, errno = 1
[062fc37504b7:00350] Read -1, expected 320800, errno = 1
[062fc37504b7:00351] Read -1, expected 32128000, errno = 1
[062fc37504b7:00350] Read -1, expected 32080000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
2018-04-14 00:50:26,644 - brc - INFO - Average loss from batch 1 to 50 is 13.09790542602539
2018-04-14 00:50:26,647 - brc - INFO - Average loss from batch 1 to 50 is 13.05476495742798
[062fc37504b7:00351] Read -1, expected 280480, errno = 1
[062fc37504b7:00350] Read -1, expected 205600, errno = 1
[062fc37504b7:00351] Read -1, expected 28048000, errno = 1
[062fc37504b7:00350] Read -1, expected 20560000, errno = 1
[062fc37504b7:00351] Read -1, expected 273120, errno = 1
[062fc37504b7:00350] Read -1, expected 279840, errno = 1
[062fc37504b7:00351] Read -1, expected 27312000, errno = 1
[062fc37504b7:00350] Read -1, expected 27984000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 173280, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 17328000, errno = 1
[062fc37504b7:00351] Read -1, expected 253600, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 25360000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
[062fc37504b7:00351] Read -1, expected 321600, errno = 1
[062fc37504b7:00350] Read -1, expected 214880, errno = 1
[062fc37504b7:00351] Read -1, expected 32160000, errno = 1
[062fc37504b7:00350] Read -1, expected 21488000, errno = 1
[062fc37504b7:00351] Read -1, expected 271360, errno = 1
[062fc37504b7:00350] Read -1, expected 277280, errno = 1
[062fc37504b7:00351] Read -1, expected 27136000, errno = 1
[062fc37504b7:00350] Read -1, expected 27728000, errno = 1
[062fc37504b7:00351] Read -1, expected 313600, errno = 1
[062fc37504b7:00350] Read -1, expected 296960, errno = 1
[062fc37504b7:00351] Read -1, expected 31360000, errno = 1
[062fc37504b7:00350] Read -1, expected 29696000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 320800, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 32080000, errno = 1
[062fc37504b7:00351] Read -1, expected 282880, errno = 1
[062fc37504b7:00350] Read -1, expected 321280, errno = 1
[062fc37504b7:00351] Read -1, expected 28288000, errno = 1
[062fc37504b7:00350] Read -1, expected 32128000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 142880, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 14288000, errno = 1
[062fc37504b7:00351] Read -1, expected 272160, errno = 1
[062fc37504b7:00350] Read -1, expected 279520, errno = 1
[062fc37504b7:00351] Read -1, expected 27216000, errno = 1
[062fc37504b7:00350] Read -1, expected 27952000, errno = 1
[062fc37504b7:00351] Read -1, expected 239840, errno = 1
[062fc37504b7:00350] Read -1, expected 256800, errno = 1
[062fc37504b7:00351] Read -1, expected 23984000, errno = 1
[062fc37504b7:00350] Read -1, expected 25680000, errno = 1
[062fc37504b7:00351] Read -1, expected 311680, errno = 1
[062fc37504b7:00350] Read -1, expected 269280, errno = 1
[062fc37504b7:00351] Read -1, expected 31168000, errno = 1
[062fc37504b7:00350] Read -1, expected 26928000, errno = 1
[062fc37504b7:00351] Read -1, expected 284160, errno = 1
[062fc37504b7:00350] Read -1, expected 240160, errno = 1
[062fc37504b7:00351] Read -1, expected 28416000, errno = 1
[062fc37504b7:00350] Read -1, expected 24016000, errno = 1
[062fc37504b7:00351] Read -1, expected 276800, errno = 1
[062fc37504b7:00350] Read -1, expected 277600, errno = 1
[062fc37504b7:00351] Read -1, expected 27680000, errno = 1
[062fc37504b7:00350] Read -1, expected 27760000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 266720, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 26672000, errno = 1
[062fc37504b7:00351] Read -1, expected 251360, errno = 1
[062fc37504b7:00350] Read -1, expected 119840, errno = 1
[062fc37504b7:00351] Read -1, expected 25136000, errno = 1
[062fc37504b7:00350] Read -1, expected 11984000, errno = 1
[062fc37504b7:00351] Read -1, expected 282400, errno = 1
[062fc37504b7:00350] Read -1, expected 320960, errno = 1
[062fc37504b7:00351] Read -1, expected 28240000, errno = 1
[062fc37504b7:00350] Read -1, expected 32096000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 286080, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 28608000, errno = 1
[062fc37504b7:00351] Read -1, expected 321440, errno = 1
[062fc37504b7:00350] Read -1, expected 271680, errno = 1
[062fc37504b7:00351] Read -1, expected 32144000, errno = 1
[062fc37504b7:00350] Read -1, expected 27168000, errno = 1
[062fc37504b7:00351] Read -1, expected 215360, errno = 1
[062fc37504b7:00350] Read -1, expected 321760, errno = 1
[062fc37504b7:00351] Read -1, expected 21536000, errno = 1
[062fc37504b7:00350] Read -1, expected 32176000, errno = 1
[062fc37504b7:00351] Read -1, expected 217440, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 21744000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 250880, errno = 1
[062fc37504b7:00350] Read -1, expected 160800, errno = 1
[062fc37504b7:00351] Read -1, expected 25088000, errno = 1
[062fc37504b7:00350] Read -1, expected 16080000, errno = 1
[062fc37504b7:00351] Read -1, expected 321280, errno = 1
[062fc37504b7:00350] Read -1, expected 218240, errno = 1
[062fc37504b7:00351] Read -1, expected 32128000, errno = 1
[062fc37504b7:00350] Read -1, expected 21824000, errno = 1
[062fc37504b7:00351] Read -1, expected 285120, errno = 1
[062fc37504b7:00350] Read -1, expected 220640, errno = 1
[062fc37504b7:00351] Read -1, expected 28512000, errno = 1
[062fc37504b7:00350] Read -1, expected 22064000, errno = 1
[062fc37504b7:00351] Read -1, expected 320960, errno = 1
[062fc37504b7:00350] Read -1, expected 122080, errno = 1
[062fc37504b7:00351] Read -1, expected 32096000, errno = 1
[062fc37504b7:00350] Read -1, expected 12208000, errno = 1
[062fc37504b7:00351] Read -1, expected 321280, errno = 1
[062fc37504b7:00350] Read -1, expected 283520, errno = 1
[062fc37504b7:00351] Read -1, expected 32128000, errno = 1
[062fc37504b7:00350] Read -1, expected 28352000, errno = 1
[062fc37504b7:00351] Read -1, expected 321120, errno = 1
[062fc37504b7:00350] Read -1, expected 271520, errno = 1
[062fc37504b7:00351] Read -1, expected 32112000, errno = 1
[062fc37504b7:00350] Read -1, expected 27152000, errno = 1
[062fc37504b7:00351] Read -1, expected 321600, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
[062fc37504b7:00351] Read -1, expected 32160000, errno = 1
[062fc37504b7:00350] Read -1, expected 32112000, errno = 1
[062fc37504b7:00351] Read -1, expected 275680, errno = 1
[062fc37504b7:00350] Read -1, expected 321120, errno = 1
```
Did I do anything wrong here.?

**Comment by alsrgv** [comment]
Great that you figured it out.

Those `[062fc37504b7:00350] Read -1, expected 321120, errno = 1` messages are typical in Docker and are not harmful.  I haven't found a way to silence them yet.

**Comment by harryxu-yscz** [comment]
Thanks! all question answered

**Comment by harryxu-yscz** [comment]
@alsrgv things were fine when I use 2 processes but went wrong with 3+ processes. 

I observed that `[062fc37504b7:00350] Read -1, expected 205600, errno = 1` stop updating and the python process just hang there. GPU volatile util was fixed at 100% for all 3 gpus. I can still put the process to background/kill it with `ctrl + c`. Any idea what's happening here?

**Comment by alsrgv** [comment]
@harryxu-yscz, if you did not get it resolved, it would be helpful to do:
1) `nvidia-smi` 
2) determine PID of training process
3) `gdb -p $PID`
4) `thread apply all bt`
& paste the output via http://gist.github.com

**Comment by harryxu-yscz** [comment]
@alsrgv Thanks for the advice. Here's the output: https://gist.github.com/harryxu-yscz/1e91aa5be6263feb481fc894d626812c

**Comment by alsrgv** [comment]
@harryxu-yscz, NVIDIA just released NCCL 2.2.12.  And we now have official docker image on DockerHub - https://hub.docker.com/r/uber/horovod/tags/.  Could you try testing `uber/horovod:0.13.0-tf1.8.0-torch0.4.0-py2.7` or `uber/horovod:0.13.0-tf1.8.0-torch0.4.0-py3.5` ?

**Comment by abidmalikwaterloo** [comment]
Any update on this? I am having the same issue #492.

**Comment by BelhalK** [comment]
@harryxu-yscz  could you explain your bug fix "It turned out I did not expose 1 gpu in the environment variable" 
I happen to have the same issue and don't know how to fix it.

Thank you
