### ISSUE TITLE
Horovod.torch import breaks with Pytorch 1.4.0

### ISSUE THREAD

**Issue by rohit497** [horovod/horovod#2441]
**Environment:**
1. Framework: Pytorch
2. Framework version: 1.4
3. Horovod version: 0.19.1
4. MPI version: mpirun (Open MPI) 3.0.0
5. CUDA version: 10.2
6. NCCL version: 2.7.3-1+cuda10.1 amd64
7. Python version: 3.7.6
8. Spark / PySpark version: - 
9. OS and version: -
10. GCC version: -
11. CMake version: -

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
I'm trying to run `import horovod.torch` on Azure Databricks but I keep running into this error: `ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory`. I've also pasted the stack trace below 

`Traceback (most recent call last):
  File "run_gender_prediction_hvd.py", line 88, in <module>
    import horovod.torch as hvd
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-545eb769-39b0-4e67-8d4f-53c63d5fe184/lib/python3.7/site-packages/horovod/torch/__init__.py", line 44, in <module>
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-545eb769-39b0-4e67-8d4f-53c63d5fe184/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 31, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib`

It works fine with Pytorch 1.5.0 but my project has a specific Pytorch requirement of 1.4.0. Can someone help me with this?

**Comment by tgaddair** [comment]
Hey @rohit497, this error suggests that Horovod was installed with a different version of PyTorch from the one you're using at runtime.  Can you try reinstalling Horovod, making sure to set `--no-cache-dir`:

```
pip uninstall horovod
HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod
```

**Comment by rohit497** [comment]
@tgaddair When I try to run this, the command line asks for input from the user. Since I am running this on databricks, I can't provide input to the command line. Is there some other way to install this?

**Comment by tgaddair** [comment]
Try `pip uninstall -y horovod`.

**Comment by rohit497** [comment]
Awesome this works! But now I'm running into segmentation faults before I'm able to start running my training process. Is there a specific version of horovod that's compatible with pytorch 1.4.0?

**Comment by rohit497** [comment]
```
[0803-202239-rest96-10-139-64-4:17003] *** Process received signal ***
[0803-202239-rest96-10-139-64-4:17003] Signal: Segmentation fault (11)
[0803-202239-rest96-10-139-64-4:17003] Signal code: Invalid permissions (2)
[0803-202239-rest96-10-139-64-4:17003] Failing at address: 0x7f7b00005619
[0803-202239-rest96-10-139-64-4:17003] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7f7bc09ed8a0]
[0803-202239-rest96-10-139-64-4:17003] [ 1] [0x7f7b00005619]
[0803-202239-rest96-10-139-64-4:17003] *** End of error message ***
```
This is the exact error I'm getting @tgaddair

**Comment by tgaddair** [comment]
Seems related to https://github.com/open-mpi/ompi/issues/1916.  The suggestion there was to try reinstalling MPI.

I would also suggest trying to reinstall Horovod using Gloo instead of MPI, unless you need to use MPI for some reason:

```
HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1
```

This should simplify the dependencies you need to run Horovod.

**Comment by rohit497** [comment]
This worked thanks!

**Comment by raotnameh** [comment]
@tgaddair Using GLOO gives me this error:


[0]<stderr>:Segmentation fault (core dumped)
Process 0 exit with status code 139.
[1]<stderr>:Segmentation fault (core dumped)
Process 1 exit with status code 139.
Traceback (most recent call last):
  File "/home/hemant/.conda/envs/hor/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 728, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 704, in run_controller
    gloo_run()
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/launch.py", line 720, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/gloo_run.py", line 284, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/runner/gloo_run.py", line 268, in launch_gloo
    raise RuntimeError('Horovod detected that one or more processes exited with non-zero '
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 139

**Comment by SHITIANYU-hue** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/38762389/158916602-56bc6a54-6d29-4999-8567-9b57d9c02225.png">

@tgaddair
