### ISSUE TITLE
horovodrun starting is stuck with timeout

### ISSUE THREAD

**Issue by egorgam** [horovod/horovod#2476]
Hello! horovodrun starting was stuck with this stdout:

```
root@ubuntu:~/hrv# horovodrun --verbose -np 4 -H worker1:1 python train.py
Filtering local host names.
Remote host found: worker1
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovod server.
Launching horovod task function: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no worker1    /usr/bin/python3.6 -m horovod.runner.task_fn gASVAwAAAAAAAABLAC4= gASVAwAAAAAAAABLAS4= gASVeQAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTVBjhpRhjARldGgwlF2UjAw5NS4yMTcuMS4xNzKUTVBjhpRhjAZldGgwOjCUXZSMCjE3Mi4yOC4wLjKUTVBjhpRhjAdkb2NrZXIwlF2UjAoxNzIuMTcuMC4xlE1QY4aUYXUu gASVVAIAAAAAAACMI2hvcm92b2QucnVubmVyLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMCG51bV9wcm9jlEsEjAd2ZXJib3NllEsCjAhzc2hfcG9ydJROjBFzc2hfaWRlbnRpdHlfZmlsZZROjA5leHRyYV9tcGlfYXJnc5ROjAh0Y3BfZmxhZ5SJjAxiaW5kaW5nX2FyZ3OUTowDa2V5lEMgEyzYX+xLLi+5xDDEvrHbb0StHusljEKHXcInICoMwc6UjA1zdGFydF90aW1lb3V0lIwiaG9yb3ZvZC5ydW5uZXIuY29tbW9uLnV0aWwudGltZW91dJSMB1RpbWVvdXSUk5QpgZR9lCiMCF90aW1lb3V0lEsejAtfdGltZW91dF9hdJRHQdfvF7WRLsqMCF9tZXNzYWdllIyhVGltZWQgb3V0IHdhaXRpbmcgZm9yIHthY3Rpdml0eX0uIFBsZWFzZSBjaGVjayBjb25uZWN0aXZpdHkgYmV0d2VlbiBzZXJ2ZXJzLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIC0tc3RhcnQtdGltZW91dCBwYXJhbWV0ZXIgaWYgeW91IGhhdmUgdG9vIG1hbnkgc2VydmVycy6UdWKMD291dHB1dF9maWxlbmFtZZROjA1ydW5fZnVuY19tb2RllImMBG5pY3OUTowHZWxhc3RpY5SJjBxwcmVmaXhfb3V0cHV0X3dpdGhfdGltZXN0YW1wlImMBWhvc3RzlIwJd29ya2VyMToxlHViLg==
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.

Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 591, in _run_static
    remote_host_names, fn_cache)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/driver/driver_service.py", line 256, in get_common_interfaces
    nics = _driver_fn(all_host_names, local_host_names, settings, fn_cache=fn_cache)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/util/cache.py", line 119, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/driver/driver_service.py", line 191, in _driver_fn
    return _run_probe(driver, settings, num_hosts)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/driver/driver_service.py", line 126, in _run_probe
    driver.wait_for_initial_registration(settings.start_timeout)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/common/service/driver_service.py", line 166, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/common/util/timeout.py", line 37, in check_time_out_for
    self._timeout
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers. Timeout after 30 seconds.

Launching horovod task function was not successful:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/task_fn.py", line 66, in <module>
    _task_fn(index, num_hosts, driver_addresses, settings)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/task_fn.py", line 30, in _task_fn
    host_hash.host_hash())
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/common/service/driver_service.py", line 205, in register_task
    self._send(RegisterTaskRequest(index, task_addresses, host_hash))
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/common/util/network.py", line 265, in _send
    return self._send_one(addr, req)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/common/util/network.py", line 245, in _send_one
    sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007f91b2145700 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/driver/driver_service.py", line 86 in _exec_command
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/util/threads.py", line 58 in fn_execute
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007f91b33ad740 (most recent call first):
Aborted
```

I have no idea whai I do wrong... Maybe closed ports? but ssh connect is successful and I see in worker1 host remote command execution `/usr/bin/python3.6 -c from multiprocessing.semaphore_tracker import main;main(4)`

**Comment by egorgam** [comment]
So I solved it by --network-interface eth0 parameter
