### ISSUE TITLE
AttributeError: module 'horovod' has no attribute 'local_rank'

### ISSUE THREAD

**Issue by egorgam** [horovod/horovod#2488]
If I try to hvd.local_rank(), I got exception:
```
>>> str(hvd.local_rank())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'horovod' has no attribute 'local_rank'
```

Versions:
horovod==0.21.0
tensorflow==2.3.0

So I think, it may be a reason of mpirun exception:
```
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
```

**Comment by tgaddair** [comment]
Hey @egorgam, make sure you're importing a specific framework module from Horovod:

```
import horovod.tensorflow as hvd
hvd.init()
print(hvd.local_rank())
```
