### ISSUE TITLE
CMake error in conda env: CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by jtchilders** [horovod/horovod#2493]
**Environment:**
1. Framework: TensorFlow, PyTorch
2. Framework version: 2.3.0 and 1.7.0
3. Horovod version: 0.21.0
4. MPI version: 3.1
5. CUDA version: none
6. NCCL version: none
7. Python version: 3.7.9
8. Spark / PySpark version: none
9. OS and version: SUSE 15
10. GCC version: 8.3.0
11. CMake version: 3.18.2

I installed the latest Miniconda via the Shell script:
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

Then did
`conda install tensorflow=2.3.0 pytorch=1.7.0 -c pytorch`

Then I tried 
`pip install --no-cache-dir horovod[tensorflow,pytorch]`

It seems to find everything OK (see below) but the pytorch CMake seems to get confused about some library locations or environment variables.

```bash
 running build_ext
  -- Could not find CCache. Consider installing CCache to speed up compilation.
  -- The CXX compiler identification is GNU 8.3.0
  -- Cray Programming Environment 2.6.5 CXX
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/cray/pe/craype/2.6.5/bin/CC - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Build architecture flags: -mf16c -mavx -mfma
  -- Using command /lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/bin/python
  -- Found MPI_CXX: /opt/cray/pe/craype/2.6.5/bin/CC (found version "3.1")
  -- Found MPI: TRUE (found version "3.1")
  -- The C compiler identification is GNU 8.3.0
  -- Cray Programming Environment 2.6.5 C
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /opt/cray/pe/craype/2.6.5/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Found MPI_C: /opt/cray/pe/craype/2.6.5/bin/cc (found version "3.1")
  -- Found MPI: TRUE (found version "3.1")
  -- MPI include path:
  -- MPI libraries:
  -- Found Tensorflow: -L/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/site-packages/tensorflow;-l:libtensorflow_framework.so.2 (found suitable version "2.3.0", minimum required is "1.15.0")
  CMake Warning (dev) at horovod/tensorflow/CMakeLists.txt:43 (add_library):
    ADD_LIBRARY called with SHARED option but the target platform does not
    support dynamic linking.  Building a STATIC library instead.  This may lead
    to problems.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Found Pytorch: 1.7.0 (found suitable version "1.7.0", minimum required is "1.2.0")
  CMake Warning (dev) at horovod/torch/CMakeLists.txt:68 (add_library):
    ADD_LIBRARY called with SHARED option but the target platform does not
    support dynamic linking.  Building a STATIC library instead.  This may lead
    to problems.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")
  -- Cray Programming Environment 2.6.5 C
  -- MPI include path:
  -- MPI libraries:
  -- Configuring done
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  FOUND_LIB_c10
      linked by target "pytorch" in directory /tmp/pip-install-zzurxfof/horovod/horovod/torch
  FOUND_LIB_torch
      linked by target "pytorch" in directory /tmp/pip-install-zzurxfof/horovod/horovod/torch
  FOUND_LIB_torch_cpu
      linked by target "pytorch" in directory /tmp/pip-install-zzurxfof/horovod/horovod/torch
  FOUND_LIB_torch_python
      linked by target "pytorch" in directory /tmp/pip-install-zzurxfof/horovod/horovod/torch

  -- Generating done
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-zzurxfof/horovod/setup.py", line 193, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-zzurxfof/horovod/setup.py", line 89, in build_extensions
      cwd=self.build_temp)
    File "/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-zzurxfof/horovod', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-zzurxfof/horovod/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE:FILEPATH=/lus/theta-fs0/software/datascience/conda/miniconda3/2020-12/bin/python']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
```

**Comment by tgaddair** [comment]
@nvcastet @leezu are either of you familiar with this issue?

@davidrpugh could this be Conda related?

**Comment by leezu** [comment]
I'd recommend you to try without conda.
As a sidenote, you should never pip install horovod when you use conda. Horovod uses MPI and the Conda MPI is different to the OS provided MPI. This can lead to deadlocks.

**Comment by davidrpugh** [comment]
I will take a look and see. A couple of key points about using Conda to install Horovod which I hope are documented here (if not I need to make some minor updates anyway and will include them).

https://horovod.readthedocs.io/en/stable/conda.html

1. Always install pip I to your Conda environment otherwise your pip install command may use some other pip installed on your system and then install Horovod in some non obvious place or fail to install properly at all.

2. If you wish to use cmake, the. I would advise installing it into the Conda environment as well instead of using whatever version is available on your system.

3. In prefer to install MPI as well into my Conda environment instead of using system provided MPI (this is not strictly necessary).

4. You will need to use the Conda Forge channel and give it priority over the defaults channel in order to get the full compiler toolchains. See the linked docs above for details.

@leezu AFAIK it is only possible to install Horovod into a Conda environment using pip.

**Comment by jtchilders** [comment]
Thanks for the suggestions. I actually tried installing from source first via `python setup.py install`. I saw the same error in both cases. In the case of MPI, I always use my system MPI compilers `CC` and `cc` as I'm on a cray cluster and need these to get the proper network utilization. I was able to move back to the tag `v0.19.5` and build without problems. I didn't try `v.0.20.x`.

**Comment by nvcastet** [comment]
pip install of Horovod inside an activated conda environment should work.
@jtchilders Could you try `pip install --no-cache-dir horovod` instead of `pip install --no-cache-dir horovod[tensorflow,pytorch]`? (since tf and pytorch come form the conda packages you already installed)

**Comment by jtchilders** [comment]
While I haven't pursued this further with the `pip install ...` I have since been installing Horovod from source using `python setup.py ...` and this works fine.
