### ISSUE TITLE
Cannot aggregrate all the lists returned by allgather_object() for all the validation steps

### ISSUE THREAD

**Issue by SRITANU** [horovod/horovod#2519]
So, I have a databricks cluster with 1 driver and 3 workers with 4 GPUs each. I have successfully trained a torch binary classification model for a tabular dataset. Now, I have a validation set of ~91M records.

I need three things to gather from all the workers:

- Actual class (the y value)
- Predicted class
- Probability of both the classes

Now I can get all these from the workers using `hvd.allgather_object()`

Two functions I wrote for this task:

```
import horovod.torch as hvd
from sparkdl import HorovodRunner

def val_output(model, df_batch, device):
  model.eval()  
 
  cat_x = df_batch['categorical_vec'].to(device)
  num_x = df_batch['numeric_scaled'].to(device)
  y  = df_batch['target_label'].to(device)
  y = y.long()

  with torch.set_grad_enabled(False):
    outputs = model(num_x, cat_x)
    prob = F.softmax(outputs, dim=1)
    val, pred = torch.max(outputs, 1)

  all_workers_ac_metrics = hvd.allgather_object(y)
  all_workers_pr_metrics = hvd.allgather_object(pred)
  all_workers_prob_metrics = hvd.allgather_object(prob)
    
  return all_workers_ac_metrics, all_workers_pr_metrics, all_workers_prob_metrics
```

```
def val_hvd():
  hvd.init()

  if torch.cuda.is_available():
    torch.cuda.set_device(hvd.local_rank())
    device = torch.cuda.current_device()
  else:
    device = torch.device("cpu")
  
  model = Net(emb_dims, n_num_features=len(numeric_var))
  model.load_state_dict(torch.load(modelpath))
  model = model.to(device)
 
  hvd.broadcast_parameters(model.state_dict(), root_rank=0)

  res = {'actual':[], 'preds':[], 'probs':[]}
  ac = []
  pr = []
  probs = []

  with converter_val.make_torch_dataloader(cur_shard=hvd.rank(), shard_count=hvd.size(),
                                           batch_size=batch_size) as val_dataloader:
    
    val_dataloader_iter = iter(val_dataloader)
    validation_steps = max(1, len(converter_val) // (batch_size * hvd.size()))
    for step in range(validation_steps):
      df_batch = next(val_dataloader_iter)
      all_workers_ac_metrics, all_workers_pr_metrics, all_workers_prob_metrics = val_output(model, df_batch, device)

      probs.extend(all_workers_prob_metrics)
      ac.extend(all_workers_ac_metrics)
      pr.extend(all_workers_pr_metrics)
  
  res['actual'] = ac
  res['preds'] = pr
  res['probs'] = probs
  
  return res
```

```
hr = HorovodRunner(np=12)
res = hr.run(val_hvd)
```

With a batch size of 8192, there are 927 validation_steps. I get the following error when I run it for all the steps. 

If I hardcode it to something less than 927, say, 900 or 910 I don't get any such errors. For `n` steps I expect `actual` and `preds` keys of the `res` dictionary to have `12*n` torch tensors each having 8192 elements and `probs` key to have `12*n` torch tensors each having 8192 2-element tensors. 

Can someone please help me out where am I going wrong here?

The error trace:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-4207552088011261> in <module>
----> 1 res = hr.run(val_hvd)

/databricks/.python_edge_libs/sparkdl/utils/instrumentation.py in instrumented(func, self, args, kwargs)
     24                                          self.__class__.__name__))
     25     try:
---> 26         return_val = func(*args, **kwargs)
     27     except Exception:
     28         error_string = traceback.format_exc()

/databricks/.python_edge_libs/sparkdl/horovod/runner.py in run(self, main, **kwargs)
    243 
    244         try:
--> 245             return self._run_program(root_working_dir, pickled_func_str, log_streaming_server_port)
    246         finally:
    247             log_streaming_server.shutdown()

/databricks/.python_edge_libs/sparkdl/horovod/runner.py in _run_program(self, root_working_dir, pickled_func_str, log_streaming_server_port)
    584             partition_bytes = self.sc.parallelize(range(num_partitions), num_partitions) \
    585                 .barrier() \
--> 586                 .mapPartitions(run_horovod_task) \
    587                 .collect()
    588             result = HorovodRunner._parse_result_bytes(partition_bytes[0])

/databricks/spark/python/pyspark/rdd.py in collect(self)
    901         # Default path used in OSS Spark / for non-credential passthrough clusters:
    902         with SCCallSiteSync(self.context) as css:
--> 903             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    904         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    905 

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    125     def deco(*a, **kw):
    126         try:
--> 127             return f(*a, **kw)
    128         except py4j.protocol.Py4JJavaError as e:
    129             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(23, 0) finished unsuccessfully.
org.apache.spark.api.python.PythonException: 'struct.error: 'i' format requires -2147483648 <= number <= 2147483647'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 676, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 668, in process
    serializer.dump_stream(out_iter, outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 284, in dump_stream
    write_int(len(bytes), stream)
  File "/databricks/spark/python/pyspark/serializers.py", line 623, in write_int
    stream.write(struct.pack("!i", value))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:599)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:734)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:717)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:552)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2371)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$9(Executor.scala:642)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1581)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2519)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2466)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2460)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2460)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2232)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2718)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2668)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2656)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:938)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2331)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2352)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2371)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2396)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1011)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:395)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1010)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:260)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SRITANU** [comment]
If make the following modifications to the val_output(), I don't get any error:

```
def val_output(model, df_batch, device):
  model.eval()  
 
  cat_x = df_batch['categorical_vec'].to(device)
  num_x = df_batch['numeric_scaled'].to(device)
  y  = df_batch['target_label'].to(device)
  #y = y.long()

  with torch.set_grad_enabled(False):
    outputs = model(num_x, cat_x)
    prob = F.softmax(outputs, dim=1)
    val, pred = torch.max(outputs, 1)
    prob = prob.detach().cpu().numpy()
    y = y.detach().cpu().numpy()
    pred = pred.detach().cpu().numpy()


  all_workers_ac_metrics = hvd.allgather_object(y)
  all_workers_pr_metrics = hvd.allgather_object(pred)
  all_workers_prob_metrics = hvd.allgather_object(prob)
    
  return all_workers_ac_metrics, all_workers_pr_metrics, all_workers_prob_metrics
```

I commented out the line where y was converted to long since one of the error lines said `struct.error: 'i' format requires -2147483648 <= number <= 2147483647`. 

If having a long tensor was truly a problem, then why was it working for something less than 927 validation steps, say, 900 or 910? 

Any help would be appreciated.

**Comment by tgaddair** [comment]
Hey @SRITANU, my guess is that even though the tensor was of long type, the values in that tensor were still within that range (the int32 range).  Only once the values went outside that range after the 927th step is when the error was observed.  At least, that's my suspicion, would need to dig into it more to validate that.  But does the current solution you found unblock you?

**Comment by SRITANU** [comment]
Not really. The moment I increase the validation size dataset to say 200MM records, I get the same error even with my second solution. Not sure where am I going wrong? Any suggestions would be appreciated.

**Comment by SRITANU** [comment]
I'd definitely try this out. 

On another thoughy, I'm using a batch size of 8192 or 16384 while calling this function. 

1. Do you think if I use something way less, say 512 or something, would it work?

2. Also, I wonder why is it working for something less than the number of validation steps but not the exact number of validation steps?

**Comment by tgaddair** [comment]
1. If you're getting good throughput / model convergence with a larger batch size, it's likely a good idea to keep using it.
2. It may be that as you run more validation steps, you collect more metrics, until the total becomes too large.  I'm not sure of the specifics of the data, but something like that may be going on.
