### ISSUE TITLE
recipe for target 'horovod/torch/CMakeFiles/pytorch.dir/all' failed

### ISSUE THREAD

**Issue by datuizhuang** [horovod/horovod#2532]
**Environment:**
1. Framework: Pytorch
2. Framework version:1.6
3. Horovod version: i don't know, only use this : HOROVOD_GPU_ALLREDUCE=NCCL pip install horovod
4. MPI version:4.0.1
5. CUDA version:10.2
6. NCCL version:nccl-repo-ubuntu1604-2.8.3-ga-cuda10.2_1-1_amd64.deb
7. Python version:3.6
8. OS and version:Ubuntu16.04
9. GCC version:5.4.0

**Your question:**

hi，i meet some error when i install horovod, and i can't find solution. 

```
/tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = double; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = double]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = float; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = float]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = gloo::float16; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = gloo::float16]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = long int; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = long int]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = int; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = int]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = short int; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = short int]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = short unsigned int; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = short unsigned int]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = signed char; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = signed char]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h: In instantiation of ‘void gloo::sum(void*, const void*, const void*, size_t) [with T = unsigned char; size_t = long unsigned int]’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:70:68:   required from ‘void horovod::common::GlooAlgorithms<T>::Allreduce(void*, int) [with T = unsigned char]’
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/gloo_operations.cc:344:1:   required from here
  /tmp/pip-install-s2ban0ve/horovod/third_party/gloo/gloo/math.h:20:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/adasum_gpu_operations.cc: In member function ‘horovod::common::Status horovod::common::AdasumGpuAllreduceOp::NcclHierarchical(std::vector<horovod::common::TensorTableEntry>&, const horovod::common::Response&)’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/common/ops/adasum_gpu_operations.cc:151:11: warning: unused variable ‘total_num_elements’ [-Wunused-variable]
     int64_t total_num_elements =
             ^
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc: In function ‘void horovod::torch::DivideInPlace(at::Tensor&, int)’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:56:42: warning: ‘bool c10::isIntegralType(c10::ScalarType)’ is deprecated: isIntegralType is deprecated. Please use the overload with 'includeBool' parameter instead. [-Wdeprecated-declarations]
     if (isIntegralType(tensor.scalar_type())) {
                                            ^
  In file included from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/c10/core/Scalar.h:10:0,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:7,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                   from /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                   from /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:21:
  /home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/c10/core/ScalarType.h:234:20: note: declared here
   static inline bool isIntegralType(ScalarType t) {
                      ^
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc: In function ‘int horovod::torch::DoGroupedAllreduce(const std::vector<at::Tensor>&, const std::vector<at::Tensor>&, int, const string&, int, double, double)’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:158:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < num_tensors; ++i) {
                       ^
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc: In lambda function:
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:177:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (*callback_count == num_tensors) {
                               ^
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc: In function ‘int horovod::torch::DoGroupedAllreduceCudaOnCPU(const std::vector<at::Tensor>&, const std::vector<at::Tensor>&, int, const string&, int, double, double)’:
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:220:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < num_tensors; ++i) {
                       ^
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc: In lambda function:
  /tmp/pip-install-s2ban0ve/horovod/horovod/torch/mpi_ops_v2.cc:244:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (*callback_count == num_tensors) {
                               ^
  make[2]: Leaving directory '/tmp/pip-install-s2ban0ve/horovod/build/temp.linux-x86_64-3.6'
  CMakeFiles/Makefile2:485: recipe for target 'horovod/torch/CMakeFiles/pytorch.dir/all' failed
  make[1]: *** [horovod/torch/CMakeFiles/pytorch.dir/all] Error 2
  make[1]: Leaving directory '/tmp/pip-install-s2ban0ve/horovod/build/temp.linux-x86_64-3.6'
  Makefile:148: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-s2ban0ve/horovod/setup.py", line 193, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-s2ban0ve/horovod/setup.py", line 91, in build_extensions
      cwd=self.build_temp)
    File "/home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for horovod

```

i think the key error is:
```
 make[2]: Leaving directory '/tmp/pip-install-s2ban0ve/horovod/build/temp.linux-x86_64-3.6'
  CMakeFiles/Makefile2:485: recipe for target 'horovod/torch/CMakeFiles/pytorch.dir/all' failed
  make[1]: *** [horovod/torch/CMakeFiles/pytorch.dir/all] Error 2
```
but i don't know how to solve it.

**Comment by tgaddair** [comment]
Hey @datuizhuang, can you try running with `... MAKEFLAGS="-j1" pip install ...` and share the full output?  That should make it easier to see where the error is coming from.

**Comment by datuizhuang** [comment]
Hey, thanks for your reply, the total log is here, please help me to solve the problem, thanks~
[horovod.log](https://github.com/horovod/horovod/files/5718824/horovod.log)

**Comment by raotnameh** [comment]
@datuizhuang I am getting the same error. Did you find any solution?

**Comment by raotnameh** [comment]
@datuizhuang I Stubled upon the same error as you did. the error is 
```
home/yckj3857/anaconda3/envs/cztorch/lib/python3.6/site-packages/torch/include/THC/THCGeneral.h:11:23: fatal error: cublas_v2.h: No such file or directory
```
Can you please confirm if it is available. 
Run ``` find /usr/ -name cublas_v2.h ```

**Comment by tgaddair** [comment]
Hey @raotnameh, thanks for digging into this.  Yes, having multiple versions of CUDA can lead to these issues if different libraries / nvcc versions are found.
