### ISSUE TITLE
OSError: [Errno 7] Argument list too long: '/bin/sh'

### ISSUE THREAD

**Issue by Moymix** [horovod/horovod#2533]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.21.0
4. MPI version: 4.0.5
5. CUDA version:V10.1.243
6. NCCL version:nccl-repo-ubuntu1804-2.8.3-ga-cuda10.1
7. Python version:3.7.7
8. OS and version: Ubuntu 18.04.3 LTS
9. GCC version: 7.4.0

I installed horovod and simply run:
`horovodrun -np 1`

And I got the following error:

```
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/common/util/safe_shell_exec.py", line 160, in _exec_middleman
    stdout=stdout_w, stderr=stderr_w)
  File "/opt/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
Process 0 exit with status code 1.
Traceback (most recent call last):
  File "/opt/conda/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 731, in _launch_job
    args.verbose)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 704, in run_controller
    gloo_run()
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 720, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 284, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/opt/conda/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 271, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 1

```
It is strange since the command is not "long" and I am confused about the "Argument too long" error.

**Comment by tgaddair** [comment]
Hey @Moymix, my suspicion is that your environment contains a lot of long keys/values.  When we spawn subprocesses, we forward the parent environment, which may be resulting very long shell commands.  Can you try running `printenv` to check and maybe try creating a new shell with a reduced environment?

**Comment by serikkehva** [comment]
Hi,
I'm getting the same error.

<details>
  <summary>Error message</summary>
  
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/mnt/storage_2/scratch/grant_531/spack/opt/spack/linux-centos7-cascadelake/gcc-10.2.0/python-3.10.8-ybwn4bptjeu4dwlva5o5j6pozvpug2nb/lib/python3.10/multiprocessing/process.py", line 314, in _boo$
    self.run()
  File "/mnt/storage_2/scratch/grant_531/spack/opt/spack/linux-centos7-cascadelake/gcc-10.2.0/python-3.10.8-ybwn4bptjeu4dwlva5o5j6pozvpug2nb/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/storage_2/scratch/grant_531/spack/opt/spack/linux-centos7-cascadelake/gcc-10.2.0/py-horovod-0.26.1-oj42cnsyieuqhz362y7ssnusykoaf346/lib/python3.10/site-packages/horovod/runner/common/util/s$
    executor_shell = subprocess.Popen(command, shell=True, env=env,
  File "/mnt/storage_2/scratch/grant_531/spack/opt/spack/linux-centos7-cascadelake/gcc-10.2.0/python-3.10.8-ybwn4bptjeu4dwlva5o5j6pozvpug2nb/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/mnt/storage_2/scratch/grant_531/spack/opt/spack/linux-centos7-cascadelake/gcc-10.2.0/python-3.10.8-ybwn4bptjeu4dwlva5o5j6pozvpug2nb/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
  
</details>

Full error message : (at the end of this file)
[stderr.txt](https://github.com/horovod/horovod/files/11507041/stderr.txt)

Printenv results in really long environment due to using spack for installed libraries. Is there anything else I can do to prevent code from crashing, other than limiting my env?

**Comment by wwj-2017-1117** [comment]
**i meet the same propblem:**


Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/common/util/safe_shell_exec.py", line 159, in _exec_middleman
    executor_shell = subprocess.Popen(command, shell=True, env=env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
Process 0 exit with status code 1.
Terminating remaining workers after failure of Process 0.
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 824, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 814, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 672, in _run_static
    _launch_job(args, settings, nics, command)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 787, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 763, in run_controller
    gloo_run()
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 779, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/gloo_run.py", line 300, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/gloo_run.py", line 284, in launch_gloo
    raise RuntimeError('Horovod detected that one or more processes exited with non-zero '
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 1
