### ISSUE TITLE
Horovod-spark KerasEstimator.fit() fails 

### ISSUE THREAD

**Issue by ajesteves** [horovod/horovod#2544]
**Environment:**
1. Framework: (TensorFlow-GPU, Spark)
2. Framework version: TensorFlow-GPU 2.3, Spark 3.0
3. Horovod version: 0.21
4. MPI version: 4.1.0
5. CUDA version: 10.1
6. NCCL version: 2.8.3
7. Python version: 3.8
8. OS and version: Centos 7/8
9. GCC version: 7.3.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide] (https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**

I am trying to run MNIST distributed training on two nodes using Horovod+keras+spark.
The code i am testing is https://github.com/horovod/horovod/tree/master/examples/spark/keraskeras_spark_mnist.py.
After removing the GPU disabling lines (78-83), the execution with two nodes goes fine up to the fit step:

	keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])

The execution of the fit() method does not complete because always occur warnings/errors complaining about the impossibility of creating directories used during the training. 

It seems that given the argument "--work-dir /tmp/mnist" it is created the folder "intermediate_train_data.0" inside that path:

/tmp/mnist/intermediate_train_data.0

But no more folders are created, and the messages report longer paths, were the intermediate folders don't exist.
For example in the error message saying it was impossible to create the file:

/tmp/mnist/intermediate_train_data.0/_temporary/0/_temporary/attempt_20201221225441_0004_m_000000_7

There are no error message about creating the intermediate folders "_temporary/0/_temporary", 
which seems that have not been created by the fit() code.

I reproduce next part of the output showing the type of ERRORs that occur.

================================================================================
`...
train_data_path=file:///tmp/mnist/intermediate_train_data.0
val_data_path=file:///tmp/mnist/intermediate_val_data.0
...

WARN scheduler.TaskSetManager: Lost task 0.1 in stage 4.0 (TID 7, HOSTNAME1, executor 1): 
	java.io.IOException: Mkdirs failed to create 
	file:/tmp/mnist/intermediate_train_data.0/_temporary/0/_temporary/attempt_20201221225441_0004_m_000000_7 
	(exists=false, cwd=file:/tmp/hadoop-hadoop/nm-local-dir/usercache/USERLOGIN/appcache/application_1605812981073_0148/container_1605812981073_0148_01_000002)

	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:458)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:443)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74)
	at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:248)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:390)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:349)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:37)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:150)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:126)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:111)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:264)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$15(FileFormatWriter.scala:205)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`
...
`WARN scheduler.TaskSetManager: Lost task 1.0 in stage 4.0 (TID 6, HOSTNAME2, executor 2): 
	TaskKilled (Stage cancelled)

Traceback (most recent call last):

  File ".../keras_spark_mnist.py", line 145, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])
  File ".../horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File ".../spark/python/pyspark/ml/base.py", line 129, in fit
    return self._fit(dataset)
  File ".../horovod/spark/common/estimator.py", line 67, in _fit
    with util.prepare_data(backend.num_processes(),
  File ".../lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File ".../horovod/spark/common/util.py", line 667, in prepare_data
    dataset_idx = _get_or_create_dataset(key, store, df, feature_columns, label_columns,
  File ".../horovod/spark/common/util.py", line 586, in _get_or_create_dataset
    train_df \
  File ".../spark/python/pyspark/sql/readwriter.py", line 936, in parquet
    self._jwrite.parquet(path)
  File ".../py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File ".../spark/python/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File ".../py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
    	py4j.protocol.Py4JJavaError: An error occurred while calling o153.parquet.
			: org.apache.spark.SparkException: Job aborted.

	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:226)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:178)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:175)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:213)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:210)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:122)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:121)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:963)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:963)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:399)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:288)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:848)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

`Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: 
	Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 
	(TID 9, HOSNAME1, executor 1): java.io.IOException: Mkdirs failed to create 
	file:/tmp/mnist/intermediate_train_data.0/_temporary/0/_temporary/attempt_20201221225441_0004_m_000000_9 
	(exists=false, cwd=file:/tmp/hadoop-hadoop/nm-local-dir/usercache/USERLOGIN/appcache/application_1605812981073_0148/container_1605812981073_0148_01_000002)`
================================================================================

**Comment by tgaddair** [comment]
Hey @ajesteves, looks like it's attempting to write to HDFS when it should be writing to local.  Can you clarify, are you running with HDFS?

**Comment by ajesteves** [comment]
Hello Travis,
Yes i have the dataset on HDFS. I tried to place the temporary folder in HDFS and local filesystem, and the same erro occurs.
Antonio
