### ISSUE TITLE
Horovod on spark pytorch demo run failed.

### ISSUE THREAD

**Issue by maqy1995** [horovod/horovod#2585]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.7.1
3. Horovod version: 0.21.1
4. MPI version: 4.0.5
5. CUDA version: 10.2
6. NCCL version: 2.8.3
7. Python version: 3.7.6
8. OS and version: centOS7
9. GCC version: 7.3
10.  **Spark version: 3.0.0**

**Your question:**
I use the horovod on spark demo with pytorch, code from:
https://github.com/horovod/horovod/blob/master/examples/spark/pytorch/pytorch_spark_mnist.py

When I submit the job to spark standalone cluster, it failed with log:
```
21/01/09 14:28:42 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58746)
21/01/09 14:28:42 INFO PythonAccumulatorV2: Connected to AccumulatorServer at host: 127.0.0.1 port: 37426
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/root/miniconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/root/miniconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/miniconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/yexin/bigData/spark-3.0.0-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/accumulators.py", line 266, in handle
    poll(authenticate_and_accum_updates)
  File "/home/yexin/bigData/spark-3.0.0-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/accumulators.py", line 239, in poll
    r, _, _ = select.select([self.rfile], [], [], 1)
ValueError: filedescriptor out of range in select()
----------------------------------------
21/01/09 14:28:42 ERROR DAGScheduler: Failed to update accumulator 0 (org.apache.spark.api.python.PythonAccumulatorV2) for task 0
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at org.apache.spark.api.python.PythonAccumulatorV2.merge(PythonRDD.scala:720)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$updateAccumulators$1(DAGScheduler.scala:1296)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$updateAccumulators$1$adapted(DAGScheduler.scala:1287)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.updateAccumulators(DAGScheduler.scala:1287)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1399)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2200)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
21/01/09 14:28:42 INFO DAGScheduler: ResultStage 1 (runJob at PythonRDD.scala:154) finished in 3.190 s
21/01/09 14:28:42 INFO DAGScheduler: Job 1 is finished. Cancelling potential speculative or zombie tasks for this job
21/01/09 14:28:42 INFO TaskSchedulerImpl: Killing all running tasks in stage 1: Stage finished
21/01/09 14:28:42 INFO DAGScheduler: Job 1 finished: runJob at PythonRDD.scala:154, took 3.194227 s
train_partitions=30
21/01/09 14:28:42 INFO ParquetFileFormat: Using default output committer for Parquet: org.apache.parquet.hadoop.ParquetOutputCommitter
21/01/09 14:28:42 INFO FileOutputCommitter: File Output Committer Algorithm version is 2
21/01/09 14:28:42 INFO FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
21/01/09 14:28:42 INFO SQLHadoopMapReduceCommitProtocol: Using user defined output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
21/01/09 14:28:42 INFO FileOutputCommitter: File Output Committer Algorithm version is 2
21/01/09 14:28:42 INFO FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
21/01/09 14:28:42 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
21/01/09 14:28:42 INFO CodeGenerator: Code generated in 10.041798 ms
21/01/09 14:28:42 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
21/01/09 14:28:42 INFO DAGScheduler: Got job 2 (parquet at NativeMethodAccessorImpl.java:0) with 4 output partitions
21/01/09 14:28:42 INFO DAGScheduler: Final stage: ResultStage 2 (parquet at NativeMethodAccessorImpl.java:0)
21/01/09 14:28:42 INFO DAGScheduler: Parents of final stage: List()
21/01/09 14:28:42 INFO DAGScheduler: Missing parents: List()
21/01/09 14:28:42 INFO DAGScheduler: Submitting ResultStage 2 (CoalescedRDD[19] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
21/01/09 14:28:42 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 221.3 KiB, free 21.2 GiB)
21/01/09 14:28:42 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 81.5 KiB, free 21.2 GiB)
21/01/09 14:28:42 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on hikBigDataTestGpu1:43705 (size: 81.5 KiB, free: 21.2 GiB)
21/01/09 14:28:42 INFO SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:1200
21/01/09 14:28:42 INFO DAGScheduler: Submitting 4 missing tasks from ResultStage 2 (CoalescedRDD[19] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0, 1, 2, 3))
21/01/09 14:28:42 INFO TaskSchedulerImpl: Adding task set 2.0 with 4 tasks
21/01/09 14:28:42 INFO TaskSetManager: Starting task 0.0 in stage 2.0 (TID 5, 10.3.68.118, executor 3, partition 0, ANY, 7988 bytes)
21/01/09 14:28:42 INFO TaskSetManager: Starting task 1.0 in stage 2.0 (TID 6, 10.3.68.118, executor 2, partition 1, ANY, 7988 bytes)
21/01/09 14:28:42 INFO TaskSetManager: Starting task 2.0 in stage 2.0 (TID 7, 10.3.68.117, executor 17, partition 2, ANY, 7988 bytes)
21/01/09 14:28:42 INFO TaskSetManager: Starting task 3.0 in stage 2.0 (TID 8, 10.3.68.117, executor 13, partition 3, ANY, 7988 bytes)
21/01/09 14:28:42 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.3.68.117:39911 (size: 81.5 KiB, free: 21.2 GiB)
21/01/09 14:28:42 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.3.68.118:38140 (size: 81.5 KiB, free: 21.2 GiB)
21/01/09 14:28:42 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.3.68.117:46522 (size: 81.5 KiB, free: 21.2 GiB)
21/01/09 14:28:42 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.3.68.118:42085 (size: 81.5 KiB, free: 21.2 GiB)
21/01/09 14:28:44 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.3.68.117:46522 (size: 29.1 KiB, free: 21.2 GiB)
21/01/09 14:28:45 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.3.68.118:42085 (size: 29.1 KiB, free: 21.2 GiB)
21/01/09 14:28:45 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.3.68.118:38140 (size: 29.1 KiB, free: 21.2 GiB)
21/01/09 14:28:48 INFO TaskSetManager: Finished task 3.0 in stage 2.0 (TID 8) in 6043 ms on 10.3.68.117 (executor 13) (1/4)
21/01/09 14:28:48 ERROR DAGScheduler: Failed to update accumulator 0 (org.apache.spark.api.python.PythonAccumulatorV2) for task 3
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at org.apache.spark.api.python.PythonAccumulatorV2.merge(PythonRDD.scala:720)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$updateAccumulators$1(DAGScheduler.scala:1296)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$updateAccumulators$1$adapted(DAGScheduler.scala:1287)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.updateAccumulators(DAGScheduler.scala:1287)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1399)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2200)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
21/01/09 14:28:50 INFO TaskSetManager: Finished task 2.0 in stage 2.0 (TID 7) in 7884 ms on 10.3.68.117 (executor 17) (2/4)
21/01/09 14:28:50 ERROR DAGScheduler: Failed to update accumulator 0 (org.apache.spark.api.python.PythonAccumulatorV2) for task 2
java.net.SocketException: Broken pipe (Write failed)

```

I submit the job by:
```
spark-submit \
--master spark://10.3.68.116:7077 \
--driver-memory 40g \
--executor-memory 40g \
--num-executors 3 \
--executor-cores 1 \
--conf spark.task.cpus=1 \
--conf spark.task.resource.gpu.amount=1 \
--conf spark.executor.resource.gpu.amount=1 \
--conf spark.task.resource.gpu.amount=1 \
--conf spark.executor.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh \
/home/maqy/horovod/horovod-spark/horovod_spark_mnist.py --num-proc 3 --data-dir hdfs:///home/maqy/horovod --work-dir hdfs:///home/maqy/horovod/tmp
```

Any idea to fix it?

**Comment by maqy1995** [comment]
update `pyspark` from `3.0.0` to `3.0.1` fix the issue.
