### ISSUE TITLE
Question about meaning of an error message when calling `fit` on `TorchEstimator`

### ISSUE THREAD

**Issue by qixuanf** [horovod/horovod#2597]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.20.0
4. MPI version: 4.0.2 (Open MPI)
5. CUDA version: Not applicable, not GPU is used.
6. NCCL version: Not applicable, not GPU is used.
7. Python version: 3.7
8. OS and version: CentOS Linux 7 (Core), rhel fedora
9. GCC version: no gcc is installed

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?  Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**

I have a PyTorch model that I would like to fit on a spark dataframe using `horovod.spark.torch.TorchEstimator`. I made sure the model training works when I manually convert the dataframe to torch tensor and then run the usual training loop. However, I got the following error when I call `horovod.spark.torch.TorchEstimator.fit`.  It would be great if you could tell me what this error means. And in general, what are the best practices to debug distributed model training `TorchEstimator`? Is there a way to run my program sequentially without multiprocessing just to debug the program?

Additionally, I also made sure that the `TorchEstimator` works for training a standard MLP model on MNIST dataset. So it shouldn't be the problem of the environment or package installation. 

Here is the snippet (not runnable, but to illustrate how I use the API):
```Python
torch_estimator = horovod.spark.torch.TorchEstimator(num_proc=num_proc,  # Number of Horovod processes.
                                             store=store,
                                             model=self.nn_model,
                                             optimizer=self.optimizer,
                                             loss=lambda pred, target: self.loss(pred, target),
                                             input_shapes=input_shapes,
                                             feature_cols=[train_dataset.features_col],
                                             label_cols=[train_dataset.label_col],
                                             batch_size=self.batch_size,
                                             epochs=epochs,
                                             verbose=2)

self.nn_model = torch_estimator.fit(train_dataset.df)
```

Here is the error message:
```Python
_check_url: hdfs://
num process:  1
num_partitions=10
writing dataframes
train_data_path=hdfs:///tmp/qfeng/intermediate_train_data.0
val_data_path=hdfs:///tmp/qfeng/intermediate_val_data.0
train_partitions=10
train_rows=24128947
mpirun --allow-run-as-root --tag-output -np 1 -H bigdata-gt4cpi4uqh-98e58676fb8587e2-exec-77126-3cf32b4a74659cb2cce57d70fc2d74b0:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include lo,eth0 -x NCCL_SOCKET_IFNAME=lo,eth0  -x BASE_TAG -x BASH_ENV -x CLASSPATH -x CLICOLOR -x CONTAINER_CPU_LIMIT -x CONTAINER_CPU_REQUEST -x CONTAINER_MEMORY_LIMIT -x CONTAINER_MEMORY_REQUEST -x CRC32C_SW_MODE -x CWD -x DATACENTER -x DEFAULT_HADOOP_CLUSTER -x DEFAULT_HADOOP_CLUSTER_NAME_SERVICE -x FLOW_BASE_URL -x GIT_PAGER -x HADOOP_CLASSPATH -x HADOOP_CONF_DIR -x HADOOP_HOME -x HIVE_CONF_DIR -x HOME -x HOSTNAME -x IMAGE_DISABLE_DOTFILES -x JAVA_HOME -x JPY_PARENT_PID -x JUPYTER_BASE_URL -x JUPYTER_NOTEBOOK_TOKEN -x JUPYTER_PATH -x KERBEROS_KEYTAB -x KERBEROS_PRINCIPAL -x KMP_DUPLICATE_LIB_OK -x KMP_INIT_AT_FORK -x KUBERNETES_CLUSTER -x KUBERNETES_PORT -x KUBERNETES_PORT_443_TCP -x KUBERNETES_PORT_443_TCP_ADDR -x KUBERNETES_PORT_443_TCP_PORT -x KUBERNETES_PORT_443_TCP_PROTO -x KUBERNETES_SERVICE_HOST -x KUBERNETES_SERVICE_PORT -x KUBERNETES_SERVICE_PORT_HTTPS -x LANG -x LC_ALL -x MPLBACKEND -x PAGER -x PATH -x PWD -x PYSPARK_DRIVER_PYTHON -x PYSPARK_PYTHON -x PYSPARK_REQUIREMENTS -x PYSPARK_REQUIREMENTS_CM_NAME -x PYSPARK_SUBMIT_ARGS -x PYTHONPATH -x PYTHONSTARTUP -x RS_CLIENT_TARGET_HOST -x RS_CLIENT_TARGET_PROTOCOL -x SERVICE_DIRECTORY_INSTALLATION -x SERVICE_DIRECTORY_PERSONA -x SERVICE_DIRECTORY_PROJECT -x SERVICE_DIRECTORY_ROLLOUT -x SERVICE_DIRECTORY_SERVICE -x SHLVL -x SPARKSHELL -x SPARK_APPLICATION -x SPARK_COMPONENT -x SPARK_DRIVER_CORES -x SPARK_DRIVER_LIMIT_MEMORY -x SPARK_DRIVER_MEMORY -x SPARK_EXECUTOR_CORES -x SPARK_EXECUTOR_INSTANCES -x SPARK_EXECUTOR_MEMORY -x SPARK_EXECUTOR_MEMORY_OVERHEAD -x SPARK_HOME -x TERM -x TZ -x _  -x NCCL_DEBUG=INFO -mca plm_rsh_agent "/opt/miniconda/bin/python3 -m horovod.spark.driver.mpirun_rsh gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTa9YhpRhjARldGgwlF2UjA4xMC4yMzkuMTM5LjExMpRNr1iGlGF1Lg== gASVvQIAAAAAAACMI2hvcm92b2QucnVubmVyLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMCG51bV9wcm9jlEsBjAd2ZXJib3NllEsCjAhzc2hfcG9ydJROjBFzc2hfaWRlbnRpdHlfZmlsZZROjA5leHRyYV9tcGlfYXJnc5ROjAh0Y3BfZmxhZ5ROjAxiaW5kaW5nX2FyZ3OUTowDa2V5lE6MDXN0YXJ0X3RpbWVvdXSUjCJob3Jvdm9kLnJ1bm5lci5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HYABfA6hmgjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowPb3V0cHV0X2ZpbGVuYW1llE6MDXJ1bl9mdW5jX21vZGWUiIwEbmljc5ROjAdlbGFzdGljlImMBWhvc3RzlIxRYmlnZGF0YS1ndDRjcGk0dXFoLTk4ZTU4Njc2ZmI4NTg3ZTItZXhlYy03NzEyNi0zY2YzMmI0YTc0NjU5Y2IyY2NlNTdkNzBmYzJkNzRiMDoxlHViLg==" /opt/miniconda/bin/python3 -m horovod.spark.task.mpirun_exec_fn gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTa9YhpRhjARldGgwlF2UjA4xMC4yMzkuMTM5LjExMpRNr1iGlGF1Lg== gASVRgcAAAAAAACMI2hvcm92b2QucnVubmVyLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMCG51bV9wcm9jlEsBjAd2ZXJib3NllEsCjAhzc2hfcG9ydJROjBFzc2hfaWRlbnRpdHlfZmlsZZROjA5leHRyYV9tcGlfYXJnc5RYhAQAACAteCBOQ0NMX0RFQlVHPUlORk8gLW1jYSBwbG1fcnNoX2FnZW50ICIvb3B0L21pbmljb25kYS9iaW4vcHl0aG9uMyAtbSBob3Jvdm9kLnNwYXJrLmRyaXZlci5tcGlydW5fcnNoIGdBU1ZQZ0FBQUFBQUFBQjlsQ2lNQW14dmxGMlVqQWt4TWpjdU1DNHdMakdVVGE5WWhwUmhqQVJsZEdnd2xGMlVqQTR4TUM0eU16a3VNVE01TGpFeE1wUk5yMWlHbEdGMUxnPT0gZ0FTVnZRSUFBQUFBQUFDTUkyaHZjbTkyYjJRdWNuVnVibVZ5TG1OdmJXMXZiaTUxZEdsc0xuTmxkSFJwYm1kemxJd0lVMlYwZEdsdVozT1VrNVFwZ1pSOWxDaU1DRzUxYlY5d2NtOWpsRXNCakFkMlpYSmliM05sbEVzQ2pBaHpjMmhmY0c5eWRKUk9qQkZ6YzJoZmFXUmxiblJwZEhsZlptbHNaWlJPakE1bGVIUnlZVjl0Y0dsZllYSm5jNVJPakFoMFkzQmZabXhoWjVST2pBeGlhVzVrYVc1blgyRnlaM09VVG93RGEyVjVsRTZNRFhOMFlYSjBYM1JwYldWdmRYU1VqQ0pvYjNKdmRtOWtMbkoxYm01bGNpNWpiMjF0YjI0dWRYUnBiQzUwYVcxbGIzVjBsSXdIVkdsdFpXOTFkSlNUbENtQmxIMlVLSXdMWDNScGJXVnZkWFJmWVhTVVIwSFlBQmZBNmhtZ2pBaGZiV1Z6YzJGblpaUllEZ0VBQUZScGJXVmtJRzkxZENCM1lXbDBhVzVuSUdadmNpQjdZV04wYVhacGRIbDlMaUJRYkdWaGMyVWdZMmhsWTJzZ2RHaGhkQ0I1YjNVZ2FHRjJaU0JsYm05MVoyZ2djbVZ6YjNWeVkyVnpJSFJ2SUhKMWJpQmhiR3dnU0c5eWIzWnZaQ0J3Y205alpYTnpaWE11SUVWaFkyZ2dTRzl5YjNadlpDQndjbTlqWlhOeklISjFibk1nYVc0Z1lTQlRjR0Z5YXlCMFlYTnJMaUJaYjNVZ2JXRjVJRzVsWldRZ2RHOGdhVzVqY21WaGMyVWdkR2hsSUhOMFlYSjBYM1JwYldWdmRYUWdjR0Z5WVcxbGRHVnlJSFJ2SUdFZ2JHRnlaMlZ5SUhaaGJIVmxJR2xtSUhsdmRYSWdVM0JoY21zZ2NtVnpiM1Z5WTJWeklHRnlaU0JoYkd4dlkyRjBaV1FnYjI0dFpHVnRZVzVrTHBSMVlvd1BiM1YwY0hWMFgyWnBiR1Z1WVcxbGxFNk1EWEoxYmw5bWRXNWpYMjF2WkdXVWlJd0VibWxqYzVST2pBZGxiR0Z6ZEdsamxJbU1CV2h2YzNSemxJeFJZbWxuWkdGMFlTMW5kRFJqY0drMGRYRm9MVGs0WlRVNE5qYzJabUk0TlRnM1pUSXRaWGhsWXkwM056RXlOaTB6WTJZek1tSTBZVGMwTmpVNVkySXlZMk5sTlRka056Qm1ZekprTnpSaU1Eb3hsSFZpTGc9PSKUjAh0Y3BfZmxhZ5ROjAxiaW5kaW5nX2FyZ3OUTowDa2V5lE6MDXN0YXJ0X3RpbWVvdXSUjCJob3Jvdm9kLnJ1bm5lci5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HYABfA6hmgjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowPb3V0cHV0X2ZpbGVuYW1llE6MDXJ1bl9mdW5jX21vZGWUiIwEbmljc5ROjAdlbGFzdGljlImMBWhvc3RzlIxRYmlnZGF0YS1ndDRjcGk0dXFoLTk4ZTU4Njc2ZmI4NTg3ZTItZXhlYy03NzEyNi0zY2YzMmI0YTc0NjU5Y2IyY2NlNTdkNzBmYzJkNzRiMDoxlHViLg==
[1,0]<stdout>:Changing cwd from /opt/spark/work-dir to /opt/spark/work-dir
----------------------------------------
Exception happened during processing of request from ('10.239.157.182', 54210)
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/miniconda/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/miniconda/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/opt/miniconda/lib/python3.7/site-packages/horovod/runner/common/util/network.py", line 110, in handle
    server._wire.write(resp, self.wfile)
  File "/opt/miniconda/lib/python3.7/site-packages/horovod/runner/common/util/network.py", line 69, in write
    message = cloudpickle.dumps(obj)
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 687, in _save_reduce_pickle5
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/opt/miniconda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 687, in _save_reduce_pickle5
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/miniconda/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/miniconda/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/miniconda/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "/opt/miniconda/lib/python3.7/multiprocessing/queues.py", line 58, in __getstate__
    context.assert_spawning(self)
  File "/opt/miniconda/lib/python3.7/multiprocessing/context.py", line 356, in assert_spawning
    ' through inheritance' % type(obj).__name__
RuntimeError: Queue objects should only be shared between processes through inheritance

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-ee6377f76cc7> in <module>
      3 attr_model.dropout = 0.0
      4 attr_model.type_rnn = 'lstm'
----> 5 attr_model.fit_cpu(train_dataset=datasets['train'], epochs=2, work_dir='hdfs:///tmp/qfeng')
      6 print(f"Fitting using horovod used {time() - start_time} seconds")
      7 

~/shared/attr_rnn/models/incremental_attribution_model.py in fit_cpu(self, train_dataset, epochs, work_dir)
    200                                              verbose=2)
    201 
--> 202         self.nn_model = torch_estimator.fit(train_dataset.df)
    203         if self.checkpoint_path:
    204             self.save({

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/common/estimator.py in fit(self, df, params)
     33             `HorovodModel` transformer wrapping the trained model.
     34         """
---> 35         return super(HorovodEstimator, self).fit(df, params)
     36 
     37     def fit_on_parquet(self, params=None):

/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py in fit(self, dataset, params)
    127                 return self.copy(params)._fit(dataset)
    128             else:
--> 129                 return self._fit(dataset)
    130         else:
    131             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/common/estimator.py in _fit(self, df)
     78             self._check_metadata_compatibility(metadata)
     79             return self._fit_on_prepared_data(
---> 80                 backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
     81 
     82     def _get_or_create_backend(self):

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/torch/estimator.py in _fit_on_prepared_data(self, backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
    260                              args=(serialized_model, optimizer_cls, model_opt_state_serialized,
    261                                    train_rows, val_rows, avg_row_size),
--> 262                              env={})
    263         return self._create_model(handle, run_id, metadata)
    264 

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/common/backend.py in run(self, fn, args, kwargs, env)
     83         return horovod.spark.run(fn, args=args, kwargs=kwargs,
     84                                  num_proc=self._num_proc, env=full_env,
---> 85                                  **self._kwargs)
     86 
     87     def num_processes(self):

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/runner.py in run(fn, args, kwargs, num_proc, start_timeout, use_mpi, use_gloo, extra_mpi_args, env, stdout, stderr, verbose, nics)
    279 
    280         # Run the job
--> 281         _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
    282     except:
    283         # Terminate Spark job.

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/runner.py in _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
    153                    use_mpi, lambda: mpi_run(settings, nics, driver, env, stdout, stderr),
    154                    False, lambda: None,
--> 155                    settings.verbose)
    156 
    157 

/opt/miniconda/lib/python3.7/site-packages/horovod/runner/launch.py in run_controller(use_gloo, gloo_run, use_mpi, mpi_run, use_jsrun, js_run, verbosity)
    700                 js_run()
    701             else:
--> 702                 mpi_run()
    703         elif gloo_built(verbose=verbose):
    704             gloo_run()

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/runner.py in <lambda>()
    151     nics = driver.get_common_interfaces()
    152     run_controller(use_gloo, lambda: gloo_run(settings, nics, driver, env),
--> 153                    use_mpi, lambda: mpi_run(settings, nics, driver, env, stdout, stderr),
    154                    False, lambda: None,
    155                    settings.verbose)

/opt/miniconda/lib/python3.7/site-packages/horovod/spark/mpi_run.py in mpi_run(settings, nics, driver, env, stdout, stderr)
     53                codec.dumps_base64(driver.addresses()),
     54                codec.dumps_base64(settings))
---> 55     hr_mpi_run(settings, nics, env, command, stdout=stdout, stderr=stderr)

/opt/miniconda/lib/python3.7/site-packages/horovod/runner/mpi_run.py in mpi_run(settings, nics, env, command, stdout, stderr)
    217         exit_code = safe_shell_exec.execute(mpirun_command, env=env, stdout=stdout, stderr=stderr)
    218         if exit_code != 0:
--> 219             raise RuntimeError("mpirun failed with exit code {exit_code}".format(exit_code=exit_code))
    220     else:
    221         os.execve('/bin/sh', ['/bin/sh', '-c', mpirun_command], env)

RuntimeError: mpirun failed with exit code 1

```

**Comment by tgaddair** [comment]
Hey @qixuanf, it looks like something in your model may not be serializable.  Is there a `multiprocessing.queue` somewhere in your environment?

You can try running in a more controlled setting using `horovod.spark.run` to test that individual parts serialize correctly.  

Feel free to share a repro and we can take a look.
