### ISSUE TITLE
Cannot run horovod docker build

### ISSUE THREAD

**Issue by mouri11** [horovod/horovod#2619]
**Environment:**
1. Framework: Keras
2. Framework version: 2.4.3
3. Horovod version: latest
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.7.5
8. OS and version: Ubuntu 20.04 x86_64
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? NA
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
Please ask your question here.
I am trying to run the horovod docker using the instructions from the above docker link. I used the following instructions:
```
$ mkdir horovod-docker-cpu
$ wget -O horovod-docker-cpu/Dockerfile https://raw.githubusercontent.com/horovod/horovod/master/Dockerfile.cpu
$ docker build -t horovod:latest horovod-docker-cpu
$ nvidia-docker run -it horovod:latest
root@fa843efafc70:/examples# horovodrun -np 4 -H localhost:4 python keras/keras_mnist_advanced.py
```

I ran into the following error:
```
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "keras/keras_mnist_advanced.py", line 28, in <module>
[1,2]<stderr>:    config = tf.ConfigProto()
[1,2]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "keras/keras_mnist_advanced.py", line 28, in <module>
[1,0]<stderr>:    config = tf.ConfigProto()
[1,0]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "keras/keras_mnist_advanced.py", line 28, in <module>
[1,3]<stderr>:    config = tf.ConfigProto()
[1,3]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "keras/keras_mnist_advanced.py", line 28, in <module>
[1,1]<stderr>:    config = tf.ConfigProto()
[1,1]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[49344,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
I then did ```pip install tensorflow```, and got this error:
```
2021-01-23 13:17:54.201401: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-01-23 13:17:54.201449: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[1,1]<stderr>:2021-01-23 13:17:56.552912: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib
[1,1]<stderr>:2021-01-23 13:17:56.553077: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[1,2]<stderr>:2021-01-23 13:17:56.559468: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib
[1,2]<stderr>:2021-01-23 13:17:56.559602: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[1,0]<stderr>:2021-01-23 13:17:56.560247: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib
[1,0]<stderr>:2021-01-23 13:17:56.560633: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[1,3]<stderr>:2021-01-23 13:17:56.595286: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib
[1,3]<stderr>:2021-01-23 13:17:56.603610: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,2]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 42, in _load_library
[1,2]<stderr>:    library = load_library.load_op_library(filename)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
[1,2]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,2]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
[1,2]<stderr>:
[1,2]<stderr>:The above exception was the direct cause of the following exception:
[1,2]<stderr>:
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "keras_mnist_advanced.py", line 11, in <module>
[1,2]<stderr>:    import horovod.keras as hvd
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/keras/__init__.py", line 19, in <module>
[1,2]<stderr>:    from horovod.tensorflow import init
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/__init__.py", line 26, in <module>
[1,2]<stderr>:    from horovod.tensorflow import elastic
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/elastic.py", line 24, in <module>
[1,2]<stderr>:    from horovod.tensorflow.functions import broadcast_object, broadcast_object_fn, broadcast_variables
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/functions.py", line 24, in <module>
[1,2]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
[1,2]<stderr>:    check_installed_version('tensorflow', tf.__version__, e)
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/common/util.py", line 268, in check_installed_version
[1,2]<stderr>:    raise HorovodVersionMismatchError(name, version, installed_version) from exception
[1,2]<stderr>:horovod.common.exceptions.HorovodVersionMismatchError: Framework tensorflow installed with version 2.3.0 but found version 2.4.1.
[1,2]<stderr>:             This can result in unexpected behavior including runtime errors.
[1,2]<stderr>:             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,0]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 42, in _load_library
[1,0]<stderr>:    library = load_library.load_op_library(filename)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
[1,0]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
[1,0]<stderr>:
[1,0]<stderr>:The above exception was the direct cause of the following exception:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "keras_mnist_advanced.py", line 11, in <module>
[1,0]<stderr>:    import horovod.keras as hvd
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/keras/__init__.py", line 19, in <module>
[1,0]<stderr>:    from horovod.tensorflow import init
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/__init__.py", line 26, in <module>
[1,0]<stderr>:    from horovod.tensorflow import elastic
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/elastic.py", line 24, in <module>
[1,0]<stderr>:    from horovod.tensorflow.functions import broadcast_object, broadcast_object_fn, broadcast_variables
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/functions.py", line 24, in <module>
[1,0]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
[1,0]<stderr>:    check_installed_version('tensorflow', tf.__version__, e)
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/common/util.py", line 268, in check_installed_version
[1,0]<stderr>:    raise HorovodVersionMismatchError(name, version, installed_version) from exception
[1,0]<stderr>:horovod.common.exceptions.HorovodVersionMismatchError: Framework tensorflow installed with version 2.3.0 but found version 2.4.1.
[1,0]<stderr>:             This can result in unexpected behavior including runtime errors.
[1,0]<stderr>:             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,1]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 42, in _load_library
[1,1]<stderr>:    library = load_library.load_op_library(filename)
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
[1,1]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
[1,1]<stderr>:
[1,1]<stderr>:The above exception was the direct cause of the following exception:
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "keras_mnist_advanced.py", line 11, in <module>
[1,1]<stderr>:    import horovod.keras as hvd
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/keras/__init__.py", line 19, in <module>
[1,1]<stderr>:    from horovod.tensorflow import init
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/__init__.py", line 26, in <module>
[1,1]<stderr>:    from horovod.tensorflow import elastic
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/elastic.py", line 24, in <module>
[1,1]<stderr>:    from horovod.tensorflow.functions import broadcast_object, broadcast_object_fn, broadcast_variables
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/functions.py", line 24, in <module>
[1,1]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
[1,1]<stderr>:    check_installed_version('tensorflow', tf.__version__, e)
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/common/util.py", line 268, in check_installed_version
[1,1]<stderr>:    raise HorovodVersionMismatchError(name, version, installed_version) from exception
[1,1]<stderr>:horovod.common.exceptions.HorovodVersionMismatchError: Framework tensorflow installed with version 2.3.0 but found version 2.4.1.
[1,1]<stderr>:             This can result in unexpected behavior including runtime errors.
[1,1]<stderr>:             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 47, in <module>
[1,3]<stderr>:    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 42, in _load_library
[1,3]<stderr>:    library = load_library.load_op_library(filename)
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
[1,3]<stderr>:    lib_handle = py_tf.TF_LoadLibrary(library_filename)
[1,3]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
[1,3]<stderr>:
[1,3]<stderr>:The above exception was the direct cause of the following exception:
[1,3]<stderr>:
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "keras_mnist_advanced.py", line 11, in <module>
[1,3]<stderr>:    import horovod.keras as hvd
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/keras/__init__.py", line 19, in <module>
[1,3]<stderr>:    from horovod.tensorflow import init
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/__init__.py", line 26, in <module>
[1,3]<stderr>:    from horovod.tensorflow import elastic
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/elastic.py", line 24, in <module>
[1,3]<stderr>:    from horovod.tensorflow.functions import broadcast_object, broadcast_object_fn, broadcast_variables
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/functions.py", line 24, in <module>
[1,3]<stderr>:    from horovod.tensorflow.mpi_ops import allgather, broadcast
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
[1,3]<stderr>:    check_installed_version('tensorflow', tf.__version__, e)
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/common/util.py", line 268, in check_installed_version
[1,3]<stderr>:    raise HorovodVersionMismatchError(name, version, installed_version) from exception
[1,3]<stderr>:horovod.common.exceptions.HorovodVersionMismatchError: Framework tensorflow installed with version 2.3.0 but found version 2.4.1.
[1,3]<stderr>:             This can result in unexpected behavior including runtime errors.
[1,3]<stderr>:             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[49259,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```
Please help. Thanks.

**Comment by chongxiaoc** [comment]
```
[1,3]<stderr>:horovod.common.exceptions.HorovodVersionMismatchError: Framework tensorflow installed with version 2.3.0 but found version 2.4.1.
[1,3]<stderr>:             This can result in unexpected behavior including runtime errors.
[1,3]<stderr>:             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.
```

You have to reinstall horovod since dynamic link to tensorflow is changed.

See the missed symbol error:

```
[1,3]<stderr>:tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/dist-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

```

**Comment by mouri11** [comment]
It seems that tf.ConfigProto is not available in tf 2.0. Probably needs some correction in keras_mnist_advanced.py?

**Comment by EnricoMi** [comment]
Looks like `Dockerfile.cpu` installs Tensorflow 2.3.0 where `examples/keras/keras_mnist_advanced.py` is Tensorflow 1.x. You can find Tensorflow 2.x examples in `examples/tensorflow2`, maybe `examples/tensorflow2/tensorflow2_keras_mnist.py` is what you are looking for.

**Comment by mouri11** [comment]
Hi. Thanks for the solution. It seems to be running now. Also, is nvidia-docker only needed if I have GPUs? Like, can I run the horovod images properly using only docker?

**Comment by EnricoMi** [comment]
There are cpu docker images, those run nicely with only docker.

**Comment by mouri11** [comment]
Ok. The thing is, everytime I try to run nvidia-docker, I get this:
```
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
```

**Comment by mouri11** [comment]
I am also not able to figure out the ssh part. Could you link a relevant article here? I created a cluster of two AWS nodes, and put the ```id_rsa.pub``` of each node in the ```~/.ssh/authorized_keys``` file of both. I am not able to figure out the ```/mnt/share``` or the ```/root/.ssh/ssh_config``` part. Thanks.

**Comment by mouri11** [comment]
> I am also not able to figure out the ssh part. Could you link a relevant article here? I created a cluster of two AWS nodes, and put the `id_rsa.pub` of each node in the `~/.ssh/authorized_keys` file of both. I am not able to figure out the `/mnt/share` or the `/root/.ssh/ssh_config` part. Thanks.

Nvm. Got it to run on the cluster. Got this though:
```
[1,0]<stderr>:2021-01-27 13:31:48.169531: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,0]<stderr>:2021-01-27 13:31:48.173542: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[1,2]<stderr>:2021-01-27 13:31:50.652959: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of free system memory.
[1,1]<stderr>:2021-01-27 13:31:50.653055: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of free system memory.
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node ip-172-31-72-130 exited on signal 9 (Killed).
--------------------------------------------------------------------------
```

I will try to run the CPU-specific image sent here, and see if I get this as well.

**Comment by tgaddair** [comment]
@mouri11, how much system memory are you allocating to your containers?  Sounds like they may need more RAM.

**Comment by mouri11** [comment]
The containers have a minimum 4GB RAM allotted. Does it need more, or can any of the thresholds be increased?

**Comment by tgaddair** [comment]
It's not clear from the error message, but something is sending a hard kill signal to your mpirun process (kill -9).

**Comment by mouri11** [comment]
Ok. Any logs that can be collected to determine what's causing this issue?

**Comment by tgaddair** [comment]
@mouri11  are you able to increase the RAM available to the containers?  That would be a good place to start.  You may be able to find logs indicating the cause in `/var/logs`, but it is not guaranteed.

**Comment by mouri11** [comment]
Hi. It seems I had to reduce the -np arg since I only have 2 cores for my container. I will try it in a distributed cluster and update.
