### ISSUE TITLE
distribution training with horovod ,Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution

### ISSUE THREAD

**Issue by Rishav09** [horovod/horovod#2691]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.1
3. Horovod version: 0.19.0
4. MPI version: 10.3.0.01rc04
5. CUDA version:  10.1.105
6. NCCL version: 2.5.6
7. Python version: 3.7.9
8. OS and version: Red Hat Enterprise Linux Server" VERSION="7.6 (Maipo)"
9. GCC version: 4.8.5 20150623 (Red Hat 4.8.5-36)

Hi, I am encountering the above warning when I am trying to run my script using horovod. I come across this issue [previously posted](https://github.com/horovod/horovod/issues/1421l).
I am not able to get much information from it but there is a brief mention of `synchronize` with optimiser in it and I want to press more about it to figure out whether I have a problem with it or not -
In my code, below is how I am currently loading the optimizer  and the criterion-

        optimizer = torch.optim.SGD(model_transfer.parameters(), lr=learning_rate*lr_scaler)
        hvd.broadcast_parameters(model_transfer.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer, root_rank=0)
        optimizer = hvd.DistributedOptimizer(
                optimizer,
                named_parameters=model_transfer.named_parameters(),
                op=hvd.Adasum if use_adasum else hvd.Average,
                )
        criterion_transfer = nn.CrossEntropyLoss(weight=weights, reduction='mean')
        scheduler = ReduceLROnPlateau(
                optimizer,
                patience=4,
                factor=0.1,
                )

and the sequence of steps in my training loop is below -

         optimizer.zero_grad()
         loss.backward()
         optimizer.step()

Am I doing it correct or the bug is in the above implementation?
Thank You.

**Comment by tgaddair** [comment]
Hey @Rishav09, when you run one of our example scripts like [pytorch_mnist.py](https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py) does everything work correctly? If so, can you share a complete repro of the issue with the full log?

**Comment by Rishav09** [comment]
@tgaddair 
I tried running the MNIST example but as our machine is a cluster and the nodes where the script runs is a closed system. So I added the MNIST dataset manually in the path and modified the script but I am getting `RuntimeError: Dataset not found. You can use download=True to download it`.
Below are my modifications of the data loading -

`    train_dataset = \
       datasets.MNIST('/scratch/netra/MNIST/processed/training.pt-%d' % hvd.rank(), train=True, download=False,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ]))`
`    test_dataset = \
        datasets.MNIST('/scratch/netra/MNIST/processed/test.pt-%d' % hvd.rank(), train=False,download=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ]))`

**Comment by Rishav09** [comment]
@tgaddair  I am not able to run the pytorch_mnist example because my cluster don't have internet connectivity on nodes where training is done 
I have tried placing the MNIST data manually and loading through the below way -
   
     datasets.MNIST('/scratch/netra-%d' % hvd.rank(), train=True, download=True,
               transform=transforms.Compose([
                   transforms.ToTensor(),
                   transforms.Normalize((0.1307,), (0.3081,))
               ]))


and I am getting the below error log - 



```
WARN DDL-2-17] Not performing connection tests. Cannot find 'mpitool' executable. This could be because you are using a version of mpi that does not ship with mpitool.
Please see /tmp/DDLRUN/DDLRUN.5jbQvQknGOXl/ddlrun.log for detailed log.
+ /home/rxs1576/.conda/envs/opt/bin/mpirun -x LD_LIBRARY_PATH -x PATH -x LSB_MCPU_HOSTS -x LSB_JOBID -disable_gdr -gpu -mca plm_rsh_num_concurrent 3 --rankfile /tmp/DDLRUN/DDLRUN.5jbQvQknGOXl/RANKFILE -n 6 -x DDL_HOST_PORT=2200 -x "DDL_HOST_LIST=t042:0,1;t065:2,3;t077:4,5" -x "DDL_OPTIONS=-mode p:2x3x1x1 " bash -c 'source /share/apps/ibm_wml_ce/1.6.2/anaconda3/etc/profile.d/conda.sh && conda activate /home/rxs1576/.conda/envs/opt > /dev/null 2>&1 && /home/rxs1576/latest_scripts/launch.sh python /home/rxs1576/latest_scripts/mnist.py'
Traceback (most recent call last):
  File "/home/rxs1576/latest_scripts/mnist.py", line 138, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 129, in download
    makedir_exist_ok(self.raw_folder)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in makedir_exist_ok
    os.makedirs(dirpath)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/netra-1'
Traceback (most recent call last):
  File "/home/rxs1576/latest_scripts/mnist.py", line 138, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 129, in download
    makedir_exist_ok(self.raw_folder)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in makedir_exist_ok
    os.makedirs(dirpath)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/netra-0'
Traceback (most recent call last):
  File "/home/rxs1576/latest_scripts/mnist.py", line 138, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 129, in download
    makedir_exist_ok(self.raw_folder)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in makedir_exist_ok
    os.makedirs(dirpath)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/netra-5'
Traceback (most recent call last):
  File "/home/rxs1576/latest_scripts/mnist.py", line 138, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 129, in download
    makedir_exist_ok(self.raw_folder)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in makedir_exist_ok
       
```                                                                                                                                                                                   1,1           Top


I have tried placing the MNIST data manually and loading through the below way -
   
     datasets.MNIST('/scratch/netra-%d' % hvd.rank(), train=True, download=True,
               transform=transforms.Compose([
                   transforms.ToTensor(),
                   transforms.Normalize((0.1307,), (0.3081,))
               ]))

**Comment by tgaddair** [comment]
You could also try running the `pytorch_synthetic_benchmark.py` script, which does not require downloading or writing to disk. Let me know how that goes.

**Comment by Rishav09** [comment]
Thanks, I tried. This is really weird - I got `Runtime Error: CUDA error: out of memory`

The complete error log is -
```
WARN DDL-2-39] Running on more than 10 nodes. Skipping checks for performance.
Please see /tmp/DDLRUN/DDLRUN.lnbyibXp5Jv9/ddlrun.log for detailed log.
[WARN DDL-2-28] The SKIPCHECKS flag is set. This removes the ability for 'ddlrun' to detect remote hardware configurations and can cause errors in non-homogenous cluster environments - i.e., machines with varying core or GPU counts.
Please see /tmp/DDLRUN/DDLRUN.lnbyibXp5Jv9/ddlrun.log for detailed log.
+ /home/rxs1576/.conda/envs/opt/bin/mpirun -x LSB_MCPU_HOSTS -x LSB_JOBID -x LD_LIBRARY_PATH -x PATH -disable_gdr -gpu -mca plm_rsh_num_concurrent 16 --rankfile /tmp/DDLRUN/DDLRUN.lnbyibXp5Jv9/RANKFILE -n 32 -x DDL_HOST_PORT=2200 -x "DDL_HOST_LIST=t029:0,1;t035:2,3;t043:4,5;t044:6,7;t049:8,9;t052:10,11;t055:12,13;t058:14,15;t066:16,17;t069:18,19;t071:20,21;t073:22,23;t074:24,25;t081:26,27;t088:28,29;t089:30,31" -x "DDL_OPTIONS=-mode p:2x16x1x1 " bash -c 'source /share/apps/ibm_wml_ce/1.6.2/anaconda3/etc/profile.d/conda.sh && conda activate /home/rxs1576/.conda/envs/opt > /dev/null 2>&1 && /home/rxs1576/latest_scripts/launch.sh python /home/rxs1576/latest_scripts/benchmark_pytorch.py'
Traceback (most recent call last):
  File "/home/rxs1576/latest_scripts/benchmark_pytorch.py", line 54, in <module>
    model.cuda()
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/home/rxs1576/.conda/envs/opt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

```

**Comment by tgaddair** [comment]
How much GPU memory do you have available? Can you run `nvidia-smi`? Also, how many workers are you using with Horovod?

**Comment by Rishav09** [comment]
Our cluster has 96 Tesla V100s(16 Gb each), and I tried running from 2 GPUs to 16 GPUs. I tried running `lsload -gpuload` which is almost equivalent to `nvidia-smi`, below is the small output of it.Also, how to find the number of workers assigned?

![image](https://user-images.githubusercontent.com/11032253/110149860-8a1dfc80-7dac-11eb-9cf4-4b222311e092.png)

**Comment by Rishav09** [comment]
Here is a sample of GPU utilisation file of 1 node: 2 GPUs.  while the process is running -

<img width="1152" alt="Screenshot 2021-03-05 at 5 50 31 PM" src="https://user-images.githubusercontent.com/11032253/110182767-6d4ced80-7ddb-11eb-8c43-b70b471ecd67.png">

Let me know, if you want to see the whole file, I could upload it somewhere.
Thanks.
