### ISSUE TITLE
'Eigen/Core' file not found when building PyTorch support after TF support

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2703]
Build with `HOROVOD_WITH_TENSORFLOW=1` successfully.

Then enable `HOROVOD_WITH_PYTORCH=1` and set `HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITH_GLOO=1`. 

The following error appears:

```
cd /Users/tgaddair/repos/horovod/build/temp.macosx-10.15-x86_64-3.7/horovod/torch && /usr/local/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DEIGEN_MPL2_ONLY=1 -DHAVE_GLOO=1 -DTORCH_API_INCLUDE_EXTENSION_H=1 -DTORCH_VERSION=1007000000 -Dpytorch_EXPORTS -I/Users/tgaddair/repos/horovod/third_party/HTTPRequest/include -I/Users/tgaddair/repos/horovod/third_party/boost/assert/include -I/Users/tgaddair/repos/horovod/third_party/boost/config/include -I/Users/tgaddair/repos/horovod/third_party/boost/core/include -I/Users/tgaddair/repos/horovod/third_party/boost/detail/include -I/Users/tgaddair/repos/horovod/third_party/boost/iterator/include -I/Users/tgaddair/repos/horovod/third_party/boost/lockfree/include -I/Users/tgaddair/repos/horovod/third_party/boost/mpl/include -I/Users/tgaddair/repos/horovod/third_party/boost/parameter/include -I/Users/tgaddair/repos/horovod/third_party/boost/predef/include -I/Users/tgaddair/repos/horovod/third_party/boost/preprocessor/include -I/Users/tgaddair/repos/horovod/third_party/boost/static_assert/include -I/Users/tgaddair/repos/horovod/third_party/boost/type_traits/include -I/Users/tgaddair/repos/horovod/third_party/boost/utility/include -I/Users/tgaddair/repos/horovod/third_party/lbfgs/include -I/Users/tgaddair/repos/horovod/third_party/gloo -I/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/tensorflow_core/include -I/Users/tgaddair/repos/horovod/third_party/flatbuffers/include -isystem /Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/torch/include -isystem /Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/torch/include/TH -isystem /Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/torch/include/THC -isystem /Users/tgaddair/.pyenv/versions/3.7.8/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0  -pthread -fPIC -Wall -ftree-vectorize  -O3 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++14 -o CMakeFiles/pytorch.dir/__/common/controller.cc.o -c /Users/tgaddair/repos/horovod/horovod/common/controller.cc
In file included from /Users/tgaddair/repos/horovod/horovod/common/controller.cc:18:
In file included from /Users/tgaddair/repos/horovod/horovod/common/controller.h:24:
In file included from /Users/tgaddair/repos/horovod/horovod/common/global_state.h:25:
/Users/tgaddair/repos/horovod/horovod/common/parameter_manager.h:26:10: fatal error: 'Eigen/Core' file not found
#include <Eigen/Core>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [horovod/torch/CMakeFiles/pytorch.dir/__/common/controller.cc.o] Error 1
make[1]: *** [horovod/torch/CMakeFiles/pytorch.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 189, in <module>
    'horovodrun = horovod.runner.launch:run_commandline'
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/Users/tgaddair/repos/ludwig/env/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 91, in build_extensions
    cwd=self.build_temp)
  File "/Users/tgaddair/.pyenv/versions/3.7.8/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
```

Seems related to recent changes to how Eigen headers are included.

**Comment by chongxiaoc** [comment]
It might be related to the cache. Horovod build tensorflow firstly, and building tensorflow could overwrite `'Eigen` header since it may come from tensorflow's path, instead of third party git submodule.
https://github.com/horovod/horovod/blob/7e36ce4255a734e955e8ce9b229c74d5807b5620/horovod/tensorflow/CMakeLists.txt#L20

A second run without Tensorflow may reuse the Cmake Cache, however, tensorflow is not included in this build.

Above is my initial guess based on output and CMake order, have to investigate it.

**Comment by chongxiaoc** [comment]
@tgaddair 
I cannot reproduce the failure locally. Probably I missed some steps you were trying.

I repeated the following `step 1` and `step 2`, but never got a failure. The system already has tf, torch and mxnet installed.
- Step 1 (use any of them):
  - `HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 python setup.py install`
  - Or `HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 python setup.py install`

- Step 2
  - `HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITH_GLOO=1 python setup.py install` 

For `Eigen headers`, from the compilation logs, since TF is disable, horovod would check it out from git submodule as below:
```
warning: no previously-included files found matching 'third_party/eigen/Eigen/src/IterativeSolvers/*'
warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/FFT'
warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/MPRealSupport'
warning: no previously-included files found matching 'third_party/eigen/doc/PreprocessorDirectives.dox'
warning: no previously-included files found matching 'third_party/eigen/doc/UsingIntelMKL.dox'
warning: no previously-included files found matching 'third_party/eigen/doc/SparseLinearSystems.dox'
warning: no previously-included files found matching 'third_party/eigen/COPYING.GPL'
warning: no previously-included files found matching 'third_party/eigen/COPYING.LGPL'
warning: no previously-included files found matching 'third_party/eigen/COPYING.README'
```
