### ISSUE TITLE
Error when using more than 1 gpu ValueError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.

### ISSUE THREAD

**Issue by raotnameh** [horovod/horovod#2716]
I get this error when using more than 1 gpu. Code works fine when trained on 1 gpu.

[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_horovod.py", line 424, in <module>
[1,1]<stderr>:    discriminator_loss.backward(retain_graph=True)
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
[1,1]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
[1,1]<stderr>:    Variable._execution_engine.run_backward(
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 224, in hook
[1,1]<stderr>:    handle, ctx = self._allreduce_grad_async(p)
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 186, in _allreduce_grad_async
[1,1]<stderr>:    handle = allreduce_async_(tensor_compressed, name=name, op=self.op,
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 260, in allreduce_async_
[1,1]<stderr>:    return _allreduce_async(tensor, tensor, name, op, prescale_factor, postscale_factor)
[1,1]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 129, in _allreduce_async
[1,1]<stderr>:    handle = getattr(mpi_lib, function)(tensor, output, divisor,
[1,1]<stderr>:ValueError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_horovod.py", line 424, in <module>
[1,0]<stderr>:    discriminator_loss.backward(retain_graph=True)
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
[1,0]<stderr>:    Variable._execution_engine.run_backward(
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 224, in hook
[1,0]<stderr>:    handle, ctx = self._allreduce_grad_async(p)
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 186, in _allreduce_grad_async
[1,0]<stderr>:    handle = allreduce_async_(tensor_compressed, name=name, op=self.op,
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 260, in allreduce_async_
[1,0]<stderr>:    return _allreduce_async(tensor, tensor, name, op, prescale_factor, postscale_factor)
[1,0]<stderr>:  File "/home/hemant/.conda/envs/hor/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 129, in _allreduce_async
[1,0]<stderr>:    handle = getattr(mpi_lib, function)(tensor, output, divisor,
[1,0]<stderr>:ValueError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56260,1],0]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by raotnameh** [comment]
@tgaddair

**Comment by tgaddair** [comment]
Hey @raotnameh, can you share a minimal repro script we can run?
