### ISSUE TITLE
Installation via `pip install -e .` doesn't work on OSX

### ISSUE THREAD

**Issue by amogkam** [horovod/horovod#2727]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): Torch
2. Framework version: torch v1.8.0
3. Horovod version: Master
4. MPI version: N/A
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.8.6
8. Spark / PySpark version: N/A
9. OS and version: macOS Catalina 10.15.7
10. GCC version: 11.0.3
11. CMake version: 3.17.3

**Bug report:**
I've cloned the repo and am trying to install horovod master on my Mac like so `HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_TENSORFLOW=1 pip install --no-cache-dir -U -e .`

But it is failing with the following error
```
Obtaining file:///Users/amog/dev/horovod
Requirement already satisfied: cloudpickle in /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages (from horovod==0.21.3) (1.6.0)
Requirement already satisfied: psutil in /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages (from horovod==0.21.3) (5.8.0)
Requirement already satisfied: pyyaml in /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages (from horovod==0.21.3) (5.3.1)
Requirement already satisfied: cffi>=1.4.0 in /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages (from horovod==0.21.3) (1.14.5)
Requirement already satisfied: pycparser in /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages (from cffi>=1.4.0->horovod==0.21.3) (2.20)
Installing collected packages: horovod
  Attempting uninstall: horovod
    Found existing installation: horovod 0.21.3
    Uninstalling horovod-0.21.3:
      Successfully uninstalled horovod-0.21.3
  Running setup.py develop for horovod
    ERROR: Command errored out with exit status 1:
     command: /Users/amog/dev/ray_lightning_accelerators/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/amog/dev/horovod/setup.py'"'"'; __file__='"'"'/Users/amog/dev/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/amog/dev/horovod/
    Complete output (95 lines):
    running develop
    running egg_info
    writing horovod.egg-info/PKG-INFO
    writing dependency_links to horovod.egg-info/dependency_links.txt
    writing entry points to horovod.egg-info/entry_points.txt
    writing requirements to horovod.egg-info/requires.txt
    writing top-level names to horovod.egg-info/top_level.txt
    reading manifest file 'horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.hpp' under directory '*'
    no previously-included directories found matching '.eggs'
    warning: no directories found matching 'third_party/eigen/Eigen'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/Eigen'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/IterativeLinearSolvers'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/MetisSupport'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/Sparse'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/SparseCholesky'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/SparseLU'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/src/IterativeSolvers/*'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/src/OrderingMethods/Amd.h'
    warning: no previously-included files found matching 'third_party/eigen/Eigen/src/SparseCholesky/*'
    warning: no previously-included files found matching 'third_party/eigen/unsupported/test/mpreal/mpreal.h'
    warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/FFT'
    warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/MPRealSupport'
    warning: no previously-included files found matching 'third_party/eigen/doc/PreprocessorDirectives.dox'
    warning: no previously-included files found matching 'third_party/eigen/doc/UsingIntelMKL.dox'
    warning: no previously-included files found matching 'third_party/eigen/doc/SparseLinearSystems.dox'
    warning: no previously-included files found matching 'third_party/eigen/COPYING.GPL'
    warning: no previously-included files found matching 'third_party/eigen/COPYING.LGPL'
    warning: no previously-included files found matching 'third_party/eigen/COPYING.README'
    warning: no directories found matching 'third_party/gloo/cmake'
    warning: no files found matching 'CMakeLists.txt' under directory 'third_party/gloo'
    warning: no files found matching '*.in' under directory 'third_party/gloo'
    writing manifest file 'horovod.egg-info/SOURCES.txt'
    running build_ext
    -- Could not find CCache. Consider installing CCache to speed up compilation.
    -- Build architecture flags:
    -- Using command /Users/amog/dev/ray_lightning_accelerators/bin/python3
    CMake Error at CMakeLists.txt:248 (add_subdirectory):
      The source directory

        /Users/amog/dev/horovod/third_party/gloo

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:250 (target_compile_definitions):
      Cannot specify compile definitions for target "gloo" which is not built by
      this project.


    CMake Error at CMakeLists.txt:314 (add_subdirectory):
      The source directory

        /Users/amog/dev/horovod/third_party/compatible_gloo

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:315 (target_compile_definitions):
      Cannot specify compile definitions for target "compatible_gloo" which is
      not built by this project.


    -- Configuring incomplete, errors occurred!
    See also "/Users/amog/dev/horovod/build/temp.macosx-10.15-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/amog/dev/horovod/setup.py", line 151, in <module>
        setup(name='horovod',
      File "/Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/amog/dev/horovod/setup.py", line 93, in build_extensions
        subprocess.check_call([cmake_bin, self.extensions[0].cmake_lists_dir] + cmake_args,
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/Users/amog/dev/horovod', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/Users/amog/dev/horovod/build/lib.macosx-10.15-x86_64-3.8', '-DPYTHON_EXECUTABLE:FILEPATH=/Users/amog/dev/ray_lightning_accelerators/bin/python3']' returned non-zero exit status 1.
    ----------------------------------------
  Rolling back uninstall of horovod
  Moving to /Users/amog/dev/ray_lightning_accelerators/bin/horovodrun
   from /private/var/folders/qt/f7ftj_xs6fn_swc4vn7kx0y80000gn/T/pip-uninstall-nvbmuvkt/horovodrun
  Moving to /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/horovod-0.21.3.dist-info/
   from /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/~orovod-0.21.3.dist-info
  Moving to /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/horovod/
   from /Users/amog/dev/ray_lightning_accelerators/lib/python3.8/site-packages/~orovod
ERROR: Command errored out with exit status 1: /Users/amog/dev/ray_lightning_accelerators/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/amog/dev/horovod/setup.py'"'"'; __file__='"'"'/Users/amog/dev/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Same error also happens with just a normal `pip install --no-cache-dir -U -e .`.

**Comment by richardliaw** [comment]
Hmm, I think you have to run this instead:

```
HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1 python setup.py install
```

**Comment by tgaddair** [comment]
@amogkam, does calling `python setup.py install` allow you to compile? In general, we don't support using `pip install -e`, as the need to use CMake during the install process can cause issues. However, if you want to install to be very fast, I would suggest running `brew install ccache`.

**Comment by stoksc** [comment]
Hit the same on macOS and realized I hadn't run `git submodule init`/`git submodule update` so I didn't have gloo vendored. 

> CMake Error at CMakeLists.txt:250 (target_compile_definitions):
      Cannot specify compile definitions for target "gloo" which is not built by
      this project.
      
That looks like that same issue. After that, I needed to grab libuv (`brew install libuv`) to get gloo to compile.

**Comment by amogkam** [comment]
Yep updating the git submodules and then doing `python setup.py install` did the trick.
