### ISSUE TITLE
Ray Horovod : HTTP request failed

### ISSUE THREAD

**Issue by Deathn0t** [horovod/horovod#2746]
**Environment:**
1. Framework:  Tensorflow
2. Framework version: 2.50
3. Horovod version: 0.21.3
4. MPI version: none
5. CUDA version: 11.0
6. NCCL version: nccl_2.8.4-1+cuda11.0_x86_64
7. Python version: 3.8.3
8. Spark / PySpark version: none
9. OS and version: Ubuntu 18.04
10. GCC version: 7.5.0
11. CMake version: none

**Checklist:**

1. Did you search issues to find if somebody asked this question before?

This issue https://github.com/horovod/horovod/issues/1364 looks similar

**Bug report:**

I am running a Ray cluster on 2 nodes, each node has 8 GPUs.

I am launching 4 RayExecutor per node (2 GPUs per RayExecutor).

I compiled Horovod with the following command:
```
HOROVOD_WITHOUT_MPI=1 HOROVOD_NCCL_HOME=/lus/theta-fs0/software/thetagpu/cuda/nccl_2.8.4-1+cuda11.0_x86_64 HOROVOD_WITH_GLOO=1 HOROVOD_GPU_OPERATIONS=NCCL pip install 'horovod[tensorflow,ray]' --no-cache-dir
```

Then I am running the [following function](https://github.com/deephyper/deephyper/blob/develop/deephyper/nas/run/horovod.py) with `.run_remote`

The exception is:
```
(pid=11118) [2021-03-26 08:37:42.910981: E /tmp/pip-install-1br0pr96/horovod_284c8b944a414cd09d36e9484ace2798/horovod/common/gloo/http_store.cc:96] HTTP GET request failed too many times, aborting. See exception message above.
(pid=11118) terminate called after throwing an instance of 'std::runtime_error'
(pid=11118)   what():  HTTP request failed.
```

I also found:
```
Traceback (most recent call last):
  File "/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/deephyper/deephyper/evaluator/_ray_evaluator.py", line 30, in _poll
    self._result = ray.get(id_done[0])
  File "/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/worker.py", line 1458, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.
```

here are the ray logs 
[logs.tar.gz](https://github.com/horovod/horovod/files/6210451/logs.tar.gz)

**Comment by Deathn0t** [comment]
For me it looks like the issue happens when calling `hvd.rank()` on a worker node (not the driver).

**Comment by Deathn0t** [comment]
This short example reproduce the same error.

```import socket
import ray

import horovod.tensorflow.keras as hvd
# import horovod.tensorflow as hvd
from horovod.ray import RayExecutor

# Start the Ray cluster or attach to an existing Ray cluster
ray.init(address="auto")

# Ray executor settings
setting = RayExecutor.create_settings(timeout_s=100)
num_hosts = 2  # number of machine to use
num_slots = 8  # number of workers to use on each machine
cpus_per_slot = 1  # number of cores to allocate to each worker
gpus_per_slot = 1 # number of GPUs to allocate to each worker

# Start num_hosts * num_slots actors on the cluster
# https://horovod.readthedocs.io/en/stable/api.html#horovod-ray-api
executor = RayExecutor(
    setting,
    num_hosts=num_hosts,
    num_slots=num_slots,
    cpus_per_slot=cpus_per_slot,
    gpus_per_slot=gpus_per_slot,
    use_gpu=True
)

# Launch the Ray actors on each machine
# This will launch `num_slots` actors on each machine
print("Start executor...", end="", flush=True)
executor.start()
print("OK", flush=True)


#! Note that there is an implicit assumption on the cluster being
#! homogenous in shape (i.e., all machines have the same number of
#! slots available). This is simply an implementation detail and is
#! not a fundamental limitation.

# Using the stateless `run` method, a function can take in any args or kwargs
def simple_fn():


    hvd.init()

    rank = hvd.rank()


    ## getting the hostname by socket.gethostname() method
    hostname = socket.gethostname()
    ## getting the IP address using socket.gethostbyname() method
    ip_address = socket.gethostbyname(hostname)

    print(f"hvd rank[{ip_address}]", rank)

    return rank


# Execute the function on all workers at once
result = executor.run(simple_fn)
print(result)

# Check that the rank of all workers is unique
assert len(set(result)) == num_hosts * num_slots

executor.shutdown()
```

This is what `ifconfig` returns me:


```
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 9000
        inet6 fe80::5029:82ff:fe1d:8930  prefixlen 64  scopeid 0x20<link>
        ether 52:29:82:1d:89:30  txqueuelen 1000  (Ethernet)
        RX packets 8585275  bytes 1089069729 (1.0 GB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 143193  bytes 108358152 (108.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

bond0.2360: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        inet 10.236.2.199  netmask 255.255.0.0  broadcast 10.236.255.255
        inet6 fe80::5029:82ff:fe1d:8930  prefixlen 64  scopeid 0x20<link>
        ether 52:29:82:1d:89:30  txqueuelen 1000  (Ethernet)
        RX packets 2113785  bytes 543693510 (543.6 MB)
        RX errors 0  dropped 190  overruns 0  frame 0
        TX packets 67649  bytes 99949270 (99.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:7b:03:01:b9  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp225s0f1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 9000
        ether 52:29:82:1d:89:30  txqueuelen 1000  (Ethernet)
        RX packets 970180  bytes 122267995 (122.2 MB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 113444  bytes 104666347 (104.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp226s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.230.2.199  netmask 255.255.0.0  broadcast 10.230.255.255
        inet6 fe80::5eff:35ff:fee1:7b83  prefixlen 64  scopeid 0x20<link>
        ether 5c:ff:35:e1:7b:83  txqueuelen 1000  (Ethernet)
        RX packets 28251705  bytes 2568411394 (2.5 GB)
        RX errors 0  dropped 1423  overruns 0  frame 0
        TX packets 31549863  bytes 33989766445 (33.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xf2700000-f277ffff

enp97s0f1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 9000
        ether 52:29:82:1d:89:30  txqueuelen 1000  (Ethernet)
        RX packets 7615095  bytes 966801734 (966.8 MB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 29749  bytes 3691805 (3.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

infinibond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 2044
        inet 172.23.2.199  netmask 255.255.0.0  broadcast 172.23.255.255
        inet6 fe80::e42:a103:4a:7794  prefixlen 64  scopeid 0x20<link>
        unspec 20-00-11-07-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 160873602  bytes 18019047127 (18.0 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6453143  bytes 1203403412 (1.2 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 7617323  bytes 3962914331 (3.9 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7617323  bytes 3962914331 (3.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mlx_ib4: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 2044
        unspec 20-00-11-07-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 256  (UNSPEC)
        RX packets 83244635  bytes 9571241290 (9.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6453143  bytes 1203403412 (1.2 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mlx_ib9: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 2044
        unspec 20-00-11-07-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 256  (UNSPEC)
        RX packets 77628967  bytes 8447805837 (8.4 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

For the ray cluster:
```
>>> ray.available_resources()
{'GPU': 16.0, 'memory': 32770.0, 'CPU': 16.0, 'node:10.230.2.199': 1.0, 'object_store_memory': 5264.0, 'node:10.230.2.198': 1.0}
```

**Comment by tgaddair** [comment]
Thanks for raising this issue @Deathn0t.  It looks like the Horovod worker is not able to make an HTTP request to the head node, causing the failure. Is it possible that the workers are not able to reach the head node this way (perhaps due to a firewall or other networking restriction)?

@richardliaw do you have any thoughts on what might be happening here?

**Comment by Deathn0t** [comment]
FIY it works well if I use `ray.remote` on multiple nodes! I am not sure if the 2 mechanisms use the same protocol for communication.

**Comment by richardliaw** [comment]
@Deathn0t thanks a bunch for making this issue! Could you help post `/tmp/ray/session_latest/logs`?

**Comment by Deathn0t** [comment]
Thanks for answering @richardliaw I posted this logs in the first message: https://github.com/horovod/horovod/files/6210451/logs.tar.gz

do you need something else?
