### ISSUE TITLE
error when set backward_passes_per_step > 1 in tensorflow keras

### ISSUE THREAD

**Issue by tiandongtao** [horovod/horovod#2806]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) 
2. Framework version: (1.15, 2.3.1, 1.6.0, 1.6.0)
3. Horovod version: 0.21.3
4. MPI version:
5. CUDA version:10.0
6. NCCL version:
7. Python version:3.7
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Bug report:**
when set backward_passes_per_step > 1 and sparse_as_dense True , execute mpirun -np 2 --allow-run-as-root python test.py   it output error
here is code 
 ```python
from __future__ import print_function
import numpy as np
from tqdm import tqdm
from bert4keras.backend import keras, K
from bert4keras.layers import Loss
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer, load_vocab
from bert4keras.optimizers import Adam
from bert4keras.snippets import sequence_padding, open
from bert4keras.snippets import DataGenerator, AutoRegressiveDecoder
from keras.models import Model
from rouge import Rouge  # pip install rouge
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
import pdb
import os
import tensorflow as tf
import keras
import horovod.tensorflow.keras as hvd

hvd.init()

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
K.set_session(tf.Session(config=config))

opt = Adam(1e-5 * hvd.size())
opt = hvd.DistributedOptimizer(opt, backward_passes_per_step=2, sparse_as_dense=True)
```

output error log :

```bash
More specifically: Substructure "type=IndexedSlices str=IndexedSlices(indices=Tensor("training/Adam/gradients/Embedding-Segment/embedding_lookup_grad/Reshape_1:0", shape=(?,), dtype=int32), values=Tensor("training/Adam/gradients/Embedding-Segment/embedding_lookup_grad/Reshape:0", shape=(?, 768), dtype=float32), dense_shape=Tensor("training/Adam/gradients/Embedding-Segment/embedding_lookup_grad/Const:0", shape=(2,), dtype=int32))" is a sequence, while substructure "type=Tensor str=Tensor("training/Adam/cond_1/truediv_1:0", shape=(2, 768), dtype=float32)" is not
Entire first structure:
[., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .]
Entire second structure:
[., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 223, in <module>
    verbose=1 if hvd.rank() == 0 else 0
  File "/usr/local/lib/python3.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training_generator.py", line 42, in fit_generator
    model._make_train_function()
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 316, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python3.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/optimizers.py", line 504, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python3.7/dist-packages/horovod/_keras/__init__.py", line 106, in get_gradients
    return self._allreduce(gradients, params)
  File "/usr/local/lib/python3.7/dist-packages/horovod/_keras/__init__.py", line 121, in _allreduce
    return self._agg_helper.compute_gradients(tuple(grads), tuple(vars))
  File "/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/gradient_aggregation.py", line 208, in compute_gradients
    lambda: grads,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1260, in cond
    "Incompatible return values of true_fn and false_fn: {}".format(e))
ValueError: Incompatible return values of true_fn and false_fn: The two structures don't have the same nested structure.
```

**Comment by tgaddair** [comment]
@rb-determined-ai could you take a look?

**Comment by rb-determined-ai** [comment]
Gladly.  I'll try to dig into it some today or tomorrow but it might take me until next week... busy week this week.

**Comment by rb-determined-ai** [comment]
Forgive me for the delay.  I am now up-to-speed with running horovod locally and would be happy to help out with fixing this.

I noticed that the example provided does not seem to include enough code to reproduce the error... looks from the stacktrace that it happens in model.fit().

It would help me out if you could share enough of an example that I could reproduce it.

But, you are also free to just go edit your `/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/gradient_aggregation.py` file.  Based on reading through the feature I think the solution might be something like this:

```diff
            # Allreduce locally aggregated gradients when the counter is equivalent to
            # `backward_passes_per_step`. This the condition is true, it also resets
            # the counter back to 0.
            allreduced_grads = tf.cond(
                tf.equal(self.counter, self.backward_passes_per_step),
                lambda: self._allreduce_grads_helper(grads, vars),
-               lambda: grads,
+               lambda: [tf.convert_to_tensor(g) if self.sparse_as_dense and isinstance(grad, tf.IndexedSlices) else g for g in grads],
            )
```

**Comment by tiandongtao** [comment]
> Forgive me for the delay. I am now up-to-speed with running horovod locally and would be happy to help out with fixing this.
> 
> I noticed that the example provided does not seem to include enough code to reproduce the error... looks from the stacktrace that it happens in model.fit().
> 
> It would help me out if you could share enough of an example that I could reproduce it.
> 
> But, you are also free to just go edit your `/usr/local/lib/python3.7/dist-packages/horovod/tensorflow/gradient_aggregation.py` file. Based on reading through the feature I think the solution might be something like this:
> 
> ```diff
>             # Allreduce locally aggregated gradients when the counter is equivalent to
>             # `backward_passes_per_step`. This the condition is true, it also resets
>             # the counter back to 0.
>             allreduced_grads = tf.cond(
>                 tf.equal(self.counter, self.backward_passes_per_step),
>                 lambda: self._allreduce_grads_helper(grads, vars),
> -               lambda: grads,
> +               lambda: [tf.convert_to_tensor(g) if self.sparse_as_dense and isinstance(grad, tf.IndexedSlices) else g for g in grads],
>             )
> ```

I'm sorry to reply now,I've been very busy recently.I have try this way  and fix this bug,thanks a lot！
