### ISSUE TITLE
examples/ray/pytorch_ray_elastic.py can not working, when ray cluster has head pod only

### ISSUE THREAD

**Issue by junhuihuang** [horovod/horovod#2826]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0+cu101
3. Horovod version: 0.21.3
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.7.5
8. Spark / PySpark version:
9. Ray version: 1.2.0
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

1. set ray cluster provider is kubernetes
2. set `min_workers: 0` in cluster.yaml
3. set head pod no gpu, and set worker has 1 gpu resource
3. `ray up cluster.yaml`
4. `ray exec cluster.yaml -- 'cd /lcs/horovod && python pytorch_ray_elastic.py'` 

```text
2021-04-07 17:47:41,029 INFO command_runner.py:171 -- NodeUpdater: ray-head-rgz4j: Running kubectl -n ray exec -it ray-head-rgz4j -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (cd /lcs/horovod && python pytorch_ray_elastic.py)'
2021-04-07 09:47:42,326 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.18.69.31:6379
INFO:root:Rendezvous INFO: HTTP rendezvous server started.
DEBUG:horovod.ray.elastic:[ray] waiting for 1 to start.
DEBUG:root:current available slots: 0
DEBUG:root:current available hosts: 0.
Traceback (most recent call last):
  File "pytorch_ray_elastic.py", line 256, in <module>
    executor.start()
  File "/usr/local/lib/python3.7/dist-packages/horovod/ray/elastic.py", line 287, in start
    self.driver.wait_for_available_slots(self.settings.num_proc)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/elastic/driver.py", line 170, in wait_for_available_slots
    tmout.check_time_out_for('minimum number of slots to become available')
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/common/util/timeout.py", line 37, in check_time_out_for
    self._timeout
Exception: Timed out waiting for minimum number of slots to become available. Please check that you have enough resources to run at least 1 Horovod processes. Timeout after 600 seconds.
command terminated with exit code 1
2021-04-07 17:57:43,101 ERROR command_runner.py:183 -- NodeUpdater: ray-head-rgz4j: Command failed:

  kubectl -n ray exec -it ray-head-rgz4j --'bash --login -c -i '"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (cd /lcs/horovod && python pytorch_ray_elastic.py)'"'"''
```

**Comment by tgaddair** [comment]
Hey @junhuihuang, thanks for reporting the issue. Is you set `min_workers: 1` does it work?

@richardliaw are there any autoscaler logs that can be checked to understand why it didn't scale up?

**Comment by richardliaw** [comment]
yeah, @junhuihuang can you post `/tmp/ray/session_latest/logs/monitor.*`?

**Comment by junhuihuang** [comment]
@tgaddair set `min_workers: 1` is not work.  

From [code](https://github.com/horovod/horovod/blob/ed323ead8012ba5894fc70ceea5a1f2974cc9d43/horovod/ray/elastic.py#L291), mini workers should be 2.


@richardliaw This is the `monitor.*` files.

[ray-monitor.zip](https://github.com/horovod/horovod/files/6302102/ray-monitor.zip)

**Comment by richardliaw** [comment]
Hey @junhuihuang sorry for the slow reply. does `min_workers: 2` work?

**Comment by junhuihuang** [comment]
@richardliaw work

**Comment by richardliaw** [comment]
OK got it. So the main issue here is that Ray doesn't support the case where there's only 1 starting worker right?

**Comment by junhuihuang** [comment]
The main issue may be that Ray autoscaler don't create more workers (e.g. min_workers: 0, max_workers: 5, but pytorch_ray_elastic.py waits for available slots timeout)
