### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by alfredyewang** [horovod/horovod#2831]
**Environment:**
1. Framework:  PyTorch
2. Framework version:  1.7.1
3. Horovod version: 0.21.3
4. MPI version: openmpi/4.0.1
5. CUDA version: 11.2
6. NCCL version: 2.7.08
7. Python version: 3.7.19
8. Spark / PySpark version:
9. Ray version:
10. OS and version:  CentOS 7
11. GCC version: gcc 4.8.5
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes.  https://github.com/horovod/horovod/issues/1586

**Bug report:**
System: 4 nodes each with 4 P100 GPUs. 

I am able to run my script on any 2 nodes each with 2 GPUs,  any 1 node each with 4 GPUs or 4 nodes each with 1 GPUs. But when I'm trying to run the script on 4 nodes each with 2/3/4 GPUs or 2 nodes each with 3/4 GPUs , it shows the following error:

```
[ywang17@yarrow06 fast_molvae]$ horovodrun --verbose --network-interface enp24s0f0  -np 8 -H localhost:4,yarrow07:4 --start-timeout 300  python hovord_test.py
Filtering local host names.
Remote host found: yarrow07
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
mpirun --allow-run-as-root --tag-output -np 8 -H localhost:4,yarrow07:4 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include enp24s0f0 -x NCCL_SOCKET_IFNAME=enp24s0f0  -x ARC -x CONDA_DEFAULT_ENV -x CONDA_EXE -x CONDA_PREFIX -x CONDA_PREFIX_1 -x CONDA_PROMPT_MODIFIER -x CONDA_PYTHON_EXE -x CONDA_SHLVL -x ENVIRONMENT -x HISTCONTROL -x HISTSIZE -x HOME -x HOSTNAME -x JOB_ID -x JOB_NAME -x JOB_SCRIPT -x LANG -x LD_LIBRARY_PATH -x LD_RUN_PATH -x LESSOPEN -x LOADEDMODULES -x LOGNAME -x LS_COLORS -x MAIL -x MANPATH -x MODULEPATH -x MODULESHOME -x MODULE_VERSION -x MODULE_VERSION_STACK -x NHOSTS -x NQUEUES -x NSLOTS -x OMPIDIR -x PATH -x PE -x PE_HOSTFILE -x PWD -x QRSH_COMMAND -x QUEUE -x REQNAME -x REQUEST -x RESTARTED -x SGE_ACCOUNT -x SGE_ARCH -x SGE_BINARY_PATH -x SGE_CELL -x SGE_CLUSTER_NAME -x SGE_CWD_PATH -x SGE_HGR_TASK_ngpus -x SGE_HGR_ngpus -x SGE_JOB_SPOOL_DIR -x SGE_O_HOME -x SGE_O_HOST -x SGE_O_LOGNAME -x SGE_O_MAIL -x SGE_O_PATH -x SGE_O_SHELL -x SGE_O_WORKDIR -x SGE_RERUN_JOB -x SGE_RERUN_REQUESTED -x SGE_ROOT -x SGE_RSH_COMMAND -x SGE_STDERR_PATH -x SGE_STDIN_PATH -x SGE_STDOUT_PATH -x SGE_TASK_FIRST -x SGE_TASK_ID -x SGE_TASK_LAST -x SGE_TASK_STEPSIZE -x SHELL -x SHLVL -x TERM -x TMPDIR -x USER -x USE_SYSTEMD -x XDG_DATA_DIRS -x _ -x _CE_CONDA -x _CE_M -x _LMFILES_  python hovord_test.py
Pseudo-terminal will not be allocated because stdin is not a terminal.
[1,6]<stderr>:Traceback (most recent call last):
[1,6]<stderr>:  File "hovord_test.py", line 126, in <module>
[1,6]<stderr>:    torch.cuda.set_device(hvd.local_rank())
[1,6]<stderr>:  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
[1,6]<stderr>:    torch._C._cuda_setDevice(device)
[1,6]<stderr>:RuntimeError: CUDA error: invalid device ordinal
[1,5]<stderr>:Traceback (most recent call last):
[1,5]<stderr>:  File "hovord_test.py", line 126, in <module>
[1,5]<stderr>:    torch.cuda.set_device(hvd.local_rank())
[1,5]<stderr>:  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
[1,5]<stderr>:    torch._C._cuda_setDevice(device)
[1,5]<stderr>:RuntimeError: CUDA error: invalid device ordinal
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "hovord_test.py", line 126, in <module>
[1,4]<stderr>:    torch.cuda.set_device(hvd.local_rank())
[1,4]<stderr>:  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
[1,4]<stderr>:    torch._C._cuda_setDevice(device)
[1,4]<stderr>:RuntimeError: CUDA error: invalid device ordinal
[1,7]<stderr>:Traceback (most recent call last):
[1,7]<stderr>:  File "hovord_test.py", line 126, in <module>
[1,7]<stderr>:    torch.cuda.set_device(hvd.local_rank())
[1,7]<stderr>:  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
[1,7]<stderr>:    torch._C._cuda_setDevice(device)
[1,7]<stderr>:RuntimeError: CUDA error: invalid device ordinal
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[18705,1],6]
  Exit code:    1
--------------------------------------------------------------------------
```

Any suggestion? Thank you in advance.

**Comment by chongxiaoc** [comment]
What's `hovorod_test.py`? 
Also can you dump out the invalid GPU indices?

**Comment by alfredyewang** [comment]
Thanks for your reply!

> What's `hovorod_test.py`?

Sorry for the confusion. This script refers to [`pytorch_mnist.py`](https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py) on examples.

> Also can you dump out the invalid GPU indices?

I didn't set CUDA_VISIBLE_DEVICES, and is there any way to dump out the invalid GPU indices? Thank you.

**Comment by chongxiaoc** [comment]
In this case, this line throws errors:
```
[1,5]<stderr>:    torch.cuda.set_device(hvd.local_rank())
```

You can print out `hvd.local_rank()`, that is the invalid GPU ids.

**Comment by alfredyewang** [comment]
> In this case, this line throws errors:
> 
> ```
> [1,5]<stderr>:    torch.cuda.set_device(hvd.local_rank())
> ```
> 
> You can print out `hvd.local_rank()`, that is the invalid GPU ids.

Thanks! `hvd.local_rank()` will give me 0-7 if I specify 8 gpus,  and 4-7 will be invalid GPU ids for each node. Is there any way to set this?  I tried `--max-np 4`,  but it still returns me 0-7.

**Comment by alfredyewang** [comment]
@chongxiaoc 
```
import horovod.torch as hvd
hvd.init()
print(hvd.local_rank(),hvd.rank(), hvd.size())
```
I tested with the above code with ` -np 16 -H yarrow05:4,yarrow06:4,yarrow07:4,yarrow02:4 ,` and it gives me
```
[1,10]<stdout>:10 10 16
[1,8]<stdout>:8 8 16
[1,9]<stdout>:9 9 16
[1,2]<stdout>:2 2 16
[1,3]<stdout>:3 3 16
[1,4]<stdout>:4 4 16
[1,5]<stdout>:5 5 16
[1,6]<stdout>:6 6 16
[1,7]<stdout>:7 7 16
[1,11]<stdout>:11 11 16
[1,12]<stdout>:12 12 16
[1,13]<stdout>:13 13 16
[1,15]<stdout>:15 15 16
[1,0]<stdout>:0 0 16
[1,1]<stdout>:1 1 16
[1,14]<stdout>:14 14 16
```

**Comment by chongxiaoc** [comment]
It looks like local rank is wrong.
In your setup, local rank should be in range [0, 4)

**Comment by chongxiaoc** [comment]
Can you try again without `--network-interface enp24s0f0`? I guess this nic is not available for all nodes, then the training is running on a single node with this nic, which makes local_rank == hvd.rank().

**Comment by alfredyewang** [comment]
> Can you try again without `--network-interface enp24s0f0`? I guess this nic is not available for all nodes, then the training is running on a single node with this nic, which makes local_rank == hvd.rank().

Thanks! If I run without specify the nic, it will raise the following connect error. 

```
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Launching horovod task function was not successful:
WARNING: Expected to connect the host 10.9.77.148:49585 using interface bond0, but reached it on interface enp24s0f0.
Traceback (most recent call last):
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/horovod/runner/task_fn.py", line 66, in <module>
    _task_fn(index, num_hosts, driver_addresses, settings)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/horovod/runner/task_fn.py", line 43, in _task_fn
    attempts=10)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/horovod/runner/task/task_service.py", line 72, in __init__
    attempts=attempts)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/horovod/runner/common/service/task_service.py", line 320, in __init__
    attempts=attempts)
  File "/home/ywang17/.conda/envs/chem3/lib/python3.7/site-packages/horovod/runner/common/util/network.py", line 198, in __init__
    'Linux.'.format(service_name=service_name, addresses=addresses))
horovod.runner.common.util.network.NoValidAddressesFound: Horovod was unable to connect to horovod task service #2 on any of the following addresses: {'lo': [('127.0.0.1', 49585)], 'bond0': [('10.9.77.148', 49585)], 'virbr0': [('192.168.122.1', 49585)]}.

One possible cause of this problem is that horovod currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
```

**Comment by chongxiaoc** [comment]
Check https://github.com/horovod/horovod/issues/2568, it should have some discussion helpful to you.

For example:

`Can you run ifconfig on each node to see what available nics are there? If there is no --network-interface specified, horovod is using ifconfig and local ip address to pick up available nics internally.
`

**Comment by alfredyewang** [comment]
> Check #2568, it should have some discussion helpful to you.
> 
> For example:
> 
> `Can you run ifconfig on each node to see what available nics are there? If there is no --network-interface specified, horovod is using ifconfig and local ip address to pick up available nics internally. `

Thanks for your information! Here is further information after checking the nic.

If I run scripts with `horovodrun --verbose  -np 4 -H yarrow01:4 ` or `horovodrun --verbose  -np 4 -H yarrow02:4 ` on yarrow06 node, it works well and gives me:
```
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Host-to-host interface checking successful.
Interfaces on all the hosts were successfully checked.
Common interface found: enp24s0f0 lo eno1 virbr0
Pseudo-terminal will not be allocated because stdin is not a terminal.
[1,0]<stdout>:0 0 4
[1,2]<stdout>:2 2 4
[1,3]<stdout>:3 3 4
[1,1]<stdout>:1 1 4
```
They both have **enp24s0f0 lo eno1 virbr0** common interface on yarrow01 and yarrow02 nodes. If I try `horovodrun --verbose  -np 8 -H yarrow01:4,yarrow02:4 --start-timeout 300`. they still have common interface found (**enp24s0f0 eno1**), but with the wrong  local rank : 
```
Filtering local host names.
Remote host found: yarrow01 yarrow02
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovod server.
Launching horovod task function: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no yarrow01
....
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Host-to-host interface checking successful.
Interfaces on all the hosts were successfully checked.
Common interface found: enp24s0f0 eno1
....
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
[1,0]<stdout>:0
[1,1]<stdout>:1
[1,4]<stdout>:4
[1,6]<stdout>:6
[1,3]<stdout>:3
[1,7]<stdout>:7
[1,2]<stdout>:2
[1,5]<stdout>:5
```

**Comment by alfredyewang** [comment]
@chongxiaoc 

I figure it out by changing `mpirun -map-by slot` to `-map-by node`, but I am still not clear with that.

**Comment by chongxiaoc** [comment]
> @chongxiaoc
> 
> I figure it out by changing `mpirun -map-by slot` to `-map-by node`, but I am still not clear with that.

I thought you were using horovodrun

**Comment by alfredyewang** [comment]
@chongxiaoc

Hi chongxiao, thank you so much! I finally solve this by renaming NIC...
