### ISSUE TITLE
Error when building Horovod-pytorch on ubuntu16.04 with pytorch1.7

### ISSUE THREAD

**Issue by hangxu124** [horovod/horovod#2836]
**Environment:**
1. Framework: Pytorch
2. Framework version:1.7.1
3. Horovod version: latest
4. MPI version:  mpirun (Open MPI) 4.0.5
5. CUDA version: 11.1
6. NCCL version: 2.8.3-cuda11.1
7. Python version:3.7
8. Spark / PySpark version:
9. Ray version:
10. OS and version: ubuntu 16.04
11. GCC version: 5.4.0
12. CMake version: 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I have a machine with ubuntu16.04 and 8 RTX3090,  I try to install horovod 0.21.3 and meet this error:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    FOUND_LIB_cudart
        linked by target "pytorch" in directory /tmp/pip-install-mhsq78vh/horovod_691e65a56c9d4756b5894563b2b6f79b/horovod/torch
Total error msg is here:
[error.txt](https://github.com/horovod/horovod/files/6295264/error.txt)

I also try to install with :
`HOROVOD_NCCL_HOME=/algo/algo/qiuqi/test/nccl_2.8.3-1+cuda11.1_x86_64 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_CUDA_HOME=/algo/modelzoo/software/cuda-11.1 FOUND_LIB_cudart=/algo/modelzoo/software/cuda-11.1/lib64/libcudart.so   pip install --no-cache-dir horovod`
It fails with same error.

I also read this issue (https://github.com/horovod/horovod/issues/2474) and install 0.19.5, however,
I run horovodrun -cb and found that NCCL is not selected.
Horovod v0.19.5:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

and when I try to run examples/pytorch/pytorch_synthetic_benchmark.py with:
`horovodrun -np 1 -H localhost:1 python pytorch_synthetic_benchmark.py`
(torch1.7) (base) qiuqi@ybjjgu024:/algo/algo/qiuqi/test/horovod/examples/pytorch$ horovodrun -np 1 -H localhost:1 python pytorch_synthetic_benchmark.py
[1,0]<stderr>:/algo/algo/qiuqi/venv/torch1.7/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning:
[1,0]<stderr>:GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
[1,0]<stderr>:The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
[1,0]<stderr>:If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
[1,0]<stderr>:
[1,0]<stderr>:  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "pytorch_synthetic_benchmark.py", line 71, in <module>
[1,0]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,0]<stderr>:  File "/algo/algo/qiuqi/venv/torch1.7/lib/python3.7/site-packages/horovod/torch/__init__.py", line 476, in broadcast_parameters
[1,0]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,0]<stderr>:  File "/algo/algo/qiuqi/venv/torch1.7/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 449, in broadcast_async_
[1,0]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,0]<stderr>:  File "/algo/algo/qiuqi/venv/torch1.7/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 359, in _broadcast_async
[1,0]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,0]<stderr>:RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[16334,1],0]
  Exit code:    1

It seems the capabilities doesn't fit for 3090

Here is output of `echo $LD_LIBRARY_PATH`:
/algo/algo/qiuqi/test/nccl_2.8.3-1+cuda11.1_x86_64/lib:/algo/algo/qiuqi/opt/openmpi/lib:/algo/modelzoo/software/cuda-11.1/lib64:/algo/modelzoo/software/cuda-11.1/lib64::/usr/local/cuda/lib64:/usr/local/cuda/lib64

**Comment by tgaddair** [comment]
I think `HOROVOD_GPU_OPERATIONS` may not have been available in 0.19.5, you would need to use `HOROVOD_GPU_ALLREDUCE` instead.

But really we should try to get things working with the latest version of Horovod. I would try setting `HOROVOD_CUDA_HOME` explicitly to make sure the right version of CUDA is being picked up.

**Comment by InfluencerNGZK** [comment]
As @tgaddair mentioned, I tried the following command
```sh
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_NCCL_LINK=SHARE HOROVOD_CUDA_HOME=/usr/local/cuda-10.1/  pip install --no-cache-dir horovod==0.19.5
```
Then after the building finished, the output of the command `horovodrun --check-build`  is 
```sh
Horovod v0.19.5:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [ ] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [ ] Gloo
```
Seems that the `RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.` error does not appear again.
