### ISSUE TITLE
'NoneType' not iterable when running with Gloo on LSF

### ISSUE THREAD

**Issue by fclingen** [horovod/horovod#2891]
1. Horovod version: 0.21.3
2. CUDA version: 10.2.89
3. NCCL version: 2.7.8
4. Python version: 3.8

Running a Gloo build of Horovod on an system that uses LSF for workload management crashes while generating the following stacktrace:

`2021-05-04 09:48:20.881897: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 728, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 682, in run_controller
    gloo_run()
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/launch.py", line 719, in gloo_run_fn
    driver_ip = network.get_driver_ip(nics)
  File "/p/home/fmoore/anaconda3/envs/tf24_prob/lib/python3.8/site-packages/horovod/runner/util/network.py", line 98, in get_driver_ip
    iface = list(nics)[0]
TypeError: 'NoneType' object is not iterable`

If I comment out lines 232 and 233 in horovod/runner/driver/driver_service.py, this error goes away (though as suggested in the comments of driver_service.py, job start is considerable slow).  Gloo does not seem to function without interface discovery.

**Comment by chongxiaoc** [comment]
yep, `gloo` cannot detect available nics on your system.
What's output of `ifconfig` on the  failed node?
`nic` discovery is nothing magic but calling `net_if_addrs()`, what a plain run of that?
