### ISSUE TITLE
Key Error: 'ib0'

### ISSUE THREAD

**Issue by TXacs** [horovod/horovod#2929]
**Environment:**
1. Framework: pytorch
2. Framework version:1.8.0
3. Horovod version:0.21.3
4. MPI version: mpich 3.0.4
5. CUDA version: 10.1
6. NCCL version:
7. Python version:
8. Spark / PySpark version: 
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

when I run `horovodrun -np 1 --start-timeout=180 --min-np 1 --max-np 3 --host-discovery-script ./discover_hosts.sh python -u pytorch_mnist_elastic.py `, I got the following error

**Bug report:**
Traceback (most recent call last):
  File "/home/test/dat01/txacs/anaconda3/envs/py36/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/launch.py", line 756, in _run
    return _run_elastic(args)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/launch.py", line 666, in _run_elastic
    gloo_run_elastic(settings, env, args.command)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 336, in gloo_run_elastic
    launch_gloo_elastic(command, exec_command, settings, env, get_common_interfaces, rendezvous)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 303, in launch_gloo_elastic
    server_ip = network.get_driver_ip(nics)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/util/network.py", line 100, in get_driver_ip
    for addr in net_if_addrs()[iface]:
KeyError: 'ib0'
Launching horovod task function was not successful:

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/util/threads.py", line 58, in fn_execute
    res = fn(*arg[:-1])
  File "/home/test/dat01/txacs/anaconda3/envs/py36/lib/python3.6/site-packages/horovod/runner/driver/driver_service.py", line 87, in _exec_command
    os._exit(exit_code)
TypeError: an integer is required (got type NoneType)

Launching horovod task function was not successful:

Please help me, thanks!

**Comment by chongxiaoc** [comment]
I think gloo doesn't support infiniband `ib0`

**Comment by chongxiaoc** [comment]
Apparently, your system doesn't have a nic which belongs to `AF_INET `. so below check is failing.

`https://github.com/horovod/horovod/blob/b21897366ae9f9a9258225defb9cfaf2e2a469f6/horovod/runner/util/network.py#L100`

**Comment by TXacs** [comment]
> Apparently, your system doesn't have a nic which belongs to `AF_INET `. so below check is failing.
> 
> https://github.com/horovod/horovod/blob/b21897366ae9f9a9258225defb9cfaf2e2a469f6/horovod/runner/util/network.py#L100

Thanks ！
