### ISSUE TITLE
Spark Horovod: what():  HTTP request failed

### ISSUE THREAD

**Issue by HongW2019** [horovod/horovod#2955]
**Environment:**
1. Framework:  PyTorch
2. Framework version:  1.8.1
3. Horovod version: 0.22.0
4. MPI version: none
5. CUDA version: none
6. NCCL version: none
7. Python version: 3.7.10
8. Spark / PySpark version: 3.0.0
9. Ray version: none
10. OS and version: CentOS Linux release 7.6.1810 (Core)
11. GCC version:  7.3.0
12. CMake version: 3.18.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
This issue #2746  looks similar 

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
I am running a Spark cluster with Hadoop+Yarn on 2 nodes: 1master+1worker
I compiled Horovod with the following command:
```
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_MXNET=1 HOROVOD_WITH_GLOO=1 pip install --no-cache-dir horovod[tensorflow,keras,pytorch,mxnet,spark]
```
Then I run what Horovod repo has offered Spark [example](https://github.com/horovod/horovod/blob/v0.22.0/examples/spark/pytorch/pytorch_spark_mnist.py) with PyTorch.
```
 python pytorch_spark_mnist.py -num-proc 4 --master yarn --epochs 1 
```
The exception is:

```
2021-06-07 12:19:19.999299: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Mon Jun  7 11:51:57 2021[1]<stderr>:[2021-06-07 11:51:57.963853: E /tmp/pip-install-s04s9x1l/horovod_dec38af3351c4b6299f67ee18a371ab0/horovod/common/gloo/http_store.cc:96] HTTP GET request failed too many times, aborting. See exception message above.
Mon Jun  7 11:51:57 2021[1]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
Mon Jun  7 11:51:57 2021[1]<stderr>:  what():  HTTP request failed.
Mon Jun  7 11:51:57 2021[2]<stderr>:[2021-06-07 11:51:57.959365: E /tmp/pip-install-s04s9x1l/horovod_dec38af3351c4b6299f67ee18a371ab0/horovod/common/gloo/http_store.cc:96] HTTP GET request failed too many times, aborting. See exception message above.
Mon Jun  7 11:51:57 2021[2]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
Mon Jun  7 11:51:57 2021[2]<stderr>:  what():  HTTP request failed.
Mon Jun  7 11:51:58 2021[0]<stderr>:[2021-06-07 11:51:58. 44421: E /tmp/pip-install-s04s9x1l/horovod_dec38af3351c4b6299f67ee18a371ab0/horovod/common/gloo/http_store.cc:96] HTTP GET request failed too many times, aborting. See exception message above.
Mon Jun  7 11:51:58 2021[0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
Mon Jun  7 11:51:58 2021[0]<stderr>:  what():  HTTP request failed.
Mon Jun  7 11:51:57 2021[3]<stderr>:[2021-06-07 11:51:57.879517: E /tmp/pip-install-s04s9x1l/horovod_dec38af3351c4b6299f67ee18a371ab0/horovod/common/gloo/http_store.cc:96] HTTP GET request failed too many times, aborting. See exception message above.
Mon Jun  7 11:51:57 2021[3]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
Mon Jun  7 11:51:57 2021[3]<stderr>:  what():  HTTP request failed.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/runner.py", line 140, in run_spark
    result = procs.mapPartitionsWithIndex(mapper).collect()
  File "/opt/Beaver/spark/python/pyspark/rdd.py", line 889, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/opt/Beaver/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/Beaver/spark/python/pyspark/sql/utils.py", line 98, in deco
    return f(*a, **kw)
  File "/opt/Beaver/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 3 cancelled part of cancelled job group horovod.spark.run.0
        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2023)
        at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1919)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleJobGroupCancelled$4(DAGScheduler.scala:931)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:930)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2172)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:752)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2093)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2133)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
        at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
        at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:168)
        at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)


Traceback (most recent call last):
  File "pytorch_spark_mnist.py", line 120, in <module>
    torch_model = torch_estimator.fit(train_df).setOutputCols(['label_prob'])
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/opt/Beaver/spark/python/pyspark/ml/base.py", line 129, in fit
    return self._fit(dataset)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 81, in _fit
    backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/torch/estimator.py", line 285, in _fit_on_prepared_data
    env={})
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/common/backend.py", line 85, in run
    **self._kwargs)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/runner.py", line 284, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/runner.py", line 155, in _launch_job
    settings.verbose)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/runner/launch.py", line 706, in run_controller
    gloo_run()
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/runner.py", line 152, in <lambda>
    run_controller(use_gloo, lambda: gloo_run(settings, nics, driver, env, stdout, stderr),
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/spark/gloo_run.py", line 67, in gloo_run
    launch_gloo(command, exec_command, settings, nics, {}, server_ip)
  File "/root/miniconda2/envs/ai_platform/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 271, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 1
Exit code: 134
```

**Comment by qianchenghao** [comment]
I encounter the same issue when using horovodrun

**Comment by HongW2019** [comment]
@Gazelle  any suggestion on this issue?

**Comment by HongW2019** [comment]
@tgaddair  Could you please give any suggestions on what might be happening here?
