### ISSUE TITLE
can not run "horovodrun -np 4 -H localhost:4 python keras_mnist_advanced.py" inside horovod container

### ISSUE THREAD

**Issue by jeff-yajun-liu** [horovod/horovod#2983]
System: 8 A100 PCIe NVIDIA GPU
CUDA: 11.2
Driver: 460.27.04
OS: Ubuntu 18.04.4 LTS

Run following cmd as horovod instructions:  
docker pull horovod/horovod
docker run -it imageID
#example/keras horovodrun -np 4 -H localhost:4 python keras_mnist_advanced.py

getting following Errors, please help!

2021-06-15 00:52:36.479715: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-06-15 00:52:38.200811: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-06-15 00:52:38.223588: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,2]<stderr>:2021-06-15 00:52:38.223589: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,3]<stderr>:2021-06-15 00:52:38.223610: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "./keras/keras_mnist_advanced.py", line 3, in <module>
[1,0]<stderr>:    import keras
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,0]<stderr>:    from . import initializers
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,0]<stderr>:    populate_deserializable_objects()
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,0]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,0]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "./keras/keras_mnist_advanced.py", line 3, in <module>
[1,2]<stderr>:    import keras
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,2]<stderr>:    from . import initializers
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,2]<stderr>:    populate_deserializable_objects()
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,2]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,2]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "./keras/keras_mnist_advanced.py", line 3, in <module>
[1,1]<stderr>:    import keras
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,1]<stderr>:    from . import initializers
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,1]<stderr>:    populate_deserializable_objects()
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,1]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,1]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "./keras/keras_mnist_advanced.py", line 3, in <module>
[1,3]<stderr>:    import keras
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,3]<stderr>:    from . import initializers
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,3]<stderr>:    populate_deserializable_objects()
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,3]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,3]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5508,1],2]
  Exit code:    1

**Comment by Tixxx** [comment]
@jeff-yajun-liu  can you try [this](https://github.com/tensorflow/tensorflow/issues/38012#issuecomment-629761550) ? seems to be related to tf build.

**Comment by LeLe9821** [comment]
You can see this [https://github.com/youdao-ai/SRNet/issues/4](url)  ，It may help you

**Comment by LeLe9821** [comment]
I think you should update horovod version ,you can see this issue [https://github.com/horovod/horovod/issues/774](url) it may help you.

**Comment by LeLe9821** [comment]
I think you should update horovod version ,you can see this issue https://github.com/horovod/horovod/issues/774 it may help you.

**Comment by aflyhorse** [comment]
The [latest horovod/horovod image](https://hub.docker.com/layers/horovod/horovod/latest/images/sha256-b38cc9f0bc59beb94f13eaa48af251933d2c2c0e1d43393d9c8f8e0ce7c438ad) still cannot smoothly run the example command. Output is:

```
root@xxxx:/horovod/examples/keras# horovodrun -np 4 -H localhost:4 python keras_mnist_advanced.py 
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "keras_mnist_advanced.py", line 28, in <module>
[1,2]<stderr>:    config = tf.ConfigProto()
[1,2]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "keras_mnist_advanced.py", line 28, in <module>
[1,0]<stderr>:    config = tf.ConfigProto()
[1,0]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "keras_mnist_advanced.py", line 28, in <module>
[1,3]<stderr>:    config = tf.ConfigProto()
[1,3]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "keras_mnist_advanced.py", line 28, in <module>
[1,1]<stderr>:    config = tf.ConfigProto()
[1,1]<stderr>:AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10753,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

I used ```import tf.compat.v1 as tf``` to replace ```import tf```, and used ```keras.utils.np_utils.to_categorical``` to replace ```keras.utils.to_categorical```, and use ```import tensorflow.keras``` to replace ```import keras```, ... and it is still popping out more errors, so I gave up.
