### ISSUE TITLE
Segmentation fault when using horovod

### ISSUE THREAD

**Issue by lingvisa** [horovod/horovod#2985]
**Environment:**
1. Framework: Tensorflow 1.14.0
2. Horovod version: 0.19.5
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 
7. Python version: 2.7

10. OS and version: Ubuntu 18.04
11. GCC version: 7.5
12. CMake version: 3.12.2

I found a similar but different question below, but it doesn't solve my issue:
https://github.com/horovod/horovod/issues/1341

I run the command as follows with Bert multiple-gpu training:
```
horovodrun -np 2 \
    -H localhost:2 \
    python mgpu_run_classifier.py \
    --task_name=mz \
    --do_train=true \
```
The error message is below:
```
Tue Jun 15 12:25:58 2021[0]<stderr>:I0615 12:25:58.330488 139989861238592 mgpu_run_classifier_varcat.py:494] Writing example 10000 of 99999
Tue Jun 15 12:25:59 2021[1]<stderr>:Segmentation fault (core dumped)
Tue Jun 15 12:25:59 2021[0]<stderr>:terminate called after throwing an instance of 'gloo::IoException'
Tue Jun 15 12:25:59 2021[0]<stderr>:  what():  [/tmp/pip-install-lYNgmj/horovod/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [127.0.0.1]:13952: Connection reset by peer
Process 1 exit with status code 139.
Tue Jun 15 12:26:11 2021[0]<stderr>:Aborted (core dumped)
Process 0 exit with status code 134.
Traceback (most recent call last):
  File "/data4/congmin/minicondap38/envs/py2/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/runner.py", line 723, in run_commandline
    _run(args)
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/runner.py", line 656, in _run
    _launch_job(args, remote_host_names, settings, nics, command)
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/runner.py", line 717, in _launch_job
    args.verbose)
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/runner.py", line 694, in run_controller
    gloo_run()
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/runner.py", line 706, in gloo_run_fn
    gloo_run(settings, remote_host_names, nics, env, driver_ip, command)
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/gloo_run.py", line 312, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/data4/congmin/minicondap38/envs/py2/lib/python2.7/site-packages/horovod/run/gloo_run.py", line 304, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 1
Exit code: 139

```

**Comment by chongxiaoc** [comment]
`em2` is not the nic on your system.
Use `ifconfig` to check available nics on your system.

**Comment by LeLe9821** [comment]
For this  "Please use tf.compat.v1.global_variables", I think the example version you use was warn.you can see this (https://www.tensorflow.org/api_docs/python/tf/all_symbols)  。
