### ISSUE TITLE
"work-dir" parameter doesn't work in Spark_Keras_mnist example

### ISSUE THREAD

**Issue by wjxiz1992** [horovod/horovod#2988]
**Environment:**
1. Framework: TensorFlow
2. Framework version:  2.5.0
3. Horovod version: 0.22.1
4. MPI version: 4.0.2
5. CUDA version: 11.2
6. NCCL version: 2.9.9
7. Python version: 3.8.8
8. Spark / PySpark version: 3.1.2
9. Ray version: /
10. OS and version: Ubuntu 20.04
11. GCC version: 9.3
12. CMake version: 3.18.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

when installing Horovod+TensorFlow and set up Spark, run

``` bash
python keras_spark_mnist.py --master spark://10.19.183.124:7077 --num-proc 1 --work-dir /home/allxu/Desktop/gitlab/hvd-spark/work-dir --num-epoch 1
```
The python file is the [one in the example folder](https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py)

Error message:
```
Wed Jun 16 17:42:16 2021[1,0]<stderr>:2021-06-16 17:42:16.262808: I tensorflow/core/profiler/rpc/client/capture_profile.cc:251] Creating directory: /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16Dumped tool data for xplane.pb to /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16/allxu-pc.xplane.pb
Wed Jun 16 17:42:16 2021[1,0]<stderr>:Dumped tool data for overview_page.pb to /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16/allxu-pc.overview_page.pb
Wed Jun 16 17:42:16 2021[1,0]<stderr>:Dumped tool data for input_pipeline.pb to /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16/allxu-pc.input_pipeline.pb
Wed Jun 16 17:42:16 2021[1,0]<stderr>:Dumped tool data for tensorflow_stats.pb to /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16/allxu-pc.tensorflow_stats.pb
Wed Jun 16 17:42:16 2021[1,0]<stderr>:Dumped tool data for kernel_stats.pb to /tmp/tmpn_eenlao/logs/train/plugins/profile/2021_06_16_17_42_16/allxu-pc.kernel_stats.pb
Wed Jun 16 17:42:16 2021[1,0]<stderr>:
Wed Jun 16 17:42:16 2021[1,0]<stderr>:WARNING:tensorflow:Callback method `on_train_batch_begin` is slow compared to the batch time (batch time: 0.0027s vs `on_train_batch_begin` time: 0.0534s). Check your callbacks.
Wed Jun 16 17:42:16 2021[1,0]<stderr>:WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0027s vs `on_train_batch_end` time: 0.0309s). Check your callbacks.
423/423 [==============================]Wed Jun 16 17:42:17 2021[1,0]<stdout>: - 5s 5ms/step - loss: 1.0698 - accuracy: 0.8546Jun 16 17:42:17 2021[1,0]<stdout>:Wed Jun 16 17:42:17 2021[1,0]<stdout>:>:
Wed Jun 16 17:42:17 2021[1,0]<stderr>:2021-06-16 17:42:17.921864: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Wed Jun 16 17:42:18 2021[1,0]<stderr>:Traceback (most recent call last):
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    return _run_code(code, main_globals, None,
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    exec(code, run_globals)
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    result = fn(*args, **kwargs)
Wed Jun 16 17:42:18 2021[1,0]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/keras/remote.py", line 262, in train
Wed Jun 16 17:42:18 2021[1,0]<stderr>:    with open(ckpt_file, 'rb') as f:
Wed Jun 16 17:42:18 2021[1,0]<stderr>:IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpn_eenlao/checkpoint'

```

When I check my work-dir, I can see files like `intermediate_train_data.0` and `intermediate_train_data.0_cached_metadata.pkl`.

**Comment by chongxiaoc** [comment]
What's your tensorflow version?
I run with `TENSORFLOW=1.15.3` and it works for me.

`(hvd-py3.7) chongxiaoc@chongxiaoc-C02DL7WPMD6R keras % python keras_spark_mnist.py --num-proc 1 --work-dir /tmp/keras_test --epochs 1`

However, `TENSORFLOW=2.4.1` fails in checkpoint part with similar error as above, without using `--work-dir`:

`python keras_spark_mnist.py --num-proc 1 --epochs 1`

```
Mon Jun 21 12:48:25 2021[1,0]<stderr>:2021-06-21 12:48:25.279175: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Mon Jun 21 12:48:26 2021[1,0]<stderr>:Traceback (most recent call last):
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    "__main__", mod_spec)
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    exec(code, run_globals)
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/horovod-0.22.1-py3.7-macosx-11-x86_64.egg/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/horovod-0.22.1-py3.7-macosx-11-x86_64.egg/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/horovod-0.22.1-py3.7-macosx-11-x86_64.egg/horovod/spark/task/__init__.py", line 61, in task_exec
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    result = fn(*args, **kwargs)
Mon Jun 21 12:48:26 2021[1,0]<stderr>:  File "/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/horovod-0.22.1-py3.7-macosx-11-x86_64.egg/horovod/spark/keras/remote.py", line 260, in train
Mon Jun 21 12:48:26 2021[1,0]<stderr>:    with open(ckpt_file, 'rb') as f:
Mon Jun 21 12:48:26 2021[1,0]<stderr>:IsADirectoryError: [Errno 21] Is a directory: '/var/folders/9f/bljm3hhd1gl4nygln5md7npw0000gp/T/tmp8safvqkd/checkpoint'
```

@tgaddair Are you aware this issue for `tensorflow2`?

**Comment by chongxiaoc** [comment]
It looks like the spark keras estimator is only expected to support tensorflow1?
Unit tests are skipped for tensorflow2
https://github.com/horovod/horovod/blob/master/test/integration/test_spark_keras.py#L75

**Comment by wjxiz1992** [comment]
Thanks for the information!
But from the mnist example, https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py#L80-L83
it seems it is supporting TensorFlow2? unclear on this part.

**Comment by chongxiaoc** [comment]
> Thanks for the information!
> But from the spark mnist example, https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py#L80-L83
> it seems it is supporting TensorFlow2? unclear on this part.

I cannot run it successfully with Tensorflow2 locally.

**Comment by wjxiz1992** [comment]
I just noticed Horovod utilizes h5py of version `2.10.0`, while my TensorFlow is `2.5.0` that requires `h5py-3.1.0`. Can that be the cause?

**Comment by chongxiaoc** [comment]
I'm using `h5py  2.10.0`.

**Comment by chongxiaoc** [comment]
Some history for `h5py` and `tf`: https://github.com/h5py/h5py/issues/1732

**Comment by szuccato** [comment]
Any update on this? I'm facing the same `IsADirectoryError` issue when calling `fit` on an `horovod.spark.keras.KerasEstimator`. I'm using tensorflow `2.4.1` and horovod `0.22.1`. Thanks.

**Comment by chongxiaoc** [comment]
The reason is for `TF2`, checkpoint is a folder instead of a single file.
We need to do similar things to here: https://github.com/horovod/horovod/blob/master/horovod/spark/keras/remote.py#L261

Let me draft a PR and try.
