### ISSUE TITLE
  Imported target "MPI::MPI_CXX" includes non-existent path

### ISSUE THREAD

**Issue by Yiltan** [horovod/horovod#2998]
Hello,

I am having some issues installing horovod with MPI, would anybody be able to give any suggestions? I have attached my setup below.

Thanks,
Yiltan

**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.15.2
3. Horovod version: v0.20.3
4. MPI version: MVAPICH2-GDR
5. CUDA version: 10.1.2436. NCCL version: n/a
7. Python version: 3.7
8. Spark / PySpark version: n/a
9. Ray version: n/a
10. OS and version: Red Hat 
11. GCC version: 8.4.0
12. CMake version: 3.16.3

**Install Script**

```
IBM_REPO="https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/"

# Create the enviroment
conda create -y python=3.7 --prefix=$(pwd)/.conda/envs/horovod_tf/
eval "$(conda shell.bash hook)"
conda activate .conda/envs/horovod_tf/
conda install -y -c $IBM_REPO tensorflow-gpu==1.15.2 keras Pillow


# Horovod variables
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITHOUT_GLOO=1
export HOROVOD_CUDA_HOME=$CUDA_HOME
export HOROVOD_GPU_OPERATIONS=MPI
export HOROVOD_WITH_MPI=1

cd packages/horovod
python setup.py install
```

**Output**

```running clean
removing 'build/temp.linux-ppc64le-3.7' (and everything under it)
running install
running bdist_egg
running egg_info
writing horovod.egg-info/PKG-INFO
writing dependency_links to horovod.egg-info/dependency_links.txt
writing entry points to horovod.egg-info/entry_points.txt
writing requirements to horovod.egg-info/requires.txt
writing top-level names to horovod.egg-info/top_level.txt
reading manifest file 'horovod.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '.eggs'
warning: no previously-included files found matching 'third_party/eigen/Eigen/src/IterativeSolvers/*'
warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/FFT'
warning: no previously-included files found matching 'third_party/eigen/unsupported/Eigen/MPRealSupport'
warning: no previously-included files found matching 'third_party/eigen/doc/PreprocessorDirectives.dox'
warning: no previously-included files found matching 'third_party/eigen/doc/UsingIntelMKL.dox'
warning: no previously-included files found matching 'third_party/eigen/doc/SparseLinearSystems.dox'
warning: no previously-included files found matching 'third_party/eigen/COPYING.GPL'
warning: no previously-included files found matching 'third_party/eigen/COPYING.LGPL'
warning: no previously-included files found matching 'third_party/eigen/COPYING.README'
writing manifest file 'horovod.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-ppc64le/egg
running install_lib
running build_py
running build_ext
-- Could not find CCache. Consider installing CCache to speed up compilation.
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /opt/base/gcc/9.3.0/bin/g++
-- Check for working CXX compiler: /opt/base/gcc/9.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build architecture flags: 
-- Using command /project/.conda/envs/horovod_tf/bin/python
CMake Error in /project/packages/horovod/build/temp.linux-ppc64le-3.7/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_CXX" includes non-existent path

    "/usr/tce/packages/cuda/cuda-10.1.243/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in /project/packages/horovod/build/temp.linux-ppc64le-3.7/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_CXX" includes non-existent path

    "/usr/tce/packages/cuda/cuda-10.1.243/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error at /opt/base/cmake/3.16.3/share/cmake-3.16/Modules/FindMPI.cmake:1194 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /opt/base/cmake/3.16.3/share/cmake-3.16/Modules/FindMPI.cmake:1245 (_MPI_try_staged_settings)
  /opt/base/cmake/3.16.3/share/cmake-3.16/Modules/FindMPI.cmake:1505 (_MPI_check_lang_works)
  CMakeLists.txt:131 (find_package)


-- Configuring incomplete, errors occurred!
See also "/project/packages/horovod/build/temp.linux-ppc64le-3.7/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 193, in <module>
    'horovodrun = horovod.runner.launch:run_commandline'
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/project/.conda/envs/horovod_tf/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 89, in build_extensions
    cwd=self.build_temp)
  File "/project/.conda/envs/horovod_tf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/project/packages/horovod', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/project/packages/horovod/build/lib.linux-ppc64le-3.7', '-DPYTHON_EXECUTABLE:FILEPATH=/project/mvapich-gdr/.conda/envs/horovod_tf/bin/python']' returned non-zero exit status 1.
```

**Comment by Yiltan** [comment]
I noticed that things worked with an older version of Horovod (v0.19.0) and use `git bisect` and determined that this bug occurs at the following commit #1949. 

@romerojosh would you have any thoughts onto why the new versions of Horovod have this issue?

```e4554de96100f5a0e8686cd41cf99a6fe8a71e62 is the first bad commit
commit e4554de96100f5a0e8686cd41cf99a6fe8a71e62
Author: romerojosh <joshr@nvidia.com>
Date:   Mon Aug 17 14:54:51 2020 -0700

    Add support for gradient_predivide_factor and averaging in Horovod backend. (#1949)
    
    Signed-off-by: Josh Romero <joshr@nvidia.com>

:100644 100644 9619819608b3d5ab809f6756d1390f3ee7bc7f40 861d2be39442b405e4eb9e297383777338e3db79 M	Jenkinsfile.ppc64le
:100644 100644 3c7fd6f5330584e8bb502c29f420b11fb136c832 f900969b46b2ac43ca8318cc356ad3d1c629c36d M	MANIFEST.in
:040000 040000 0832607e44d87f363ce4ae2d4768b81dcfd6f19e ff1617ca324516cecfe6058621e934fbc3a66b49 M	docs
:040000 040000 b922e226a86f10c937c71d07ccec1edd6be2b54c c28a86b774f9e70743dceb232b4d22942fa27915 M	examples
:040000 040000 c4264cc647c27c3b0221a53a9399f98a3c14ea9d 7c9b4eaf6c60160cbf10ff2c17d6397bfb06b6dc M	horovod
:100644 100644 ff705d118b74a179bf41f34397bf42b505546a36 7a968cf5a34f0ad0015dd498d20a17e7aa7fc59d M	setup.py
:040000 040000 01b269f0ed7ee8c368e84829076b0b41b06cb10e d1862fdb0a3b882f378a2bb71cf39e5999bd2980 M	test```

**Comment by romerojosh** [comment]
It looks like your build environment is unable to locate CUDA headers. See this error message in your original log:
```
  Imported target "MPI::MPI_CXX" includes non-existent path

    "/usr/tce/packages/cuda/cuda-10.1.243/include
```
Can you check to make sure that path exists?

#1949 is the first commit to show this installation issue because it is the one that introduced CUDA compilation dependencies in Horovod.
