### ISSUE TITLE
Horovod cannot support dynamic system environment variables when using Spark as backend

### ISSUE THREAD

**Issue by wjxiz1992** [horovod/horovod#3005]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TensorFlow
2. Framework version: 2.5.0
3. Horovod version: 0.22.1
4. MPI version: 4.0.2
5. CUDA version: 11.2
6. NCCL version: 2.9.9
7. Python version: 3.8.5
8. Spark / PySpark version: 3.1.1
9. Ray version:
10. OS and version: Ubuntu 20.04
11. GCC version: 9.3
12. CMake version: 3.18.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? 
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**

Environment: Spark Standalone mode, with 4 GPU equipped. 

According to https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark3_rossmann.py#L398 , since the TF1 API has been changed in TF2, I tried to use `os.environ['CUDA_VISIBLE_DEVICES']` to control visible GPU devices for TF. 
But put this code inside train_fn doesn't work. TF2 is still able to detect all 4 GPUs no matter which number I pass to `CUDA_VISIBLE_DEVICES`. 

Another thing I noticed is, the default environment vars are not passed to [mpi_run,](https://github.com/horovod/horovod/blob/master/horovod/spark/mpi_run.py#L23) . I print this env, and there's nothing. so I have to pass env to spark.run API manually.

**Comment by romerojosh** [comment]
The issue is that you are setting `CUDA_VISIBLE_DEVICES` _after_ you are importing TF. If you want this to work, the env var needs to be set before. 
With that said, is there are specific reason you are using `CUDA_VISIBLE_DEVICES` env var to restrict visibility to a single device, rather than what we do in the examples with `tf.config.experimental.set_visible_devices`?: https://github.com/horovod/horovod/blob/b1af36a4f933f4ebf74ba6962f473b09c17576cd/examples/tensorflow2/tensorflow2_keras_mnist.py#L19-L27

**Comment by wjxiz1992** [comment]
@romerojosh Hi, thanks for the reply!
For the code position, I'm still confused. For _importing TF_, I assume your refer to the tensorflow import statement, is it? So I tried the following code
```
import os
import tensorflow as tf
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
```
returns `E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

while 
```
import os
import tensorflow as tf
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
```
returns `[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')]`

That makes me wonder, if TF is initialized when `hvd.init()` ? But even if that's the case, I still cannot set the env var before it because I actually need the `hvd.rank()` which should be after `hvd.init()`. 

For the specific reason, yes, I am prototyping a demo to replace Petastorm with GPU accelerated data loader. When I use the code you mentioned above, I got the following error: (a little bit long, thanks for patience)
```
Fri Jun 25 10:15:15 2021[1,1]<stderr>:Traceback (most recent call last):
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    return _run_code(code, main_globals, None,
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    exec(code, run_globals)
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    result = fn(*args, **kwargs)
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/e2e_train/./main.py", line 206, in train_fn
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    train_tensor_x = cudf_to_tensor(gdf_x)
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/e2e_train/./main.py", line 187, in cudf_to_tensor
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    x = tf.experimental.dlpack.from_dlpack(dlpack)
Fri Jun 25 10:15:15 2021[1,1]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/tensorflow/python/dlpack/dlpack.py", line 66, in from_dlpack
Fri Jun 25 10:15:15 2021[1,1]<stderr>:    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)
Fri Jun 25 10:15:15 2021[1,1]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: GPU:1 unknown device.
Fri Jun 25 10:15:15 2021[1,3]<stderr>:Traceback (most recent call last):
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    return _run_code(code, main_globals, None,
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    exec(code, run_globals)
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    result = fn(*args, **kwargs)
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/e2e_train/./main.py", line 206, in train_fn
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    train_tensor_x = cudf_to_tensor(gdf_x)
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/e2e_train/./main.py", line 187, in cudf_to_tensor
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    x = tf.experimental.dlpack.from_dlpack(dlpack)
Fri Jun 25 10:15:15 2021[1,3]<stderr>:  File "/home/allxu/miniconda3/lib/python3.8/site-packages/tensorflow/python/dlpack/dlpack.py", line 66, in from_dlpack
Fri Jun 25 10:15:15 2021[1,3]<stderr>:    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)
Fri Jun 25 10:15:15 2021[1,3]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: GPU:3 unknown device.
```
It is said that, _TF reindexes your GPUs to 0 no matter what the number is on the device_ that make it happen. 
NVTabular is using a [wrapper_script](https://github.com/NVIDIA/NVTabular/blob/main/examples/multi-gpu-movielens/hvd_wrapper.sh) to deal with this problem. But my case is with Spark, I cannot use a script. So I have to do it by python code.

**Comment by romerojosh** [comment]
Thanks for the example. Seems I was mistaken on where TF initializes GPUs. For your use case, instead of using `hvd.rank()`, which requires calling `hvd.init()`, seems like maybe you can instead set `os.environ['CUDA_VISIBLE_DEVICES'] = os.environ['OMPI_COMM_WORLD_LOCAL_RANK']` before doing anything with TF or Horovod?

In general though, you should aim to write code that does not depend on masking GPUs with `CUDA_VISIBLE_DEVICES` to work properly.

**Comment by wjxiz1992** [comment]
Yes, I got your point. My case is for Spark, I haven't found a _code_ way to do so. Then it seems I got blocked here. I'm now checking the spark call chain to see if I have any chance to hack.
