### ISSUE TITLE
CMake Error in horovod/torch/CMakeLists.txt:     Target "pytorch" requires the language dialect "CXX14" , but CMake does not     know the compile flags to use to enable it.

### ISSUE THREAD

**Issue by Junzh821** [horovod/horovod#3027]
**Environment:**
1. Framework: (PyTorch,)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

-- Configuring done
  CMake Error in horovod/torch/CMakeLists.txt:
    Target "pytorch" requires the language dialect "CXX14" , but CMake does not
    know the compile flags to use to enable it.
  
  
  -- Generating done
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3j8y4qov/horovod_155b0d6aeac74d1899be1b6ff9cb8742/setup.py", line 199, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-3j8y4qov/horovod_155b0d6aeac74d1899be1b6ff9cb8742/setup.py", line 95, in build_extensions
      cwd=cmake_build_dir)
    File "/home/xx/.conda/envs/dalle_test/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-3j8y4qov/horovod_155b0d6aeac74d1899be1b6ff9cb8742', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-3j8y4qov/horovod_155b0d6aeac74d1899be1b6ff9cb8742/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE:FILEPATH=/home/xx/.conda/envs/dalle_test/bin/python3.7']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for horovod

**Comment by maxhgerlach** [comment]
Hi @Junzh821, 
could you fill out the OS, tool and package versions in the environment section of the issue template? Something is probably amiss there on your system. Also, what steps did you follow exactly to install Horovod?
