### ISSUE TITLE
use torch amp with horovod failed

### ISSUE THREAD

**Issue by syyxsxx** [horovod/horovod#3160]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.8.1
3. Horovod version:0.22.1

hi, i use torch amp with horovod failed, the error:
```
AssertionError: optimizer.zero_grad() was called after loss.backward() but before optimizer.step() or optimizer.synchronize(). This is prohibited as it can cause a race condition.
Traceback (most recent call last):
  File "pytorch/imagenet/main.py", line 626, in <module>
    main()
  File "pytorch/imagenet/main.py", line 239, in main
    main_worker(args.gpu, ngpus_per_node, args, train_dataset, val_loader,
  File "pytorch/imagenet/main.py", line 389, in main_worker
    efdl_train(state, args, train_sampler, optimizer, model, criterion,
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/efdl/common/controller.py", line 15, in wrapper
    return func(state, *args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/efdl/backend/horovod/torch/base.py", line 37, in wrapper
    return func(state, *args, **kwargs)
  File "pytorch/imagenet/main.py", line 442, in efdl_train
    optimizer.zero_grad()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 329, in zero_grad
    raise AssertionError("optimizer.zero_grad() was called after loss.backward() "
```
this is my code
```
with amp.autocast(enabled=True):
    # compute output
    output = model(images)
    loss = criterion(output, target)
  
    # compute gradient and do SGD step
    optimizer.zero_grad()
    scaler.scale(loss).backward()
    optimizer.synchronize() 
    with optimizer.skip_synchronize():
        scaler.step(optimizer)
        scaler.update()

```

**Comment by syyxsxx** [comment]
when i put the optimizer.synchronize() before optimizer.zero_grad(), it does not has the error but got the nan loss

**Comment by syyxsxx** [comment]
finally i use this code solve my  problem 
```
optimizer.zero_grad()
output = model(images)
loss = criterion(output, target)

# compute gradient and do SGD step
scaler.scale(loss).backward()
optimizer.synchronize()
with optimizer.skip_synchronize():
    scaler.step(optimizer)
    scaler.update()

```
#1089
