### ISSUE TITLE
Spark with Horovod fails with py4j.protocol.Py4JJavaError

### ISSUE THREAD

**Issue by aakash-sharma** [horovod/horovod#3162]
**Environment:**
1. Framework: TensorFlow, Keras
2. Framework version: tensorflow-2.4.3, keras-2.6.0
3. Horovod version: horovod-0.22.1
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: python-3.6.9
8. Spark / PySpark version: Spark-3.1.2
9. Ray version:
10. OS and version: Ubuntu 18
11. GCC version:  gcc-7.5.0
12. CMake version: cmake-3.21.2

When running the sample script keras_spark_rossmann_estimator.py, spark app fails at model training with the following error:

Total params: 2,715,603
Trainable params: 2,715,567
Non-trainable params: 36
__________________________________________________________________________________________________
/home/cc/.local/lib/python3.6/site-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
num_partitions=80
writing dataframes
train_data_path=file:///tmp/intermediate_train_data.0
val_data_path=file:///tmp/intermediate_val_data.0
train_partitions=76===========================================>   (15 + 1) / 16]
val_partitions=8                                                                
/home/cc/.local/lib/python3.6/site-packages/horovod/spark/common/util.py:479: FutureWarning: The 'field_by_name' method is deprecated, use 'field' instead
  metadata, avg_row_size = make_metadata_dictionary(train_data_schema)
train_rows=806871
val_rows=37467
Exception in thread Thread-3:                                       (0 + 8) / 8]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/runner.py", line 140, in run_spark
    result = procs.mapPartitionsWithIndex(mapper).collect()
  File "/usr/local/lib/python3.6/dist-packages/pyspark/rdd.py", line 949, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/cc/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.6/dist-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/cc/.local/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 63 cancelled part of cancelled job group horovod.spark.run.0
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:2154)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleJobGroupCancelled$4(DAGScheduler.scala:1048)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:1047)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2407)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:180)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Traceback (most recent call last):
  File "keras_spark_rossmann_estimator.py", line 397, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales_output'])
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/local/lib/python3.6/dist-packages/pyspark/ml/base.py", line 161, in fit
    return self._fit(dataset)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 81, in _fit
    backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/keras/estimator.py", line 317, in _fit_on_prepared_data
    env=env)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/common/backend.py", line 85, in run
    **self._kwargs)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/runner.py", line 284, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/runner.py", line 155, in _launch_job
    settings.verbose)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/runner/launch.py", line 706, in run_controller
    gloo_run()
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/runner.py", line 152, in <lambda>
    run_controller(use_gloo, lambda: gloo_run(settings, nics, driver, env, stdout, stderr),
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/spark/gloo_run.py", line 67, in gloo_run
    launch_gloo(command, exec_command, settings, nics, {}, server_ip)
  File "/home/cc/.local/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 271, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 255

**Comment by aakash-sharma** [comment]
Since I wasnt able to get this to work, I tried horovod with MPI. I installed MPI 4.0.0 and reinstalled horovod. But now horovod simply hangs. The toy example with spark doesnt work too and it simple hangs. Following is the code that I tried:

```
>>> def fn(magic_number):
...     import horovod.torch as hvd
...     hvd.init()
...     print('Hello, rank = %d, local_rank = %d, size = %d, local_size = %d, magic_number = %d' % (hvd.rank(), hvd.local_rank(), hvd.size(), hvd.local_size(), magic_number))
...     return hvd.rank()
... 
>>> import horovod.spark
>>> horovod.spark.run(fn, args=(42,))
```
I also tried horovod (MPI controller) without spark by running some examples and it seems to work fine.

**Comment by aakash-sharma** [comment]
I tried the fix in [https://github.com/horovod/horovod/issues/1222](url) using OPAL_PREFIX to build horovod but that didnt fix the hang issue either.
