### ISSUE TITLE
how to run horovod from different gpus

### ISSUE THREAD

**Issue by AlexYoung757** [horovod/horovod#3164]
I have installed the GPU version of horovod with NCCL 2 on my local machines.

When I run the following command in the terminal:
horovodrun -np 2 -H 192.168.1.181:1 192.168.1.182:1 python TF_MNIST.py

192.168.1.181 and 192.168.1.181 have 2 NVIDIA GPUs.

I get the following error:
Traceback (most recent call last):
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 722, in run_commandline
    _run(args)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 712, in _run
    return _run_static(args)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 573, in _run_static
    _launch_job(args, settings, nics, command)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 688, in _launch_job
    args.verbose)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 661, in run_controller
    gloo_run()
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/launch.py", line 677, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 271, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 234, in launch_gloo
    host_alloc_plan = get_host_assignments(hosts, settings.num_proc)
  File "/home/appadmin/anaconda3/envs/env_horovod_tf/lib/python3.6/site-packages/horovod/runner/common/util/hosts.py", line 135, in get_host_assignments
    .format(min_np, world_size))
ValueError: Requested more processes (2) than there are available slots (1)

when i run one gpus，it works well. the command:
horovodrun -np 1 -H 192.168.1.181:1 python TF_MNIST.py

what's wrong with this. how to solve it? anyone who can help me

**Comment by chongxiaoc** [comment]
`horovodrun -np 2 -H 192.168.1.181:1,192.168.1.182:1 python TF_MNIST.py`

**Comment by AlexYoung757** [comment]
> `horovodrun -np 2 -H 192.168.1.181:1,192.168.1.182:1 python TF_MNIST.py`

please look at my description. i have tried to do this command.but it doesnot work

**Comment by maxhgerlach** [comment]
@AlexYoung757, your command line misses the comma.
