### ISSUE TITLE
KeyError: 'CSM_ALLOCATION_ID' for LSF task with hovorod

### ISSUE THREAD

**Issue by Cloudac7** [horovod/horovod#3166]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.3.0
3. Horovod version: 0.22.3
4. MPI version: Intel MPI 2017.5.239
5. CUDA version: 10.1
6. NCCL version: 2.8.3
7. Python version: 3.8
8. Spark / PySpark version: None
9. Ray version: None
10. OS and version: CentOS 7.4
11. GCC version: 7.4.0
12. CMake version: 3.18.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? 
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

All have been checked.

**Bug report:**
When task with horovod submitted by LSF, it soon fell down and error shown below raised, showing the lack of `CSM_ALLOCATION_ID` in environment. It seems that CSM is not enabled on our host from official document and unfortunately I have no permission to enable it.

```
Traceback (most recent call last):
  File "/share/apps/deepmd/2.0/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/share/apps/deepmd/2.0/lib/python3.8/site-packages/horovod/runner/launch.py", line 770, in run_commandline
    _run(args)
  File "/share/apps/deepmd/2.0/lib/python3.8/site-packages/horovod/runner/launch.py", line 743, in _run
    for host in lsf.LSFUtils.get_compute_hosts())
  File "/share/apps/deepmd/2.0/lib/python3.8/site-packages/horovod/runner/util/lsf.py", line 75, in get_compute_hosts
    return LSFUtils.get_allocation_info()["compute_nodes"]
  File "/share/apps/deepmd/2.0/lib/python3.8/site-packages/horovod/runner/util/lsf.py", line 43, in get_allocation_info
    lsf_allocation_id = os.environ["CSM_ALLOCATION_ID"].strip()
  File "/share/apps/deepmd/2.0/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CSM_ALLOCATION_ID'
```

**Comment by YinhuiYi** [comment]
Have you solve the ploblem? I also encountered this problem. I think it relates to the type of hosts in lsf. The official CSM configuration is for IBM Power, but my hosts are mostly x86_64.

**Comment by rajnichahal** [comment]
Hello, I am facing the same issue. Please let me know if the bug is resolved. Thanks

**Comment by Cloudac7** [comment]
> Hello, I am facing the same issue. Please let me know if the bug is resolved. Thanks

Sorry for no solution yet. Once solution found out, please also put it here. Thanks.
