### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by behome** [horovod/horovod#3223]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Ubuntu 18.04.3 LTS
11. GCC version:
12. CMake version:
13. Docker version: 19.03.13, build 4484c46d9d

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
I want to build my own docker image through the Dockerfile provided in the project. But error happend. I changed nothing.

```
Running setup.py install for horovod: started
    Running command /usr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4j_mtnr3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4j_mtnr3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hn4z8609/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/horovod
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.7/horovod
    creating build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/sync_batch_norm.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/functions.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/optimizer.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/torch
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/sync_batch_norm.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/functions.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/gradient_aggregation.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/elastic.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/gradient_aggregation_eager.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    creating build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/exceptions.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/process_sets.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/util.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/basics.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/elastic.py -> build/lib.linux-x86_64-3.7/horovod/common
    creating build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/utils.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/runner.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/strategy.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/__init__.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/ray_logger.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/elastic.py -> build/lib.linux-x86_64-3.7/horovod/ray
    copying horovod/ray/worker.py -> build/lib.linux-x86_64-3.7/horovod/ray
    creating build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/gloo_run.py -> build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/conf.py -> build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/runner.py -> build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/mpi_run.py -> build/lib.linux-x86_64-3.7/horovod/spark
    creating build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/compression.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/functions.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    creating build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/elastic.py -> build/lib.linux-x86_64-3.7/horovod/keras
    creating build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/elastic.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    creating build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/run_task.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/gloo_run.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/js_run.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/task_fn.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/launch.py -> build/lib.linux-x86_64-3.7/horovod/runner
    copying horovod/runner/mpi_run.py -> build/lib.linux-x86_64-3.7/horovod/runner
    creating build/lib.linux-x86_64-3.7/horovod/data
    copying horovod/data/data_loader_base.py -> build/lib.linux-x86_64-3.7/horovod/data
    copying horovod/data/__init__.py -> build/lib.linux-x86_64-3.7/horovod/data
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.7/horovod/torch/elastic
    copying horovod/torch/elastic/state.py -> build/lib.linux-x86_64-3.7/horovod/torch/elastic
    copying horovod/torch/elastic/sampler.py -> build/lib.linux-x86_64-3.7/horovod/torch/elastic
    copying horovod/torch/elastic/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/elastic
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/elastic.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    creating build/lib.linux-x86_64-3.7/horovod/spark/torch
    copying horovod/spark/torch/remote.py -> build/lib.linux-x86_64-3.7/horovod/spark/torch
    copying horovod/spark/torch/util.py -> build/lib.linux-x86_64-3.7/horovod/spark/torch
    copying horovod/spark/torch/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/torch
    copying horovod/spark/torch/estimator.py -> build/lib.linux-x86_64-3.7/horovod/spark/torch
    creating build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/rendezvous.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/rsh.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/host_discovery.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    creating build/lib.linux-x86_64-3.7/horovod/spark/data_loaders
    copying horovod/spark/data_loaders/pytorch_data_loaders.py -> build/lib.linux-x86_64-3.7/horovod/spark/data_loaders
    copying horovod/spark/data_loaders/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/data_loaders
    creating build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/legacy.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/datamodule.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/remote.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/util.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    copying horovod/spark/lightning/estimator.py -> build/lib.linux-x86_64-3.7/horovod/spark/lightning
    creating build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/params.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/serialization.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/store.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/util.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/constants.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/cache.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/_namedtuple_fix.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/backend.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    copying horovod/spark/common/estimator.py -> build/lib.linux-x86_64-3.7/horovod/spark/common
    creating build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/gloo_exec_fn.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/task_info.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    creating build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/tensorflow.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/remote.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/optimizer.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/util.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/bare.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    copying horovod/spark/keras/estimator.py -> build/lib.linux-x86_64-3.7/horovod/spark/keras
    creating build/lib.linux-x86_64-3.7/horovod/runner/driver
    copying horovod/runner/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/runner/driver
    copying horovod/runner/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/driver
    creating build/lib.linux-x86_64-3.7/horovod/runner/http
    copying horovod/runner/http/http_server.py -> build/lib.linux-x86_64-3.7/horovod/runner/http
    copying horovod/runner/http/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/http
    copying horovod/runner/http/http_client.py -> build/lib.linux-x86_64-3.7/horovod/runner/http
    creating build/lib.linux-x86_64-3.7/horovod/runner/common
    copying horovod/runner/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/common
    creating build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/network.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/lsf.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/streams.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/remote.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/threads.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/cache.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    copying horovod/runner/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/util
    creating build/lib.linux-x86_64-3.7/horovod/runner/task
    copying horovod/runner/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/runner/task
    copying horovod/runner/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/task
    creating build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/registration.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/rendezvous.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/settings.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/discovery.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/constants.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/driver.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    copying horovod/runner/elastic/worker.py -> build/lib.linux-x86_64-3.7/horovod/runner/elastic
    creating build/lib.linux-x86_64-3.7/horovod/runner/common/service
    copying horovod/runner/common/service/task_service.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/service
    copying horovod/runner/common/service/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/service
    copying horovod/runner/common/service/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/service
    creating build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/env.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/network.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/tiny_shell_exec.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/hosts.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/settings.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/codec.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/host_hash.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/secret.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/timeout.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    copying horovod/runner/common/util/config_parser.py -> build/lib.linux-x86_64-3.7/horovod/runner/common/util
    running build_ext
    -- Could not find CCache. Consider installing CCache to speed up compilation.
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Build architecture flags: -mf16c -mavx -mfma
    -- Using command /usr/bin/python
    -- Found MPI_CXX: /usr/local/lib/libmpi.so (found version "3.1")
    -- Found MPI: TRUE (found version "3.1")
    -- Could NOT find NVTX (missing: NVTX_INCLUDE_DIR)
    CMake Error at CMakeLists.txt:265 (add_subdirectory):
      add_subdirectory given source "third_party/gloo" which is not an existing
      directory.


    CMake Error at CMakeLists.txt:267 (target_compile_definitions):
      Cannot specify compile definitions for target "gloo" which is not built by
      this project.


    Tensorflow_LIBRARIES := -L/usr/local/lib/python3.7/dist-packages/tensorflow -l:libtensorflow_framework.so.2
    -- Found Tensorflow: -L/usr/local/lib/python3.7/dist-packages/tensorflow -l:libtensorflow_framework.so.2 (found suitable version "2.5.0", minimum required is "1.15.0")
    -- Found Pytorch: 1.8.1+cu102 (found suitable version "1.8.1+cu102", minimum required is "1.2.0")
    -- Found Mxnet: /usr/local/lib/python3.7/dist-packages/mxnet/libmxnet.so (found suitable version "1.8.0", minimum required is "1.4.0")
    CMake Error at CMakeLists.txt:327 (file):
      file COPY cannot find "/tmp/pip-req-build-4j_mtnr3/third_party/gloo".


    CMake Error at CMakeLists.txt:331 (add_subdirectory):
      The source directory

        /tmp/pip-req-build-4j_mtnr3/third_party/compatible_gloo

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:332 (target_compile_definitions):
      Cannot specify compile definitions for target "compatible_gloo" which is
      not built by this project.


    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    /tmp/pip-req-build-4j_mtnr3/horovod/mxnet/TF_FLATBUFFERS_INCLUDE_PATH
       used as include directory in directory /tmp/pip-req-build-4j_mtnr3/horovod/mxnet
    /tmp/pip-req-build-4j_mtnr3/horovod/tensorflow/TF_FLATBUFFERS_INCLUDE_PATH
       used as include directory in directory /tmp/pip-req-build-4j_mtnr3/horovod/tensorflow
    /tmp/pip-req-build-4j_mtnr3/horovod/torch/TF_FLATBUFFERS_INCLUDE_PATH
       used as include directory in directory /tmp/pip-req-build-4j_mtnr3/horovod/torch

    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-4j_mtnr3/build/temp.linux-x86_64-3.7/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4j_mtnr3/setup.py", line 211, in <module>
        'horovodrun = horovod.runner.launch:run_commandline'
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-req-build-4j_mtnr3/setup.py", line 99, in build_extensions
        cwd=cmake_build_dir)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-4j_mtnr3', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-req-build-4j_mtnr3/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python']' returned non-zero exit status 1.
    Running setup.py install for horovod: finished with status 'error'
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4j_mtnr3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4j_mtnr3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hn4z8609/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/horovod Check the logs for full command output.
The command '/bin/bash -cu python setup.py sdist &&     bash -c "HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install --no-cache-dir -v $(ls /horovod/dist/horovod-*.tar.gz)[spark,ray]" &&     horovodrun --check-build' returned a non-zero code: 1

```

**Comment by Tixxx** [comment]
when you cloned the repo, did you recursively clone all submodules? i.e git clone --recursive
If you don't plan to use gloo, you can add HOROVOD_WITHOUT_GLOO=1 to your pip install command.
