### ISSUE TITLE
Permission denied (publickey,password) Docker with multiple machine

### ISSUE THREAD

**Issue by xml94** [horovod/horovod#3236]
**Environment:**
1. Framework: PyTorch
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version: 11.2
6. NCCL version:
7. Python version: 
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I try to use horovod docker for multiple machines (2 machines in fact).
following this page: https://github.com/horovod/horovod/blob/master/docs/docker.rst

1)  ssh
I create the ssh following this page: http://www.linuxproblem.org/art_9.html
after making the ssh, using ssh user@IP in both machine is ok (do not need password).
I save the ssh in this directory: ~/.ssh

2) install the docker image
I installed horovod:horovod:latest docker image. (10 Oct, 2021).

3) check the single machine: ok
command: nvidia-docker run -it --shm-size=50g --network=host -v ~/.ssh:/root/.ssh horovod/horovod:latest
command: horovodrun --network=host -np 4 -H 113.198.60.xx:4 python pytorch/pytorch_mnist.py

4) not ok with multiple machines:
machine1: user: oem, IP: 113.198.60.xx
machine2: user: oem, IP: 113.198.60.xx
(both machine install horovod/horovod:latest)
step 1 in machine1, nvidia-docker run -it --shm-size=50g --network=host -v ~/.ssh:/root/.ssh horovod/horovod:latest
step 2 in machine 2: nvidia-docker run -it --shm-size=50g --network=host -v  ~/.ssh:/root/.ssh horovod/horovod:latest bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
step 3 in machine 1: horovodrun --network=host -np 4 -H 113.198.60.xx:4 -p 12345 python pytorch/pytorch_mnist.py
Output in machine 1:

    ssh not successful for host 113.198.60.xx:
    root@113.198.60.xx: Permission denied (publickey,password).
    
    Traceback (most recent call last):
      File "/usr/local/bin/horovodrun", line 8, in <module>
        sys.exit(run_commandline())
      File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 770, in run_commandline
        _run(args)
      File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 760, in _run
        return _run_static(args)
      File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 587, in _run_static
        raise RuntimeError('could not connect to some hosts via ssh')
    RuntimeError: could not connect to some hosts via ssh

**Comment by siddhantsahu** [comment]
@xml94 did you find any solution to this? I am also facing this issue.

**Comment by EmreOzkose** [comment]
I have same issue

**Comment by EmreOzkose** [comment]
I think it is not a bug, this issue is explained [here](https://github.com/horovod/horovod/blob/master/docs/running.rst#failures-due-to-ssh-issues), but I don't know how to get rid of this. My servers require password to connect
