### ISSUE TITLE
Error on KerasEstimator for Spark

### ISSUE THREAD

**Issue by WaterKnight1998** [horovod/horovod#3256]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TensorFlow
2. Framework version: 2.6.0
3. Horovod version: 0.22.1
7. Python version: 3.8.10
8. Spark / PySpark version: 3.2.0

**Bug report:**
I have an spark dataframe with two columns: `content`, binary content of x images loaded with Databricks Spark Autoloader for Cloud Files and `class`, another column with long format and class value.

I defined the `KerasEstimator` to use a `transformation_fn`, this function loads the binary data of content and returns it as numpy array of shape (256,256,3), the class value is returned as it is.

When I trigger the fit method of the model I get this error:

```
[1,0]<stderr>:
[1,0]<stderr>:Function call stack:
[1,0]<stderr>:train_function
[1,0]<stderr>:
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[1,2]<stderr>:2021-11-02 08:50:51.469193: W tensorflow/core/framework/op_kernel.cc:1669] OP_REQUIRES failed at cast_op.cc:121 : Unimplemented: Cast string to float is not supported
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1,2]<stderr>:    return _run_code(code, main_globals, None,
[1,2]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1,2]<stderr>:    exec(code, run_globals)
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
[1,2]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
[1,2]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[1,2]<stderr>:    result = fn(*args, **kwargs)
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/horovod/spark/keras/remote.py", line 242, in train
[1,2]<stderr>:    history = fit(model, train_data, val_data, steps_per_epoch,
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/horovod/spark/keras/util.py", line 40, in fn
[1,2]<stderr>:    return model.fit(
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
[1,2]<stderr>:    tmp_logs = self.train_function(iterator)
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
[1,2]<stderr>:    result = self._call(*args, **kwds)
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
[1,2]<stderr>:    return self._stateless_fn(*args, **kwds)
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
[1,2]<stderr>:    return graph_function._call_flat(
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
[1,2]<stderr>:    return self._build_call_outputs(self._inference_function.call(
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
[1,2]<stderr>:    outputs = execute.execute(
[1,2]<stderr>:  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
[1,2]<stderr>:    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
[1,2]<stderr>:tensorflow.python.framework.errors_impl.UnimplementedError:  Cast string to float is not supported
[1,2]<stderr>:	 [[node model/Cast (defined at databricks/python/lib/python3.8/site-packages/horovod/spark/keras/util.py:40) ]] [Op:__inference_train_function_11503]
```

**Comment by chongxiaoc** [comment]
might be related? https://stackoverflow.com/questions/52517298/tensorflow-error-unimplementederror-cast-string-to-float-is-not-supported-l
String type is not supported?

**Comment by WaterKnight1998** [comment]
> might be related? https://stackoverflow.com/questions/52517298/tensorflow-error-unimplementederror-cast-string-to-float-is-not-supported-l String type is not supported?

@chongxiaoc  I solved it Unrolling Image in Spark Dataframe and removing `preprocess_fn`. Horovod or PetaStorm is reshaping the array into the correct .

I saw it in this issue: https://github.com/horovod/horovod/issues/2104
