### ISSUE TITLE
Containerized horovod

### ISSUE THREAD

**Issue by dimanzt** [horovod/horovod#3281]
Hi all,
I have a problem running horovod using containerized environment.
I'm running it on the host and trying to run on one single machine first:

```
horovodrun -np 4 -H localhost:4 python keras_mnist_advanced.py
2021-11-18 00:12:14.851827: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-11-18 00:12:17.677706: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,2]<stderr>:2021-11-18 00:12:17.677699: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-18 00:12:17.678337: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,3]<stderr>:2021-11-18 00:12:17.715725: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "keras_mnist_advanced.py", line 3, in <module>
[1,1]<stderr>:    import keras
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,1]<stderr>:    from . import initializers
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,1]<stderr>:    populate_deserializable_objects()
[1,1]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,1]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,1]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "keras_mnist_advanced.py", line 3, in <module>
[1,2]<stderr>:    import keras
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,2]<stderr>:    from . import initializers
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,2]<stderr>:    populate_deserializable_objects()
[1,2]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,2]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,2]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "keras_mnist_advanced.py", line 3, in <module>
[1,0]<stderr>:    import keras
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,0]<stderr>:    from . import initializers
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,0]<stderr>:    populate_deserializable_objects()
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,0]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,0]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "keras_mnist_advanced.py", line 3, in <module>
[1,3]<stderr>:    import keras
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 20, in <module>
[1,3]<stderr>:    from . import initializers
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
[1,3]<stderr>:    populate_deserializable_objects()
[1,3]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
[1,3]<stderr>:    generic_utils.populate_dict_with_module_objects(
[1,3]<stderr>:AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[44863,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

Any idea on how to fix this?

**Comment by maxhgerlach** [comment]
Hi @dimanzt, 

I think you are experiencing the same symptoms seen in https://github.com/horovod/horovod/issues/2983, so I am closing this issue as a duplicate.

Are you sure you are running the latest release of Horovod?
