### ISSUE TITLE
Error when running example script `pytorch_spark_mnist.py`

### ISSUE THREAD

**Issue by jizezhang** [horovod/horovod#3298]
Hello, I was trying to run the [example file](https://github.com/horovod/horovod/blob/master/examples/spark/pytorch/pytorch_spark_mnist.py) `pytorch_spark_mnist.py` on a spark cluster from a cloud provider, but got the following error. The script runs fine inside the `horovod-cpu` image locally. Could someone point to me what could be the cause? Thank you.
```writing dataframes
train_data_path=file:///opt/spark/work-dir/intermediate_train_data.0
val_data_path=file:///opt/spark/work-dir/intermediate_val_data.0
train_partitions=18
Traceback (most recent call last):
  File "/tmp/spark-f2a912ef-52c7-443e-adad-873d31030415/pytorch_spark_mnist.py", line 124, in <module>
    torch_model = torch_estimator.fit(train_df).setOutputCols(['label_prob'])
  File "/opt/dataflow/python/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/opt/dataflow/python/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 77, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/dataflow/python/lib/python3.6/site-packages/horovod/spark/common/util.py", line 737, in prepare_data
    num_partitions, num_processes, verbose)
  File "/opt/dataflow/python/lib/python3.6/site-packages/horovod/spark/common/util.py", line 648, in _get_or_create_dataset
    saved_file_list = _get_spark_df_saved_file_list(train_data_path)
  File "/opt/dataflow/python/lib/python3.6/site-packages/horovod/spark/common/util.py", line 594, in _get_spark_df_saved_file_list
    return list(spark_session.read.parquet(saved_path)._jdf.inputFiles())
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 353, in parquet
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 134, in deco
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.;
```

**Comment by Brycebywang** [comment]
I'm having the same problem
