### ISSUE TITLE
RayExecutor does not work with Horovod Settings

### ISSUE THREAD

**Issue by EnricoMi** [horovod/horovod#3413]
The documentation of RayExecutor says `You can use a standard Horovod Settings object` for the `settings` parameter, but this fails with:

```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    executor.start()
  File "/home/enrico/Work/git/articles/venv/lib/python3.8/site-packages/horovod/ray/runner.py", line 284, in start
    return self._maybe_call_ray(self.driver.start, **kwargs_)
  File "/home/enrico/Work/git/articles/venv/lib/python3.8/site-packages/horovod/ray/runner.py", line 360, in _maybe_call_ray
    return driver_func(**kwargs)
  File "/home/enrico/Work/git/articles/venv/lib/python3.8/site-packages/horovod/ray/runner.py", line 452, in start
    self.workers, node_workers = self.strategy.create_workers()
  File "/home/enrico/Work/git/articles/venv/lib/python3.8/site-packages/horovod/ray/strategy.py", line 174, in create_workers
    pg_timeout=self.settings.placement_group_timeout_s)
AttributeError: 'Settings' object has no attribute 'placement_group_timeout_s'
```

Here is some code reproducing the issue:
```python
from horovod.ray import RayExecutor
from horovod.runner.common.util.settings import Settings
import ray

ray.init()
settings = Settings()
executor = RayExecutor(settings, num_workers=1)
executor.start()
```
As the error says, the Horovod `Settings` class does not contain the `placement_group_timeout_s` attribute.

**Comment by ashahab** [comment]
@EnricoMi thanks for catching this. The issue is that the default value of placement_group_timeout_s is not being applied. I'll try to take a look this week.
