### ISSUE TITLE
Horovod 0.21.0 with Pytorch and GPU support installation error

### ISSUE THREAD

**Issue by Snoeprol** [horovod/horovod#3414]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.10.1+cu102
3. Horovod version: 0.21.0
4. MPI version: mpirun (Open MPI) 3.1.3
5. CUDA version: CUDA/10.1.243
6. NCCL version:  NCCL/2.5.6-CUDA-10.1.243
7. Python version: Python 3.8.8
8. Spark / PySpark version: 3.2.0
9. Ray version: .
10. OS and version:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

11. GCC version: 8.3.0
12. CMake version: 3.13.4

**Bug report:**
I am trying to install horvod 0.21.0. I used the following steps:

```
HOROVOD_WITH_PYTORCH=1
HOROVOD_WITH_TENSORFLOW=0
HOROVOD_WITH_MXNET=0
HOROVOD_WITHOUT_TENSORFLOW=1
HOROVOD_WITHOUT_MXNET=1
HOROVOD_WITHOUT_PYTORCH=0
HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod[pytorch]==0.21.0
```

This produces the error:

```
  Another error similar to the one below -> 

      cd /scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8/third_party/compatible_gloo/gloo && /usr/bin/cmake -P CMakeFiles/compatible_gloo.dir/cmake_clean_target.cmake
      cd /scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8/third_party/compatible_gloo/gloo && /usr/bin/cmake -E cmake_link_script CMakeFiles/compatible_gloo.dir/link.txt --verbose=1
      /usr/bin/ar qc libcompatible_gloo.a  CMakeFiles/compatible_gloo.dir/algorithm.cc.o CMakeFiles/compatible_gloo.dir/allgather.cc.o CMakeFiles/compatible_gloo.dir/allgatherv.cc.o CMakeFiles/compatible_gloo.dir/allreduce.cc.o CMakeFiles/compatible_gloo.dir/allreduce_local.cc.o CMakeFiles/compatible_gloo.dir/alltoall.cc.o CMakeFiles/compatible_gloo.dir/alltoallv.cc.o CMakeFiles/compatible_gloo.dir/barrier.cc.o CMakeFiles/compatible_gloo.dir/broadcast.cc.o CMakeFiles/compatible_gloo.dir/context.cc.o CMakeFiles/compatible_gloo.dir/gather.cc.o CMakeFiles/compatible_gloo.dir/gatherv.cc.o CMakeFiles/compatible_gloo.dir/reduce.cc.o CMakeFiles/compatible_gloo.dir/scatter.cc.o CMakeFiles/compatible_gloo.dir/types.cc.o CMakeFiles/compatible_gloo.dir/common/logging.cc.o CMakeFiles/compatible_gloo.dir/common/linux.cc.o CMakeFiles/compatible_gloo.dir/mpi/context.cc.o CMakeFiles/compatible_gloo.dir/rendezvous/context.cc.o CMakeFiles/compatible_gloo.dir/rendezvous/file_store.cc.o CMakeFiles/compatible_gloo.dir/rendezvous/hash_store.cc.o CMakeFiles/compatible_gloo.dir/rendezvous/prefix_store.cc.o CMakeFiles/compatible_gloo.dir/rendezvous/store.cc.o CMakeFiles/compatible_gloo.dir/transport/address.cc.o CMakeFiles/compatible_gloo.dir/transport/buffer.cc.o CMakeFiles/compatible_gloo.dir/transport/context.cc.o CMakeFiles/compatible_gloo.dir/transport/device.cc.o CMakeFiles/compatible_gloo.dir/transport/pair.cc.o CMakeFiles/compatible_gloo.dir/transport/unbound_buffer.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/address.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/buffer.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/device.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/loop.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/pair.cc.o CMakeFiles/compatible_gloo.dir/transport/tcp/unbound_buffer.cc.o
      /usr/bin/ranlib libcompatible_gloo.a
      make[2]: Leaving directory '/scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8'
      [ 50%] Linking CXX static library libgloo.a
      cd /scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8/third_party/gloo/gloo && /usr/bin/cmake -P CMakeFiles/gloo.dir/cmake_clean_target.cmake
      [ 50%] Built target compatible_gloo
      cd /scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8/third_party/gloo/gloo && /usr/bin/cmake -E cmake_link_script CMakeFiles/gloo.dir/link.txt --verbose=1
      /usr/bin/ar qc libgloo.a  CMakeFiles/gloo.dir/algorithm.cc.o CMakeFiles/gloo.dir/allgather.cc.o CMakeFiles/gloo.dir/allgatherv.cc.o CMakeFiles/gloo.dir/allreduce.cc.o CMakeFiles/gloo.dir/allreduce_local.cc.o CMakeFiles/gloo.dir/alltoall.cc.o CMakeFiles/gloo.dir/alltoallv.cc.o CMakeFiles/gloo.dir/barrier.cc.o CMakeFiles/gloo.dir/broadcast.cc.o CMakeFiles/gloo.dir/context.cc.o CMakeFiles/gloo.dir/gather.cc.o CMakeFiles/gloo.dir/gatherv.cc.o CMakeFiles/gloo.dir/reduce.cc.o CMakeFiles/gloo.dir/scatter.cc.o CMakeFiles/gloo.dir/types.cc.o CMakeFiles/gloo.dir/common/logging.cc.o CMakeFiles/gloo.dir/common/linux.cc.o CMakeFiles/gloo.dir/mpi/context.cc.o CMakeFiles/gloo.dir/rendezvous/context.cc.o CMakeFiles/gloo.dir/rendezvous/file_store.cc.o CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o CMakeFiles/gloo.dir/rendezvous/prefix_store.cc.o CMakeFiles/gloo.dir/rendezvous/store.cc.o CMakeFiles/gloo.dir/transport/address.cc.o CMakeFiles/gloo.dir/transport/buffer.cc.o CMakeFiles/gloo.dir/transport/context.cc.o CMakeFiles/gloo.dir/transport/device.cc.o CMakeFiles/gloo.dir/transport/pair.cc.o CMakeFiles/gloo.dir/transport/unbound_buffer.cc.o CMakeFiles/gloo.dir/transport/tcp/address.cc.o CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o CMakeFiles/gloo.dir/transport/tcp/context.cc.o CMakeFiles/gloo.dir/transport/tcp/device.cc.o CMakeFiles/gloo.dir/transport/tcp/loop.cc.o CMakeFiles/gloo.dir/transport/tcp/pair.cc.o CMakeFiles/gloo.dir/transport/tcp/unbound_buffer.cc.o
      /usr/bin/ranlib libgloo.a
      make[2]: Leaving directory '/scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8'
      [ 50%] Built target gloo
      make[1]: Leaving directory '/scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/build/temp.linux-x86_64-3.8'
      make: *** [Makefile:130: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/setup.py", line 144, in <module>
          setup(name='horovod',
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/sw/arch/Debian10/EB_production/2021/software/Anaconda3/2021.05/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/home/rooijm/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/scratch/pip-install-c158jwy5/horovod_2bb67489ec2e4bfebb17b533f73b6ca4/setup.py", line 90, in build_extensions
          subprocess.check_call([cmake_bin, '--build', '.'] + cmake_build_args,
        File "/sw/arch/Debian10/EB_production/2021/software/Anaconda3/2021.05/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> horovod

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure. 
```

I can't seem to figure out what I'm doing wrong. The error does not tell me much.

**Comment by Snoeprol** [comment]
I have a link to the full error here:

https://file.io/cU0EBPjNBjn3

**Comment by maxhgerlach** [comment]
Hi @Snoeprol,
you will need to upgrade to Horovod 0.24.0. Older releases are not compatible with your version of PyTorch.
