### ISSUE TITLE
Rank() returns all zero on multi-GPU

### ISSUE THREAD

**Issue by takahh** [horovod/horovod#3469]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4.0
3. Horovod version: 0.23.0
4. MPI version: 3.1.4
5. CUDA version: 11.0.194
6. NCCL version: 2.8.4
7. Python version: 3.6.5
8. Spark / PySpark version:
9. Ray version:
10. OS and version: SuSE Linux ES12 SP2
11. GCC version: 8.3 or 4.8??
12. CMake version: 3.22.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? -
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? -
4. Did you check if you question is answered in the [troubleshooting guide] Yes (https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I am using the university's HPC. Multi nodes and GPUs. I got no error but noticed that the rank() always returns zero in any server in multi-nodes calculations. I cannot know server names in advance, so I did not use -H option. 

Here is the script for submitting a job to the HPC.
<pre><code>
#!/bin/bash
#$ -cwd
#$ -l q_node=2
#$ -l h_rt=1:00:00
#$ -p -4
#$ -N ftest

. /etc/profile.d/modules.sh
source /home/2/18D38035/.bashrc
conda activate myenv
module load python/3.8.3
module load python/3.6.5
module load cuda/11.0.194
#module load cuda/11.2.146
module load nccl/2.8.4
module load intel openmpi
mpirun --version
module load cudnn/8.1
module load tensorflow/2.4.1
module load gcc/8.3

export PATH=$PATH:/home/2/18D38035/.local/bin
export PATH="/gs/hs0/tga-science/kimura/transformer_tape_dnabert/cmake-3.22.2/bin/:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/2/18D38035/.local/"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/gs/hs0/tga-science/kimura/transformer_tape_dnabert:/gs/hs0/tga-science/kimura/transformer_tape_dnabert/anaconda/envs/myenv/x86_64-conda-linux-gnu/lib/"
export PYTHONPATH="$PYTHONPATH:/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod"

python -m pip install --user --upgrade pip
python -m pip install --user --upgrade cmake
python -m pip install --user numpy --upgrade
pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.4.0-cp36-cp36m-manylinux2010_x86_64.whl
alias cmake='/gs/hs0/tga-science/kimura/transformer_tape_dnabert/bin/cmake'
/gs/hs0/tga-science/kimura/transformer_tape_dnabert/anaconda/bin/conda install gcc_linux-64 gxx_linux-64

cd /gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod

HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 NCCL_INCLUDE_DIR=/home/2/18D38035/.local/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/nccl NCCL_LIBRARY=/home/2/18D38035/.local/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/ncclpip install horovod -v -e .

ln -s /home/2/18D38035/.local/lib/libpython3.6m.so.1.0 /gs/hs0/tga-science/kimura/transformer_tape_dnabert/libpython3.6m.a

mpirun -np 2 -npernode 1 -bind-to none -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -mca pml ob1 -mca btl ^openib python /gs/hs0/tga-science/kimura/transformer_tape_dnabert/python/multi_nodes/multi_nodes.py</pre></code>

Thank you!

**Comment by takahh** [comment]
I did but got an error about C library so I chose mpi. Horovodrun looked to have recognized GPU until the error message.  I will try to make it again. Thank you!

**Comment by takahh** [comment]
I ran horovodrun and got Gloo error although I added HOROVOD_WITH_GLOO=1 in the installation from a file

<pre><code>
`gcc(3):ERROR:105: Unable to locate a modulefile for 'gcc/8.3'

==> WARNING: A newer version of conda exists. <==
  current version: 4.11.0
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base -c defaults conda

install: omitting directory 'horovod'
ln: failed to create symbolic link '/gs/hs0/tga-science/kimura/transformer_tape_dnabert/libpython3.6m.a': File exists
2022-03-17 06:27:43.420982: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.s
o.11.0
2022-03-17 06:27:50.023290: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.s
o.11.0
[0]<stderr>:2022-03-17 06:27:53.335672: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
[1]<stderr>:2022-03-17 06:27:53.335674: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
[1]<stderr>:2022-03-17 06:27:56.134493: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices
 not set
[0]<stderr>:2022-03-17 06:27:56.134588: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices
 not set
[0]<stderr>:2022-03-17 06:27:56.135714: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcuda.so.1
[1]<stderr>:2022-03-17 06:27:56.135715: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcuda.so.1
[0]<stderr>:2022-03-17 06:27:56.146677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[0]<stderr>:pciBusID: 0000:87:00.0 name: Tesla P100-SXM2-16GB computeCapability: 6.0
[1]<stderr>:2022-03-17 06:27:56.146742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[0]<stderr>:coreClock: 1.4805GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
[1]<stderr>:pciBusID: 0000:87:00.0 name: Tesla P100-SXM2-16GB computeCapability: 6.0
[0]<stderr>:2022-03-17 06:27:56.146707: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
[1]<stderr>:coreClock: 1.4805GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
[1]<stderr>:2022-03-17 06:27:56.146773: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
[1]<stderr>:2022-03-17 06:27:56.635349: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublas.so.11
[0]<stderr>:2022-03-17 06:27:56.635362: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublas.so.11
[1]<stderr>:2022-03-17 06:27:56.635443: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublasLt.so.11
[0]<stderr>:2022-03-17 06:27:56.635450: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublasLt.so.11
[1]<stderr>:2022-03-17 06:27:56.782076: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcufft.so.10
[0]<stderr>:2022-03-17 06:27:56.782077: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcufft.so.10
[0]<stderr>:2022-03-17 06:27:57.015912: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcurand.so.10
[1]<stderr>:2022-03-17 06:27:57.015911: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcurand.so.10
[1]<stderr>:2022-03-17 06:27:57.385559: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusolver.so.10
[0]<stderr>:2022-03-17 06:27:57.385562: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusolver.so.10
[1]<stderr>:2022-03-17 06:27:57.569623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusparse.so.11
[0]<stderr>:2022-03-17 06:27:57.569622: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusparse.so.11
[1]<stderr>:2022-03-17 06:27:57.576981: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudnn.so.8
[0]<stderr>:2022-03-17 06:27:57.576982: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudnn.so.8
[0]<stderr>:2022-03-17 06:27:57.581602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1]<stderr>:2022-03-17 06:27:57.581631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1]<stderr>:Traceback (most recent call last):
[1]<stderr>:  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/python/multi_nodes/multi_nodes.py", line 30, in <module>
[1]<stderr>:    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
[1]<stderr>:IndexError: list index out of range
[0]<stderr>:2022-03-17 06:27:57.591942: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAP
I Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
[0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[0]<stderr>:2022-03-17 06:27:57.592821: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices
 not set
[0]<stderr>:2022-03-17 06:27:57.594161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[0]<stderr>:pciBusID: 0000:87:00.0 name: Tesla P100-SXM2-16GB computeCapability: 6.0
[0]<stderr>:coreClock: 1.4805GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
[0]<stderr>:2022-03-17 06:27:57.594197: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
[0]<stderr>:2022-03-17 06:27:57.594223: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublas.so.11
[0]<stderr>:2022-03-17 06:27:57.594238: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcublasLt.so.11
[0]<stderr>:2022-03-17 06:27:57.594251: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcufft.so.10
[0]<stderr>:2022-03-17 06:27:57.594273: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcurand.so.10
[0]<stderr>:2022-03-17 06:27:57.594286: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusolver.so.10
[0]<stderr>:2022-03-17 06:27:57.594300: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcusparse.so.11
[0]<stderr>:2022-03-17 06:27:57.594313: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudnn.so.8
[0]<stderr>:2022-03-17 06:27:57.596550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[0]<stderr>:2022-03-17 06:27:57.596589: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library
 libcudart.so.11.0
Traceback (most recent call last):
  File "/home/2/18D38035/.local/bin/horovodrun", line 33, in <module>
    sys.exit(load_entry_point('horovod', 'console_scripts', 'horovodrun')())
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 773, in run_commandline
    _run(args)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 763, in _run
    return _run_static(args)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 619, in _run_static
    _launch_job(args, settings, nics, command)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 736, in _launch_job
    args.verbose)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 709, in run_controller
    gloo_run()
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/launch.py", line 725, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/gloo_run.py", line 298, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/gs/hs0/tga-science/kimura/transformer_tape_dnabert/horovod/horovod/runner/gloo_run.py", line 285, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first pro
cess to do so was:
Process name: 1
Exit code: 1
</code></pre>

**Comment by takahh** [comment]
I think I found out why this happened. I will share the result here when it is done.

**Comment by takahh** [comment]
It was a problem of incomplete installation of horovod. Now it works. Thank you.
