### ISSUE TITLE
Horovod0.24.2 +pytorch 1.10.2 throw unexpected fault

### ISSUE THREAD

**Issue by upwindflys** [horovod/horovod#3472]
**Environment:**
1. Framework:PyTorch
2. Framework version:1.10.2
3. Horovod version:0.24.2
4. MPI version:
5. CUDA version:10.2
6. NCCL version:2.8.4
7. Python version:3.6
8. Spark / PySpark version:
9. Ray version:
10. OS and version:centos7
11. GCC version:7.5
12. CMake version:3.23

**Checklist:**
1. Did you search issues to find if somebody asked this question before? YES
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? NO
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? NO

**Bug report:**
I tried to run the code _https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py_ with command 
```horovodrun -np 2 -H localhost:2 python pytorch_mnist.py```
But an exception occurd.
```python
Process 0 exit with status code 137.
Traceback (most recent call last):
  File "/home/shangyw/virtualenv/torch/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 773, in run_commandline
    _run(args)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 763, in _run
    return _run_static(args)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 619, in _run_static
    _launch_job(args, settings, nics, command)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 736, in _launch_job
    args.verbose)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 709, in run_controller
    gloo_run()
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/launch.py", line 725, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 298, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/shangyw/virtualenv/torch/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 285, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 137

```

**Comment by hashiting** [comment]
I guess you should run it with command "horovodrun -np 2 -H localhost:2 python pytorch_mnist.py" ?

**Comment by upwindflys** [comment]
> I guess you should run it with command "horovodrun -np 2 -H localhost:2 python pytorch_mnist.py" ?

Thanks.I have modified the spelling error.

**Comment by upwindflys** [comment]
I found a solution that reinstall horovod == 0.22.Is there any other tips?

**Comment by EnricoMi** [comment]
I don't quite understand your last message. Did you find a solution or not? What else do you need?
