### ISSUE TITLE
Horovod installation for TF CPU nightly fails with error: no member "tensorflow_gpu_device_info"!

### ISSUE THREAD

**Issue by ashahba** [horovod/horovod#3511]
**Environment:**
1. TensorFlow
2. Framework version: 2.10 nightly
3. Horovod version: 0.24.2 all the way up to tip of master
4. MPI version: 4.0.3
5. CUDA version: N/A this is CPU install
6. NCCL version: N/A
7. Python version: 3.8.10
8. Spark / PySpark version: N/A
9. Ray version: N/A
10. OS and version: Ubuntu 20.04.4 LTS
11. GCC version: 9.4.0
12. CMake version: 3.16.3

While installing any version of Horovod from `0.24.2` all the way up to tip of `master` branch and with the following settings I get:

```
# Install Horovod
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_VERSION=v0.24.2
```

and then:
```
python3 -m pip install git+https://github.com/horovod/horovod.git@${HOROVOD_VERSION}
```

and I'm getting this error during installation:
```
/tmp/pip-req-build-xs138tj2/horovod/common/ops/gloo_operations.h:51:8:   required from here
  /tmp/pip-req-build-xs138tj2/third_party/gloo/gloo/math.h:20:22: warning: comparison of integer expressions of different signedness: â€˜intâ€™ and â€˜size_tâ€™ {aka â€˜long unsigned intâ€™} [-Wsign-compare]
  [ 99%] Building CXX object horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o
  cd /tmp/pip-req-build-xs138tj2/build/temp.linux-x86_64-cpython-38/RelWithDebInfo/horovod/tensorflow && /usr/bin/c++  -DEIGEN_MPL2_ONLY=1 -DHAVE_GLOO=1 -DHAVE_MPI=1 -DTENSORFLOW_VERSION=2010000000 -Dtensorflow_EXPORTS -I/tmp/pip-req-build-xs138tj2/third_party/HTTPRequest/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/assert/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/config/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/core/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/detail/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/iterator/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/lockfree/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/mpl/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/parameter/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/predef/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/preprocessor/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/static_assert/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/type_traits/include -I/tmp/pip-req-build-xs138tj2/third_party/boost/utility/include -I/tmp/pip-req-build-xs138tj2/third_party/lbfgs/include -I/tmp/pip-req-build-xs138tj2/third_party/gloo -I/tmp/pip-req-build-xs138tj2/third_party/flatbuffers/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/local/lib/python3.8/dist-packages/tensorflow/include  -I/usr/local/lib/python3.8/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -DEIGEN_MAX_ALIGN_BYTES=64  -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -O3 -g -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/tensorflow.dir/mpi_ops.cc.o -c /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc: In function â€˜int horovod::tensorflow::{anonymous}::GetDeviceID(tensorflow::OpKernelContext*)â€™:
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc:389:26: error: â€˜class tensorflow::DeviceBaseâ€™ has no member named â€˜tensorflow_gpu_device_infoâ€™; did you mean â€˜tensorflow_accelerator_device_infoâ€™?
         context->device()->tensorflow_gpu_device_info() != nullptr) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
                            tensorflow_accelerator_device_info
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc:390:33: error: â€˜class tensorflow::DeviceBaseâ€™ has no member named â€˜tensorflow_gpu_device_infoâ€™; did you mean â€˜tensorflow_accelerator_device_infoâ€™?
       device = context->device()->tensorflow_gpu_device_info()->gpu_id;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                   tensorflow_accelerator_device_info
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc: At global scope:
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc:384:18: warning: â€˜tensorflow::OpKernelContext* horovod::tensorflow::{anonymous}::TFOpContext::GetKernelContext() constâ€™ defined but not used [-Wunused-function]
   OpKernelContext* TFOpContext::GetKernelContext() const { return context_; }
                    ^~~~~~~~~~~
  /tmp/pip-req-build-xs138tj2/horovod/tensorflow/mpi_ops.cc:293:30: warning: â€˜const tensorflow::Tensor* horovod::tensorflow::{anonymous}::TFTensor::tensor() constâ€™ defined but not used [-Wunused-function]
   const ::tensorflow::Tensor*  TFTensor::tensor() const { return &tensor_; }
                                ^~~~~~~~
  make[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/build.make:453: horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o] Error 1
  make[2]: Leaving directory '/tmp/pip-req-build-xs138tj2/build/temp.linux-x86_64-cpython-38/RelWithDebInfo'
  make[1]: *** [CMakeFiles/Makefile2:443: horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
  make[1]: Leaving directory '/tmp/pip-req-build-xs138tj2/build/temp.linux-x86_64-cpython-38/RelWithDebInfo'
  make: *** [Makefile:130: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-xs138tj2/setup.py", line 166, in <module>
      setup(name='horovod',
    File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build.py", line 136, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-req-build-xs138tj2/setup.py", line 100, in build_extensions
      subprocess.check_call([cmake_bin, '--build', '.'] + cmake_build_args,
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', 'VERBOSE=1']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
```

**Comment by maxhgerlach** [comment]
Thanks for the report @ashahba! I hope #3513 will fix the build with tf-nightly.

**Comment by ashahba** [comment]
Thanks @maxhgerlach 
I'll keep my eyes on that PR.

I can also test it today.

**Comment by ashahba** [comment]
Now that PR is merged, I'm testing the fix now.

**Comment by ashahba** [comment]
This worked like a charm!

Thanks @maxhgerlach 

Closing the ticket now.
