### ISSUE TITLE
Can not run `RayExecutor`

### ISSUE THREAD

**Issue by JiahaoYao** [horovod/horovod#3589]
Code: 

```python
import ray
from horovod.ray import RayExecutor
import horovod.torch as hvd

# Start the Ray cluster or attach to an existing Ray cluster
ray.init()
num_workers = 1

# Start num_workers actors on the cluster
settings = RayExecutor.create_settings(timeout_s=30)
executor = RayExecutor(
    settings, num_workers=num_workers,cpus_per_worker=1, use_gpu=True)

# This will launch `num_workers` actors on the Ray Cluster.
executor.start()

# Using the stateless `run` method, a function can take in any args or kwargs
def simple_fn():
    hvd.init()
    print("hvd rank", hvd.rank())
    return hvd.rank()

# Execute the function on all workers at once
result = executor.run(simple_fn)
print(result)
executor.shutdown()
```

Result: 
```python
2022-06-28 22:05:33,656 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
(BaseHorovodWorker pid=14896) *** SIGSEGV received at time=1656453935 on cpu 0 ***
(BaseHorovodWorker pid=14896) PC: @     0x7f80eff99fcc  (unknown)  horovod::common::(anonymous namespace)::BackgroundThreadLoop()
(BaseHorovodWorker pid=14896)     @     0x7f833f117980       4560  (unknown)
(BaseHorovodWorker pid=14896)     @     0x7f833cbffaa3         24  execute_native_thread_routine
(BaseHorovodWorker pid=14896)     @ ... and at least 4 more frames
(BaseHorovodWorker pid=14896) [2022-06-28 22:05:35,709 E 14896 14934] logging.cc:325: *** SIGSEGV received at time=1656453935 on cpu 0 ***
(BaseHorovodWorker pid=14896) [2022-06-28 22:05:35,709 E 14896 14934] logging.cc:325: PC: @     0x7f80eff99fcc  (unknown)  horovod::common::(anonymous namespace)::BackgroundThreadLoop()
(BaseHorovodWorker pid=14896) [2022-06-28 22:05:35,710 E 14896 14934] logging.cc:325:     @     0x7f833f117980       4560  (unknown)
(BaseHorovodWorker pid=14896) [2022-06-28 22:05:35,710 E 14896 14934] logging.cc:325:     @     0x7f833cbffaa3         24  execute_native_thread_routine
(BaseHorovodWorker pid=14896) [2022-06-28 22:05:35,710 E 14896 14934] logging.cc:325:     @ ... and at least 4 more frames
(BaseHorovodWorker pid=14896) Fatal Python error: Segmentation fault
(BaseHorovodWorker pid=14896) 
2022-06-28 22:05:35,839 WARNING worker.py:1728 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff192c4de9ae2ac15aafc2ab1801000000 Worker ID: 64a4d8791c417ee4cc7d4ea3473dcb4fa6303705700c01ddc8bfd3fa Node ID: 78571af15b4fb6c918265637b8618542b59fd3c7f493a81a0b6b7569 Worker IP address: 10.0.2.180 Worker port: 33549 Worker PID: 14896 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "test_0628.py", line 25, in <module>
    result = executor.run(simple_fn)
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/horovod/ray/runner.py", line 376, in run
    return self._maybe_call_ray(self.adapter.run, **kwargs_)
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/horovod/ray/runner.py", line 421, in _maybe_call_ray
    return driver_func(**kwargs)
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/horovod/ray/runner.py", line 599, in run
    return ray.get(self._run_remote(fn=f))
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/ray/_private/worker.py", line 2176, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: BaseHorovodWorker
        actor_id: 192c4de9ae2ac15aafc2ab1801000000
        pid: 14896
        namespace: acb48abc-7432-420d-923f-2d19a510800c
        ip: 10.0.2.180
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
None
Exception ignored in: <function ActorHandle.__del__ at 0x7f93cce2ef70>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/hd/lib/python3.8/site-packages/ray/actor.py", line 1029, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
```

**Comment by shaowei-su** [comment]
Hey @JiahaoYao , sorry to ping you for an ancient issue. Did you resolve this issue and find a fix? do you mind linking me to the solutions, thanks!
