### ISSUE TITLE
RuntimeError: Horovod detected that one or more processes exited with non-zero status

### ISSUE THREAD

**Issue by Alxe1** [horovod/horovod#3647]
**Environment:**
1. Framework: (TensorFlow, Keras)
2. Framework version:TensorFlow-2.3.0
3. Horovod version:0.25.0
4. MPI version:NA
5. CUDA version:NA
6. NCCL version:NA
7. Python version:3.6.5
8. Spark / PySpark version:2.4.6
9. Ray version:NA
10. OS and version:
11. GCC version:gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
12. CMake version:3.24.0

I run the provided code `https://raw.githubusercontent.com/horovod/horovod/master/examples/spark/keras/keras_spark_rossmann_estimator.py`, It get 
the error:
```
num_partitions=80
writing dataframes
train_data_path=file:///tmp/intermediate_train_data.0
val_data_path=file:///tmp/intermediate_val_data.0
[Stage 344:================================================>      (14 + 2) / 16]train_partitions=76
[Stage 364:>                                                       (0 + 8) / 16]22/08/12 14:15:30 WARN MemoryManager: Total allocation exceeds 95.00% (967,258,919 bytes) of heap memory
Scaling row group sizes to 90.08% for 8 writers
[Stage 364:========================>                               (7 + 8) / 16]22/08/12 14:15:32 WARN MemoryManager: Total allocation exceeds 95.00% (967,258,919 bytes) of heap memory
Scaling row group sizes to 90.08% for 8 writers
[Stage 364:============================>                           (8 + 8) / 16]22/08/12 14:15:32 WARN MemoryManager: Total allocation exceeds 95.00% (967,258,919 bytes) of heap memory
Scaling row group sizes to 90.08% for 8 writers
val_partitions=8                                                                
22/08/12 14:15:34 WARN MemoryManager: Total allocation exceeds 95.00% (967,258,919 bytes) of heap memory
Scaling row group sizes to 90.08% for 8 writers
train_rows=806871
val_rows=37467
[Stage 377:>                                                        (0 + 8) / 8]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/mnt/softwares/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/softwares/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/runner.py", line 142, in run_spark
    result = procs.mapPartitionsWithIndex(mapper).collect()
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 65 cancelled part of cancelled job group horovod.spark.run.0
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1826)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:907)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:907)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:907)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:907)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2081)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:990)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:989)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)


Traceback (most recent call last):
  File "keras_spark_rossmann_estimator.py", line 390, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales_output'])
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/common/estimator.py", line 81, in _fit
    backend, train_rows, val_rows, metadata, avg_row_size, dataset_idx)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/keras/estimator.py", line 277, in _fit_on_prepared_data
    env=self.getBackendEnv())
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/common/backend.py", line 85, in run
    **self._kwargs)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/runner.py", line 290, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr, executable)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/runner.py", line 158, in _launch_job
    settings.verbose)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/runner/launch.py", line 763, in run_controller
    gloo_run()
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/runner.py", line 155, in <lambda>
    run_controller(use_gloo, lambda: gloo_run(executable, settings, nics, driver, env, stdout, stderr),
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/spark/gloo_run.py", line 68, in gloo_run
    launch_gloo(command, exec_command, settings, nics, {}, server_ip)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 287, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 2
Exit code: 139
```

**Comment by Apprisco** [comment]
This is an error with your own code, not horovod. The error occurs whenever horovod detects that one of the runs have errored and completed, and thus kills all other runs as well.
