### ISSUE TITLE
Databricks  Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.

### ISSUE THREAD

**Issue by KrishnanJothi** [horovod/horovod#3712]
Hi,

I am doing masked language modeling training using Horovod in Databricks with a GPU cluster. In the middle of the training after 13 epochs the mentioned error arises. Kindly let me know how to solve this.

Code:
```
def train_one_epoch(model, device, data_loader, optimizer, scheduler, epoch):
    model.train()
    for batch_idx, batch in enumerate(data_loader):
        batch = {key:batch[key].to(device) for key in batch.keys()}
        optimizer.zero_grad()
        loss = model(**batch).loss
        loss.backward()
        optimizer.step()
        scheduler.step()
        if batch_idx % args.log_interval == 0:
          if hvd.rank() == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                  epoch, batch_idx, len(data_loader), 100. * batch_idx / len(data_loader), loss.item()))  
    return loss.item()

def train_hvd(learning_rate):
  
  # Initialize Horovod
  hvd.init()  
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  
  if device.type == 'cuda':
    # Pin GPU to local rank
    torch.cuda.set_device(hvd.local_rank())
  
  # Configure the sampler so that each worker gets a distinct sample of the input dataset
  train_sampler = DistributedSampler(train_dataset, num_replicas=hvd.size(), rank=hvd.rank())
  
  # Use train_sampler to load a different sample of data on each worker
  train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=args.train_batch_size, sampler=train_sampler, collate_fn=data_collator)
 
  # loading the model
  config = AutoConfig.from_pretrained(args.model_name_or_path, return_dict=True)
  model = AutoModelForMaskedLM.from_pretrained(args.model_name_or_path, config = config)
  model = model.to(device)
  
  # Define optimizer
  optimizer = optim.AdamW(model.parameters(), lr=learning_rate)
  
  # Broadcast initial parameters so all workers start with the same parameters
  hvd.broadcast_parameters(model.state_dict(), root_rank=0)
  hvd.broadcast_optimizer_state(optimizer, root_rank=0)
 
  # Wrap the local optimizer with hvd.DistributedOptimizer so that Horovod handles the distributed optimization
  # Horovod: (optional) compression algorithm.
  optimizer = hvd.DistributedOptimizer(optimizer, 
                                       named_parameters=model.named_parameters())
  
  scheduler = get_linear_schedule_with_warmup(optimizer,
                                              num_warmup_steps=steps_per_process // warmup_divider,
                                              num_training_steps=steps_per_process)
 
  for epoch in range(1, args.num_epochs + 1):
    final_loss = train_one_epoch(model, device, train_loader, optimizer, scheduler, epoch)
    # Save checkpoints only on worker 0 to prevent conflicts between workers
    if hvd.rank() == 0:
      save_checkpoint(hvd_log_dir, model, optimizer, epoch, final_loss)
```

Error: 
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1071304970804777> in <module>
      1 hr = HorovodRunner(np=args.np)
----> 2 hr.run(train_hvd, learning_rate=args.lr)

/databricks/.python_edge_libs/sparkdl/utils/instrumentation.py in instrumented(func, self, args, kwargs)
     24                                          self.__class__.__name__))
     25     try:
---> 26         return_val = func(*args, **kwargs)
     27     except Exception:
     28         error_string = traceback.format_exc()

/databricks/.python_edge_libs/sparkdl/horovod/runner.py in run(self, main, **kwargs)
    243 
    244         try:
--> 245             return self._run_program(root_working_dir, pickled_func_str, log_streaming_server_port)
    246         finally:
    247             log_streaming_server.shutdown()

/databricks/.python_edge_libs/sparkdl/horovod/runner.py in _run_program(self, root_working_dir, pickled_func_str, log_streaming_server_port)
    583         try:
    584             num_partitions = mapper.num_partitions
--> 585             partition_bytes = self.sc.parallelize(range(num_partitions), num_partitions) \
    586                 .barrier() \
    587                 .mapPartitions(run_horovod_task) \

/databricks/spark/python/pyspark/rdd.py in collect(self)
    964         # Default path used in OSS Spark / for non-credential passthrough clusters:
    965         with SCCallSiteSync(self.context) as css:
--> 966             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    967         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    968 

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(2, 37) finished unsuccessfully.
ExecutorLostFailure (executor 85 exited unrelated to the running tasks) Reason: Executor decommission.
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3029)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2976)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2970)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2970)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2603)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3235)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3179)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3167)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1152)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2651)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1036)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:419)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1034)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:260)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by EnricoMi** [comment]
Try to find the logs of individual executors, they might provide insides into the underlying issue. This `Py4JJavaError` is a very general errors, saying something went wrong on some executor.
