### ISSUE TITLE
RuntimeError: ncclCommInitRank failed: invalid usage

### ISSUE THREAD

**Issue by Cancerhzc** [horovod/horovod#3752]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
2. Framework version: 1.12.1+cu113
3. Horovod version: 0.26.1
4. MPI version: OpenMPI 4.1.4
5. CUDA version: 11.1
6. NCCL version: 2.7.8-1+cuda11.1
7. Python version: 3.8
8. Spark / PySpark version:  --
9. Ray version:--
10. OS and version: CentOS 7.9
11. GCC version: 4.8.5 / 9.3.1 
12. CMake version: 3.24.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? --
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

Traceback (most recent call last):
[1,1]<stderr>:  File "/home/xxx/anaconda3/envs/mg/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 1253, in synchronize
[1,1]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,1]<stderr>:RuntimeError: ncclCommInitRank failed: invalid usage
[1,1]<stderr>:

**Comment by maxhgerlach** [comment]
What command line did you use to run your training script?

Could you set `NCCL_DEBUG=INFO` and check the full log for additional messages from NCCL?

**Comment by maxhgerlach** [comment]
```
[1,1]<stdout>:slave1:98179:98293 [0] init.cc:525 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 2f000
# ...
[1,0]<stdout>:slave1:98178:98292 [0] init.cc:525 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 2f000
```
Thanks for the logs. These warning stand out to me. Could you check how you pin your GPUs (and compare to example code in `examples/pytorch`)?

> `master:1,slave1:2,slave2:1`

Alternatively, for trouble shooting, have you tried distributing your work load symmetrically, e.g., using just one GPU on each node?

**Comment by Cancerhzc** [comment]
Hi, @maxhgerlach Thank you for your help.
I changed version of CUDA & NCCL & Pytorch and reinstalled horovod.
CUDA version 11.7
nccl version 2.14.3-1+cuda11.7
torch version '1.12.1+cu116'
horovod version 0.26.1

But when  I ran this command `horovodrun -np 4 -H master:1,slave1:2,slave2:1 --mpi-args="-x NCCL_DEBUG=INFO" python pytorch_mnist.py` (This py file is horovod pytorch example)   it showed

```
horovodrun -np 4 -H master:1,slave1:2,slave2:1 --mpi-args="-x NCCL_DEBUG=INFO" python pytorch_mnist.py
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Bootstrap : Using mynet0:192.168.71.30<0>
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO cudaDriverVersion 11070
[1,0]<stdout>:NCCL version 2.14.3+cuda11.7
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO cudaDriverVersion 11070
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO cudaDriverVersion 11070
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO cudaDriverVersion 11070
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Failed to open libibverbs.so[.1]
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO NET/Socket : Using [0]mynet0:192.168.71.30<0>
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Using network Socket
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO Bootstrap : Using mynet0:192.168.71.30<0>
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO Failed to open libibverbs.so[.1]
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO Bootstrap : Using mynet0:192.168.71.31<0>
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO Bootstrap : Using mynet0:192.168.71.32<0>
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO NET/Socket : Using [0]mynet0:192.168.71.30<0>
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO Using network Socket
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO Failed to open libibverbs.so[.1]
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO Failed to open libibverbs.so[.1]
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO NET/Socket : Using [0]mynet0:192.168.71.31<0>
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO Using network Socket
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO NET/Socket : Using [0]mynet0:192.168.71.32<0>
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO Using network Socket
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO Setting affinity for GPU 0 to ff
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO Setting affinity for GPU 0 to ff
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO Setting affinity for GPU 1 to ff00
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Setting affinity for GPU 0 to ff
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 3/-1/-1->1->0
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Channel 00/02 :    0   1   2   3
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Channel 01/02 :    0   1   2   3
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO Trees [0] 1/3/-1->0->-1 [1] 1/-1/-1->0->2
...
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO comm 0x7fa79822ec30 rank 0 nranks 4 cudaDev 0 busId 2f000 - Init COMPLETE
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO comm 0x7f96f0224e30 rank 2 nranks 4 cudaDev 0 busId 6000 - Init COMPLETE
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank 1 nranks 4 cudaDev 1 busId 86000 - Init COMPLETE
[1,0]<stdout>:
[1,0]<stdout>:slave1:126623:126757 [0] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO enqueue.cc:1417 -> 1
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO enqueue.cc:1457 -> 1
[1,0]<stdout>:slave1:126623:126757 [0] NCCL INFO enqueue.cc:1462 -> 1
[1,1]<stdout>:
[1,1]<stdout>:slave1:126624:126758 [1] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1417 -> 1
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1457 -> 1
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1462 -> 1
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO comm 0x7f855c22ce50 rank 3 nranks 4 cudaDev 0 busId 6000 - Init COMPLETE
[1,0]<stdout>:slave1:126623:126841 [0] NCCL INFO [Service thread] Connection closed by localRank 0
[1,1]<stdout>:slave1:126624:126840 [1] NCCL INFO [Service thread] Connection closed by localRank 1
[1,2]<stdout>:
[1,2]<stdout>:master:141585:141605 [0] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO enqueue.cc:1417 -> 1
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO enqueue.cc:1457 -> 1
[1,2]<stdout>:master:141585:141605 [0] NCCL INFO enqueue.cc:1462 -> 1
[1,3]<stdout>:
[1,3]<stdout>:slave2:17646:17669 [0] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO enqueue.cc:1417 -> 1
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO enqueue.cc:1457 -> 1
[1,3]<stdout>:slave2:17646:17669 [0] NCCL INFO enqueue.cc:1462 -> 1
[1,2]<stdout>:master:141585:141638 [0] NCCL INFO [Service thread] Connection closed by localRank 0
[1,3]<stdout>:slave2:17646:17690 [0] NCCL INFO [Service thread] Connection closed by localRank 0
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank 1 nranks 4 cudaDev 1 busId 86000 - Abort COMPLETE
[1,1]<stdout>:
[1,1]<stdout>:slave1:126624:126758 [1] misc/argcheck.cc:39 NCCL WARN Broadcast : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1450 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1462 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank -1 nranks -1 cudaDev -1 busId ffffffffffffffff - Abort COMPLETE
[1,1]<stdout>:
[1,1]<stdout>:slave1:126624:126758 [1] misc/argcheck.cc:39 NCCL WARN Broadcast : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1450 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1462 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank -1 nranks -1 cudaDev -1 busId ffffffffffffffff - Abort COMPLETE
[1,1]<stdout>:
[1,1]<stdout>:slave1:126624:126758 [1] misc/argcheck.cc:39 NCCL WARN Broadcast : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1450 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1462 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank -1 nranks -1 cudaDev -1 busId ffffffffffffffff - Abort COMPLETE
[1,1]<stdout>:
[1,1]<stdout>:slave1:126624:126758 [1] misc/argcheck.cc:39 NCCL WARN Broadcast : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1450 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO enqueue.cc:1462 -> 4
[1,1]<stdout>:slave1:126624:126758 [1] NCCL INFO comm 0x7f7258228580 rank -1 nranks -1 cudaDev -1 busId ffffffffffffffff - Abort COMPLETE
...

[1,2]<stdout>:master:139778:139808 [0] init.cc:1479 NCCL WARN comm 0x7fa47c226cc0 has already been destroyed
[1,3]<stdout>:slave2:17230:17253 [0] NCCL INFO comm 0x7f84fc22ecf0 rank -1 nranks -1 cudaDev -1 busId ffffffffffffffff - Abort COMPLETE
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "/home/xxx/anaconda3/envs/mg/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 1253, in synchronize
[1,3]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,3]<stderr>:RuntimeError: ncclBroadcast failed: unhandled cuda error
[1,3]<stderr>:
[1,3]<stderr>:During handling of the above exception, another exception occurred:
[1,3]<stderr>:
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "pytorch_mnist.py", line 263, in <module>
[1,3]<stderr>:    main(args)
[1,3]<stderr>:  File "pytorch_mnist.py", line 222, in main
[1,3]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,3]<stderr>:  File "/home/xxx/anaconda3/envs/mg/lib/python3.8/site-packages/horovod/torch/functions.py", line 59, in broadcast_parameters
[1,3]<stderr>:    synchronize(handle)
[1,3]<stderr>:  File "/home/xxx/anaconda3/envs/mg/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 1258, in synchronize
[1,3]<stderr>:    raise HorovodInternalError(e)
[1,3]<stderr>:horovod.common.exceptions.HorovodInternalError: ncclBroadcast failed: unhandled cuda error

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[13344,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by maxhgerlach** [comment]
```NCCL WARN Cuda failure 'CUDA driver is a stub library'``` -- this appears to be a separate issue, related to how your NCCL library is built (see discussion in https://github.com/horovod/horovod/issues/3625). You could build it yourself (with default configuration) or downgrade the package a bit: 2.11 worked in Horovod's CI (https://github.com/horovod/horovod/pull/3673#issuecomment-1254892694).

Regarding the original problem: Can you run Horovod's example scripts, like https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py, on your setup?

**Comment by Cancerhzc** [comment]
@maxhgerlach Thanks for your help.  I downgraded nccl to 2.11, reinstall horovod and used `horovodrun -np 4 -H master:1,slave1:2,slave2:1 python pytorch_mnist.py` to run [https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py](url). I'm excited that it can work properly.

```
[1,1]<stdout>:Train Epoch: 10 [12800/15000 (85%)]       Loss: 0.131831
[1,0]<stdout>:Train Epoch: 10 [12800/15000 (85%)]       Loss: 0.090284
[1,3]<stdout>:Train Epoch: 10 [12800/15000 (85%)]       Loss: 0.096681
[1,2]<stdout>:Train Epoch: 10 [12800/15000 (85%)]       Loss: 0.269539
[1,2]<stdout>:Train Epoch: 10 [13440/15000 (89%)]       Loss: 0.139085
[1,1]<stdout>:Train Epoch: 10 [13440/15000 (89%)]       Loss: 0.202409
[1,0]<stdout>:Train Epoch: 10 [13440/15000 (89%)]       Loss: 0.111249
[1,3]<stdout>:Train Epoch: 10 [13440/15000 (89%)]       Loss: 0.152737
[1,1]<stdout>:Train Epoch: 10 [14080/15000 (94%)]       Loss: 0.317158
[1,3]<stdout>:Train Epoch: 10 [14080/15000 (94%)]       Loss: 0.167515
[1,2]<stdout>:Train Epoch: 10 [14080/15000 (94%)]       Loss: 0.094338
[1,0]<stdout>:Train Epoch: 10 [14080/15000 (94%)]       Loss: 0.291808
[1,1]<stdout>:Train Epoch: 10 [14720/15000 (98%)]       Loss: 0.078131
[1,0]<stdout>:Train Epoch: 10 [14720/15000 (98%)]       Loss: 0.251146
[1,2]<stdout>:Train Epoch: 10 [14720/15000 (98%)]       Loss: 0.132247
[1,3]<stdout>:Train Epoch: 10 [14720/15000 (98%)]       Loss: 0.154996
[1,0]<stdout>:
[1,0]<stdout>:Test set: Average loss: 0.0541, Accuracy: 98.28%
[1,0]<stdout>:
```

**Comment by maxhgerlach** [comment]
Please re-open if the original problem persists.
