### ISSUE TITLE
mpirun failed with exit status 1 while running spark submit with master yarn on horovod

### ISSUE THREAD

**Issue by mtsol** [horovod/horovod#3762]
**Environment:**
1. Framework: (Keras)
2. Framework version: 2.6.0
3. Horovod version: 0.25.0
4. MPI version: 3
5. CUDA version: 11.7
6. NCCL version: NA
7. Python version: 3.8
8. Spark / PySpark version: 3.1.1
9. Ray version: NA
10. OS and version: ubuntu
11. GCC version:
12. CMake version:

8881 [0] NCCL INFO comm 0x7fd37c402d10 rank 1 nranks 2 cudaDev 0 busId 2000 - Init COMPLETE
Thu Nov 10 07:45:12 2022[1,0]<stderr>:/usr/local/lib/python3.8/dist-packages/petastorm/fs_utils.py:88: FutureWarning: pyarrow.localfs is deprecated as of 2.0.0, please use pyarrow.fs.LocalFileSystem instead.
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Shared lib path is pointing to: <CDLL '/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_lib.cpython-38-x86_64-linux-gnu.so', handle 53613d0 at 0x7fea411798b0>
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Found TensorBoard callback, updating log_dir to /tmp/tmp_kuatqj9/logs
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Training parameters: Epochs: 12, Scaled lr: 2.0, Shuffle size: 17444, random_seed: 1
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  self._filesystem = pyarrow.localfs
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Train rows: 34888, Train batch size: 128, Train_steps_per_epoch: 137
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Val rows: 3464, Val batch size: 128, Val_steps_per_epoch: None
Thu Nov 10 07:45:12 2022[1,0]<stdout>:Checkpoint file: file:///tmp/runs/keras_1668066293, Logs dir: file:///tmp/runs/keras_1668066293/logs
Thu Nov 10 07:45:12 2022[1,0]<stdout>:
Thu Nov 10 07:45:12 2022[1,0]<stderr>:Traceback (most recent call last):
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    return _run_code(code, main_globals, None,
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    exec(code, run_globals)
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    result = fn(*args, **kwargs)
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/remote.py", line 258, in train
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    with reader_factory(remote_store.train_data_path,
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 317, in make_batch_reader
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    return Reader(filesystem, dataset_path_or_paths,
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 448, in __init__
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    filtered_row_group_indexes, worker_predicate = self._filter_row_groups(self.dataset, row_groups, predicate,
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 529, in _filter_row_groups
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    filtered_row_group_indexes = self._partition_row_groups(dataset, row_groups, shard_count,
Thu Nov 10 07:45:12 2022[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 550, in _partition_row_groups
Thu Nov 10 07:45:12 2022[1,0]<stderr>:    raise NoDataAvailableError('Number of row-groups in the dataset must be greater or equal to the number of '
Thu Nov 10 07:45:12 2022[1,0]<stderr>:petastorm.errors.NoDataAvailableError: Number of row-groups in the dataset must be greater or equal to the number of requested shards. Otherwise, some of the shards will end up being empty.
Thu Nov 10 07:45:12 2022[1,1]<stderr>:/usr/local/lib/python3.8/dist-packages/petastorm/fs_utils.py:88: FutureWarning: pyarrow.localfs is deprecated as of 2.0.0, please use pyarrow.fs.LocalFileSystem instead.
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  self._filesystem = pyarrow.localfs
Thu Nov 10 07:45:12 2022[1,1]<stderr>:Traceback (most recent call last):
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/etl/dataset_metadata.py", line 414, in infer_or_load_unischema
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    return get_schema(dataset)
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/etl/dataset_metadata.py", line 363, in get_schema
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    raise PetastormMetadataError(
Thu Nov 10 07:45:12 2022[1,1]<stderr>:petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
Thu Nov 10 07:45:12 2022[1,1]<stderr>:
Thu Nov 10 07:45:12 2022[1,1]<stderr>:During handling of the above exception, another exception occurred:
Thu Nov 10 07:45:12 2022[1,1]<stderr>:
Thu Nov 10 07:45:12 2022[1,1]<stderr>:Traceback (most recent call last):
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    return _run_code(code, main_globals, None,
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    exec(code, run_globals)
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 52, in <module>
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/mpirun_exec_fn.py", line 45, in main
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK', 'OMPI_COMM_WORLD_LOCAL_RANK')
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    result = fn(*args, **kwargs)
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/remote.py", line 258, in train
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    with reader_factory(remote_store.train_data_path,
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 317, in make_batch_reader
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    return Reader(filesystem, dataset_path_or_paths,
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/reader.py", line 409, in __init__
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    stored_schema = infer_or_load_unischema(self.dataset)
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/etl/dataset_metadata.py", line 418, in infer_or_load_unischema
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    return Unischema.from_arrow_schema(dataset)
Thu Nov 10 07:45:12 2022[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/petastorm/unischema.py", line 317, in from_arrow_schema
Thu Nov 10 07:45:12 2022[1,1]<stderr>:    meta = parquet_dataset.pieces[0].get_metadata()
Thu Nov 10 07:45:12 2022[1,1]<stderr>:IndexErrorThu Nov 10 07:45:12 2022[1,1]<stderr>:: list index out of range
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56569,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/horovod/examples/spark/keras/keras_spark_mnist.py", line 122, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/estimator.py", line 35, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 161, in fit
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/estimator.py", line 80, in _fit
    return self._fit_on_prepared_data(
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/estimator.py", line 275, in _fit_on_prepared_data
    handle = backend.run(trainer,
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/backend.py", line 83, in run
    return horovod.spark.run(fn, args=args, kwargs=kwargs,
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/runner.py", line 290, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr, executable)
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/runner.py", line 155, in _launch_job
    run_controller(use_gloo, lambda: gloo_run(executable, settings, nics, driver, env, stdout, stderr),
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 761, in run_controller
    mpi_run()
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/runner.py", line 156, in <lambda>
    use_mpi, lambda: mpi_run(executable, settings, nics, driver, env, stdout, stderr),
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/mpi_run.py", line 56, in mpi_run
    hr_mpi_run(settings, nics, env, command, stdout=stdout, stderr=stderr)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/mpi_run.py", line 252, in mpi_run
    raise RuntimeError("mpirun failed with exit code {exit_code}".format(exit_code=exit_code))
RuntimeError: mpirun failed with exit code 1

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

**Comment by xiaodaxia** [comment]
Did you solve this problem? And how did you solve it?
I encounter the same issue.

**Comment by shadowinlife** [comment]
Any guys resolved this? I catch same issue with spark 3.2.0 on k8s

**Comment by Parvez-Khan-1** [comment]
I am facing the similar error
