### ISSUE TITLE
TypeError: DistributedOptimizer() got multiple values for argument 'named_parameters' 

### ISSUE THREAD

**Issue by xchisgood** [horovod/horovod#3780]
when i run the code named pytorch_mnist.py from [https://github.com/sands-lab/grace/tree/master/examples/torch], i wanna to get the reason ?thank you to help me solve the problem.
**Environment:**
1. Framework: PyTorch
2. Framework version:1.5.0
3. Horovod version:0.26.1
4. MPI version:4.0.0
5. CUDA version:11.6
6. NCCL version:2.8.3
7. Python version:3.7
8. Spark / PySpark version:
9. Ray version:
10. OS and version:Linux
11. GCC version:
12. CMake version:
**Bug report:**
[0]<stderr>:Traceback (most recent call last):
[1]<stderr>:Traceback (most recent call last):
[0]<stderr>:  File "pytorch_mnist.py", line 117, in <module>
[1]<stderr>:  File "pytorch_mnist.py", line 117, in <module>
[0]<stderr>:    optimizer = hvd.DistributedOptimizer(optimizer, grc, named_parameters=model.named_parameters())
[1]<stderr>:    optimizer = hvd.DistributedOptimizer(optimizer, grc, named_parameters=model.named_parameters())
[0]<stderr>:TypeError: DistributedOptimizer() got multiple values for argument 'named_parameters'
[1]<stderr>:TypeError: DistributedOptimizer() got multiple values for argument 'named_parameters'
Process 1 exit with status code 1.
Terminating remaining workers after failure of Process 1.
Process 0 exit with status code 1.
Traceback (most recent call last):
  File "/home/wangty/.conda/envs/pytorch/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 837, in run_
    _run(args)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 827, in _run
    return _run_static(args)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 685, in _run
    _launch_job(args, settings, nics, command)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 803, in _lau
    args.verbose)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 754, in run_
    gloo_run()
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/launch.py", line 792, in gloo
    gloo_run(settings, nics, env, driver_ip, command)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 300, in gl
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/home/wangty/.conda/envs/pytorch/lib/python3.6/site-packages/horovod/runner/gloo_run.py", line 287, in la
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be
Process name: 1
Exit code: 1

**Comment by maxhgerlach** [comment]
Closing as this is about a thirdparty script using Horovod.
