### ISSUE TITLE
TF 2.11.0 (mixed_float16): 'LossScaleOptimizerV3' object has no attribute

### ISSUE THREAD

**Issue by RicoOscar** [horovod/horovod#3807]
**Environment:**
1. Framework: TensorFlow
2. Framework version:2.11.0
3. Horovod version:0.26.1
4. MPI version:4.1.4
5. CUDA version:11.6
6. NCCL version:2.11.4-1
7. Python version:3.8
8. OS and version: Ubuntu 20.04

**Bug report:**
When a run a training in Tensorflow 2.11.0 with mixed_float16 with horovod. I have the following error message:

```bash
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1,0]<stderr>:    return _run_code(code, main_globals, None,
[1,0]<stderr>:  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1,0]<stderr>:    exec(code, run_globals)
[1,0]<stderr>:  File "/home/bruno/erx-ai/src/erxai/tf_train/tf_train.py", line 920, in <module>
[1,0]<stderr>:    main(sys.argv[1:])
[1,0]<stderr>:  File "/home/bruno/erx-ai/src/erxai/tf_train/tf_train.py", line 899, in main
[1,0]<stderr>:    tf_train_semantic.run_train()
[1,0]<stderr>:  File "/home/bruno/erx-ai/src/erxai/tf_train/tf_train.py", line 625, in run_train
[1,0]<stderr>:    self.model.fit(
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
[1,0]<stderr>:    raise e.with_traceback(filtered_tb) from None
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/_keras/callbacks.py", line 53, in on_batch_end
[1,0]<stderr>:    hvd.broadcast_variables(self.model.optimizer.variables(),
[1,0]<stderr>:AttributeError: 'LossScaleOptimizerV3' object has no attribute '_variables'
```

**Comment by maxhgerlach** [comment]
Horovod doesn't yet support the reworked Keras optimizers that have been made default in TF 2.11, see https://github.com/horovod/horovod/issues/3726 (contributions are welcome!). I think `LossScaleOptimizerV3` is one of those. For now you would have to use the "classic" optimizers with Horovod that have been moved into `tf.keras.optimizers.legacy`: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/legacy

**Comment by RicoOscar** [comment]
Thank you @maxhgerlach for your reply . 
It seems that it does not work only when we enable the training in mixed_float16 in TF 2.11. The training in float32 does not return any error with horovod 0.26.1 and TF 2.11 despite using tf.keras.optimizers as the main optimizer.

**Comment by nvcastet** [comment]
@RicoOscar In fact it is due to a bug in TF. See discussions at https://github.com/keras-team/keras/issues/17275
It should be fixed in tf nightly with this commit: https://github.com/keras-team/keras/commit/c98ea36b96f6036b1dec569e5e496aee06a44b29

**Comment by maxhgerlach** [comment]
@RicoOscar, is this still a problem with TensorFlow 2.12 (which includes the commit posted by Nicolas)?

**Comment by RicoOscar** [comment]
Thank you @maxhgerlach and @nvcastet . The issue seems to be solve with the Tensorflow and Keras 2.12.0

**Comment by maxhgerlach** [comment]
Good to hear, thanks for getting back to us!
