### ISSUE TITLE
Docker build horovod-nvtabular fails

### ISSUE THREAD

**Issue by maxhgerlach** [horovod/horovod#3850]
`pip` installing `cudf-cu11` results in an error:
```
#12 [ 7/37] RUN pip install --no-cache-dir cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com/
#12 1.247 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
#12 2.285 Collecting cudf-cu11
#12 2.391   Downloading cudf_cu11-23.2.0.tar.gz (6.5 kB)
#12 2.525     ERROR: Command errored out with exit status 1:
#12 2.525      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lwkt7jbg/cudf-cu11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lwkt7jbg/cudf-cu11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lwkt7jbg/cudf-cu11/pip-egg-info
#12 2.525          cwd: /tmp/pip-install-lwkt7jbg/cudf-cu11/
#12 2.525     Complete output (5 lines):
#12 2.525     Traceback (most recent call last):
#12 2.525       File "<string>", line 1, in <module>
#12 2.525       File "/tmp/pip-install-lwkt7jbg/cudf-cu11/setup.py", line 137, in <module>
#12 2.525         raise RuntimeError(open("ERROR.txt", "r").read())
#12 2.525     FileNotFoundError: [Errno 2] No such file or directory: 'ERROR.txt'
#12 2.525     ----------------------------------------
```
https://github.com/horovod/horovod/actions/runs/4192929617/jobs/7277248027

**Comment by maxhgerlach** [comment]
@leewyang, should we update the `--extra-index-url`?

https://pypi.org/project/cudf-cu11/ was updated recently. The message there points to https://pypi.nvidia.com.
