### ISSUE TITLE
Install failed in the process"Building CXX object horovod/tensorflow/CMakeFiles/tensorflow.dir/__/common/timeline.cc.o"

### ISSUE THREAD

**Issue by SeeleVolle** [horovod/horovod#3876]
**Environment:**
1. Framework: Tensorflow 
2. Framework version: 2.6.0
3. Horovod version: 0.27.0
4. MPI version: 
5. CUDA version: 11.7 
6. NCCL version: 2.17.1
7. Python version: 3.7.16
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Debian 11, Linux version 5.10.0-21-amd64 (debian-kernel@lists.debian.org)
11. GCC version:  10.2.1 20210110 (Debian 10.2.1-6)
12. CMake version: 3.18.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

command: 
`HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_NCCL_HOME=/home/huangjinjun/.local/nccl  pip install horovod `

The result is shown below:
[ 58%] Building CXX object horovod/tensorflow/CMakeFiles/tensorflow.dir/__/common/timeline.cc.o
      cd /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/build/temp.linux-x86_64-cpython-37/RelWithDebInfo/horovod/tensorflow && /home/huangjinjun/.conda/envs/asc2022/bin/x86_64-conda-linux-gnu-c++ -DEIGEN_MPL2_ONLY=1 -DHAVE_CUDA=1 -DHAVE_GPU=1 -DHAVE_NCCL=1 -DHAVE_NVTX=1 -DHOROVOD_GPU_ALLGATHER=78 -DHOROVOD_GPU_ALLREDUCE=78 -DHOROVOD_GPU_ALLTOALL=78 -DHOROVOD_GPU_BROADCAST=78 -DHOROVOD_GPU_REDUCESCATTER=78 -DTENSORFLOW_VERSION=2006000000 -Dtensorflow_EXPORTS -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/HTTPRequest/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/assert/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/config/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/core/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/detail/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/iterator/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/lockfree/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/mpl/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/parameter/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/predef/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/preprocessor/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/static_assert/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/type_traits/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/boost/utility/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/lbfgs/include -I/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/third_party/flatbuffers/include -isystem /home/huangjinjun/.local/cuda-11.7/targets/x86_64-linux/include -isystem /home/huangjinjun/.local/nccl/include -isystem /home/huangjinjun/.local/cuda-11.7/include -isystem /home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/tensorflow/include -I/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -DEIGEN_MAX_ALIGN_BYTES=64 -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/huangjinjun/.conda/envs/asc2022/include -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -O3 -g -DNDEBUG -fPIC -std=c++14 -o CMakeFiles/tensorflow.dir/__/common/timeline.cc.o -c /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/timeline.cc
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In constructor 'horovod::common::ProcessSetTable::ProcessSetTable()':
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:165:8: warning: unused variable 'process_set_id' [-Wunused-variable]
        165 |   auto process_set_id = RegisterProcessSet();
            |        ^~~~~~~~~~~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In member function 'void horovod::common::ProcessSetTable::Initialize_(const Context&)':
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:173:10: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
        173 |   Get(0).Initialize(global_context);
            |          ^~~~~~~~~~
            |          Finalize
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In member function 'int32_t horovod::common::ProcessSetTable::InitializeRegisteredAndRemoveMarkedIfReady_(const Context&, const horovod::common::Status&)':
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:209:39: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
        209 |       bool newly_registered = Get(id).Initialize(global_context);
            |                                       ^~~~~~~~~~
            |                                       Finalize
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:212:13: error: 'TRACE' was not declared in this scope
        212 |         LOG(TRACE, global_controller.GetRank())
            |             ^~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:212:9: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
        212 |         LOG(TRACE, global_controller.GetRank())
            |         ^~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:212:9: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:226:11: error: 'TRACE' was not declared in this scope
        226 |       LOG(TRACE, global_controller.GetRank())
            |           ^~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:226:7: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
        226 |       LOG(TRACE, global_controller.GetRank())
            |       ^~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In member function 'void horovod::common::ProcessSetTable::Finalize_(const Context&, const horovod::common::Status&)':
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:247:9: error: 'TRACE' was not declared in this scope
        247 |     LOG(TRACE, Get(0).controller->GetRank())
            |         ^~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:247:5: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
        247 |     LOG(TRACE, Get(0).controller->GetRank())
            |     ^~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:265:7: error: 'TRACE' was not declared in this scope
        265 |   LOG(TRACE, Get(0).controller->GetRank())
            |       ^~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:265:3: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
        265 |   LOG(TRACE, Get(0).controller->GetRank())
            |   ^~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: At global scope:
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:26:13: warning: 'std::string horovod::common::{anonymous}::RanksString(const std::vector<int>&)' defined but not used [-Wunused-function]
         26 | std::string RanksString(const std::vector<int>& ranks) {
            |             ^~~~~~~~~~~
      gmake[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/build.make:199: horovod/tensorflow/CMakeFiles/tensorflow.dir/__/common/process_set.cc.o] Error 1
      gmake[2]: *** Waiting for unfinished jobs....
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/controller.cc: In member function 'horovod::common::Response horovod::common::Controller::ConstructResponse(const string&, int)':
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/controller.cc:811:27: warning: 'reduce_op' may be used uninitialized in this function [-Wmaybe-uninitialized]
        811 |     response.set_reduce_op(reduce_op);
            |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/controller.cc:810:34: warning: 'postscale_factor' may be used uninitialized in this function [-Wmaybe-uninitialized]
        810 |     response.set_postscale_factor(postscale_factor);
            |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
      /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/controller.cc:809:33: warning: 'prescale_factor' may be used uninitialized in this function [-Wmaybe-uninitialized]
        809 |     response.set_prescale_factor(prescale_factor);
            |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
      gmake[2]: Leaving directory '/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/build/temp.linux-x86_64-cpython-37/RelWithDebInfo'
      gmake[1]: *** [CMakeFiles/Makefile2:178: horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
      gmake[1]: Leaving directory '/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/build/temp.linux-x86_64-cpython-37/RelWithDebInfo'
      gmake: *** [Makefile:103: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/setup.py", line 257, in <module>
          'horovodrun = horovod.runner.launch:run_commandline'
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/setup.py", line 145, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/home/huangjinjun/.conda/envs/asc2022/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for horovod

+ The tensorflow is installed from **conda**, and gxx_impl_linux-64, gxx_linux-64 are already installed from conda

**Comment by SeeleVolle** [comment]
I have checked all the issues about failed installtation, but none of them helps

**Comment by lawrence910426** [comment]
I have encountered similar problems. But I had no idea how to solve it.

**Comment by maxhgerlach** [comment]
>  `HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_NCCL_HOME=/home/huangjinjun/.local/nccl  pip install horovod`

1. Could you add a `-v` to your `pip install` and post the full log?

>  /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In member function 'void horovod::common::ProcessSetTable::Initialize_(const Context&)':
/tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:173:10: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
173 | Get(0).Initialize(global_context);

2. Since you request to build Horovod without Gloo (`HOROVOD_WITHOUT_GLOO`), you will need Open MPI or some other implementation of MPI. That compile error is triggered because neither MPI nor Gloo are available.

**Comment by SeeleVolle** [comment]
> > `HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_NCCL_HOME=/home/huangjinjun/.local/nccl  pip install horovod`
> 
> 1. Could you add a `-v` to your `pip install` and post the full log?
> 
> > /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc: In member function 'void horovod::common::ProcessSetTable::Initialize_(const Context&)':
> > /tmp/pip-install-c7iazdzy/horovod_1fbec6e2e4cc4d839cf45c7ef4281dbb/horovod/common/process_set.cc:173:10: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
> > 173 | Get(0).Initialize(global_context);
> 
> 2. Since you request to build Horovod without Gloo (`HOROVOD_WITHOUT_GLOO=1`), you will need Open MPI or some other implementation of MPI. That compile error is triggered because neither MPI nor Gloo are available.

I have seen the full log, and find the question there: 
 -- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
  CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find MPI (missing: MPI_CXX_FOUND)

But I have installed openmpi-4.1.5, and set the MPI_HOME and other environment variables.
When I run mpirun -V, it shows "mpirun (Open MPI) 4.1.5"

**Comment by AlexisEspinosaGayosso** [comment]
Dear @maxhgerlach , I'm suffering of exactly the same problem. My compilation instructions are (for installation with ROCM on a HPE-CRAY system):
```
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_GPU=ROCM
export HOROVOD_GPU_OPERATIONS=NCCL
export HOROVOD_WITHOUT_GLOO=1
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_ROCM_PATH=$ROCM_PATH
export HOROVOD_RCCL_HOME=$HOROVOD_ROCM_PATH/rccl
export RCCL_INCLUDE_DIRS=$HOROVOD_RCCL_HOME/include
export HOROVOD_RCCL_LIB=$HOROVOD_RCCL_HOME/lib
export HOROVOD_MPICXX_SHOW="CC --cray-print-opts=all"
export HCC_AMDGPU_TARGET=gfx90a
MPICXX=CC MPICC=cc CXX=CC CC=cc pip install --verbose horovod
```

And the error messages seem to be the same as indicated by @SeeleVolle :
```
Running CMake in build/temp.linux-x86_64-cpython-310/RelWithDebInfo:
  cmake /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/build/lib.linux-x86_64-cpython-310 -DPYTHON_EXECUTABLE:FILEPATH=/software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/bin/python3
  cmake --build . --config RelWithDebInfo -- -j8 VERBOSE=1
  -- Could not find CCache. Consider installing CCache to speed up compilation.
  -- The CXX compiler identification is GNU 12.2.0
  -- Cray Programming Environment 2.7.20 CXX
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/cray/pe/craype/2.7.20/bin/CC - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Build architecture flags: -mf16c -mavx -mfma
  -- Using command /software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/bin/python3
  -- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
  -- Could NOT find MPI (missing: MPI_CXX_FOUND)
  -- Looking for a CUDA compiler
  -- Looking for a CUDA compiler - NOTFOUND
  -- Looking for a CUDA host compiler - /opt/cray/pe/craype/2.7.20/bin/CC
  -- Could not find nvcc, please set CUDAToolkit_ROOT. 
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- hip::amdhip64 is SHARED_LIBRARY
  -- HIP library name: amdhip64
  -- Found ROCM: /opt/rocm/lib/libamdhip64.so
  -- Could NOT find NVTX (missing: NVTX_INCLUDE_DIR)
  Tensorflow_LIBRARIES := -L/software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/lib/python3.10/site-packages/tensorflow -l:libtensorflow_framework.so.2 /software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  -- Found Tensorflow: -L/software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/lib/python3.10/site-packages/tensorflow -l:libtensorflow_framework.so.2 /software/projects/manual/software/pythonEnvironments/python/3.10.10/deepmd-env/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so (found suitable version "2.8.3", minimum required is "1.15.0")
  -- Build Horovod for ROCm
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/build/temp.linux-x86_64-cpython-310/RelWithDebInfo
  .
  .
  .
    /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc: In constructor 'horovod::common::ProcessSetTable::ProcessSetTable()':
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc:165:8: warning: unused variable 'process_set_id' [-Wunused-variable]
    165 |   auto process_set_id = RegisterProcessSet();
        |        ^~~~~~~~~~~~~~
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc: In member function 'void horovod::common::ProcessSetTable::Initialize_(const Context&)':
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc:173:10: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
    173 |   Get(0).Initialize(global_context);
        |          ^~~~~~~~~~
        |          Finalize
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc: In member function 'int32_t horovod::common::ProcessSetTable::InitializeRegisteredAndRemoveMarkedIfReady_(const Context&, const horovod::common::Status&)':
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc:209:39: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
    209 |       bool newly_registered = Get(id).Initialize(global_context);
        |                                       ^~~~~~~~~~
        |                                       Finalize
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc:212:13: error: 'TRACE' was not declared in this scope
    212 |         LOG(TRACE, global_controller.GetRank())
        |             ^~~~~
  /tmp/pip-install-l8hc8drz/horovod_c0d9207c8d49408584aa6c4c50364de9/horovod/common/process_set.cc:212:9: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
    212 |         LOG(TRACE, global_controller.GetRank())
        |         ^~~
```
I have checked the links you provided above as possible help for solving this issue, but indications there does not seem to help. I'm hoping you have some new hints that I can use here. Thanks.

**Comment by intel-hm** [comment]
I could resolve a similar issue on Intel oneAPI-AI 2023.3 by overloading a suitable MPI. oneAPI-AI does not contain the complete MPI environment, and it looks like that made all the difference.

**Comment by wwj-2017-1117** [comment]
I also meet the same bug

**Comment by oabuhamdan** [comment]
I have the same issue. Any solution yet?
