### ISSUE TITLE
Failed to Build Horovod (Cmake trying to import tensorflow and torch while installing horovod[pytorch])

### ISSUE THREAD

**Issue by fahadh4ilyas** [horovod/horovod#3902]
**Environment:**
1. Framework: Pytorch
2. Framework version: 2.0.0 (show up when installing horovod)
3. Horovod version: 0.27.0 (show up when installing horovod)
4. MPI version: 4.1.5 (check using `mpirun --version`)
5. CUDA version: 11.7 (check using `nvcc --version`)
6. NCCL version: 2.14.3
7. Python version: 3.9
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Ubuntu 22.04
11. GCC version: 11.3.0 (check using `gcc --version`)
12. CMake version: 3.26.3 (check using `cmake --version`)

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Not about hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Not about docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
I'm installing horovod using this command
`HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod[pytorch]`

This error show up when building horovod
```
Building wheels for collected packages: horovod, lit
  Building wheel for horovod (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.                                                                                                     │ exit code: 1
  ╰─> [290 lines of output]
      /root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel                                                                                                                                         running build
      running build_py
      creating build                                                                                                                                              creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/horovod
      copying horovod/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod                                                                                    creating build/lib.linux-x86_64-cpython-39/horovod/tensorflow
      copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                              copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                               copying horovod/tensorflow/gradient_aggregation.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                  copying horovod/tensorflow/sync_batch_norm.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                       copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                           copying horovod/tensorflow/functions.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                             copying horovod/tensorflow/gradient_aggregation_eager.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                            copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                                  copying horovod/tensorflow/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow                                                               creating build/lib.linux-x86_64-cpython-39/horovod/keras
      copying horovod/keras/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/keras                                                                        copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-cpython-39/horovod/keras                                                                       copying horovod/keras/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/keras                                                                         creating build/lib.linux-x86_64-cpython-39/horovod/torch                                                                                                    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                        copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                         copying horovod/torch/optimizer.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                       copying horovod/torch/sync_batch_norm.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                 copying horovod/torch/compression.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                     copying horovod/torch/functions.py -> build/lib.linux-x86_64-cpython-39/horovod/torch                                                                       creating build/lib.linux-x86_64-cpython-39/horovod/mxnet
      copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/mxnet                                                                        copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-cpython-39/horovod/mxnet
      copying horovod/mxnet/compression.py -> build/lib.linux-x86_64-cpython-39/horovod/mxnet
      copying horovod/mxnet/functions.py -> build/lib.linux-x86_64-cpython-39/horovod/mxnet
      creating build/lib.linux-x86_64-cpython-39/horovod/data
      copying horovod/data/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/data
      copying horovod/data/data_loader_base.py -> build/lib.linux-x86_64-cpython-39/horovod/data
      creating build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/driver_service.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/utils.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/ray_logger.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/elastic_v2.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/runner.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/worker.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/adapter.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/strategy.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      copying horovod/ray/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/ray
      creating build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/process_sets.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/basics.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/util.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      copying horovod/common/exceptions.py -> build/lib.linux-x86_64-cpython-39/horovod/common
      creating build/lib.linux-x86_64-cpython-39/horovod/_keras
      copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/_keras
      copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-cpython-39/horovod/_keras
      copying horovod/_keras/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/_keras
      creating build/lib.linux-x86_64-cpython-39/horovod/spark
      copying horovod/spark/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark
      copying horovod/spark/runner.py -> build/lib.linux-x86_64-cpython-39/horovod/spark
      copying horovod/spark/mpi_run.py -> build/lib.linux-x86_64-cpython-39/horovod/spark
      copying horovod/spark/conf.py -> build/lib.linux-x86_64-cpython-39/horovod/spark
      copying horovod/spark/gloo_run.py -> build/lib.linux-x86_64-cpython-39/horovod/spark
      creating build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/js_run.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/mpi_run.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/run_task.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/launch.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/task_fn.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      copying horovod/runner/gloo_run.py -> build/lib.linux-x86_64-cpython-39/horovod/runner
      creating build/lib.linux-x86_64-cpython-39/horovod/tensorflow/keras
      copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/keras
      copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/keras                                  [501/768]      copying horovod/tensorflow/keras/elastic.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/keras
      creating build/lib.linux-x86_64-cpython-39/horovod/tensorflow/data
      copying horovod/tensorflow/data/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/data
      copying horovod/tensorflow/data/compute_service.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/data
      copying horovod/tensorflow/data/compute_worker.py -> build/lib.linux-x86_64-cpython-39/horovod/tensorflow/data
      creating build/lib.linux-x86_64-cpython-39/horovod/torch/elastic
      copying horovod/torch/elastic/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/torch/elastic
      copying horovod/torch/elastic/sampler.py -> build/lib.linux-x86_64-cpython-39/horovod/torch/elastic
      copying horovod/torch/elastic/state.py -> build/lib.linux-x86_64-cpython-39/horovod/torch/elastic
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/data_loaders
      copying horovod/spark/data_loaders/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/data_loaders
      copying horovod/spark/data_loaders/pytorch_data_loaders.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/data_loaders
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/tensorflow
      copying horovod/spark/tensorflow/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/tensorflow
      copying horovod/spark/tensorflow/compute_worker.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/tensorflow
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/remote.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/datamodule.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/tensorflow.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/bare.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/estimator.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/optimizer.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      copying horovod/spark/keras/util.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/keras
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      copying horovod/spark/torch/remote.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      copying horovod/spark/torch/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      copying horovod/spark/torch/datamodule.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      copying horovod/spark/torch/estimator.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      copying horovod/spark/torch/util.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/torch
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/rsh.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/host_discovery.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/rendezvous.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/driver
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/task
      copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/task
      copying horovod/spark/task/gloo_exec_fn.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/task
      copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/task
      copying horovod/spark/task/task_info.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/task
      copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/task
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/backend.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/params.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/datamodule.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/estimator.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/constants.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/_namedtuple_fix.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/cache.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/store.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/serialization.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      copying horovod/spark/common/util.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/common
      creating build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/remote.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/datamodule.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/estimator.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/legacy.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      copying horovod/spark/lightning/util.py -> build/lib.linux-x86_64-cpython-39/horovod/spark/lightning
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/driver
      copying horovod/runner/driver/driver_service.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/driver
      copying horovod/runner/driver/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/driver
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/task
      copying horovod/runner/task/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/task
      copying horovod/runner/task/task_service.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/task
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/http
      copying horovod/runner/http/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/http
      copying horovod/runner/http/http_client.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/http
      copying horovod/runner/http/http_server.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/http
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/remote.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/threads.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/network.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/cache.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/streams.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      copying horovod/runner/util/lsf.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/util
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/settings.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/driver.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/worker.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/constants.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic                                      [414/768]      copying horovod/runner/elastic/registration.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/discovery.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      copying horovod/runner/elastic/rendezvous.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/elastic
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/common
      copying horovod/runner/common/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/common/service
      copying horovod/runner/common/service/driver_service.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/service
      copying horovod/runner/common/service/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/service
      copying horovod/runner/common/service/task_service.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/service
      copying horovod/runner/common/service/compute_service.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/service
      creating build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/hosts.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/__init__.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/tiny_shell_exec.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/codec.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/env.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/settings.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/network.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/config_parser.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/timeout.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/secret.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/host_hash.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      copying horovod/runner/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-cpython-39/horovod/runner/common/util
      running build_ext
      Running CMake in build/temp.linux-x86_64-cpython-39/RelWithDebInfo:
      cmake /tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d/build/lib.linux-x86_64-cpython-39 -DPYTHON_EXECUTABLE:FILEPATH=/root/anaconda3/envs/horovod/bin/python
      cmake --build . --config RelWithDebInfo -- -j8 VERBOSE=1
      -- Could not find CCache. Consider installing CCache to speed up compilation.
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Build architecture flags: -mf16c -mavx -mfma
      -- Using command /root/anaconda3/envs/horovod/bin/python
      -- Found MPI_CXX: /usr/local/lib/libmpi.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1")
      -- Looking for a CUDA compiler
      -- Looking for a CUDA compiler - /usr/local/cuda-11.7/bin/nvcc
      -- The CUDA compiler identification is NVIDIA 11.7.99
      -- Detecting CUDA compiler ABI info                                                                                                          [370/768]      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda-11.7/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Found CUDAToolkit: /usr/local/cuda-11.7/include (found version "11.7.99")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- Linking against static NCCL library
      -- Found NCCL: /usr/include
      -- Determining NCCL version from the header file: /usr/include/nccl.h
      -- NCCL_MAJOR_VERSION: 2
      -- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl_static.a)
      -- Found NVTX: /usr/local/cuda-11.7/include
      -- Found NVTX (include: /usr/local/cuda-11.7/include, library: dl)
      -- The C compiler identification is GNU 11.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Gloo build as STATIC library
      -- Found MPI_C: /usr/local/lib/libmpi.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1")
      -- MPI include path: /usr/local/include
      -- MPI libraries: /usr/local/lib/libmpi.so
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'tensorflow'
      -- Could NOT find Tensorflow (missing: Tensorflow_LIBRARIES) (Required is at least version "1.15.0")
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'torch'
      CMake Error at /opt/cmake-3.26.3-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Pytorch: (Required is at least version "1.5.0") (found )
      Call Stack (most recent call first):
        /opt/cmake-3.26.3-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
        cmake/Modules/FindPytorch.cmake:20 (find_package_handle_standard_args)
        horovod/torch/CMakeLists.txt:12 (find_package)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>                                                                                                       [326/768]        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d/setup.py", line 213, in <module>
          setup(name='horovod',
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/root/anaconda3/envs/horovod/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d/setup.py", line 145, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/root/anaconda3/envs/horovod/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-4jmqjdqt/horovod_b092ad354ccf4e93896fc6618e5df32d/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE:FILEPATH=/root/anaconda3/envs/horovod/bin/python']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
  Building wheel for lit (setup.py) ... done
  Created wheel for lit: filename=lit-16.0.2-py3-none-any.whl size=88174 sha256=c962f3854af9b409b23db49b3f23247a7c9808deddb38e02e9da07b8445e6c41
  Stored in directory: /tmp/pip-ephem-wheel-cache-4aaqazn5/wheels/bf/a0/7c/a850abc2cfad92656c1bc61795c340ce1f741c1686ad9f0908
Successfully built lit
Failed to build horovod
```

**Comment by maxhgerlach** [comment]
You need to ensure that `pytorch` is installed in your environment before you install Horovod.

**Comment by fahadh4ilyas** [comment]
> You need to ensure that `pytorch` is installed in your environment before you install Horovod.

You can see that in the errror, Tensorflow is also needed even tough I clearly write `horovod[pytorch]`.

Even after I install Pytorch first, `horovodrun --check-build` did not detect it
```
Horovod v0.27.0:

Available Frameworks:
    [ ] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [ ] MPI
    [ ] Gloo
```

This is really weird because when I install it on another computer, it's working perfectly.

**Comment by maxhgerlach** [comment]
> You can see that in the errror, Tensorflow is also needed even tough I clearly write horovod[pytorch].

No, you can disregard that message if you don't want TensorFlow support. It only failed after the pytorch check because you explicitly demanded `HOROVOD_WITH_PYTORCH=1`.

Are you able to reproduce the problem in a clean virtual environment where you did nothing but `pip install pytorch` before installing Horovod?

**Comment by fahadh4ilyas** [comment]
> HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod[pytorch]

Like I said before, after running `horovodrun --check-build`, the result is this:
```
Horovod v0.27.0:

Available Frameworks:
    [ ] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [ ] MPI
    [ ] Gloo
```

**Comment by fahadh4ilyas** [comment]
[horovod.log](https://github.com/horovod/horovod/files/11342227/horovod.log)

Here is the log from installing horovod

**Comment by maxhgerlach** [comment]
> [horovod.log](https://github.com/horovod/horovod/files/11342227/horovod.log)
> 
> Here is the log from installing horovod

This is different from your original posting. This time pytorch is found during the Horovod build.

> Are you able to reproduce the problem in a clean virtual environment where you did nothing but pip install pytorch before installing Horovod?

You didn't answer the question. 

Also it looks like you are using conda. I have no experience with that personally, but I think other people posted related issues here and found conda-specific help.

**Comment by fahadh4ilyas** [comment]
> > You need to ensure that `pytorch` is installed in your environment before you install Horovod.
> 
> You can see that in the errror, Tensorflow is also needed even tough I clearly write `horovod[pytorch]`.
> 
> Even after I install Pytorch first, `horovodrun --check-build` did not detect it
> 
> ```
> Horovod v0.27.0:
> 
> Available Frameworks:
>     [ ] TensorFlow
>     [ ] PyTorch
>     [ ] MXNet
> 
> Available Controllers:
>     [ ] MPI
>     [ ] Gloo
> 
> Available Tensor Operations:
>     [ ] NCCL
>     [ ] DDL
>     [ ] CCL
>     [ ] MPI
>     [ ] Gloo
> ```
> 
> This is really weird because when I install it on another computer, it's working perfectly.

I literally already said that "Even after I install Pytorch first, `horovodrun --check-build` did not detect it". What do you mean I didn't answer the question?

And no. This is not conda spesific problem. If it is, I can not install it in all of my servers. But, I already installed it succesfully in one of my servers.

**Comment by maxhgerlach** [comment]
> I literally already said that "Even after I install Pytorch first, horovodrun --check-build did not detect it". What do you mean I didn't answer the question?

You didn't answer whether you tried the following:

```
python -m venv temp
source temp/bin/activate
python -m pip install --no-cache-dir pytorch
HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL python -m pip install -v --no-cache-dir horovod[pytorch]
```

**Comment by fahadh4ilyas** [comment]
> > I literally already said that "Even after I install Pytorch first, horovodrun --check-build did not detect it". What do you mean I didn't answer the question?
> 
> You didn't answer whether you tried the following:
> 
> ```
> python -m venv temp
> source temp/bin/activate
> python -m pip install --no-cache-dir pytorch
> HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL python -m pip install -v --no-cache-dir horovod[pytorch]
> ```
> 
> > And no. This is not conda spesific problem. If it is, I can not install it in all of my servers. But, I already installed it succesfully in one of my servers.
> 
> So most likely the environment differs on one of your servers in a way that the specific setup is broken there?

I already tried in a new "conda" environment and still not working. Even when I tried in a new environment on my already successful server, the installation is success. But, when I tried again and again on another server, always failed. The difference is only on OS version. My successful server is using Ubuntu 18.04 where the failure server is using Ubuntu 22.04. Is there a possibility that the OS version might be the problem?
