### ISSUE TITLE
Error in Horovod installation

### ISSUE THREAD

**Issue by AmirHex** [horovod/horovod#401]
Hi, 

I tried to install horovod on linux. I see the following error log. I appreciate if you can help me with the error?

Collecting horovod
  Downloading https://files.pythonhosted.org/packages/2c/7e/54f7759bc693ab19480c1b525decab5c1d846cd5fc3af97bda18364a1aa5/horovod-0.13.10.tar.gz (100kB)
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.18)
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod: started
  Running setup.py bdist_wheel for horovod: finished with status 'error'
  Complete output from command /home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qa7_bzmk/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-344jssst --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
  creating build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
  creating build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
  creating build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
  creating build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  running build_ext
  gcc -pthread -B /home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/user/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  gcc -pthread -shared -B /home/user/anaconda3/compiler_compat -L/home/user/anaconda3/lib -Wl,-rpath=/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
  /home/user/anaconda3/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
  /home/user/anaconda3/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
  INFO: Unable to build TensorFlow plugin, will skip it.
  
  Traceback (most recent call last):
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 52, in check_tf_version
      import tensorflow as tf
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/install_sources#common_installation_problems
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 588, in build_extensions
      abi_compile_flags = build_tf_extension(self, options)
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 441, in build_tf_extension
      check_tf_version()
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 59, in check_tf_version
      'import tensorflow failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import tensorflow failed, is it installed?
  
  Traceback (most recent call last):
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 52, in check_tf_version
      import tensorflow as tf
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/install_sources#common_installation_problems
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  
  
  INFO: Unable to build PyTorch plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 471, in check_torch_import
      import torch
    File "/home/user/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
      from torch._C import *
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 599, in build_extensions
      build_torch_extension(self, options, abi_compile_flags)
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 519, in build_torch_extension
      check_torch_import()
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 474, in check_torch_import
      'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 471, in check_torch_import
      import torch
    File "/home/user/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
      from torch._C import *
  ImportError: /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)
  
  
  error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
  
  ----------------------------------------
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod: started
    Running setup.py install for horovod: finished with status 'error'
    Complete output from command /home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qa7_bzmk/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-nq7ym760/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    running build_ext
    gcc -pthread -B /home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/user/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/user/anaconda3/compiler_compat -L/home/user/anaconda3/lib -Wl,-rpath=/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    /home/user/anaconda3/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
    /home/user/anaconda3/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
    INFO: Unable to build TensorFlow plugin, will skip it.
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 52, in check_tf_version
        import tensorflow as tf
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/install_sources#common_installation_problems
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 588, in build_extensions
        abi_compile_flags = build_tf_extension(self, options)
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 441, in build_tf_extension
        check_tf_version()
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 59, in check_tf_version
        'import tensorflow failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import tensorflow failed, is it installed?
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 52, in check_tf_version
        import tensorflow as tf
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/user/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/install_sources#common_installation_problems
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    
    
    INFO: Unable to build PyTorch plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 471, in check_torch_import
        import torch
      File "/home/user/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
        from torch._C import *
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 599, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 519, in build_torch_extension
        check_torch_import()
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 474, in check_torch_import
        'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qa7_bzmk/horovod/setup.py", line 471, in check_torch_import
        import torch
      File "/home/user/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
        from torch._C import *
    ImportError: /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)
    
    
    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
    
    ----------------------------------------

**Comment by alsrgv** [comment]
As per [this thread](https://github.com/ContinuumIO/anaconda-issues/issues/483), folks recommend trying `conda install libgcc`.

**Comment by ghltshubh** [comment]
Is this error solved. I think anybody using conda will face this issue: https://github.com/conda-forge/libgfortran-feedstock/issues/15#issuecomment-421184741
