### ISSUE TITLE
Error install Horovod with python-3.11.5 on macos  11.3.1

### ISSUE THREAD

**Issue by DriverSong** [horovod/horovod#4012]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.12.0
3. Horovod version:  v0.28.1
4. MPI version: X
5. CUDA version: X
6. NCCL version: X
7. Python version: 3.11.5
8. Spark / PySpark version: X
9. Ray version:  2.9.0
10. OS and version: macOS 11.3.1
11. GCC version: 9.5.0
12. CMake version: 3.28.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
The install cmd:  
`pip install 'horovod[tensorflow]'`  

The envs:  
`HOROVOD_WITH_TENSORFLOW=1
HOROVOD_WITHOUT_PYTORCH=1
HOROVOD_WITHOUT_MXNET=1`   

The errors:  
`      running install_scripts
      [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
      build/bdist.macosx-10.9-x86_64/wheel/horovod/tensorflow/mpi_lib.cpython-311-darwin.soTraceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/7t/kj0yg5_x5c398pp4jht7p6tm0000gp/T/pip-install-q40x46lh/horovod_611b3167fef94970beb553a171d240da/setup.py", line 213, in <module>
          setup(name='horovod',
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
                                        ^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
                 ^^^^^^^^^^^^^^^^^^^^^
      AssertionError: would build wheel with unsupported tag ('cp311', 'cp311', 'macosx_11_0_x86_64')`

**Comment by DriverSong** [comment]
The formatted errors
```shell
      running install_scripts
      [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
      build/bdist.macosx-10.9-x86_64/wheel/horovod/tensorflow/mpi_lib.cpython-311-darwin.soTraceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/7t/kj0yg5_x5c398pp4jht7p6tm0000gp/T/pip-install-q40x46lh/horovod_611b3167fef94970beb553a171d240da/setup.py", line 213, in <module>
          setup(name='horovod',
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
                                        ^^^^^^^^^^^^^^
        File "/Users/qiujiawei9/anaconda3/envs/ray-examples/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
                 ^^^^^^^^^^^^^^^^^^^^^
      AssertionError: would build wheel with unsupported tag ('cp311', 'cp311', 'macosx_11_0_x86_64')
```
