### ISSUE TITLE
Index out of range for list of gpus

### ISSUE THREAD

**Issue by laytonjbgmail** [horovod/horovod#4065]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)  Tensorflow
2. Framework version: Whatever is in latest horovod container from docker hub (2.9.2)
3. Horovod version: Whatever is in latest docker hub image (not sure)
4. MPI version: OpenMPI 4.1.4
5. CUDA version: Whatever is in latest docker hub image (not sure)
6. NCCL version:Whatever is in latest docker hub image (not sure)
7. Python version: 3.8.10
8. Spark / PySpark version: Whatever is in latest docker hub image (not sure)
9. Ray version: Whatever is in latest docker hub image (not sure)
10. OS and version:  Ubuntu 20.04.5
11. GCC version: 9.4.0
12. CMake version: Whatever is in latest docker hub image (not sure)

**Checklist:**
1. Did you search issues to find if somebody asked this question before?  Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I was following the guidance in using Horovod with a TF 2.x code to initialize the GPUs. The on-line manual lin is,

https://horovod.readthedocs.io/en/stable/tensorflow.html

In the link there is the following code:

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

In my case I'm getting a "list out of range" message for the last line.

I'm running on two nodes with 8 GPUs each for a total of 16 GPUs. However, the length of the list "gpus" is only 8. Shouldn't the length be 16? Otherwise the list is too small and "hvd.local_rank()" is greater than 7 because it is on the second node and the list is too short.

Any tips?

Thanks!

**Comment by laytonjbgmail** [comment]
To add a little more to the report, I'm using two nodes with 8 GPUs per node for a 16 GPU, 2 Node run of my code. When I run local_rank() and rank(), I get the following.

print("Horovod local rank = ",hvd.local_rank(), " rank = ",hvd.rank(), flush=True)

Horovod local rank =  10  rank =  10
Horovod local rank =  0  rank =  0
Horovod local rank =  2  rank =  2
Horovod local rank =  3  rank =  3
Horovod local rank =  6  rank =  6
Horovod local rank =  8  rank =  8
Horovod local rank =  11  rank =  11
Horovod local rank =  15  rank =  15
Horovod local rank =  9  rank =  9
Horovod local rank =  13  rank =  13
Horovod local rank =  1  rank =  1
Horovod local rank =  12  rank =  12
Horovod local rank =  5  rank =  5
Horovod local rank =  4  rank =  4
Horovod local rank =  7  rank =  7
Horovod local rank =  14  rank =  14

Is the local rank supposed to be the same as the "global" rank when there are more than one node?

**Comment by laytonjbgmail** [comment]
The next part of the code is the following:

gpus = tf.config.experimental.list_physical_devices('GPU')



if (hvd.local_rank() == 0):
    print(" ", flush=True)
    print("gpus = ", gpus, flush=True)
# end if

for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
# end for
if gpus:
    print("local_rank = ", hvd.local_rank(), " rank = ",hvd.rank(), " len(gpus) = ", len(gpus), flush=True)
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
# end if

I get an error:

Traceback (most recent call last):
  File "/home/jelayton/BERT_SCRIPT/NEW_BERT/new_bert_02.py", line 220, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/jelayton/BERT_SCRIPT/NEW_BERT/new_bert_02.py", line 220, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/jelayton/BERT_SCRIPT/NEW_BERT/new_bert_02.py", line 220, in <module>
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
IndexError: list index out of range

Line 220 is the tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

The length of the list "gpus" is only 8 but there are 16 ranks. The list of gpus is obtained with this line:

gpus = tf.config.experimental.list_physical_devices('GPU')

It appears that this function call is only returning the GPUs on the first node.

Thanks!
