### ISSUE TITLE
Failed to install Horovod

### ISSUE THREAD

**Issue by adityakm24** [horovod/horovod#4073]
**Environment:**
1. **Framework**: TensorFlow, PyTorch
2. **Framework version**:
   - TensorFlow: 2.18.0
   - PyTorch: 2.4.1
3. **Horovod version**: Attempting to install latest via pip
4. **MPI version**: Microsoft MPI (attempted with version 10)
5. **CUDA version**: 11.8
6. **NCCL version**: None
7. **Python version**: 3.11.9
8. **Spark / PySpark version**: N/A
9. **Ray version**: N/A
10. **OS and version**: Windows 10
11. **GCC version**: Not installed (Windows environment)
12. **CMake version**: 3.30

---

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if your question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

---

**Bug report:**
I'm encountering issues installing Horovod on Windows 10 with TensorFlow and PyTorch frameworks. Here’s a summary of the setup and error details:

**Steps Taken**:
1. Set environment variables:
   ```cmd
   set HOROVOD_WITH_MPI=1
   set HOROVOD_WITH_CUDA=1
   set HOROVOD_CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
   set MPI_HOME="E:/Program Files/Microsoft MPI"
   set MPIEXEC_EXECUTABLE="E:\Program Files\Microsoft MPI\Bin\mpiexec.exe"
   ```
2. Attempted installation command:
   ```bash
   pip install horovod --no-cache-dir
   ```

**Error**:
```plaintext
Could NOT find MPI (missing: MPI_CXX_FOUND)
CMake Error: The source directory "E:/Projects" does not appear to contain CMakeLists.txt.
```

**Additional Details**:
- Running `mpiexec --version` did not provide the expected version output.
- Verified CUDA 11.8 installation via `nvcc --version`.
- Using Microsoft MPI, but suspect compatibility issues with Horovod on Windows.

**Comment by adityakm24** [comment]
```
(ML) E:\Projects\Eye-Prediction>pip install horovod                                                                                                     
DEPRECATION: Loading egg at e:\users\aditya\anaconda3\envs\ml\lib\site-packages\huggingface_hub-0.23.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting horovod
  Using cached horovod-0.28.1.tar.gz (3.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cloudpickle in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from horovod) (3.1.0)
Requirement already satisfied: psutil in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from horovod) (6.0.0)
Requirement already satisfied: pyyaml in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from horovod) (6.0.1)
Requirement already satisfied: packaging in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from horovod) (23.2)
Requirement already satisfied: cffi>=1.4.0 in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from horovod) (1.16.0)
Requirement already satisfied: pycparser in e:\users\aditya\anaconda3\envs\ml\lib\site-packages (from cffi>=1.4.0->horovod) (2.21)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [264 lines of output]
      E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-311\horovod
      copying horovod\__init__.py -> build\lib.win-amd64-cpython-311\horovod
      creating build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\basics.py -> build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\elastic.py -> build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\exceptions.py -> build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\process_sets.py -> build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\util.py -> build\lib.win-amd64-cpython-311\horovod\common
      copying horovod\common\__init__.py -> build\lib.win-amd64-cpython-311\horovod\common
      creating build\lib.win-amd64-cpython-311\horovod\data
      copying horovod\data\data_loader_base.py -> build\lib.win-amd64-cpython-311\horovod\data
      copying horovod\data\__init__.py -> build\lib.win-amd64-cpython-311\horovod\data
      creating build\lib.win-amd64-cpython-311\horovod\keras
      copying horovod\keras\callbacks.py -> build\lib.win-amd64-cpython-311\horovod\keras
      copying horovod\keras\elastic.py -> build\lib.win-amd64-cpython-311\horovod\keras
      copying horovod\keras\__init__.py -> build\lib.win-amd64-cpython-311\horovod\keras
      creating build\lib.win-amd64-cpython-311\horovod\mxnet
      copying horovod\mxnet\compression.py -> build\lib.win-amd64-cpython-311\horovod\mxnet
      copying horovod\mxnet\functions.py -> build\lib.win-amd64-cpython-311\horovod\mxnet
      copying horovod\mxnet\mpi_ops.py -> build\lib.win-amd64-cpython-311\horovod\mxnet
      copying horovod\mxnet\__init__.py -> build\lib.win-amd64-cpython-311\horovod\mxnet
      creating build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\adapter.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\driver_service.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\elastic.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\elastic_v2.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\ray_logger.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\runner.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\strategy.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\utils.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\worker.py -> build\lib.win-amd64-cpython-311\horovod\ray
      copying horovod\ray\__init__.py -> build\lib.win-amd64-cpython-311\horovod\ray
      creating build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\gloo_run.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\js_run.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\launch.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\mpi_run.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\run_task.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\task_fn.py -> build\lib.win-amd64-cpython-311\horovod\runner
      copying horovod\runner\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner
      creating build\lib.win-amd64-cpython-311\horovod\spark
      copying horovod\spark\conf.py -> build\lib.win-amd64-cpython-311\horovod\spark
      copying horovod\spark\gloo_run.py -> build\lib.win-amd64-cpython-311\horovod\spark
      copying horovod\spark\mpi_run.py -> build\lib.win-amd64-cpython-311\horovod\spark
      copying horovod\spark\runner.py -> build\lib.win-amd64-cpython-311\horovod\spark
      copying horovod\spark\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark
      creating build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\compression.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\elastic.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\functions.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\gradient_aggregation.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\gradient_aggregation_eager.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\mpi_ops.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\sync_batch_norm.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\util.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      copying horovod\tensorflow\__init__.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow
      creating build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\compression.py -> build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\functions.py -> build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\mpi_ops.py -> build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\optimizer.py -> build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\sync_batch_norm.py -> build\lib.win-amd64-cpython-311\horovod\torch
      copying horovod\torch\__init__.py -> build\lib.win-amd64-cpython-311\horovod\torch
      creating build\lib.win-amd64-cpython-311\horovod\_keras
      copying horovod\_keras\callbacks.py -> build\lib.win-amd64-cpython-311\horovod\_keras
      copying horovod\_keras\elastic.py -> build\lib.win-amd64-cpython-311\horovod\_keras
      copying horovod\_keras\__init__.py -> build\lib.win-amd64-cpython-311\horovod\_keras
      creating build\lib.win-amd64-cpython-311\horovod\runner\common
      copying horovod\runner\common\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\common
      creating build\lib.win-amd64-cpython-311\horovod\runner\driver
      copying horovod\runner\driver\driver_service.py -> build\lib.win-amd64-cpython-311\horovod\runner\driver
      copying horovod\runner\driver\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\driver
      creating build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\constants.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\discovery.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\driver.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\registration.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\rendezvous.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\settings.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\worker.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      copying horovod\runner\elastic\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\elastic
      creating build\lib.win-amd64-cpython-311\horovod\runner\http
      copying horovod\runner\http\http_client.py -> build\lib.win-amd64-cpython-311\horovod\runner\http
      copying horovod\runner\http\http_server.py -> build\lib.win-amd64-cpython-311\horovod\runner\http
      copying horovod\runner\http\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\http
      creating build\lib.win-amd64-cpython-311\horovod\runner\task
      copying horovod\runner\task\task_service.py -> build\lib.win-amd64-cpython-311\horovod\runner\task
      copying horovod\runner\task\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\task
      creating build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\cache.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\lsf.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\network.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\remote.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\streams.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\threads.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      copying horovod\runner\util\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\util
      creating build\lib.win-amd64-cpython-311\horovod\runner\common\service
      copying horovod\runner\common\service\compute_service.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\service
      copying horovod\runner\common\service\driver_service.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\service
      copying horovod\runner\common\service\task_service.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\service
      copying horovod\runner\common\service\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\service
      creating build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\codec.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\config_parser.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\env.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\hosts.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\host_hash.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\network.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\safe_shell_exec.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\secret.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\settings.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\timeout.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\tiny_shell_exec.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      copying horovod\runner\common\util\__init__.py -> build\lib.win-amd64-cpython-311\horovod\runner\common\util
      creating build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\backend.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\cache.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\constants.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\datamodule.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\estimator.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\params.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\serialization.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\store.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\util.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\_namedtuple_fix.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      copying horovod\spark\common\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\common
      creating build\lib.win-amd64-cpython-311\horovod\spark\data_loaders
      copying horovod\spark\data_loaders\pytorch_data_loaders.py -> build\lib.win-amd64-cpython-311\horovod\spark\data_loaders
      copying horovod\spark\data_loaders\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\data_loaders
      creating build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\driver_service.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\host_discovery.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\job_id.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\mpirun_rsh.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\rendezvous.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\rsh.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      copying horovod\spark\driver\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\driver
      creating build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\bare.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\datamodule.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\estimator.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\optimizer.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\remote.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\tensorflow.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\util.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      copying horovod\spark\keras\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\keras
      creating build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\datamodule.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\estimator.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\legacy.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\remote.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\util.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      copying horovod\spark\lightning\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\lightning
      creating build\lib.win-amd64-cpython-311\horovod\spark\task
      copying horovod\spark\task\gloo_exec_fn.py -> build\lib.win-amd64-cpython-311\horovod\spark\task
      copying horovod\spark\task\mpirun_exec_fn.py -> build\lib.win-amd64-cpython-311\horovod\spark\task
      copying horovod\spark\task\task_info.py -> build\lib.win-amd64-cpython-311\horovod\spark\task
      copying horovod\spark\task\task_service.py -> build\lib.win-amd64-cpython-311\horovod\spark\task
      copying horovod\spark\task\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\task
      creating build\lib.win-amd64-cpython-311\horovod\spark\tensorflow
      copying horovod\spark\tensorflow\compute_worker.py -> build\lib.win-amd64-cpython-311\horovod\spark\tensorflow
      copying horovod\spark\tensorflow\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\tensorflow
      creating build\lib.win-amd64-cpython-311\horovod\spark\torch
      copying horovod\spark\torch\datamodule.py -> build\lib.win-amd64-cpython-311\horovod\spark\torch
      copying horovod\spark\torch\estimator.py -> build\lib.win-amd64-cpython-311\horovod\spark\torch
      copying horovod\spark\torch\remote.py -> build\lib.win-amd64-cpython-311\horovod\spark\torch
      copying horovod\spark\torch\util.py -> build\lib.win-amd64-cpython-311\horovod\spark\torch
      copying horovod\spark\torch\__init__.py -> build\lib.win-amd64-cpython-311\horovod\spark\torch
      creating build\lib.win-amd64-cpython-311\horovod\tensorflow\data
      copying horovod\tensorflow\data\compute_service.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\data
      copying horovod\tensorflow\data\compute_worker.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\data
      copying horovod\tensorflow\data\__init__.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\data
      creating build\lib.win-amd64-cpython-311\horovod\tensorflow\keras
      copying horovod\tensorflow\keras\callbacks.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\keras
      copying horovod\tensorflow\keras\elastic.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\keras
      copying horovod\tensorflow\keras\__init__.py -> build\lib.win-amd64-cpython-311\horovod\tensorflow\keras
      creating build\lib.win-amd64-cpython-311\horovod\torch\elastic
      copying horovod\torch\elastic\sampler.py -> build\lib.win-amd64-cpython-311\horovod\torch\elastic
      copying horovod\torch\elastic\state.py -> build\lib.win-amd64-cpython-311\horovod\torch\elastic
      copying horovod\torch\elastic\__init__.py -> build\lib.win-amd64-cpython-311\horovod\torch\elastic
      running build_ext
      Running CMake in build\temp.win-amd64-cpython-311\Release\RelWithDebInfo:
      E:\Users\ADITYA\anaconda3\envs\ML\Scripts\cmake.exe C:\Users\ADITYA\AppData\Local\Temp\pip-install-ngq9szr7\horovod_b79f5ea43a844a69addef3269b67896f -DCMAKE_BUILD_TYPE=RelWit
hDebInfo -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=C:\Users\ADITYA\AppData\Local\Temp\pip-install-ngq9szr7\horovod_b79f5ea43a844a69addef3269b67896f\build\lib.win-amd64-cpython-311 -DPYTHON_EXECUTABLE:FILEPATH=E:\Users\ADITYA\anaconda3\envs\ML\python.exe
      E:\Users\ADITYA\anaconda3\envs\ML\Scripts\cmake.exe --build . --config RelWithDebInfo -- -j8 VERBOSE=1
      -- Building for: Visual Studio 16 2019
      -- Could not find CCache. Consider installing CCache to speed up compilation.
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22631.
      -- The CXX compiler identification is MSVC 19.29.30156.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Build architecture flags:
      -- Using command E:/Users/ADITYA/anaconda3/envs/ML/python.exe
      -- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
      CMake Error at E:/Users/ADITYA/anaconda3/envs/ML/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
        Could NOT find MPI (missing: MPI_CXX_FOUND)
      Call Stack (most recent call first):
        E:/Users/ADITYA/anaconda3/envs/ML/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
        E:/Users/ADITYA/anaconda3/envs/ML/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/FindMPI.cmake:1841 (find_package_handle_standard_args)
        CMakeLists.txt:138 (find_package)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ADITYA\AppData\Local\Temp\pip-install-ngq9szr7\horovod_b79f5ea43a844a69addef3269b67896f\setup.py", line 213, in <module>
          setup(name='horovod',
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\dist.py", line 991, in run_command
          super().run_command(command)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\command\bdist_wheel.py", line 407, in run
          self.run_command("build")
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\dist.py", line 991, in run_command
          super().run_command(command)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\dist.py", line 991, in run_command
          super().run_command(command)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\command\build_ext.py", line 98, in run
          _build_ext.run(self)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\ADITYA\AppData\Local\Temp\pip-install-ngq9szr7\horovod_b79f5ea43a844a69addef3269b67896f\setup.py", line 145, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "E:\Users\ADITYA\anaconda3\envs\ML\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['E:\\Users\\ADITYA\\anaconda3\\envs\\ML\\Scripts\\cmake.exe', 'C:\\Users\\ADITYA\\AppData\\Local\\Temp\\pip-install-ngq9szr7\\horovod
_b79f5ea43a844a69addef3269b67896f', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=C:\\Users\\ADITYA\\AppData\\Local\\Temp\\pip-install-ngq9s
zr7\\horovod_b79f5ea43a844a69addef3269b67896f\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE:FILEPATH=E:\\Users\\ADITYA\\anaconda3\\envs\\ML\\python.exe']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (horovod)

(ML) E:\Projects\Eye-Prediction>x


```

**Comment by Sowrabh0-0** [comment]
Thanks

**Comment by aashikrasool** [comment]
I'm also facing the same issue

**Comment by kingsman1960** [comment]
Still facing issue..... Can't run the project code :(

**Comment by Emre-Baris** [comment]
I am also facing the issue anyone with any fixes?
