### ISSUE TITLE
IOError: [Errno 4] Interrupted system call

### ISSUE THREAD

**Issue by Jongchan** [horovod/horovod#553]
I am using Horovod upon 4 Azure VMs (NC24s_v2 with 4 P100 GPUs) with docker setups.

The training process is okay for many epochs (~100 epochs), but I see an error which ends the training. I have tried 2 times, with 2 nodes / 4 nodes respectively. 
Both cases ended with the same error.

The code with the error is at the "print" line
```
def train(epoch):
    net.train()
    train_loss = 0
    correct = 0
    total = 0

    print('\n=> Training Epoch #%d, LR=%.4f' %(epoch, cf.learning_rate(args.lr*batch_size, epoch, args.warmup_epoch, 0, len(trainloader), hvd.size())))
    ...
```

The error message is as below
```
Traceback (most recent call last):
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 336, in <module>
    train(epoch)
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 274, in train
    print('\n=> Training Epoch #%d, LR=%.4f' %(epoch, cf.learning_rate(args.lr*batch_size, epoch, args.warmup_epoch, 0, len(trainloader), hvd.size())))
IOError: [Errno 4] Interrupted system call
Traceback (most recent call last):
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 336, in <module>
    train(epoch)
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 285, in train
    loss.backward()  # Backward Propagation
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/__init__.py", line 84, in hook
    handle = allreduce_async_(tensor_compressed, average=True, name=name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 173, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 78, in _allreduce_async
    name.encode() if name is not None else _NULL)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 336, in <module>
    train(epoch)
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 285, in train
    loss.backward()  # Backward Propagation
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/__init__.py", line 84, in hook
    handle = allreduce_async_(tensor_compressed, average=True, name=name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 173, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 78, in _allreduce_async
    name.encode() if name is not None else _NULL)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 336, in <module>
    train(epoch)
  File "Pytorch-Horovod-Examples/examples/cifar100/main_horovod.py", line 285, in train
    loss.backward()  # Backward Propagation
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/__init__.py", line 84, in hook
    handle = allreduce_async_(tensor_compressed, average=True, name=name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 173, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/usr/local/lib/python2.7/dist-packages/horovod/torch/mpi_ops.py", line 78, in _allreduce_async
    name.encode() if name is not None else _NULL)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36774,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

During the first trial, I used 2 nodes with 8 processes (1 GPU per proc), ended at 95 epoch (~1.5 hours)
During the second trial, I used 4 nodes with 4 processes (4 GPU per proc), ended at 133 epochs (~54 minutes)

My mpirun code is as below
```
mpirun -np 4 -H localhost:1,host1:1,host2:1,host3:1 -mca plm_rsh_args "-p 22222"  <python script>
```

Do you know why such error occurs?

**Comment by alsrgv** [comment]
@Jongchan, here Python 2.7 is blamed https://github.com/pytorch/pytorch/issues/7364.  Can you try running the code using Python 3.5+?
