### ISSUE TITLE
mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by Aki57** [horovod/horovod#656]
Environment:
- CentOS Linux release 7.5.1804 (Core)
- Python 3.6.5
- CUDA 9.2
- NCCL 2.3.7
- Tensorflow-GPU 1.11.0
- OpenMPI 3.1.1
- Horovod 0.15.1

Horovod is installed with pip, using the comand of `HOROVOD_NCCL_HOME=/usr/local/nccl-<version> HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`.

Error Info:
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 37, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 58, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow8OpKernel4nameEv
```
I've got this problem for week, anyone have the same problem or any advice?

**Comment by Aki57** [comment]
```
(gpu7) [qiuhanh@gpu-1-7 tensorflow]$ ldd mpi_lib.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffe2d9d4000)
        libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00007f9000ce0000)
        libmpi.so.40 => /home/qiuhanh/local/openmpi/lib/libmpi.so.40 (0x00007f90009e5000)
        libtensorflow_framework.so => not found
        libstdc++.so.6 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libstdc++.so.6 (0x00007f9005b51000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f90006e3000)
        libgcc_s.so.1 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libgcc_s.so.1 (0x00007f9005b3b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f90004c7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f90000fa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9005a80000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8fffef6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f8fffcee000)
        libopen-rte.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-rte.so.40 (0x00007f8fffa39000)
        libopen-pal.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-pal.so.40 (0x00007f8fff732000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f8fff52f000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f8fff319000)
```

**Comment by Aki57** [comment]
I have found `libtensorflow_framework.so` in the directionary `/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow`, how to solve the link?

**Comment by Aki57** [comment]
And I used conda installing tensorflow-gpu, and use pip for horovod. Is this the reason?

**Comment by tgaddair** [comment]
Hey @Aki57, you need to add that .so file to your `LD_LIBRARY_PATH`.  It looks like you're running outside your conda environment.  If you installed horovod to system paths, then it shouldn't be an issue to try running Horovod from within your conda environment.

**Comment by Aki57** [comment]
Sorry for late reply :-)
I have tried adding the missing .so file to the system path, and the error was going on.
```
[qiuhanh@gpu-1-7 ~]$ source activate gpu7
(gpu7) [qiuhanh@gpu-1-7 ~]$ cd miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/
(gpu7) [qiuhanh@gpu-1-7 tensorflow]$ ldd mpi_lib.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffe82bc0000)
        libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00007fb5e7321000)
        libpython3.6m.so.1.0 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libpython3.6m.so.1.0 (0x00007fb5e6e1c000)
        libmpi.so.40 => /home/qiuhanh/local/openmpi/lib/libmpi.so.40 (0x00007fb5e6b21000)
        libtensorflow_framework.so => not found
        libstdc++.so.6 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libstdc++.so.6 (0x00007fb5ec191000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb5e681f000)
        libgcc_s.so.1 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libgcc_s.so.1 (0x00007fb5ec17c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb5e6603000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb5e6236000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb5ec0c1000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb5e6032000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb5e5e2a000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fb5e5c27000)
        libopen-rte.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-rte.so.40 (0x00007fb5e5972000)
        libopen-pal.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-pal.so.40 (0x00007fb5e566b000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb5e5455000)
(gpu7) [qiuhanh@gpu-1-7 tensorflow]$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/
(gpu7) [qiuhanh@gpu-1-7 tensorflow]$ ldd mpi_lib.cpython-36m-x86_64-linux-gnu.so                                                            linux-vdso.so.1 =>  (0x00007ffd51366000)
        libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00007f4cfd7d7000)
        libpython3.6m.so.1.0 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libpython3.6m.so.1.0 (0x00007f4cfd2d2000)
        libmpi.so.40 => /home/qiuhanh/local/openmpi/lib/libmpi.so.40 (0x00007f4cfcfd7000)
        libtensorflow_framework.so => /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/libtensorflow_framework.so (0x00007f4cfc0bf000)
        libstdc++.so.6 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libstdc++.so.6 (0x00007f4d02654000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4cfbdbd000)
        libgcc_s.so.1 => /home/qiuhanh/miniconda3/envs/gpu7/lib/libgcc_s.so.1 (0x00007f4d02632000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4cfbba1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4cfb7d4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4d02577000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4cfb5d0000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4cfb3c8000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f4cfb1c5000)
        libopen-rte.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-rte.so.40 (0x00007f4cfaf10000)
        libopen-pal.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-pal.so.40 (0x00007f4cfac09000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4cfa9f3000)
        libcublas.so.9.2 => /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/../../../libcublas.so.9.2 (0x00007f4cf6fa2000)
        libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f4cf5ea2000)
        libcudnn.so.7 => /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/../../../libcudnn.so.7 (0x00007f4ce490a000)
        libcufft.so.9.2 => /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/../../../libcufft.so.9.2 (0x00007f4cdf2ae000)
        libcurand.so.9.2 => /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/../../../libcurand.so.9.2 (0x00007f4cdb36f000)
        libnvidia-fatbinaryloader.so.410.73 => /lib64/libnvidia-fatbinaryloader.so.410.73 (0x00007f4cdb122000)
(gpu7) [qiuhanh@gpu-1-7 tensorflow]$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 37, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 58, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/qiuhanh/miniconda3/envs/gpu7/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow8OpKernel4nameEv
>>>
```
Actually I have setuped an environment on another machine, and I found some thing wried.
```
(gpu4) [qiuhanh@gpu-1-4 tensorflow]$ ldd mpi_lib.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffd7550d000)
        libmpi.so.40 => /home/qiuhanh/local/openmpi/lib/libmpi.so.40 (0x00007f85e06a2000)
        libtensorflow_framework.so => not found
        libstdc++.so.6 => /home/qiuhanh/miniconda3/envs/gpu4/lib/libstdc++.so.6 (0x00007f85e054c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f85e024a000)
        libgcc_s.so.1 => /home/qiuhanh/miniconda3/envs/gpu4/lib/libgcc_s.so.1 (0x00007f85e0234000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f85e0018000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f85dfc4b000)
        libopen-rte.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-rte.so.40 (0x00007f85df995000)
        libopen-pal.so.40 => /home/qiuhanh/local/openmpi/lib/libopen-pal.so.40 (0x00007f85df68e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f85df48a000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f85df281000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f85df07e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f85dee68000)
        /lib64/ld-linux-x86-64.so.2 (0x000055c214ed1000)
(gpu4) [qiuhanh@gpu-1-4 tensorflow]$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import horovod.tensorflow as hvd
>>>
```
The .so file is not found but it still works.

So this this error may be caused by some mismatch error like #678  , but I'm not clear which is reason.

**Comment by alsrgv** [comment]
@Aki57, is it possible that you've upgraded TF after you've installed Horovod on the first machine?  Or that you installed Horovod while being outside of your Conda environment?

**Comment by YFwang1992** [comment]
same error

**Comment by YFwang1992** [comment]
i think i find a way to deal this error
ues pip install tensorflow except conda install  tensorflow
i dont know why but can word
https://github.com/uber/horovod/issues/431
if your cuda is 9.2 you cant pip ,so change cudu to 9.0 or 8.0

**Comment by Aki57** [comment]
@YFwang1992 Glad that you have found the solution.  Maybe 9.2 is not usable now. I'm not sure too.

**Comment by nicolefinnie** [comment]
> i think i find a way to deal this error
> ues pip install tensorflow except conda install tensorflow
> i dont know why but this really work for me ,you can infer this issue #431
> if your cuda is 9.2 you cant pip ,so change cudu to 9.0 or 8.0

If you can live with the pip tensorflow without MKL DNN performance libraries, you can find "solutions" in the issue #431.  The current pip tensorflow 1.10~1.12 (or 1.13) is built with CUDA 9.0 (or 10.0) so it requires `libcublas.so.9.0` or `libcublas.so.10.0`. That's why you can't run it with CUDA 9.2.

**Comment by michaelkyu** [comment]
I'm also getting the same error. Any ideas? Thanks!

My environment:

```
CentOS Linux release 7.6.1810 (Core)
CUDA 10.1
Python 3.7.3
tensorflow-gpu 1.13.1 (installed by conda)
Horovod 0.16.1 (installed by pip)
```

My install setup:

```
(horovod-test) [mikeyu ~]$ conda install tensorflow-gpu
(horovod-test) [mikeyu ~]$ pip install horovod
```

Error message:

```
(horovod-test) [mikeyu@ ~]$ python
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/horovod/tensorflow/__init__.py", line 38, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/horovod/tensorflow/mpi_ops.py", line 59, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/horovod/tensorflow/mpi_ops.py", line 46, in _load_library
    library = load_library.load_op_library(filename)
  File "/home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

However, this '.so' file does exist

```
(horovod-test) [mikeyu@ ~]$ ldd /home-nfs/mikeyu/anaconda3/envs/horovod-test/lib/python3.7/site-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc3371b000)
	libmpicxx.so.12 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/libmpicxx.so.12 (0x00007f7d95b70000)
	libmpi.so.12 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/libmpi.so.12 (0x00007f7d91e6c000)
	libtensorflow_framework.so => not found
	libstdc++.so.6 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/libstdc++.so.6 (0x00007f7d95a19000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7d91b6a000)
	libgcc_s.so.1 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/libgcc_s.so.1 (0x00007f7d95a03000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7d9194e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7d91581000)
	libgomp.so.1 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/./libgomp.so.1 (0x00007f7d959dc000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7d91379000)
	libgfortran.so.4 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/./libgfortran.so.4 (0x00007f7d9124b000)
	libquadmath.so.0 => /home-nfs/mikeyu/anaconda3/envs/ffn/lib/./libquadmath.so.0 (0x00007f7d959a7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d9596f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7d91047000)
```

Output of `conda list`

```
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.0                    py37_0  
astor                     0.7.1                    py37_0  
blas                      1.0                         mkl  
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py37_0  
cffi                      1.12.2                   pypi_0    pypi
cloudpickle               0.8.1                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.3.1                cuda10.0_0  
cupti                     10.0.130                      0  
gast                      0.2.2                    py37_0  
grpcio                    1.16.1           py37hf8bcb03_1  
h5py                      2.9.0            py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
horovod                   0.16.1                   pypi_0    pypi
intel-openmp              2019.3                      199  
keras-applications        1.0.7                      py_0  
keras-preprocessing       1.0.9                      py_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.6.1                hd408876_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
markdown                  3.0.1                    py37_0  
mkl                       2019.3                      199  
mkl_fft                   1.0.10           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
mock                      2.0.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.2           py37h7e9f1db_0  
numpy-base                1.16.2           py37hde5b4d6_0  
openssl                   1.1.1b               h7b6447c_1  
pbr                       5.1.3                      py_0  
pip                       19.0.3                   py37_0  
protobuf                  3.6.1            py37he6710b0_0  
psutil                    5.6.1                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
python                    3.7.3                h0371630_0  
readline                  7.0                  h7b6447c_5  
scipy                     1.2.1            py37h7c811a0_0  
setuptools                41.0.0                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.27.2               h7b6447c_0  
tensorboard               1.13.1           py37hf484d3e_0  
tensorflow                1.13.1          gpu_py37hc158e3b_0  
tensorflow-base           1.13.1          gpu_py37h8d69cac_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                    py37_1  
tk                        8.6.8                hbc83047_0  
werkzeug                  0.15.2                     py_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by alsrgv** [comment]
@michaelkyu, can you try to reinstall Horovod using `[flags] pip install --no-cache-dir horovod`?

**Comment by alsrgv** [comment]
@michaelkyu, @Aki57, I've been able to repro this internally and found a solution.

```
$ conda install gcc_linux-64 gxx_linux-64
```

The root cause of the issue is that Conda's TensorFlow is built with GCC 5+, while on the system you have GCC 4.x.  This solution upgrades GCC inside Anaconda to 7.2.0.

**Comment by nicolefinnie** [comment]
@alsrgv  thanks for reproducing this problem yourself, the misleading information was that the tensorflow doc states that the official tensorflow package is built with GCC4 ( [source](https://www.tensorflow.org/install/source) ) which is misleading, most people get the prebuilt tensorflow version from `conda` and that is apparently built using `GCC 5` and that causes the mismatched mangled symbol problem on CentOS/RHEL, where `GCC 4.8.5` is the default compiler. I recall you'd need to install a [developer toolset](https://developers.redhat.com/products/developertoolset/updates/) on RHEL to get a GCC > 4.8.5. And the version of `gcc` in conda was still 4.8.5, but I need to double check if `gcc_linux-64 > 5` was available. Thanks!

**Comment by dengc367** [comment]
https://github.com/horovod/horovod/issues/431#issuecomment-493030517

follow this method, i want you can solve it.

**Comment by fanbeatsman** [comment]
I am having this problem too and none of the above steps are solving it for me. 

Ubuntu 18.04
OpenMpi 4.0.2
Python 3.6.10
Cuda 10.0
Tensorflow 1.14


```
>>> import horovod.tensorflow

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 28, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4gloo3mpi7ContextC1ERKP19ompi_communicator_t 
```

**Comment by yeamusic21** [comment]
Hitting this issue on Azure Data Science Virtual Machine :-(

**Comment by Tonyhukaifan** [comment]
The same problem for PyTorch, anyone has a resolution?
