### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by samrudhdhirangrej** [horovod/horovod#695]
Hi,

I am trying to run Glow: https://github.com/openai/glow/tree/d3906b2f61183e2178feeb1d63dd5e5c9b78d04e

I experience following error. I have installed libraries using requirement.txt which reads as follows:
tensorflow-gpu==1.8.0
keras==2.2.0
pillow==5.2.0
toposort==1.5
horovod==0.13.8

I have tried with OpenMPI versions 4.0 and 3.1. with no success.

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import horovod.tensorflow as hvd
  File "/usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 42, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "/usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 57, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 44, in _load_library
    library = load_library.load_op_library(filename)
  File "/usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningENS_6StatusE

Any help is appreciated. Thanks.

**Comment by tgaddair** [comment]
Hey @samrudhdhirangrej, could you run `ldd /usr/local/data/srangrej/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so` and print the result?  Looks like a missing runtime dependency needs to be added to `LD_LIBRARY_PATH`.
