### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by Microndgt** [horovod/horovod#727]
I have encountered this problem:

```
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 11:07:58) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.tensorflow as hvd
python(8390,0x7fffbaa6c3c0) malloc: *** error for object 0x7ff188522358: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    8390 abort      python
```

the version of horovod and tensorflow are as follows:

```
tensorflow                    1.5.0               
tensorflow-tensorboard        1.5.1 
horovod                       0.14.0
```

platform:

```
macOS Sierra 10.12.6
```

And monitor shows:

[monitor.txt](https://github.com/uber/horovod/files/2720158/monitor.txt)

Thanks for your help!

**Comment by alsrgv** [comment]
@Microndgt, which version of Open MPI are you using?  Can you try upgrading to 4.0.0?

**Comment by Microndgt** [comment]
@alsrgv 

the version of Open MPI is already 4.0.0

```
~ » mpirun --version
mpirun (Open MPI) 4.0.0

Report bugs to http://www.open-mpi.org/community/help/
```

**Comment by alsrgv** [comment]
@Microndgt, great! Can you upgrade to latest Horovod 0.15.2 as well?

**Comment by Microndgt** [comment]
I have tried the version 0.13.11, 0.14, 0.15.2 but none of them works.

And there is another different error appears in 0.13.11 version:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 43, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 57, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 44, in _load_library
    library = load_library.load_op_library(filename)
  File "/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so, 6): Symbol not found: __ZN10tensorflow15OpKernelContext21CtxFailureWithWarningEPKciRKNS_6StatusE
  Referenced from: /Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so
  Expected in: /Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so
 in /Users/skyrover/miniconda3/envs/project/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so
```

**Comment by alsrgv** [comment]
Not sure. On my Mac 10.14.1:
```
➜  pip install tensorflow==1.5.0
Collecting tensorflow==1.5.0
...
➜  pip install horovod
Collecting horovod
...
➜  python
Python 2.7.15 (default, Oct  2 2018, 11:47:18)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.tensorflow as hvd
>>>
```

Does simply `import tensorflow` work for you?

**Comment by Microndgt** [comment]
@alsrgv Yes, this import works.

**Comment by alsrgv** [comment]
@Microndgt, not sure - can you upgrade your MacOS, Python2 and clang just in case?

**Comment by Microndgt** [comment]
@alsrgv OK. I will leave a comment here if anything changes...
