### ISSUE TITLE
Freezing Tensorflow Graph for Inference

### ISSUE THREAD

**Issue by mwoodson1** [horovod/horovod#731]
Is there a working example of how to freeze a Tensorflow graph after training? I tried following the inference doc and was able to run the optimize script but have not been able to successfully run the freeze script on the optimized model. Any guidance here would be much appreciated.

**Comment by alsrgv** [comment]
@mwoodson1, what was the issue you experienced with running the freeze script?

**Comment by mwoodson1** [comment]
After running the optimization script I run the following:
```python -m tensorflow.python.tools.freeze_graph --input_graph optimized_graph.pb --input_checkpoint ./checkpoints/model.ckpt-10 --output_graph frozen_graph.pb --output_node_names=output_node```
and get the following traceback:
```Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 491, in <module>
    run_main()
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 488, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 487, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 381, in main
    flags.saved_model_tags, checkpoint_version)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 363, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 190, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 773, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 680, in _ValidateAndSliceInputs
    for converted_saveable_object in self.SaveableObjectsForOp(op, name):
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 654, in SaveableObjectsForOp
    variable, "", name)
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 128, in __init__
    self.handle_op = var.op.inputs[0]
  File "/mnt/ilcompf8d1/user/woodson/video-ai/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2128, in __getitem__
    return self._inputs[i]
IndexError: list index out of range```

**Comment by tgaddair** [comment]
Hey @mwoodson1, one issue that can arise when freezing graphs with Horovod ops is that Horovod needs to be imported in order for the graph to deserialize properly.  Not sure if this is the exact issue in your case, but can you try running your freeze command as a script and `import horovod.tensorflow`?

For example, here's a simple example for the `tensorflow_mnist.py` example:

```
from tensorflow.python.tools import freeze_graph
import horovod.tensorflow

input_graph_path = './checkpoints/graph.pbtxt'
checkpoint_path = './checkpoints/model.ckpt-0'
input_saver_def_path = ""
input_binary = False
output_node_names = "ArgMax"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'frozen.pb'
output_optimized_graph_name = 'optimized.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, checkpoint_path, output_node_names,
                          restore_op_name, filename_tensor_name,
                          output_frozen_graph_name, clear_devices, "")
```

**Comment by Himscipy** [comment]
Hey @mwoodson1 , I am facing the similar issue. @tgaddair  I used your suggestion but it didn't worked for me for my model  freezing.

**Comment by tgaddair** [comment]
Hey @Himscipy, can you take a look at our [inference](https://github.com/horovod/horovod/blob/master/docs/inference.rst) page and try running the optimization script provided there?
