### ISSUE TITLE
tensorflow_mnist_estimator run false : ncclCommInitRank failed: unhandled cuda error

### ISSUE THREAD

**Issue by vangogh0318** [horovod/horovod#785]
I have two machine : server1, server2. I want to run example in two machine.
but, I got error. ncclCommInitRank failed: unhandled cuda error.

my script is here:

export CUDA_VISIBLE_DEVICES=2,3

mpirun -np 2 \
    -H server1:1,server2:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    /export/homes/XXX/software/tools/anaconda2/bin/python tensorflow_mnist_estimator.py

-------------------------------------------------------------------------------------
my error log 
+ export CUDA_VISIBLE_DEVICES=2,3
+ CUDA_VISIBLE_DEVICES=2,3
+ mpirun -np 2 -H server1:1,server2:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl '^openib' /export/homes/XXX/software/tools/anaconda2/bin/python tensorflow_mnist.py

/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-01-26 18:44:24.994070: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Graph was finalized.
2019-01-26 18:44:25.066263: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-26 18:44:32.759378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:02:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2019-01-26 18:44:32.759422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-01-26 18:44:33.125473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-26 18:44:33.125520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2019-01-26 18:44:33.125530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2019-01-26 18:44:33.125873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10744 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:02:00.0, compute capability: 3.5)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2019-01-26 18:44:33.763942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:84:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2019-01-26 18:44:33.764001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-01-26 18:44:34.122027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-26 18:44:34.122076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2019-01-26 18:44:34.122084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2019-01-26 18:44:34.122448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10742 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:84:00.0, compute capability: 3.5)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./checkpoints/model.ckpt.
HOSTNAME:4974:4981 [0] NCCL INFO NET : Using interface eth0:server1<0>
HOSTNAME:4974:4981 [0] NCCL INFO NET/Socket : 1 interfaces found
HOSTNAME:4974:4981 [0] NCCL INFO No network plugin found.

HOSTNAME:4974:4981 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
HOSTNAME:4974:4981 [0] NCCL INFO Using network Socket
NCCL version 2.3.7+cuda9.0
HOSTNAME:4974:4981 [0] NCCL INFO rank 0 nranks 2
HOSTNAME:2753:2762 [0] NCCL INFO NET : Using interface eth0:server2<0>
HOSTNAME:2753:2762 [0] NCCL INFO NET/Socket : 1 interfaces found
HOSTNAME:2753:2762 [0] NCCL INFO No network plugin found.

HOSTNAME:2753:2762 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
HOSTNAME:2753:2762 [0] NCCL INFO Using network Socket
HOSTNAME:2753:2762 [0] NCCL INFO rank 1 nranks 2
HOSTNAME:2753:2762 [0] NCCL INFO comm 0x7f66042708b0 rank 1 nranks 2
HOSTNAME:4974:4981 [0] NCCL INFO comm 0x7f91142e91e0 rank 0 nranks 2
HOSTNAME:4974:4981 [0] NCCL INFO CUDA Dev 0, Socket NIC distance :  SOC
HOSTNAME:4974:4981 [0] NCCL INFO Using 128 threads
HOSTNAME:2753:2762 [0] NCCL INFO CUDA Dev 0, Socket NIC distance :  PHB
HOSTNAME:4974:4981 [0] NCCL INFO Min Comp Cap 3
HOSTNAME:4974:4981 [0] NCCL INFO Ring 00 :    0   1
HOSTNAME:4974:4981 [0] NCCL INFO Ring 01 :    0   1
HOSTNAME:2753:2762 [0] NCCL INFO Ring 00 : 1[0] -> 0[0] via P2P/IPC
HOSTNAME:4974:4981 [0] NCCL INFO Ring 00 : 0[0] -> 1[0] via P2P/IPC

HOSTNAME:4974:4981 [0] transport/p2p.cu:548 NCCL WARN failed to open CUDA IPC handle : 11 invalid argument
HOSTNAME:4974:4981 [0] NCCL INFO init.cu:568 -> 1
HOSTNAME:4974:4981 [0] NCCL INFO init.cu:642 -> 1

HOSTNAME:2753:2762 [0] transport/p2p.cu:548 NCCL WARN failed to open CUDA IPC handle : 64 peer access is not supported between these two devices
HOSTNAME:2753:2762 [0] NCCL INFO init.cu:568 -> 1
HOSTNAME:2753:2762 [0] NCCL INFO init.cu:642 -> 1
HOSTNAME:4974:4981 [0] NCCL INFO rank 0 nranks 2
HOSTNAME:4974:4981 [0] NCCL INFO comm 0x7f9114224540 rank 0 nranks 2
HOSTNAME:2753:2762 [0] NCCL INFO rank 1 nranks 2
HOSTNAME:2753:2762 [0] NCCL INFO comm 0x7f66042749d0 rank 1 nranks 2
HOSTNAME:4974:4981 [0] NCCL INFO CUDA Dev 0, Socket NIC distance :  SOC
HOSTNAME:2753:2762 [0] NCCL INFO CUDA Dev 0, Socket NIC distance :  PHB
HOSTNAME:4974:4981 [0] NCCL INFO Using 128 threads
HOSTNAME:4974:4981 [0] NCCL INFO Min Comp Cap 3
HOSTNAME:4974:4981 [0] NCCL INFO Ring 00 :    0   1
HOSTNAME:4974:4981 [0] NCCL INFO Ring 01 :    0   1
HOSTNAME:4974:4981 [0] NCCL INFO Ring 00 : 0[0] -> 1[0] via P2P/IPC

HOSTNAME:4974:4981 [0] transport/p2p.cu:548 NCCL WARN failed to open CUDA IPC handle : 11 invalid argument
HOSTNAME:2753:2762 [0] NCCL INFO Ring 00 : 1[0] -> 0[0] via P2P/IPC
HOSTNAME:4974:4981 [0] NCCL INFO init.cu:568 -> 1
HOSTNAME:4974:4981 [0] NCCL INFO init.cu:642 -> 1

HOSTNAME:2753:2762 [0] transport/p2p.cu:548 NCCL WARN failed to open CUDA IPC handle : 64 peer access is not supported between these two devices
HOSTNAME:2753:2762 [0] NCCL INFO init.cu:568 -> 1
HOSTNAME:2753:2762 [0] NCCL INFO init.cu:642 -> 1
Traceback (most recent call last):
  File "tensorflow_mnist.py", line 161, in <module>
    tf.app.run()
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 157, in main
    mon_sess.run(train_op, feed_dict={image: image_, label: label_})
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
Traceback (most recent call last):
  File "tensorflow_mnist.py", line 161, in <module>
    return self._sess.run(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    tf.app.run()
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 157, in main
    run_metadata_ptr)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    mon_sess.run(train_op, feed_dict={image: image_, label: label_})
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    feed_dict_tensor, options, run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError    raise six.reraise(*original_exc_info)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled cuda error
	 [[{{node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]

Caused by op u'DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0', defined at:
  File "tensorflow_mnist.py", line 161, in <module>
    tf.app.run()
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 122, in main
    train_op = opt.minimize(loss, global_step=global_step)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 401, in minimize
    grad_loss=grad_loss)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 203, in compute_gradients
    compression=self._compression)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): ncclCommInitRank failed: unhandled cuda error
	 [[{{node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]

: ncclCommInitRank failed: unhandled cuda error
	 [[{{node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]

Caused by op u'DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0', defined at:
  File "tensorflow_mnist.py", line 161, in <module>
    tf.app.run()
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 122, in main
    train_op = opt.minimize(loss, global_step=global_step)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 401, in minimize
    grad_loss=grad_loss)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 203, in compute_gradients
    compression=self._compression)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/export/homes/XXX/software/tools/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): ncclCommInitRank failed: unhandled cuda error
	 [[{{node DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]

  Process name: [[51955,1],1]
  Exit code:    1

thanks.

**Comment by vangogh0318** [comment]
> @vangogh0318, are both servers called `hostname`? NCCL requires different servers to have a different hostname.

@alsrgv  thank you very much. After modify hostname configuration , the demo successed. 
it is great.
