### ISSUE TITLE
Installation issue in Ubuntu 16.04

### ISSUE THREAD

**Issue by hillolsarker** [horovod/horovod#836]
OS: Ubuntu 16.04

`apt-get install libnccl2 libnccl-dev`
Installs 2.4.2-1+cuda9.2

`nvcc --version`
> V9.2.148

Horovod installation fails for the following command:
`HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod`

Log:

`Failed to load the native TensorFlow runtime.

Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.5/imp.py", line 242, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-jfkl8bt_/horovod/setup.py", line 54, in check_tf_version
        import tensorflow as tf
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.5/imp.py", line 242, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`

**Comment by tsmolcic** [comment]
Are you sure you have CUDA installed?
IIRC, I had the same error once installing Horovod. Solved it using the following command to install it:

```HOROVOD_NCCL_HOME=/path/to/nccl HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/path/to/cuda pip install --no-cache-dir horovod```

**Comment by hillolsarker** [comment]
It was inside a singularity environment which needed some flags to mount the drivers.
