### ISSUE TITLE
Error when running with large dataset

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#844]
I am able to run my parallel code using horovod with a small dataset, but when i switch to a larger dataset I get following Error:
`2019-02-20 11:37:32.386397: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /mnt/lustre/cds/cdsudit/hvd-14feb/models/TransE.py:45: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /mnt/lustre/cds/cdsudit/hvd-14feb/models/TransE.py:45: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: MPI_Bcast failed, see MPI output for details.
	 [[Node: HorovodBroadcast_model_ent_embeddings_0 = HorovodBroadcast[T=DT_FLOAT, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/ent_embeddings/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_train_transe.py", line 35, in <module>
    con.set_model(models.TransE)
  File "/mnt/lustre/cds/cdsudit/hvd-14feb/config/Config.py", line 320, in set_model
    self.sess.run(hvd.broadcast_global_variables(0))
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: MPI_Bcast failed, see MPI output for details.
	 [[Node: HorovodBroadcast_model_ent_embeddings_0 = HorovodBroadcast[T=DT_FLOAT, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/ent_embeddings/read)]]

Caused by op 'HorovodBroadcast_model_ent_embeddings_0', defined at:
  File "example_train_transe.py", line 35, in <module>
    con.set_model(models.TransE)
  File "/mnt/lustre/cds/cdsudit/hvd-14feb/config/Config.py", line 320, in set_model
    self.sess.run(hvd.broadcast_global_variables(0))
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 98, in broadcast_global_variables
    for var in tf.global_variables()])
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 98, in <listcomp>
    for var in tf.global_variables()])
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 164, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 187, in horovod_broadcast
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/mnt/lustre/cds/cdsudit/miniconda3/envs/horovod-cpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): MPI_Bcast failed, see MPI output for details.
	 [[Node: HorovodBroadcast_model_ent_embeddings_0 = HorovodBroadcast[T=DT_FLOAT, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/ent_embeddings/read)]]
`
What's the Issue here?

**Comment by alsrgv** [comment]
@UditGupta10, is it possible that you have different versions of Horovod on different nodes?

**Comment by UditGupta10** [comment]
The error was due to out of memory. I am using a word2vec kind of model. After reducing the dimensions of embedding by 10 times it worked fine. I wonder how the memory issue can be resolved.

**Comment by alsrgv** [comment]
@UditGupta10, are you running one process per server?

**Comment by UditGupta10** [comment]
Yes, one process per server.

**Comment by alsrgv** [comment]
@UditGupta10, I guess you can try to use fp16 embeddings which may decrease memory usage by ~2x, assuming embeddings dominate the space.

**Comment by UditGupta10** [comment]
Any references to model parallelism that can be used within horovod?

**Comment by alsrgv** [comment]
@UditGupta10, #96 has some examples & discussion.
