### ISSUE TITLE
No module named horovod.spark

### ISSUE THREAD

**Issue by bluesummers1129** [horovod/horovod#883]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow
2. Framework version:
1.13.1
3. Horovod version:
0.16
4. MPI version:
3.0.0
5. CUDA version:
N/A
6. NCCL version:
N/A
7. Python version:
2.7
8. OS and version:
Amazon Linux AMI release 2018.03

**Your question:**
Please ask your question here.
When I try to run the toy or end-to-end Spark examples I get the following error after the dataset is prepared for model training:
```
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1551747816130_0020/container_1551747816130_0020_01_000003/pyspark.zip/pyspark/worker.py", line 217, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1551747816130_0020/container_1551747816130_0020_01_000003/pyspark.zip/pyspark/worker.py", line 59, in read_command
    command = serializer._read_with_length(file)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1551747816130_0020/container_1551747816130_0020_01_000003/pyspark.zip/pyspark/serializers.py", line 170, in _read_with_length
    return self.loads(obj)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1551747816130_0020/container_1551747816130_0020_01_000003/pyspark.zip/pyspark/serializers.py", line 562, in loads
    return pickle.loads(obj)
ImportError: No module named horovod.spark
```
I tried building the horovod egg from source and adding that as a --py-file in the spark-submit call to see if this was a broadcasting issue, but that only produced the following error:
```
Traceback (most recent call last):
  File "/home/hadoop/keras_spark_rossmann.py", line 309, in <module>
    import horovod.tensorflow.keras as hvd
  File "build/bdist.linux-x86_64/egg/horovod/tensorflow/__init__.py", line 35, in <module>

  File "build/bdist.linux-x86_64/egg/horovod/common/__init__.py", line 48, in check_extension

ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.
```
However, I definitely built horovod with tensorflow and it produced no errors.

I assume this is some issue with modules not being able to be pickled properly in Spark. Any pointers?

**Comment by alsrgv** [comment]
@bluesummers1129, do you have TensorFlow & Horovod installed on Spark workers?

**Comment by bluesummers1129** [comment]
@alsrgv D'oh that appeared to be the problem. I installed the libraries on the workers as well and it seems to have fixed the issue and I can run it end-to-end, though now I'm seeing the cluster hang if I ctrl-c out of a training run of the rossman Spark script and then try to run it again. That is, after I spark-submit it gets to the training and I see
```
19/03/06 05:53:57 INFO YarnScheduler: Adding task set 0.0 with 1 tasks
```
and then the job just hangs forever.

**Comment by alsrgv** [comment]
@bluesummers1129, it it because you don't have enough workers?  You should have at least the same # of executors as `num_proc` value that you're passing to `horovod.spark.run()`.
