### ISSUE TITLE
Question about Tensorflow using horovod

### ISSUE THREAD

**Issue by xyy-Iv** [horovod/horovod#892]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13.1
3. Horovod version: 0.16.0
4. MPI version: openmpi-bin (1.10.2-8ubuntu1)
5. CUDA version: 10, RTX2070 GPU, CUDNN 7.4.2
6. NCCL version: 2.4.2
7. Python version: 3.7
8. OS and version: Ubuntu 16.04

I have a tensorflow problem, it cannot use Convolution layers with horovod. Here is the output:
```
clic_001 /home/ivdai/AlgoNew/SJN/tfrecords/clic_div2k_qp36_50x50_rgb/ 2
(?, 50, 50, 3) (?, 50, 50, 3)
WARNING:tensorflow:From /home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/ops/losses/losses_impl.py:277: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
hvd.size() 1
2019-03-07 02:28:44.224622: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-07 02:28:44.289985: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200015000 Hz
2019-03-07 02:28:44.294000: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55678cc39840 executing computations on platform Host. Devices:
2019-03-07 02:28:44.294037: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-07 02:28:45.385388: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55678ccbdde0 executing computations on platform CUDA. Devices:
2019-03-07 02:28:45.385436: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-03-07 02:28:45.385772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:84:00.0
totalMemory: 7.77GiB freeMemory: 423.50MiB
2019-03-07 02:28:45.385843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-07 02:28:45.387992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-07 02:28:45.388026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-07 02:28:45.388044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-03-07 02:28:45.388272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 198 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:84:00.0, compute capability: 7.5)
WARNING:tensorflow:From /home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1070: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
2019-03-07 02:28:57.338791: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-07 02:28:57.355704: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node generator/conv1/Conv2D}}]]
	 [[{{node absolute_difference/value}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_mse_horovod.py", line 227, in <module>
    train()
  File "main_mse_horovod.py", line 183, in train
    errM, merged_result, _ = sess.run([l1_loss, merged, train_op_l1])
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node generator/conv1/Conv2D (defined at /home/ivdai/AlgoNew/CLIC/Track2/model.py:117) ]]
	 [[node absolute_difference/value (defined at /home/ivdai/AlgoNew/CLIC/Track2/loss.py:40) ]]

Caused by op 'generator/conv1/Conv2D', defined at:
  File "main_mse_horovod.py", line 227, in <module>
    train()
  File "main_mse_horovod.py", line 72, in train
    sr_image = clic_001(lr_image)
  File "/home/ivdai/AlgoNew/CLIC/Track2/model.py", line 8, in clic_001
    x = conv_leaky_relu(input_tensor, [3, 3, 3, 64], [1, 1, 1, 1], 'conv1', 'SAME', reuse)
  File "/home/ivdai/AlgoNew/CLIC/Track2/model.py", line 117, in conv_leaky_relu
    conv = tf.nn.conv2d(inputs, conv_weights, strides=strides, padding=padding)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ivdai/anaconda3/envs/clic/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node generator/conv1/Conv2D (defined at /home/ivdai/AlgoNew/CLIC/Track2/model.py:117) ]]
	 [[node absolute_difference/value (defined at /home/ivdai/AlgoNew/CLIC/Track2/loss.py:40) ]]
```

**Comment by tgaddair** [comment]
Hey @xyy-Iv, this looks like a TensorFlow config issue on one or more machines.  When you run this exact program without any Horovod statements, does it also produce this error message?
