### ISSUE TITLE
keras_spark_rossman.py is throwing type error while trying to train

### ISSUE THREAD

**Issue by anjuanjup** [horovod/horovod#922]
**Environment:**
1. Framework:  tensorflow 1.12.0, Spark 2.2.1
2. Horovod version: 0.16.0
3. MPI version: openMPI 3.1.1
4. CUDA version: NA
5. NCCL version: NA
6. Python version: 3.6
7. OS and version: CentOS 7

**Question:**
--------------------------------------------------------------------------

######
I'm getting a type error while trying to run the training using keras_spark_rossman.py. The stacktrace is given below:
[1,3]<stdout>:Epoch 1/100
[1,0]<stdout>:Epoch 1/100
[1,1]<stdout>:Epoch 1/100
[1,2]<stdout>:Epoch 1/100
[1,3]<stderr>:2019-03-17 23:10:18.765660: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,3]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,3]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:
[1,3]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 467, in generator_py_func
[1,3]<stderr>:    ret, dtype=dtype.as_numpy_dtype))
[1,3]<stderr>:
[1,3]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 166, in _convert
[1,3]<stderr>:    result = np.asarray(value, dtype=dtype, order="C")
[1,3]<stderr>:
[1,3]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
[1,3]<stderr>:    return array(a, dtype, copy=False, order=order)
[1,3]<stderr>:
[1,3]<stderr>:TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date'
[1,3]<stderr>:
[1,3]<stderr>:
[1,3]<stderr>:During handling of the above exception, another exception occurred:
[1,3]<stderr>:
[1,3]<stderr>:
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:
[1,3]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
[1,3]<stderr>:    ret = func(*args)
[1,3]<stderr>:
[1,3]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 472, in generator_py_func
[1,3]<stderr>:    "element was %s." % (dtype.name, ret))
[1,3]<stderr>:
[1,3]<stderr>:TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,3]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,3]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,3]<stderr>:
[1,3]<stderr>:
[1,3]<stderr>:2019-03-17 23:10:18.789159: F ./tensorflow/core/common_runtime/bfc_allocator.h:298] Could not find Region for 0x7f9f34035740
[1,1]<stderr>:2019-03-17 23:10:19.201863: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,1]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,1]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 467, in generator_py_func
[1,1]<stderr>:    ret, dtype=dtype.as_numpy_dtype))
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 166, in _convert
[1,1]<stderr>:    result = np.asarray(value, dtype=dtype, order="C")
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
[1,1]<stderr>:    return array(a, dtype, copy=False, order=order)
[1,1]<stderr>:
[1,1]<stderr>:TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date'
[1,1]<stderr>:
[1,1]<stderr>:
[1,1]<stderr>:During handling of the above exception, another exception occurred:
[1,1]<stderr>:
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
[1,1]<stderr>:    ret = func(*args)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 472, in generator_py_func
[1,1]<stderr>:    "element was %s." % (dtype.name, ret))
[1,1]<stderr>:
[1,1]<stderr>:TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,1]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,1]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,1]<stderr>:
[1,1]<stderr>:
[1,1]<stderr>:2019-03-17 23:10:19.230461: F ./tensorflow/core/common_runtime/bfc_allocator.h:298] Could not find Region for 0x7fd0f0033310
[1,0]<stderr>:2019-03-17 23:10:19.310791: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,0]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,0]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:
[1,0]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 467, in generator_py_func
[1,0]<stderr>:    ret, dtype=dtype.as_numpy_dtype))
[1,0]<stderr>:
[1,0]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 166, in _convert
[1,0]<stderr>:    result = np.asarray(value, dtype=dtype, order="C")
[1,0]<stderr>:
[1,0]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
[1,0]<stderr>:    return array(a, dtype, copy=False, order=order)
[1,0]<stderr>:
[1,0]<stderr>:TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date'
[1,0]<stderr>:
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:
[1,0]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
[1,0]<stderr>:    ret = func(*args)
[1,0]<stderr>:
[1,0]<stderr>:  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 472, in generator_py_func
[1,0]<stderr>:    "element was %s." % (dtype.name, ret))
[1,0]<stderr>:
[1,0]<stderr>:TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int64, but the yielded element was [datetime.date(2013, 1, 2) datetime.date(2013, 1, 2)
[1,0]<stderr>: datetime.date(2013, 1, 2) ... datetime.date(2015, 7, 31)
[1,0]<stderr>: datetime.date(2015, 7, 31) datetime.date(2015, 7, 31)].
[1,0]<stderr>:
[1,0]<stderr>:
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
[1,0]<stderr>:2019-03-17 23:10:19.338393: F ./tensorflow/core/common_runtime/bfc_allocator.h:298] Could not find Region for 0x7fd8f4033080
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node localhost exited on signal 6 (Aborted).
--------------------------------------------------------------------------
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/horovod/spark/__init__.py", line 69, in run_spark
    _make_mapper(driver.addresses(), num_proc, tmout, key)).collect()
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/pyspark/rdd.py", line 809, in collect
    port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 0 cancelled part of cancelled job group horovod.spark.run.0
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
        at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1457)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:799)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
        at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1707)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2094)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
        at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:467)
        at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)

Traceback (most recent call last):
  File "keras_spark_rossmann.py", line 501, in <module>
    horovod.spark.run(train_fn, args=(model_bytes,), num_proc=NUM_TRAINING_PROC, verbose=2)[0]
  File "/home/user1/anaconda3/envs/env_horovod_spark/lib/python3.6/site-packages/horovod/spark/__init__.py", line 180, in run
    raise Exception('mpirun exited with code %d, see the error above.' % exit_code)
Exception: mpirun exited with code 134, see the error above.
19/03/17 23:10:20 ERROR TaskContextImpl: Error in TaskCompletionListener
java.lang.IllegalStateException: Block broadcast_0 not found
        at org.apache.spark.storage.BlockInfoManager$$anonfun$2.apply(BlockInfoManager.scala:293)
        at org.apache.spark.storage.BlockInfoManager$$anonfun$2.apply(BlockInfoManager.scala:293)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.storage.BlockInfoManager.unlock(BlockInfoManager.scala:292)
        at org.apache.spark.storage.BlockManager.releaseLock(BlockManager.scala:720)
        at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$releaseLock$1.apply(TorrentBroadcast.scala:250)
        at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$releaseLock$1.apply(TorrentBroadcast.scala:250)
        at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:128)
        at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:117)
        at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:117)
        at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:130)
        at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:128)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:128)
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:116)
        at org.apache.spark.scheduler.Task.run(Task.scala:118)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Please help to solve the problem

**Comment by Qiuzhuang** [comment]
I got this issue too.

**Comment by umangkeshri** [comment]
I'm also getting the same issue.

**Comment by Qiuzhuang** [comment]
I use make_batch_reader's schema_fields to fetch only desired columns excluding the date field as follows:

    with make_batch_reader('%s/train_df.parquet' % DATA_LOCATION, num_epochs=None,
                           cur_shard=hvd.rank(), shard_count=hvd.size(),
                           schema_fields=all_cols + ['Sales'],
                           hdfs_driver=PETASTORM_HDFS_DRIVER) as train_reader:

It looks good to me.

**Comment by alsrgv** [comment]
Seems like there was an issue with Petastorm which was fixed in [this commit](https://github.com/uber/petastorm/commit/0979a5f503ae25d4a132a248d481319317400029).

Could you upgrade to `petastorm>=0.7.0`?

Also, if you're using Python 3, please see #957 for the fix.  The script will be updated shortly.

cc @selitvin

**Comment by Qiuzhuang** [comment]
Thanks @alsrgv, upgrading to 0.7.0 along with python 3 fixing look good to me now.
