### ISSUE TITLE
Error in the script - keras_spark_rossmann.py

### ISSUE THREAD

**Issue by mohanraj1311** [horovod/horovod#964]
While i am able to run the sample example, this is the error that i get :
Am i missing something,?
```
2019-03-28 02:53:22 INFO  DAGScheduler:54 - ResultStage 198 (collect at /tmp/spark-671ffa17-ce8f-4d0c-9bed-92b818a0d44d/horovod-spark-tf-example.py:219) finished in 1.328 s
2019-03-28 02:53:22 INFO  DAGScheduler:54 - Job 45 finished: collect at /tmp/spark-671ffa17-ce8f-4d0c-9bed-92b818a0d44d/horovod-spark-tf-example.py:219, took 2.625915 s
Traceback (most recent call last):
  File "/tmp/spark-671ffa17-ce8f-4d0c-9bed-92b818a0d44d/horovod-spark-tf-example.py", line 291, in <module>
    categorical_cols)
  File "/tmp/spark-671ffa17-ce8f-4d0c-9bed-92b818a0d44d/horovod-spark-tf-example.py", line 219, in build_vocabulary
    vocab[col] = sorted([r[0] for r in df.select(col).distinct().collect()])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
2019-03-28 02:53:23 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2019-03-28 02:53:23 INFO  AbstractConnector:318 - Stopped Spark@59cd049b{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-03-28 02:53:23 INFO  SparkUI:54 - Stopped Spark web UI at http://spark-horo-tf-1553740756666-driver-svc.hdfs1.svc:4040
2019-03-28 02:53:23 INFO  KubernetesClusterSchedulerBackend:54 - Shutting down all executors
```

**Comment by alsrgv** [comment]
@mohanraj1311, this was recently fixed.  Can you use updated https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann.py ?
