### ISSUE TITLE
Requirements for spark.run call

### ISSUE THREAD

**Issue by bluesummers1129** [horovod/horovod#974]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow
2. Framework version:
1.13.1
3. Horovod version:
0.16
4. MPI version:
3.0.0
5. CUDA version:
N/A
6. NCCL version:
N/A
7. Python version:
2.7
8. OS and version:
Amazon Linux AMI release 2018.03

**Your question:**
I've been playing around more with the horovod + Spark functionality and have a general question about what input arguments are supported. In the keras_spark_rossman example, I've been experimenting with changing the arguments for train_fn(), which currently just takes a string train_fn(model_bytes). If I add an integer type kwarg to it (e.g. train_fn(model_bytes, training_epochs=DEFAULT_EPOCHS) and change the spark.run() call to
```
horovod.spark.run(train_fn, args=(model_bytes,), kwargs={"training_epochs": 1}, ...)
```
works fine, but when I try to add a dictionary arg of some sort like {'train_rows': 10, 'val_rows': 1}
```
some_dict = {'train_rows': 10, 'val_rows': 1}
horovod.spark.run(train_fn, args=(model_bytes, some_dict), kwargs="training_epochs": 1}, ...)
```
I get pickling errors like
```
  File "/usr/lib64/python2.7/pickle.py", line 655, in save_dict
----------------------------------------[1,0]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code

[1,0]<stderr>:    exec code in run_globals
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 55, in <module>
    self._batch_setitems(obj.iteritems())
[1,0]<stderr>:    main(codec.loads_base64(sys.argv[1]))
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 46, in main
[1,0]<stderr>:    fn, args, kwargs = driver_client.code()
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/driver/driver_service.py", line 138, in code
  File "/usr/lib64/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
[1,0]<stderr>:    [1,0]<stderr>:resp = self._send(CodeRequest())
  File "/usr/lib64/python2.7/pickle.py", line 306, in save
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/run/common/util/network.py", line 243, in _send
[1,0]<stderr>:    return self._send_one(addr, req)
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/run/common/util/network.py", line 228, in _send_one
[1,1]<stderr>:    "__main__", fname, loader, pkg_name)
[1,1]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    rv = reduce(self.proto)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
[1,0]<stderr>:    resp = self._wire.read(rfile)
    answer, self.gateway_client, self.target_id, self.name)
[1,0]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/run/common/util/network.py", line 79, in read
[1,1]<stderr>:    exec code in run_globals
[1,1]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 55, in <module>
[1,1]<stderr>:    main(codec.loads_base64(sys.argv[1]))
[1,0]<stderr>:    message_len = struct.unpack('i', rfile.read(4))[0]
[1,1]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 46, in main
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
[1,1]<stderr>:    fn, args, kwargs = driver_client.code()
    return f(*a, **kw)
[1,1]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/driver/driver_service.py", line 138, in code
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
Py4JError: An error occurred while calling o71.__getnewargs__. Trace:
py4j.Py4JException: Method __getnewargs__([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

It seems like the issue is that the dictionary is not being pickled properly before being sent to the Spark workers, whereas the primitive types like str, int, etc. are being serialized without issue. In general, how should I be serializing and deserializing my objects for passing to the function in horovod.spark.run()? Do I need to implement custom serialize() deserialize() functions as in keras_spark_rossman.py for anything that isn't a primitive, even for things that should be straightforward to pickle such as dictionaries?

**Comment by tgaddair** [comment]
Hey @bluesummers1129, Horovod uses cloudpickle to serialize/deserialize your functions are arguments. Python dictionaries with only standard types shouldn't cause any issues.

Can you provide the updated signature of the `train_fn` where you're seeing these issues?

**Comment by bluesummers1129** [comment]
I realized the issue was trying to pass a Spark DataFrame as one of the args, which can't be pickled for executors. I refactored things and resolved it.
