### ISSUE TITLE
Horovod hangs even after specifying non-routed interfaces

### ISSUE THREAD

**Issue by AdrianLsk** [horovod/horovod#98]
Hi, I managed to install everything, but I have a problem with the process hanging after launching the code in tensorflow_mnist.py

I tried to exclude the non-routed interfaces (although my knowledge here is very limited). The interfaces I excluded: enp30s0,docker0,br-bb10fb5deea4. I determined them by running `ip addr`, here is it's output:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

2: enp30s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 30:9c:23:06:7d:4f brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.46/24 brd 192.168.178.255 scope global dynamic enp30s0
       valid_lft 815561sec preferred_lft 815561sec
    inet6 2001:980:3fdd:1:d19e:4af0:2a3c:50b5/64 scope global dynamic noprefixroute 
       valid_lft 5835sec preferred_lft 3250sec
    inet6 fe80::581b:628d:c75e:7c5b/64 scope link 
       valid_lft forever preferred_lft forever

3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:42:58:ca:84 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:42ff:fe58:ca84/64 scope link 
       valid_lft forever preferred_lft forever

4: br-bb10fb5deea4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:70:71:d5:21 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-bb10fb5deea4
       valid_lft forever preferred_lft forever

6: veth1316791@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 6e:fa:a5:c7:3d:3b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::6cfa:a5ff:fec7:3d3b/64 scope link 
       valid_lft forever preferred_lft forever

8: veth144f6e0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 62:aa:eb:04:af:8f brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::60aa:ebff:fe04:af8f/64 scope link 
       valid_lft forever preferred_lft forever
```
Here is the output of the test script containing code in tensorflow_mnist.py 
`
mpirun -mca btl_tcp_if_exclude enp30s0,docker0,br-bb10fb5deea4 -np 2 -bind-to none -oversubscribe -x NCCL_DEBUG=INFO python test.py 
Extracting MNIST-data-0/train-images-idx3-ubyte.gz
Extracting MNIST-data-1/train-images-idx3-ubyte.gz
Extracting MNIST-data-0/train-labels-idx1-ubyte.gz
Extracting MNIST-data-0/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-1/train-labels-idx1-ubyte.gz
Extracting MNIST-data-1/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-0/t10k-labels-idx1-ubyte.gz
Extracting MNIST-data-1/t10k-labels-idx1-ubyte.gz
INFO:tensorflow:Create CheckpointSaverHook.
2017-11-17 00:01:43.504939: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 00:01:43.505590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:24:00.0
totalMemory: 7.92GiB freeMemory: 7.83GiB
2017-11-17 00:01:43.505606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 1, name: GeForce GTX 1070, pci bus id: 0000:24:00.0, compute capability: 6.1)
2017-11-17 00:01:43.525607: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 00:01:43.526169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:23:00.0
totalMemory: 7.92GiB freeMemory: 7.79GiB
2017-11-17 00:01:43.526188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:23:00.0, compute capability: 6.1)

admin-pc:14732:14831 [0] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
admin-pc:14732:14831 [0] INFO Using internal Network Socket
**admin-pc:14732:14831 [0] INFO NET : Using interface enp30s0:192.168.178.46<0>
admin-pc:14732:14831 [0] INFO NET : Using interface docker0:172.17.0.1<0>
admin-pc:14732:14831 [0] INFO NET : Using interface br-bb10fb5deea4:172.18.0.1<0>
admin-pc:14732:14831 [0] INFO NET : Using interface veth1316791:fe80::6cfa:a5ff:fec7:3d3b%veth1316791<0>
admin-pc:14732:14831 [0] INFO NET : Using interface veth144f6e0:fe80::60aa:ebff:fe04:af8f%veth144f6e0<0>**
admin-pc:14732:14831 [0] INFO NET/Socket : 5 interfaces found
NCCL version 2.0.5 compiled with CUDA 9.0

admin-pc:14733:14828 [1] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
**admin-pc:14733:14828 [1] INFO Using internal Network Socket
admin-pc:14733:14828 [1] INFO NET : Using interface enp30s0:192.168.178.46<0>
admin-pc:14733:14828 [1] INFO NET : Using interface docker0:172.17.0.1<0>
admin-pc:14733:14828 [1] INFO NET : Using interface br-bb10fb5deea4:172.18.0.1<0>
admin-pc:14733:14828 [1] INFO NET : Using interface veth1316791:fe80::6cfa:a5ff:fec7:3d3b%veth1316791<0>**
admin-pc:14733:14828 [1] INFO NET : Using interface veth144f6e0:fe80::60aa:ebff:fe04:af8f%veth144f6e0<0>
admin-pc:14733:14828 [1] INFO NET/Socket : 5 interfaces found
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO Using 256 threads
admin-pc:14732:14831 [0] INFO [0] Ring 0 :    0   1
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO 0 -> 1 via P2P/IPC
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO 1 -> 0 via P2P/IPC
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14732:14831 [0] INFO 0 -> 1 via P2P/IPC
admin-pc:14733:14828 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:14733:14828 [1] INFO 1 -> 0 via P2P/IPC
`

Why are the excluded interfaces still used in the output? Any ideas why it still hangs?

**Comment by alsrgv** [comment]
@AdrianLsk, can you try adding `-x NCCL_SOCKET_IFNAME=enp30s0`?  Typically NCCL is much better at detecting non-routed interfaces than Open MPI, but in your case, it didn't find `eth` or `ib`, so it just added all of them.

**Comment by AdrianLsk** [comment]
@alsrgv, adding the argument gets rid of the other interfaces, but it still hangs a bit and then gives a synchronization error due to timeout (as it did also last time):

```shell
mpirun -mca btl_tcp_if_exclude enp30s0,docker0,br-bb10fb5deea4 -np 2 -bind-to none -oversubscribe -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=enp30s0 python test.py
Extracting MNIST-data-1/train-images-idx3-ubyte.gz
Extracting MNIST-data-0/train-images-idx3-ubyte.gz
Extracting MNIST-data-0/train-labels-idx1-ubyte.gz
Extracting MNIST-data-0/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-1/train-labels-idx1-ubyte.gz
Extracting MNIST-data-1/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-0/t10k-labels-idx1-ubyte.gz
Extracting MNIST-data-1/t10k-labels-idx1-ubyte.gz
0
INFO:tensorflow:Create CheckpointSaverHook.
1
2017-11-17 08:26:01.600401: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 08:26:01.601043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:24:00.0
totalMemory: 7.92GiB freeMemory: 7.83GiB
2017-11-17 08:26:01.601062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 1, name: GeForce GTX 1070, pci bus id: 0000:24:00.0, compute capability: 6.1)
2017-11-17 08:26:01.612718: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 08:26:01.613141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:23:00.0
totalMemory: 7.92GiB freeMemory: 7.79GiB
2017-11-17 08:26:01.613154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:23:00.0, compute capability: 6.1)

admin-pc:20869:20965 [0] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
admin-pc:20869:20965 [0] INFO Using internal Network Socket
admin-pc:20869:20965 [0] INFO NET : Using interface enp30s0:192.168.178.46<0>
admin-pc:20869:20965 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.0.5 compiled with CUDA 9.0

admin-pc:20870:20968 [1] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
admin-pc:20870:20968 [1] INFO Using internal Network Socket
admin-pc:20870:20968 [1] INFO NET : Using interface enp30s0:192.168.178.46<0>
admin-pc:20870:20968 [1] INFO NET/Socket : 1 interfaces found
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO Using 256 threads
admin-pc:20869:20965 [0] INFO [0] Ring 0 :    0   1
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO 0 -> 1 via P2P/IPC
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO 1 -> 0 via P2P/IPC
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20869:20965 [0] INFO 0 -> 1 via P2P/IPC
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO nvmlDeviceGetNvLinkCapability() failed: Not Supported 
admin-pc:20870:20968 [1] INFO 1 -> 0 via P2P/IPC



Traceback (most recent call last):
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: cudaEventSynchronize failed: the launch timed out and was terminated
	 [[Node: DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer2_Conv_Conv2D_grad_tuple_control_dependency_1_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv_layer2/Conv/Conv2D_grad/tuple/control_dependency_1)]]
	 [[Node: DistributedRMSPropOptimizer/update/_218 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_420_DistributedRMSPropOptimizer/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 119, in <module>
    tf.app.run()
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 115, in main
    mon_sess.run(train_op, feed_dict={image: image_, label: label_})
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: cudaEventSynchronize failed: the launch timed out and was terminated
	 [[Node: DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer2_Conv_Conv2D_grad_tuple_control_dependency_1_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv_layer2/Conv/Conv2D_grad/tuple/control_dependency_1)]]
	 [[Node: DistributedRMSPropOptimizer/update/_218 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_420_DistributedRMSPropOptimizer/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer2_Conv_Conv2D_grad_tuple_control_dependency_1_0', defined at:
  File "test.py", line 119, in <module>
    tf.app.run()
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 84, in main
    train_op = opt.minimize(loss, global_step=global_step)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 180, in compute_gradients
    device_sparse=self._device_sparse)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 76, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 145, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 37, in horovod_allreduce
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/adrian/.pyenv/versions/tf_latest/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): cudaEventSynchronize failed: the launch timed out and was terminated
	 [[Node: DistributedRMSPropOptimizer_Allreduce/HorovodAllreduce_gradients_conv_layer2_Conv_Conv2D_grad_tuple_control_dependency_1_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv_layer2/Conv/Conv2D_grad/tuple/control_dependency_1)]]
	 [[Node: DistributedRMSPropOptimizer/update/_218 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_420_DistributedRMSPropOptimizer/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

2017-11-17 08:27:13.941738: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941772: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941776: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941780: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941784: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941787: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941791: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941794: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941797: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941801: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941804: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941807: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941811: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941814: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941817: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
2017-11-17 08:27:13.941821: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x4cd9b10: CUDA_ERROR_LAUNCH_TIMEOUT
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63684,1],0]
  Exit code:    1
``` 

Do I need to call some synchronization method in my code?

**Comment by alsrgv** [comment]
I don't think I've seen this error. Is `enp30s0` interface routed?  If not, you can add another interface to `-x NCCL_SOCKET_IFNAME=...`.

**Comment by AdrianLsk** [comment]
@alsrgv, unfortunately I don't know how to check if it's routed. I tried other interfaces but none of them worked. I am running it on a desktop machine with 2 GPUs. If you point me to what I should be looking for, then I can figure it out. How can I check that any of the interfaces is routed?

**Comment by alsrgv** [comment]
@AdrianLsk, are you able to run single-GPU training on both GPUs?  You can check by running `CUDA_VISIBLE_DEVICES=0 python test.py` and `CUDA_VISIBLE_DEVICES=1 python test.py`.

Also, in [this thread](https://github.com/tensorflow/tensorflow/issues/2121#issuecomment-225659476), folks recommend using `CUDA_LAUNCH_BLOCKING=1` to debug. You can set it via `-x CUDA_LAUNCH_BLOCKING=1` in your `mpirun` command.

**Comment by AdrianLsk** [comment]
@alsrgv, single GPU training works, `python test.py` or `CUDA_VISIBLE_DEVICES=1 python test.py` worked, even using MPI with only one process 
```
mpirun -mca btl_tcp_if_exclude docker0 -np 1 -bind-to none -oversubscribe -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=enp30s0 python test.py
``` 
worked, adding `-x CUDA_LAUNCH_BLOCKING=1` to `mpirun` with 2 processes yields the same error as before, just to note, I am running it on TF 1.4 with CUDA 9.0 + CUDNN 7.0 + NCCL 2.0.5

**Comment by alsrgv** [comment]
@AdrianLsk, can you try to run this sample NCCL program?

```bash
$ wget https://gist.githubusercontent.com/alsrgv/445107a83fdf077bc150b809241f7d53/raw/4cfaa4d707b3a04044a4d7243e45745a8ed25cba/test_nccl.c -O test_nccl.c
$ mpicc -std=c11 test_nccl.c -o test_nccl -I$CUDA_HOME/include -I$NCCL_HOME/include -L$CUDA_HOME/lib64 -lcudart -L$NCCL_HOME/lib -lnccl
$ mpirun -np 2 -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO ./test_nccl
```

If that doesn't work, can you try upgrading to NCCL 2.1 that just came out?

**Comment by dashesy** [comment]
@alsrgv that test is very helpful, and reproduces an issue I have.
I use NCCL2.1 and CUDA9.

When calling ncclCommInitRank I get this error:

```text
machine [0] misc/ibvwrap.cu:269 WARN Call to ibv_create_qp failed
```
Followed by

```text
Failed, NCCL error test_nccl.c:99 'unhandled system error'
```
Any help/hint is appreciated.

**Comment by alsrgv** [comment]
@dashesy, what does `ulimit -l` show?  Any messages in `dmesg`?

**Comment by alsrgv** [comment]
@dashesy, what does `ibv_devinfo` show on both nodes?

**Comment by alsrgv** [comment]
Closing due to lack of activity.  Going forward, `horovodrun` is a preferred way to run Horovod, while `mpirun` should be reserved for advanced use cases.

**Comment by zrss** [comment]
> @alsrgv that test is very helpful, and reproduces an issue I have.
> I use NCCL2.1 and CUDA9.
> 
> When calling ncclCommInitRank I get this error:
> 
> ```
> machine [0] misc/ibvwrap.cu:269 WARN Call to ibv_create_qp failed
> ```
> 
> Followed by
> 
> ```
> Failed, NCCL error test_nccl.c:99 'unhandled system error'
> ```
> 
> Any help/hint is appreciated.

i met the same case with @dashesy , and it seems the mem lock is too small ?

dmesg show

![image](https://user-images.githubusercontent.com/8072378/96432206-251b9d00-1237-11eb-87d0-79200b35d2ea.png)

ulimit -a show

![image](https://user-images.githubusercontent.com/8072378/96432186-1cc36200-1237-11eb-9cf2-a3732de1078b.png)

@alsrgv , sorry for posting in a closed issue ... i come here as google the `WARN Call to ibv_create_qp failed` ... but it seems the `16`(dmesg) not match with the `64` (ulimit), could u give me some helps ... i just wanna to confirm where the definition of limit(16)

**Comment by zrss** [comment]
finally, i found this err msg came from the driver of mlnx-ofed, many thanks for the `dmesg` and `ulimit` hint @alsrgv

![image](https://user-images.githubusercontent.com/8072378/96596623-8028bf00-131f-11eb-9a54-e65816a1d53a.png)

ref:

https://www.mellanox.com/related-docs/prod_software/Mellanox_OFED_Linux_User_Manual_v4_3.pdf

and the src of mlnx-ofed

```
/tmp/MLNX_OFED_LINUX-4.3-1.0.1.0-ubuntu16.04-x86_64/src/MLNX_OFED_SRC-4.3-1.0.1.0/SOURCES/mlnx-ofed-kernel-4.3/drivers/infiniband/core
```
